nocobase/nocobase

packages/core/client/src/schema-component/antd/grid/Grid.tsx
=> refactor: colDivider style improve for draging overing

packages/core/client/src/collection-manager/mixins/InheritanceCollectionMixin.ts, packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts
=> fix: collections undefined in useCollectionState

packages/core/client/src/powered-by/index.tsx, packages/core/client/src/user/Help.tsx, packages/core/utils/src/client.ts, packages/core/utils/src/parseHTML.ts
在 core 中适配插件 plugin-custom-brand 配置的内容。
=> chore: adapt to plugin-custom-brand

packages/core/client/src/collection-manager/interfaces/url.ts
=> refactor: url field support text type as availableTypes

packages/core/client/src/schema-component/antd/action/Action.tsx
=> fix: configure openSize for table action is only immediately  valid for one row

packages/core/client/src/modules/blocks/data-blocks/details-multi/DetailsBlockInitializer.tsx, packages/core/client/src/modules/blocks/data-blocks/form/FormBlockInitializer.tsx, packages/core/client/src/modules/blocks/filter-blocks/collapse/FilterCollapseBlockInitializer.tsx, packages/core/client/src/modules/blocks/filter-blocks/form/FilterFormBlockInitializer.tsx, packages/core/client/src/schema-initializer/buttons/RecordBlockInitializers.tsx, packages/core/client/src/schema-initializer/items/DataBlockInitializer.tsx
=> fix: fix the disappearing collections when searching

packages/plugins/@nocobase/plugin-acl/src/client/RolesManagement.tsx, packages/plugins/@nocobase/plugin-users/src/server/__tests__/role-users.test.ts, packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts
Filtering worked properly.
Filtering did not work.
#3733 
Close T-3622
For excluding users already have the role, request does not utilize the standard API and the custom API did not correctly handle `filter` params.
Append `filter` params to API logic.
=> fix(acl): bug of user filtering when adding them to roles

packages/core/client/src/collection-manager/interfaces/nanoid.ts, packages/core/client/src/collection-manager/interfaces/uuid.ts
=> fix: uuid & nanoid field name should be disabled when editing in collection 

packages/core/client/src/collection-manager/Configuration/components/index.tsx
=> fix(foreign key): first character entered in foreign key input is not displayed

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix: filter params should not allow passing empty objects

packages/core/client/src/schema-settings/SchemaSettingsSortingRule.tsx
=> fix(subTable): fix sorting rule setting

packages/core/client/src/collection-manager/Configuration/components/index.tsx
=> fix: through collection support search

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditCollectionAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/locale/zh-CN.json
=> refactor: view collection support filterTargetKey config

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/RolesResourcesActions.tsx
=> fix: field permission all fields should be displayed

packages/core/client/src/application/hoc/withDynamicSchemaProps.tsx
局部的 scope 覆盖了全局的 scope，但是 hoc 里取的还是全局的 scope
=> fix: useExpressionScope

packages/core/client/src/schema-component/antd/expand-action/Expand.Action.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> fix: expand action and add new action should support drag & sort

packages/core/client/src/pm/PluginManager.tsx
=> fix(plugin-manager): plugin manager support keywords classification

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/DatabaseConnectionManager.tsx
=> fix: reload when data source click refresh

packages/core/client/src/collection-manager/templates/components/PresetFields.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts
=> refactor: file collection template preset fields should be disabled

packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20240325213145-fix-schema.ts
Manual node UI configuration disappeared after upgrade to multiple data source of workflow.
1. Configure a manual node with UI before upgrade to d691e4c7e6485ae16134f035e7689f37f95c01ef.
2. Upgrade to d691e4c7e6485ae16134f035e7689f37f95c01ef.
3. Open manual node UI configuration.
Blocks should be preserved.
Disappeared.
None.
Migration logic is not correct.
Fix migration.
=> fix(plugin-workflow-manual): fix schema migration

packages/core/test/src/server/mockServer.ts
Fix agent chained type.
Agent type is not correct after chained `login()`.
- Frontend
- Backend
None.
None.
None.
=> chore(test): fix agent type

packages/core/client/src/application/__tests__/hoc/withDynamicSchemaProps.test.tsx, packages/core/client/src/application/hoc/withDynamicSchemaProps.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix(Table): fix invalid pagination

.github/workflows/nocobase-test-backend.yml, .github/workflows/nocobase-test-e2e.yml, .github/workflows/nocobase-test-frontend.yml, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> optimize ci

packages/plugins/@nocobase/plugin-api-keys/src/client/Configuration/schema.tsx, packages/plugins/@nocobase/plugin-multi-app-manager/src/client/settings/schemas/applications.ts, packages/plugins/@nocobase/plugin-verification/src/client/schemas/providers.ts, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
=> fix: missing button icon

packages/plugins/@nocobase/plugin-acl/src/client/permissions/GeneralPermissions.tsx, packages/plugins/@nocobase/plugin-acl/src/client/permissions/MenuPermissions.tsx, packages/plugins/@nocobase/plugin-acl/src/client/permissions/Permissions.tsx, packages/plugins/@nocobase/plugin-acl/src/client/permissions/PluginPermissions.tsx
=> chore: menu permissions & plugins setting permissions

packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/configure.test.ts, packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts
=> fix: acl e2e failed

packages/plugins/@nocobase/plugin-data-visualization/src/client/__tests__/chart-api.test.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/antd/statistic.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/antd/table.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/chart.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/bar.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/dualAxes.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/g2plot.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/index.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/pie.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRenderer.tsx
=> fix(data-vi): charts flickers

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/g2plot.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRenderer.tsx
https://github.com/antvis/G2/issues/3037#issuecomment-754531110
1. Record the height when first rendering.
2. Assign the recorded height to the parent container.
=> fix(data-vi): canvas height keeps increasing when filtering/reseting

packages/core/client/src/block-provider/DetailsBlockProvider.tsx, packages/core/client/src/block-provider/index.tsx, packages/plugins/@nocobase/plugin-action-print/src/client/utils.ts
=> fix: reporting error when clicking on the print action in detail block

packages/core/client/src/schema-component/antd/form/Form.tsx, packages/plugins/@nocobase/plugin-acl/src/client/schemas/roles.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/FileStorage.tsx, packages/plugins/@nocobase/plugin-verification/src/client/schemas/providers.ts
=> refactor: default role & default field storage

packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/component/BulkEditField.tsx
=> chore: remove add-attach option from bulk update action

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/collections/executions.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/CreateInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/DestroyInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/QueryInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/UpdateInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
Add transaction check from data source.
Transaction can not be used across different data sources.
- Frontend
- Backend
- Add common method to check transaction from specific data source.
None.
None.
None.
=> refactor(plugin-workflow): add transaction check from data source

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditCollectionAction.tsx
=> fix: filterTargetKey only support view collection

packages/plugins/@nocobase/plugin-workflow/src/server/instructions/CreateInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts
Change  `model.primaryKeyAttribute` to `collection.filterTargetKey`.
Use generic collection API instead of model API.
- Frontend
- Backend
- Triggers and instructions.
None.
None.
None.
=> refactor(plugin-workflow): change  `model.primaryKeyAttribute` to `collection.filterTargetKey`

packages/core/client/src/block-provider/FormBlockProvider.tsx
=> fix(client): formBlockProvider block display

packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx
=> fix(formula-field): setFormValueChanged undefined

packages/core/client/src/collection-manager/interfaces/nanoid.ts, packages/core/client/src/collection-manager/interfaces/properties/index.ts, packages/core/client/src/collection-manager/interfaces/uuid.ts, packages/core/client/src/locale/zh-CN.json, packages/core/database/package.json, packages/core/database/src/__tests__/fields/nanoid-field.test.ts, packages/core/database/src/__tests__/fields/uuid-field.test.ts, packages/core/database/src/fields/nanoid-field.ts, packages/core/database/src/fields/uuid-field.ts, yarn.lock
=> refactor: uuid & nanoid support default value configuration

packages/core/client/src/schema-initializer/utils.ts
=> fix: avoid duplicate menu keys

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> fix: association field support data scope linkage

packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/templatesOfBug.ts, packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/test/src/e2e/e2eUtils.ts
=> fix: fieldNames missing when setting data scope

packages/plugins/@nocobase/plugin-custom-request/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-custom-request/src/client/schemaSettings.ts
=> fix(plugin-custom-request): fix edit button dialog

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemDesigner.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
Allows to set data scope for fields of chart filter block.
=> feat(data-vi): data scope for chart filter fields

packages/core/build/src/constant.ts, packages/core/build/src/tarPlugin.ts
=> fix: tar bug

packages/plugins/@nocobase/plugin-action-print/src/client/utils.ts
=> fix: history block add print button, click print button to report error

packages/core/client/src/application/hoc/withDynamicSchemaProps.tsx
=> fix(withDynamicSchemaProps): change deep merge to shallow merge

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
=> fix: sort params missing when switch page numbers

packages/core/client/src/collection-manager/interfaces/properties/index.ts
=> fix: select field options initialValue

packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/pagination.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
=> fix(Table): fix Pagination

packages/core/actions/src/utils.ts, packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/block-provider/hooks/useDataBlockSourceId.tsx, packages/core/client/src/index.ts, packages/core/client/src/modules/blocks/data-blocks/details-multi/hooks/useDetailsWithPaginationDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/details-single/hooks/useDetailsDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/form/hooks/useCreateFormBlockDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/form/hooks/useEditFormBlockDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/grid-card/hooks/useGridCardBlockDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/list/hooks/useListBlockDecoratorProps.ts, packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockDecoratorProps.ts, packages/core/client/src/modules/blocks/useParentRecordCommon.ts, packages/core/data-source-manager/src/default-actions/utils.ts, packages/plugins/@nocobase/plugin-calendar/src/client/hooks/useCalendarBlockDecoratorProps.ts
当 sourceId 为空时，不影响 assocation 的查询
close T-3870
=> fix: source id null

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
=> fix: gantt block pagination

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/templatesOfBug.ts, packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx
=> fix(defaultValue): should immediate effect when set default value

packages/core/client/src/schema-component/antd/input-number/ReadPretty.tsx
=> fix: number display format

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/modules/blocks/filter-blocks/collapse/filterCollapseItemFieldSettings.ts, packages/core/client/src/modules/blocks/filter-blocks/collapse/filterCollapseItemInitializer.tsx
=> fix(Collapse): fix error for chinaRegions

packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaInitializer.test.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/CalendarBlockProvider.tsx
=> fix(Table): fix the problem that the content of the association field is not displayed

packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx, packages/core/client/src/schema-component/antd/upload/Upload.tsx
=> fix(Lightbox): fix zIndex

packages/core/client/src/schema-component/antd/table-v2/index.ts, packages/core/client/src/schema-settings/index.ts, packages/plugins/@nocobase/plugin-formula-field/src/client/FormulaComponentFieldSettings.tsx, packages/plugins/@nocobase/plugin-formula-field/src/client/index.tsx
=> feat: formula field support format

packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx
=> fix: formula field caluation error

packages/core/client/src/collection-manager/interfaces/properties/index.ts
=> fix: automatically generate default values

packages/core/client/src/collection-manager/interfaces/nanoid.ts
=> fix(nanoid): nanoid availableTypes

packages/plugins/@nocobase/plugin-formula-field/src/client/index.tsx, packages/plugins/@nocobase/plugin-formula-field/src/client/scopes.tsx
1. Add approval workflow.
2. Add a formula field in application from block.
Field added correctly.
Page error.
None.
Component not added via old API (Provider).
Migrate to new API (`app.addComponents`).
=> fix(plugin-formula-field): fix component context

packages/core/client/src/collection-manager/interfaces/nanoid.ts, packages/core/client/src/collection-manager/interfaces/properties/index.ts, packages/core/client/src/collection-manager/interfaces/uuid.ts, packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx
=> fix(collection manager): collection manager primarykey & nanoid & uuid suport index setting

packages/core/client/src/schema-component/hooks/__tests__/addAppVersion.test.ts, packages/core/client/src/schema-component/hooks/__tests__/addAppVersion.test.tsx, packages/core/client/src/schema-component/hooks/addAppVersion.tsx, packages/core/client/src/schema-component/hooks/useDesignable.tsx
=> chore: add appVersion to Schema

packages/core/client/src/schema-component/antd/input/ReadPretty.tsx, packages/core/client/src/schema-component/antd/rich-text/style.ts
=> fix(RichText): unify style

packages/core/client/src/collection-manager/Configuration/components/index.tsx
=> fix(collection manager): throughCollection support fuzzy search

packages/core/client/src/collection-manager/interfaces/properties/index.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditFieldAction.tsx
=> refactor: nanoid &uuid autoFill 

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/client/src/schema-component/antd/page/Page.tsx
=> fix: left menu title modify

packages/plugins/@nocobase/plugin-workflow-request/package.json, packages/plugins/@nocobase/plugin-workflow/package.json, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Add comments for APIs.
Note API clearly.
- Frontend
- Backend
None.
None.
None.
=> chore(plugin-workflow): add comments

packages/plugins/@nocobase/plugin-formula-field/src/client/FormulaComponentFieldSettings.tsx, packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx
=> refactor: only numerical formula fields support format

packages/core/client/src/collection-manager/interfaces/properties/index.ts
=> refactor: select options configuration

packages/plugins/@nocobase/plugin-localization-management/src/server/plugin.ts
=> fix(localization): incorrect locale when first entering

packages/core/client/src/collection-manager/interfaces/sort.ts
=> refactor: sort field should not has defaultValue

packages/core/client/src/block-provider/TableBlockProvider.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockProvider.tsx
=> fix(gantt-block): gantt collapse & expand

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Add modifier or comments to workflow plugin API.
Make some API more clear.
- Frontend
- Backend
None.
None.
None.
=> refactor(plugin-workflow): adjust comments

packages/core/client/src/modules/fields/component/SubTable/subTablePopoverComponentFieldSettings.tsx
=> fix: sub -table support allowSelectExistingRecord setting

packages/core/client/src/user/EditProfile.tsx, packages/plugins/@nocobase/plugin-users/src/server/collections/users.ts, packages/plugins/@nocobase/plugin-users/src/server/migrations/20240410152410-update-phone-interface.ts
Close T-3958, #4003
由于不同国家号码验证问题，暂时移除用户表的手机号字段验证规则，后续提供更好的解决方案。
=> fix(users): remove phone validation due to incorrect check of foreign phone numebrs

packages/core/client/src/modules/fields/component/Tag/tagComponentFieldSettings.tsx
=> fix: tag filed setting

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts, packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/__tests__/trigger.test.ts
Support association actions to trigger.
Make post-action event on `categories/1/posts:create` to be triggerable.
- Frontend
- Backend
- ActionTrigger
Through cases.
None.
None.
=> feat(plugin-workflow-action-trigger): support association actions to trigger

packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx
=> fix: after selecting all, bulk update prompts for unselected data

packages/core/client/src/schema-initializer/utils.ts, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: remove active field should not clear value

packages/core/client/src/schema-component/antd/quick-edit/QuickEdit.tsx
=> fix: sub-table big field should support variable default value

packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockProvider.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/gantt.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/task-gantt-content.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/components/other/style.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/components/task-item/task-item.tsx
=> refactor: gantt block

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx
=> fix(defaultValue): fix the issue of default values disappearing after refreshing the page

packages/core/client/src/schema-initializer/utils.ts
=> fix(filterForm): avoid duplicate names

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/action/utils.ts
=> fix: deletion of operation linkage rules does not take effect in real time

packages/core/client/src/collection-manager/templates/components/sql-collection/FieldsConfigure.tsx
=> fix(sql-collection): can't select interface when setting fields

packages/core/client/src/modules/blocks/data-blocks/details-multi/detailsWithPaginationSettings.tsx, packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx
=> fix(data-scope): reset page number when setting block data scope

packages/plugins/@nocobase/plugin-users/src/server/collections/users.ts, packages/plugins/@nocobase/plugin-users/src/server/migrations/20240418101937-update-system-fields.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts
=> fix: missing fields

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/modules/fields/component/DatePicker/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-component/antd/form-item/FormItem.Settings.tsx, packages/plugins/@nocobase/plugin-action-bulk-update/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-action-duplicate/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/fields/manyToMany/schemaSettings1.test.ts
close T-4025
修改为了下图这样（不显示 Allow add new data）
=> fix(subTable): should not display Allow add new data option

packages/core/client/src/schema-component/antd/form-dialog/index.tsx, packages/core/client/src/schema-settings/LinkageRules/index.tsx
=> perf(LinkageRules): solve lagging problems

packages/core/client/src/collection-manager/templates/tree.tsx
=> fix: tree collection target error

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix(linkage-rule): linkage rule support empty condiction

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx
=> fix: association select support adding mode

packages/core/client/src/schema-initializer/items/DataBlockInitializer.tsx, packages/core/client/src/schema-initializer/utils.ts
=> feat: add filterOtherRecordsCollection for DataBlockInitializer

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Add checker for periodically dispatching.
In some edge cases, triggered workflows not start to process.
- Frontend
- Backend
- Workflow plugin
None.
None.
None.
=> feat(plugin-workflow): add checker for periodically dispatching

packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/ScheduleEventTrigger/configuration.test.ts
=> fix: scheduleEventTrigger

packages/core/client/src/schema-component/antd/action/ActionBar.tsx
=> style: actionBar style improve

packages/core/client/src/schema-component/antd/space/index.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-initializer/utils.ts
=> style: tableActionColumn style improve

packages/core/client/src/schema-component/antd/grid/Grid.tsx
=> fix: grid schema 

packages/core/client/src/collection-manager/Configuration/AddCollectionAction.tsx, packages/core/client/src/collection-manager/templates/components/PresetFields.tsx, packages/core/client/src/collection-manager/templates/properties/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts
=> refactor: collection template support presetFieldsDisabled

packages/plugins/@nocobase/plugin-acl/src/server/__tests__/users.test.ts, packages/plugins/@nocobase/plugin-users/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts
=> fix(users): improve users:updateProfile

packages/core/client/src/collection-manager/interfaces/password.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/CollectionFields.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/CollectionFieldInterfaceSelect.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/schema/collectionFields.ts
=> refactor:  external data source collection manager

packages/plugins/@nocobase/plugin-workflow/src/client/CanvasContent.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
* Add "Go back" button to no result workflow page.
* Add hint on executed workflow.
* Disable trigger title editing in executed workflow.
Refine experiences.
- Frontend
- Workflow client and locale.
- Backend
None.
None.
None.
=> fix(plugin-workflow): refine experience

packages/core/client/src/schema-component/antd/input-number/ReadPretty.tsx
=> fix: number field support separator setting

packages/core/client/src/schema-component/antd/input-number/__tests__/input-number.test.tsx
=> test: input  number separator test

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/__tests__/trigger.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/executions.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/nodes.test.ts
Add test cases.
For increase coverage.
- Frontend
- Backend
- Workflow test cases.
None.
None.
None.
=> test(plugin-workflow): add test cases

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Refresh the list after sync.
Sync action will reload enabled status of all workflow, refresh after sync will be more convenience.
- Frontend
- Add refresh invoking after sync action.
- Backend
None.
None.
None.
=> feat(plugin-workflow): refresh the list after sync

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
=> fix: missing pageSize parameters when setting column field sorting

packages/core/client/src/schema-component/hooks/useFieldModeOptions.tsx
=> refactor: association field support sub-table & sub-detail which target collection is tree collection

packages/core/client/src/modules/blocks/data-blocks/grid-card/SetTheCountOfColumnsDisplayedInARow.tsx, packages/core/client/src/modules/blocks/data-blocks/grid-card/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/grid-card/gridCardBlockSettings.ts, packages/core/client/src/schema-component/antd/grid-card/GridCard.Designer.tsx
Extract the duplicate code to the SetTheCountOfColumnsDisplayedInARow component.
=> refactor: extract to SetTheCountOfColumnsDisplayedInARow

packages/core/acl/src/acl.ts, packages/core/logger/package.json, packages/core/server/src/gateway/index.ts, yarn.lock
=> fix(logger): gateway log cache issue && upgrade winston

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
Fix error log in variable component
Mistaken usage of `console.error`.
- Frontend
- Variable.TextArea
- Backend
None.
None.
None.
=> fix(client): fix error log in variable component

packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/datablocks.test.ts, packages/plugins/@nocobase/plugin-workflow-parallel/src/client/__e2e__/parallelBranch.test.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/calculationNode/formulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/calculationNode/mathEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoBasicType.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoMathEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesBasicType.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesMathEngine.test.ts
Fix typo.
Typo
- Frontend
- Workflow e2e
- Backend
None.
None.
None.
=> fix(plugin-workflow): fix e2e typo

packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
Fix response log in request instruction.
Log of request node should be different between success and failure. And need response status instead of job status.
- Frontend
- Backend
- Request instruction.
None.
None.
None.
=> fix(plugin-workflow-request): fix response log

packages/core/client/src/collection-manager/Configuration/DeleteCollectionAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> fix: bulk delete collection field should not close modal

packages/core/client/src/collection-manager/templates/view.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditCollectionAction.tsx
=> refactor: external data source view collection createMainOnly

packages/core/client/src/modules/actions/ActionSchemaToolbar.tsx
=> fix: actionSchemaToolbar support x-toolbar-props

packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoMathEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesMathEngine.test.ts
=> test conditionNode e2e

packages/core/client/src/schema-component/antd/action/context.tsx
=> fix: configure data scope in action permission reporting error

packages/core/client/src/modules/actions/add-child/CreateChildInitializer.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> style: add child action style improve

packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoMathEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesMathEngine.test.ts
=> test: optimal calculationNode e2e

packages/core/client/src/collection-manager/templates/tree.tsx
=> fix: create tree collection field

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> fix:  main collection should support title field setting

packages/core/server/src/application.ts, packages/plugins/@nocobase/plugin-logger/src/client/LogsDownloader.tsx, packages/plugins/@nocobase/plugin-logger/src/server/resourcer/logger.ts
=> fix(logger): list log files by application name

packages/plugins/@nocobase/plugin-kanban/src/client/CreateAndSelectSort/index.tsx
=> fix: create kanban block reporting error

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix: table column should support blank column occupancy

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> fix: after setting title field the collection data should refresh

packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx, packages/core/client/src/schema-component/antd/input-number/ReadPretty.tsx, packages/core/client/src/schema-component/antd/input-number/__tests__/input-number.test.tsx, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/color/schemaInitializer.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/integer/schemaSettings.test.ts
=> fix: accuracy loss in bigint field read pretty

packages/core/client/src/collection-manager/Configuration/AddCollectionAction.tsx, packages/core/client/src/collection-manager/templates/components/PresetFields.tsx, packages/core/client/src/collection-manager/templates/properties/index.ts, packages/core/client/src/collection-manager/templates/tree.tsx
=> refactor: tree collection support presetFieldsDisabledIncludes

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> fix: the inherited field should be able to be set as the title field

packages/plugins/@nocobase/plugin-data-visualization/src/client/utils.ts
=> fix(data-vi): transform values of multiple selection fields to labels

packages/core/client/src/user/Help.tsx
=> fix: change License link

packages/core/client/src/powered-by/index.tsx, packages/core/client/src/user/Help.tsx
Fix typo in link target
1. Click "Home page" in toolbar
2. Click "Handbook" in toolbar
Two new tabs opened.
One tab on the handbook page
=> fix: Fix typo in link target

packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useFormVariable.ts
=> fix: useCurrentFormVariable 

packages/core/database/src/collection.ts, packages/core/database/src/database.ts, packages/core/logger/src/config.ts, packages/core/logger/src/format.ts, packages/core/logger/src/logger.ts, packages/core/logger/src/system-logger.ts, packages/core/server/src/application.ts, packages/core/server/src/locale/locale.ts, packages/core/server/src/plugin-manager/plugin-manager.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/repositories/collection-repository.ts
1. Add `dailyRotateFile` to default logger transport under development environment
2. Add `trace` level
3. Adjust some logs to `trace` level
close T-4306
=> feat(logger): add `dailyRotateFile` to default transport & add `trace` level

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> refactor: collection manager setting title field

packages/core/client/src/collection-manager/interfaces/unixTimestamp.tsx, packages/core/client/src/schema-component/antd/unix-timestamp/UnixTimestamp.tsx, packages/core/client/src/schema-component/antd/unix-timestamp/__tests__/UnixTimestamp.test.tsx
=> refactor: the default accuracy of the UnixTimestamp field is second

packages/core/client/src/block-provider/hooks/index.ts
=> fix: error in deleting data query after block linkage filtering

packages/plugins/@nocobase/plugin-action-custom-request/src/client/__tests__/initializer/CustomRequestInitializer.test.tsx, packages/plugins/@nocobase/plugin-action-custom-request/src/client/initializer/CustomRequestInitializer.tsx
=> fix(plugin): resolve error caused by duplicate addition of custom request

packages/core/client/src/schema-settings/LinkageRules/useValues.ts
… are selected
- Frontend
- Backend
=> refactor: form linkage rule to cancel assignment when multiple fields are selected

packages/core/client/src/modules/fields/component/SubTable/subTablePopoverComponentFieldSettings.tsx
=> fix: sub-table support allowAddNew setting

packages/core/client/src/modules/blocks/data-blocks/table/TableActionColumnInitializers.tsx
=> chore: add group title to Table item action settings

packages/core/client/src/modules/actions/submit/updateSubmitActionSettings.tsx
=> fix: missing linkage rules configuration for submit action in edit form

packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/forms/custom.tsx
1. Add custom form block in manual node UI configuration.
2. Add a single line text field.
3. Add a checkbox field.
Checkbox field should be added.
Field added as another single line text type.
None.
Schema references miss managed.
Fix schema references by hooks.
=> fix(plugin-workflow-manual): fix custom form field wrong interface in manual node

packages/core/client/src/schema-initializer/utils.ts
=> fix:  association field  enablement affecting block field states

packages/core/client/src/schema-component/hooks/useFieldModeOptions.tsx
=> fix: disable cascading select component mode for association field in sub-table

packages/core/client/src/block-provider/FormBlockProvider.tsx
=> fix(client): fix data template style

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings1.test.ts
close T-4412
add test case for #4531.
=> test(block-templates): add test case

packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
=> fix: show cascade select when no data in edit form

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/plugins/@nocobase/plugin-field-formula/src/client/components/Formula/Result.tsx
=> fix: data filtering and formula field value errors after subtable record selection

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx
Allow to select any path of a variable in condition node.
Easy to do calculation in condition node, same as in calculation node.
- Frontend
- Condition node.
- Backend
None.
Usage by user.
=> feat(plugin-workflow): allow to select any path of a variable in condition node

packages/core/client/src/schema-component/antd/unix-timestamp/UnixTimestamp.tsx
=> fix: correct precision conversion error for Unix timestamp in readPretty

packages/core/client/src/schema-component/antd/page/FixedBlock.tsx, packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx, packages/plugins/@nocobase/plugin-kanban/src/client/KanbanBlockProvider.tsx, packages/plugins/@nocobase/plugin-kanban/src/client/board/hook.ts
=> fix: compatibility issues with historical kanban and iframe block

packages/core/client/src/variables/VariablesProvider.tsx, packages/core/client/src/variables/__tests__/removeThroughCollectionFields.test.tsx, packages/core/client/src/variables/__tests__/useVariables.test.tsx
=> fix(variable): should remove through collection field

packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx
=> fix: style issues for gridCard in mobile client

packages/core/client/src/locale/ja_JP.json, packages/core/client/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx
=> fix: iframe block loses height when set to default

packages/core/actions/src/__tests__/list-action.test.ts, packages/core/actions/src/actions/list.ts, packages/core/data-source-manager/src/default-actions/list.ts
Support filtering child nodes in tree collection block.
fix T-4497
- Frontend
- Backend
- Set `tree=true` to `tree=false` as `filter` parameter is not empty when filtering tree collection.
https://github.com/nocobase/nocobase/assets/3250534/bd34d25e-c7c7-47ef-8f55-feb5e3bd8e40
=> feat(tree-block): support filtering child nodes

packages/plugins/@nocobase/plugin-action-export/src/client/useExportAction.tsx
=> fix(export): export button remaining in loading state after cancel

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix: table block height issue with a small amount data

packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Map.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/Map.tsx
=> fix: missing height in map history block

packages/core/client/src/schema-component/antd/block-item/BlockItem.tsx, packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx, packages/core/client/src/schema-component/antd/page/style.ts, packages/core/client/src/schema-component/hooks/useBlockSize.ts
=> fix: block height calculation

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx
=> style: markdown block style improve

packages/plugins/@nocobase/plugin-workflow/src/client/components/AssignedFieldsFormSchemaConfig.tsx
Add card layout for assigning fields.
To make the assigning area be different with other node configuration fields.
- Frontend
- AssignedFieldsFormSchemaConfig.tsx
- Backend
None.
None.
=> refactor(plugin-workflow): add card layout for assigning fields

packages/core/client/src/schema-component/antd/block-item/BlockItem.tsx, packages/core/client/src/schema-component/antd/grid/Grid.tsx, packages/core/client/src/schema-settings/SchemaSettingsBlockHeightItem.tsx
=> style(client): grid style improve

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx
=> fix: client test

packages/core/client/src/modules/blocks/data-blocks/list/__tests__/createListBlockSchema.test.ts, packages/core/client/src/modules/blocks/data-blocks/list/createListBlockUISchema.ts, packages/core/client/src/modules/blocks/filter-blocks/form/__tests__/createFilterFormBlockSchema.test.ts, packages/core/client/src/modules/blocks/filter-blocks/form/createFilterFormBlockSchema.ts, packages/core/client/src/schema-component/antd/action/ActionBar.tsx, packages/core/client/src/schema-component/antd/form-v2/hook.ts, packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx, packages/core/client/src/schema-component/antd/grid-card/hooks.ts, packages/plugins/@nocobase/plugin-kanban/src/client/board/hook.ts, packages/plugins/@nocobase/plugin-kanban/src/client/board/style.ts
fix #4654
close T-4543
- Frontend
- Backend
=> fix: form/detail/filter block height

packages/plugins/@nocobase/plugin-data-visualization/src/client/configure/schemas/configure.ts
=> feat(data-vi): allows to use json5 in chart json config

packages/core/client/src/schema-component/antd/action/ActionBar.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterBlockInitializer.tsx
=> fix: chart block actionBar style

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> fix: restore field height spacing after removing description in form

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx, packages/core/client/src/schema-component/hooks/useBlockSize.ts, packages/core/client/src/schema-settings/SchemaSettingsBlockHeightItem.tsx
…nd approval block
- Frontend
- Backend
=> fix:  block height calculation for full-height tabs in workflow  approval initiation and approval block

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
=> refactor: sub-table disabled dragSort

packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> fix: refresh list automatically after closing modal following adding action

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockProvider.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Block.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/Block.tsx
=> fix: select field set as title field

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
Fix undefined error of action trigger.
1. Add a trigger workflow button for users (table/form).
2. Click the button.
Success message from server.
Error with 404.
None.
Middleware misused.
Fix the injection of middleware.
=> fix(plugin-workflow): fix undefined error of action trigger

packages/core/client/src/schema-component/antd/action/ActionBar.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/hook.ts, packages/core/client/src/schema-component/antd/grid/Grid.tsx
=> fix(grid): grid style

packages/plugins/@nocobase/plugin-data-visualization/src/server/plugin.ts
=> chore(data-vi):  remove `addMigrations`

packages/core/client/src/block-provider/hooks/index.ts
=> fix: variable parse issue in link action  with variables in paths

packages/core/client/src/modules/fields/component/Tag/e2e/schemaSettings.test.ts, packages/core/client/src/modules/fields/component/Tag/e2e/templatesOfBug.ts, packages/core/client/src/modules/fields/component/Tag/tagComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/association-field/Editable.tsx, packages/core/client/src/schema-component/antd/association-field/InternalPopoverNester.tsx
=> fix: tag component should support enable link

packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/page/style.ts
=> fix: double scrollbar on mobile client causing scrolling issues

packages/core/build/src/tarPlugin.ts
=> fix: tar build bug

packages/core/server/src/locale/locale.ts, packages/plugins/@nocobase/plugin-error-handler/src/server/server.ts, packages/plugins/@nocobase/plugin-localization/src/server/actions/localization.ts, packages/plugins/@nocobase/plugin-localization/src/server/plugin.ts
Allows to use l10n plugin resources in backend
- Frontend
- Backend
1. Allows to register resources storer in `app.localeManager` and load resources from storers
2. Register custom l10n resources storer when loading plugin-localization
=> feat(l10n): allows to use l10n plugin resources in backend

packages/core/client/src/collection-manager/Configuration/OverridingCollectionField.tsx
=> fix: error when overriding sorting field

packages/core/client/src/application/schema-settings/utils/createModalSettingsItem.tsx, packages/core/client/src/application/schema-settings/utils/createSelectSettingsItem.tsx, packages/core/client/src/schema-component/antd/filter/DynamicComponent.tsx, packages/core/client/src/schema-component/antd/filter/index.ts
=> fix: export filter component

packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
…n template blocks
- Frontend
- Backend
=> fix: missing data on first load in cascading association field component within template block

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-static.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/StaticScheduleTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts
Schedule workflow duplicated triggering.
Can not reproduce.
No duplicated triggering.
Duplicated triggered.
#4701.
Not sure.
Add test case.
=> test(plugin-workflow): check for duplicated triggering

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx
Add mode column to show if sync or not in workflow list.
Sync or not may effect some configuration or executions. Better to show it more obviously.
- Frontend
- Workflow list
- Workflow canvas
- Backend
None.
None.
None.
=> feat(plugin-workflow): add mode column to show if sync or not

packages/core/client/src/block-provider/hooks/useParsedFilter.ts, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix(data-scope): avoid cyclic invocation of the same API

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts
Add deferred option for async workflow triggering.
Some workflow is not planed to be start immediately.
- Frontend
- Backend
- Workflow plugin core.
Through cases.
None.
None.
=> refactor(plugin-workflow): add deferred option for async workflow triggering

packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2eUtils.ts
=> test: approvals workflow e2e

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/TitleField.tsx
=> fix: external data source not reloading when title field is updated

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/components/Entity.tsx, packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/utils.tsx
=> fix(graph-collection): incorrect highlight linkage for association field

packages/core/client/src/schema-component/hooks/useBlockSize.ts
=> fix: table height shrinking with large data set at full height

packages/core/server/src/commands/create-migration.ts
| 🇺🇸 English |  Version calculation error when creating migration |
| 🇨🇳 Chinese |  创建 migration 时版本计算错误 |
=> fix: version calculation error when creating migration

packages/core/client/src/schema-component/antd/association-field/InternalNester.tsx
=> fix: sub-form acl check in workflow

.github/workflows/nocobase-test-backend.yml, packages/core/database/src/collection.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/field-load.test.ts
#4814 
| 🇺🇸 English |  should not add field when binding error     |
| 🇨🇳 Chinese |  修复字段绑定报错之后添加无效字段的问题 |
=> fix(database): should not add field when binding error

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/CollectionTitle.tsx
=> fix: external data source filterTargetKey undefined in filter action

packages/core/client/src/schema-component/antd/list/List.tsx
=> fix : scrollbar issue at default height of list block

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Show entire error in node result for better debugging.
Expose entire error into node result when node throw error.
None.
None.
| 🇺🇸 English | Expose entire error into node result |
| 🇨🇳 Chinese | 将节点执行的错误完整地输出到节点的执行结果中 |
=> chore(plugin-workflow): expose entire error into node result

packages/core/app/client/public/robots.txt, packages/core/cli/nocobase.conf.tpl
| 🇺🇸 English |   Disable search engine indexing  |
| 🇨🇳 Chinese |  禁止搜索引擎收录  |
=> chore: disable search engine indexing

packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts
| 🇺🇸 English |    export with custom field title       |
| 🇨🇳 Chinese |    修复导出按钮自定义标题不生效的问题       |
=> fix(action-export): export with custom field title

.github/workflows/manual-build-pro-image.yml
CI action for pro PRs is not working.
Trigger the manual action for pro PRs throw error.
None.
| 🇺🇸 English | Fix CI script error for pro pr |
| 🇨🇳 Chinese | 修复 CI 脚本报错问题 |
=> fix(ci): fix ci script error for pro

packages/plugins/@nocobase/plugin-field-formula/src/client/components/Formula/Result.tsx
| 🇺🇸 English |    page freeze issue when hiding formula fields through linkage rules       |
| 🇨🇳 Chinese |     在表单区块联动规则中设置隐藏公式字段时页面卡死      |
=> fix: page freeze issue when hiding formula fields through linkage rules

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/index.ts, packages/core/client/src/modules/actions/__e2e__/link/basic.test.ts, packages/core/client/src/modules/actions/link/customizeLinkActionSettings.tsx, packages/core/client/src/modules/actions/link/useURLAndParamsSchema.tsx, packages/core/client/src/modules/menu/LinkMenuItem.tsx, packages/core/client/src/modules/menu/__e2e__/schemaInitializer.test.ts, packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/client/src/schema-component/antd/menu/Menu.tsx, packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx, packages/plugins/@nocobase/plugin-block-iframe/src/client/schemaSettings.tsx
Unified interaction.
1. First, refactor the previous code by extracting the common code into a hook.
2. Then, use the extracted hook to implement the functionality.
close T-4797
merge https://github.com/nocobase/docs/pull/105
| 🇺🇸 English |      The Link menu supports setting Search params and using variables.     |
| 🇨🇳 Chinese |     Link 菜单支持设置 Search params 和支持使用变量。      |
=> feat(Menu): add support for setting search params and using variables in links

.github/workflows/e2e.yml
=> chore: fetch-depth=0

.github/workflows/nocobase-test-backend.yml, packages/core/server/src/sync-manager.ts
1. To let user of syncManager to know if it is available.
2. Prepare CI services for testing.
1. Add `available` getter to syncManager.
2. Add Redis service to CI.
None.
None.
=> refactor(server): sync manager and ci

packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
Approval Workflow Withdrawal Button Settings Adjustment
Add Enable Withdrawal Button locator
| 🇺🇸 English |Add locator for approval workflow to enable the withdraw button|
| 🇨🇳 Chinese |增加审批工作流启用撤回按钮的locator|
=> test: add locator for approval workflow to enable the withdraw button

.github/workflows/release-next.yml, .github/workflows/release.yml, packages/core/cli/src/commands/upgrade.js
=> chore: next release ci

packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx
| 🇺🇸 English |    the iframe block fails to load properly after configuring the URL    |
| 🇨🇳 Chinese |    Iframe 区块配置 URL 之后无法正常加载      |
=> fix: the iframe block fails to load properly after configuring the URL

packages/plugins/@nocobase/plugin-action-import/src/client/useImportAction.ts
| 🇺🇸 English |       x-data-source in headers for external data source import    |
| 🇨🇳 Chinese |        外部数据源导入headers 传入 x-data-source   |
=> fix: x-data-source in headers for external data source import

packages/core/database/src/decorators/transaction-decorator.ts, packages/core/database/src/model.ts, packages/core/database/src/sync-runner.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/fields/auto-incr-field.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/models/field.ts
=> fix: create multiple auto incr field in mysql

packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
=> chore(action-import): report sequelize error message

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/ScopeSelect.tsx
… data scope list
| 🇺🇸 English |      Fix dataSourceKey parameter error for multiple data sources in ACL data scope |
| 🇨🇳 Chinese |     ACL 多数据源数据范围dataSourceKey 传参错误      |
=> fix: dataSourceKey parameter error for external  data sources in acl data scope

packages/core/client/src/collection-manager/interfaces/properties/operators.ts, packages/core/client/src/collection-manager/interfaces/richText.ts, packages/core/client/src/schema-initializer/utils.ts
| 🇺🇸 English |        Adjust rich text filter to Input component   |
| 🇨🇳 Chinese |      富文本筛选时换成 Input 组件     |
=> refactor: adjust rich text filter to Input component

packages/plugins/@nocobase/plugin-field-formula/src/client/components/Formula/Result.tsx
| 🇺🇸 English |        issue when deleting object with formula fields in sub-form  |
| 🇨🇳 Chinese |        子表单中配置了公式字段，点击子表单对象删除按钮异常  |
=> fix: exception when deleting object with formula fields in sub-form

.env.example, packages/core/cli/src/commands/start.js, packages/core/server/src/plugin.ts, packages/core/server/src/sync-manager.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Add cluster mode for enable multi-core processes.
Start app in cluster mode when env is set.
None.
None.
| 🇺🇸 English | Add cluster mode for starting app |
| 🇨🇳 Chinese | 新增多核模式启动应用 |
| 🇺🇸 English | [Environment Variables](https://docs.nocobase.com/welcome/getting-started/env#cluster_mode) |
| 🇨🇳 Chinese | [环境变量](https://docs-cn.nocobase.com/welcome/getting-started/env#cluster_mode) |
=> feat(server): add cluster mode for starting app

packages/core/client/src/collection-manager/interfaces/markdown.ts, packages/core/client/src/collection-manager/interfaces/properties/operators.ts, packages/core/client/src/collection-manager/interfaces/richText.ts, packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/interfaces/markdown-vditor.tsx
…tering
| 🇺🇸 English |      Adjust the markdown field to use the input component in filtering operations   |
| 🇨🇳 Chinese |     调整 markdown 字段在筛选操作中使用Input 作为输入控件      |
=> refactor: adjust the markdown field to use the input component in filtering

packages/core/client/src/modules/variable/__e2e__/currentObject.test.ts, packages/core/client/src/modules/variable/__e2e__/templates.ts, packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useIterationVariable.ts
Complements the collection context of the association field in the [SubTable](https://github.com/nocobase/nocobase/blob/1b3f96f424a4d17efe53f98bedd66cf3bd435cd7/packages/core/client/src/schema-component/antd/association-field/SubTable.tsx#L91-L259) component.
close T-4874
| 🇺🇸 English |       Fix context error with 'current object' variable.    |
| 🇨🇳 Chinese |     修复“当前对象”变量上下文错误的问题。      |
=> fix(variable): fix context error with 'current object' variable

packages/core/client/src/schema-settings/SchemaSettings.tsx
Change the condition that whether the element is action or form field.
| 🇺🇸 English |  custom request linkage rules cannot be used  |
| 🇨🇳 Chinese |  无法使用自定义请求的联动规则 |
=> fix: custom request linkage rules cannot be used

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
Fix "Or" condition bug in collection trigger.
When "Or" conditions configured, event still triggered without respect the conditions.
Fix #4923.
None.
| 🇺🇸 English | Fix "Or" condition bug in collection trigger. |
| 🇨🇳 Chinese | 修复数据表事件中配置了“任意”触发条件不生效的问题。 |
=> fix(plugin-workflow): fix or condition bug in collection trigger

.github/workflows/build-pro-image.yml
=> fix: build image ci

packages/core/client/src/global-theme/type.ts, packages/core/client/src/schema-component/antd/card-item/style.ts, packages/plugins/@nocobase/plugin-mobile-client/package.json, packages/plugins/@nocobase/plugin-mobile/package.json, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/content/styles.ts, packages/plugins/@nocobase/plugin-mobile/src/client/pages/mobile-action-page/MobileActionPage.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/meta/category.ts, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/token-panel-pro/token-meta.json
Mobile theme token.
| 🇺🇸 English |  Add more theme token | 
| 🇨🇳 Chinese | 添加更多的主题 token |
=> fix: mobile style bug

packages/plugins/@nocobase/plugin-action-import/src/server/actions/import-xlsx.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
=> fix(action-import): import with createdBy & updatedBy field

packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlock.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockDesigner.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockInitializer.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/AntChart.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/configs.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/g2plot.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRendererProvider.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/locale/en-US.json, packages/plugins/@nocobase/plugin-data-visualization/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx
Adapt styles to mobile client.
1. Allows to set background to transparent in chart blocks.
2. Allows to hide padding in chart blocks.
3. Allows to set aspect ratio or fixed height for charts.
1. Allows to set background to transparent in chart blocks.
2. Allows to hide padding in chart blocks.
3. Allows to set aspect ratio or fixed height for charts.
| 🇺🇸 English |  Optimize style settings for chart blocks<br />1. Allows to set background to transparent in chart blocks.<br />2. Allows to hide padding in chart blocks.<br >3. Allows to set aspect ratio or fixed height for charts.           |
| 🇨🇳 Chinese | 优化图表区块的样式设置<br />1. 支持将图表区块设置为透明背景。<br />2. 支持隐藏图表区块的内边距。<br />3. 支持设置图形的宽高比或固定高度值。          |
| ---------- | …
=> feat(data-vi): optimize style settings for chart blocks

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/data-source/data-block/DataBlockProvider.tsx, packages/core/client/src/filter-provider/FilterProvider.tsx, packages/core/client/src/filter-provider/utils.ts, packages/core/client/src/schema-settings/SchemaSettingsConnectDataBlocks.tsx
fix #4905 
fix #4903 
None.
#4905 
#4903 
https://forum.nocobase.com/t/topic/201
None.
| 🇺🇸 English |       Migrate DataBlockCollector to DataBlockProvider.    |
| 🇨🇳 Chinese |     将  DataBlockCollector 迁移到  DataBlockProvider 中。   |
=> refactor: migrate DataBlockCollector to DataBlockProvider

package.json
| 🇺🇸 English |    ignore pro packages dir  |
| 🇨🇳 Chinese |   忽略 pro packages |
| 🇺🇸 English |    ignore pro packages dir  |
| 🇨🇳 Chinese |   忽略 pro packages |
=> fix: ignore pro

packages/core/client/src/global-theme/type.ts, packages/core/client/src/schema-component/antd/card-item/style.ts, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/meta/category.ts, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/token-panel-pro/token-meta.json
| 🇺🇸 English | Remove block token |
| 🇨🇳 Chinese |移除区块 token|
=> fix: remove block token

packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2eUtils.ts
Add custom action event workflow e2e
| 🇺🇸 English |Add custom action event workflow e2e|
| 🇨🇳 Chinese |增加自定义操作事件工作流e2e|
=> test: custom action e2e

packages/core/cli/templates/plugin/src/client/locale.ts, packages/core/client/src/i18n/i18n.ts
```diff
+ useT()
- usePluginTranslation()
```
```diff
+ tStr('some text')
- generatePluginTranslationTemplate('some text')
```
| 🇺🇸 English |optimize i18n utility functions in plugin templates|
| 🇨🇳 Chinese |优化插件模板中的 i18n 工具函数命名|
=> fix: i18n plugin utils

packages/core/client/src/i18n/i18n.ts, packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts
https://github.com/user-attachments/assets/241995cc-7ff6-4c80-a16c-d14612b7c15f
| 🇺🇸 English |remove i18n fallbackNS|
| 🇨🇳 Chinese |移除 i18n fallbackNS|
=> fix: remove i18n fallbackNS

packages/core/cli/templates/plugin/src/client/locale.ts
| 🇺🇸 English |improve i18n `tStr()`|
| 🇨🇳 Chinese |优化 i18n `tStr()` 函数|
=> fix: improve i18n `tStr()`

packages/plugins/@nocobase/plugin-acl/src/server/middlewares/with-acl-meta.ts
=> fix(acl): get allowedAction when condition is empty

packages/core/database/src/fields/number-field.ts, packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts
=> chore(action-export): format of number field

packages/core/client/src/collection-manager/Configuration/EditCollectionAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditCollectionAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/ConfigurationTable.tsx
| 🇺🇸 English |      collection manager support filterTargetKey setting      |
| 🇨🇳 Chinese |      所有表都可以配置 记录唯一标识符     |
=> fix: collection manager support filterTargetKey setting

packages/core/client/src/modules/blocks/data-blocks/form/fieldSettingsFormItem.tsx, packages/core/client/src/modules/blocks/filter-blocks/form/filterFormItemFieldSettings.ts, packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/bulkEditFormItemSettings.ts
| 🇺🇸 English |      required constraint becomes invalid after setting validation rules on form fields     |
| 🇨🇳 Chinese |       表单中字段的Set validation rules设置会取消必填限制    |
=> fix: required constraint becomes invalid after setting validation rules on form fields

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
close T-4927
| 🇺🇸 English | Table performance |
| 🇨🇳 Chinese |表格性能问题|
=> fix: table columns bug

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/ConfigurationTable.tsx
| 🇺🇸 English |      filter FilterTargetKeys options based on titleUsable     |
| 🇨🇳 Chinese |     根据titleUsable 筛选FilterTargetKeys的可选项      |
=> refactor: filter FilterTargetKeys options based on titleUsable

packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts
=> chore(action-export): error message when field not found

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts, packages/plugins/@nocobase/plugin-mobile-client/src/client/index.tsx, packages/plugins/@nocobase/plugin-mobile-client/src/locale/en-US.json, packages/plugins/@nocobase/plugin-mobile-client/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-mobile/package.json
| 🇺🇸 English |after closing the model, to reset the Form data|
| 🇨🇳 Chinese |当关闭弹窗后，应该重置表单数据|
=> feat: mobile modal bug

packages/core/client/src/schema-component/antd/action/utils.ts
| 🇺🇸 English |      linkage ruler for action buttons not working as expected     |
| 🇨🇳 Chinese |        按钮联动规则不符合预期   |
=> fix: linkage ruler for action buttons not working as expected

packages/core/client/src/acl/ACLProvider.tsx
| 🇺🇸 English |      issue with ACLCollectionFieldProvider field permission evaluation     |
| 🇨🇳 Chinese |      修复ACLCollectionFieldProvider字段权限判断错误      |
=> fix: issue with ACLCollectionFieldProvider field permission evaluation

packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |     disabled action to maintain font color on mouse hover      |
| 🇨🇳 Chinese |     禁用操作，鼠标hover操作字体不需要变色      |
=> fix: disabled action to maintain font color on mouse hover

packages/core/client/src/schema-component/antd/cascader/Cascader.tsx
| 🇺🇸 English |      unable to clear china region field     |
| 🇨🇳 Chinese |    中国行政区划字段没法清空       |
=> fix: unable to clear china region field

packages/core/client/src/schema-component/common/utils/uitls.tsx
| 🇺🇸 English |   markdown block should  supports the markdown syntax        |
| 🇨🇳 Chinese |    markdown 区块应该支持markdown 语法       |
=> fix:  markdown block should  supports the markdown syntax

packages/core/client/src/schema-initializer/items/index.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/initializers/CalendarFormActionInitializers.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/items/DeleteEventActionInitializer.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/items/index.ts
| 🇺🇸 English |     acl permission check issue for 'Delete Event' action      |
| 🇨🇳 Chinese |      Delete Event action权限判断错误     |
=> fix:  acl permission check issue for 'Delete Event' action

packages/plugins/@nocobase/plugin-backup-restore/src/server/dumper.ts
=> fix: backup file dir of sub apps

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/grid-card/GridCard.Decorator.style.ts
| 🇺🇸 English |    The style of the mobile menu button is incorrect       |
| 🇨🇳 Chinese |     移动端菜单按钮样式不对      |
=> style: action style improve

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx, packages/core/client/src/collection-manager/templates/components/sql-collection/FieldsConfigure.tsx
…n and view collection
| 🇺🇸 English |     source field type filtering association fields in sql collection & view collection      |
| 🇨🇳 Chinese |    sql表、视图表（保留多对一）中来源字段类型过滤关系字段       |
=> fix: source field type filtering association fields in sql collection & view collection

packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.style.ts, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/FilterAction.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/hideDivider.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/mobile-action-page/MobileTabsForMobileActionPage.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/index.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-blocks/settings-block/MobileSettings.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-blocks/settings-block/MobileSettingsBlockInitializer.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-blocks/settings-block/schemaSettings.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/content/initializer.tsx, packages/plugins/@nocobase/plugin-mobile/src/locale/en-US.json, packages/plugins/@nocobase/plugin-mobile/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-theme-editor/src/client/hooks/useThemeSettings.tsx
On mobile, users can also configure the app.
Copy the Settings block from the old mobile version to the new version.
None.
| 🇺🇸 English |      Support for adding setting blocks on mobile.     |
| 🇨🇳 Chinese |     支持在移动端添加设置区块。      |
=> feat: support to add Settings block in mobile

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
Fix bug.
Get the correct foreign key field value.
None.
None.
| 🇺🇸 English |      Fix the problem of incorrect filter value when using foreign key for filtering.     |
| 🇨🇳 Chinese |     修复使用外键进行筛选时，筛选值不正确的问题。      |
=> fix: correct foreign key value errors

packages/core/client/src/data-source/collection/CollectionManagerProvider.tsx
| 🇺🇸 English |`ExtendCollectionsProvider` cache bug|
| 🇨🇳 Chinese |`ExtendCollectionsProvider` 缓存 BUG|
=> fix: extend collection cache bug

packages/core/database/src/sync-runner.ts
=> fix(database): skip table doesn't exist

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
| 🇺🇸 English |  Missing sort parameter |
| 🇨🇳 Chinese |  丢失排序参数  |
=> fix(client): missing sort parameter

packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx, packages/plugins/@nocobase/plugin-block-iframe/src/client/__e2e__/inPopup.test.ts, packages/plugins/@nocobase/plugin-block-iframe/src/client/__e2e__/templates.ts
Fix BUG.
Changes to the src of an Iframe can affect the browser's history, which can cause the popup window to not close and open properly. The fix is to prevent the src of the Iframe from changing multiple times.
close T-4940
See E2E.
| 🇺🇸 English |      Fix the issue that popup windows containing Iframe blocks do not work properly.     |
| 🇨🇳 Chinese |     修复包含 Iframe 区块的弹窗无法正常工作的问题。      |
=> fix(iframe): fix the popup contained Iframe block does not work

packages/core/database/src/__tests__/inhertits/collection-inherits.test.ts, packages/core/database/src/inherited-collection.ts
=> fix: load parent field in inherited collection

packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/styles.ts
| 🇺🇸 English |    table column configuration fields action style improve       |
| 🇨🇳 Chinese |   表格全高状态下配置字段列样式异常        |
=> style: table column configuration fields action style improve

packages/plugins/@nocobase/plugin-data-visualization/package.json
=> fix(data-vi): dependency typo

packages/core/database/src/__tests__/query-interface/query-interface.test.ts, packages/core/database/src/query-interface/mysql-query-interface.ts
=> fix: quote table name in mysql query interface

packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx
| 🇺🇸 English |    gridCard blocks cannot flip pages when using API data sources       |
| 🇨🇳 Chinese |      网格区块使用api数据源时不能翻页     |
=> fix: gridCard blocks cannot flip pages when using API data sources

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx
| 🇺🇸 English |     html rendering in markdown block      |
| 🇨🇳 Chinese |    html在markdown中不生效       |
=> fix: html rendering in markdown block

packages/plugins/@nocobase/plugin-multi-app-manager/package.json, yarn.lock
=> chore: update mysql2 version

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/BreadcumbTitle.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/ConfigurationTable.tsx
| 🇺🇸 English |      修复数据源管理中数据源状态的显示     |
| 🇨🇳 Chinese |    incorrect display of data source status in data source management       |
=> fix: the display of data source status

packages/core/client/src/schema-component/antd/page/Page.tsx, packages/core/client/src/schema-component/antd/page/__tests__/page.test.tsx
Fix BUG.
- The embed plugin need to add a new route for page tabs.
- Use dynamic pathname.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/tabs/fmvu0hrcp8m/popups/z7tn73yxs73/filterbytk/109
None.
| 🇺🇸 English |      Fix the problem that the page is not normal after clicking the page tab.     |
| 🇨🇳 Chinese |     修复点击页面 tab 后，页面不正常的问题。      |
=> fix(embed): fix the problem that switching tabs doesn't work

packages/core/client/src/locale/zh-CN.json, packages/core/client/src/modules/blocks/other-blocks/markdown/markdownBlockSettings.ts, packages/core/client/src/schema-settings/SchemaSettingsRenderEngine.tsx
| 🇺🇸 English |  markdown block setting of rendering engine         |
| 🇨🇳 Chinese |     修改markdown 区块设置中模板引擎文案      |
=> refactor: markdown  block setting of rendering engine

packages/plugins/@nocobase/plugin-kanban/src/client/KanbanBlockInitializer.tsx
Fix BUG.
The componentType of Kanban should be "Kanban".
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/tabs/fmvu0hrcp8m/popups/z7tn73yxs73/filterbytk/69
None.
| 🇺🇸 English |      Fix Kanban not being able to create blocks with templates.     |
| 🇨🇳 Chinese |     修复看板不能用模板创建区块的问题。      |
=> fix(kanban): fix Kanban not being able to create blocks with templates

packages/core/client/src/locale/zh-CN.json
Update the chaniese translation for "Style".
Update the chaniese translation for "Style".
| 🇺🇸 English |   Update the chaniese translation for "Style".        |
| 🇨🇳 Chinese |   更新"Style"的中文翻译为样式     |
- [ x ] All changes have been self-tested and work as expected
- [ x ] Test cases are updated/provided or not needed
- [ x ] Doc is updated/provided or not needed
- [ x ] Component demo is updated/provided or not needed
- [ x ] Changelog is provided or not needed
- [ x ] Request a code review if it is necessary
=> feat: update the chaniese translation for "Style".

README.ja-JP.md, README.md, README.zh-CN.md
=> 日本語readmeを追加する

packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/action.test.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts
=> feat: create file record via path

packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx, packages/core/client/src/schema-settings/LinkageRules/components/LinkageHeader.tsx
| 🇺🇸 English |      Error adjusting order of linkage rules     |
| 🇨🇳 Chinese |     调整联动规格顺序时出现错误      |
=> fix: error adjusting order of linkage rules

packages/plugins/@nocobase/plugin-data-visualization/src/client/configure/schemas/configure.ts, packages/plugins/@nocobase/plugin-data-visualization/src/locale/en-US.json, packages/plugins/@nocobase/plugin-data-visualization/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts
| 🇺🇸 English | Allow to set `DISTINCT` for chart query measures |
| 🇨🇳 Chinese | 支持给图表查询度量配置”去重“选项    |
=> feat(data-vi): allow to set distinct for query measures

packages/core/actions/src/actions/list.ts, packages/core/client/src/block-provider/TableBlockProvider.tsx, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx, packages/core/client/src/schema-component/antd/table-v2/__tests__/Table.settings.test.tsx, packages/core/client/src/schema-settings/SchemaSettingsPagingMode.tsx, packages/core/client/src/schema-settings/index.ts, packages/core/data-source-manager/src/default-actions/list.ts
| 🇺🇸 English |      Performance optimization of big data tables     |
| 🇨🇳 Chinese |      大数据量表性能优化     |
=> refactor: support simple Paginate

packages/core/client/src/block-provider/FormBlockProvider.tsx
Fix BUG.
Clear out the form's default values before initializing the edit form's values.
https://tasks.aliyun.nocobase.com/admin/n98vgrxn4f4/popups/l5ty8dbb996/puid/b3vts0scuen/filterbytk/182
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/174
None.
=> fix(varaible): resolve error on template block submission

packages/core/client/src/schema-settings/SchemaSettings.tsx
| 🇺🇸 English |   issue with button assigning values         |
| 🇨🇳 Chinese |     按钮字段赋值错误，历史配置的字段也赋值    |
=> fix: issue with button assigning values

packages/core/client/src/collection-manager/templates/properties/index.ts, packages/core/client/src/locale/zh-CN.json
| 🇺🇸 English |       description for simple pagination mode    |
| 🇨🇳 Chinese |      为简单分页模式添加描述     |
=> refactor: description for simple pagination mode

packages/core/client/src/block-provider/FilterFormBlockProvider.tsx
| 🇺🇸 English |    filter form block action bar style improve       |
| 🇨🇳 Chinese |     调整筛选表单按钮靠右      |
=> style: filter form block action bar style improve

packages/core/server/src/pub-sub-manager/handler-manager.ts
Fix usage of package not imported.
None.
None.
None.
=> fix(server): fix import crypto in pub sub manager

packages/core/client/src/schema-component/antd/page/PagePopups.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/header/tabs/MobilePageTabs.tsx
Fix BUG.
None.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/194
None.
| 🇺🇸 English |       Fix the problem of errors on mobile pages.    |
| 🇨🇳 Chinese |      修复移动端页面报错的问题。     |
=> fix(mobile): avoid crashing

packages/core/client/src/schema-component/antd/markdown/demos/demo2.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useURLSearchParamsVariable.ts
react-router 的 hooks 必须要在 Router 上下文中调用，不然就会报错。demo 里都是单独的上下文，所以如果组件中有使用 react-router 的 hooks 就需要在demo 外面包一下 Route
=> fix：markdown demo rendering failure

packages/core/client/src/schema-component/antd/markdown/__tests__/markdown.test.tsx
=> fix: markdown test

packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |    action linkage rules not working correctly in tree table       |
| 🇨🇳 Chinese |     树表格下按钮联动规则不符合预期      |
=> fix: action linkage rules not working correctly in tree table

packages/core/cli/src/util.js
| 🇺🇸 English |  The time zone defaults to the system time zone  |
| 🇨🇳 Chinese |  时区默认为系统时区  |
=> fix: the time zone defaults to the system time zone

packages/core/client/src/schema-component/antd/action/Action.Page.tsx
| 🇺🇸 English |  Cannot access 'ActionPage' before initialization  |
| 🇨🇳 Chinese | ActionPage 改为 function 方式定义      |
=> fix: cannot access 'ActionPage' before initialization

packages/core/cli/src/commands/upgrade.js
| 🇺🇸 English |  support upgrade to next  |
| 🇨🇳 Chinese |  支持更新到 next 版本   |
=> fix(cli): support upgrade to next

packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts, packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
| 🇺🇸 English |  missing collection schema  |
| 🇨🇳 Chinese | tree collection 缺失 schema 参数 |
=> fix(tree): missing collection schema

packages/core/client/src/block-provider/__tests__/hooks/index.test.ts, packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/schema-settings/hooks/useParseDataScopeFilter.ts, packages/core/client/src/variables/VariablesProvider.tsx, packages/core/client/src/variables/__tests__/useVariables.test.tsx, packages/core/client/src/variables/types.ts, packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
Fix bug.
1. Refactor the `parseVariable` method to return more contexts
2. If the value of the variable does not match the current field, it is ignored.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/199
None.
| 🇺🇸 English |      Ignores variable values that do not match the current field.     |
| 🇨🇳 Chinese |     忽略掉与当前字段不匹配的变量值。      |
=> fix(defaultValue): ignores variable values that do not match the current field

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/executions.tsx
Allow to delete single or selected executions form list.
None.
None.
| 🇺🇸 English | Allow to delete execution in list. |
| 🇨🇳 Chinese | 支持在执行历史列表中删除执行记录。 |
=> feat(plugin-workflow): allow to delete execution in list

packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/redirect.test.ts, packages/plugins/@nocobase/plugin-mobile/src/client/index.tsx
Fix bug.
Should use `/m/` instead of `/m` to replace URL.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/270
None.
| 🇺🇸 English |      Fix the problem of wrong path jumping in mobile.     |
| 🇨🇳 Chinese |     修复移动端路径跳转错误的问题。      |
=> fix(mobile): resovle redirect issue

packages/core/client/src/modules/blocks/data-blocks/details-single/ReadPrettyFormItemInitializers.tsx, packages/core/client/src/modules/blocks/other-blocks/markdown/MarkdownFormItemInitializer.tsx, packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx, packages/core/client/src/schema-settings/SchemaSettingsRenderEngine.tsx
| 🇺🇸 English |     "add text"  should support handlebars      |
| 🇨🇳 Chinese |     “添加文本” 应支持 handlebars     |
=> fix: "add text"  should support handlebars

packages/core/database/src/view/field-type-map.ts
=> chore: support year data type in mysql

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/utils.ts
Fix the issue of parsing variables in chart filter block.
| 🇺🇸 English | Fix the issue of parsing variables in chart filter block       |
| 🇨🇳 Chinese | 修复图表过滤区块中变量解析的 BUG           |
=> fix(data-vi): issue of parsing variables in filter block

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
| 🇺🇸 English |     issue with association select data scope linkage in sub-table      |
| 🇨🇳 Chinese |     子表格关系字段数据范围交互缺陷      |
=> fix:  issue with association select data scope linkage in sub-table

packages/core/client/src/acl/ACLProvider.tsx, packages/plugins/@nocobase/plugin-collection-tree/src/client/index.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/redirectInDesktopDevices.test.ts, packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/redirectInMobileDevices.test.ts, packages/plugins/@nocobase/plugin-mobile/src/client/__tests__/Mobile.test.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/DesktopMode-basic.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/Mobile-basic.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/MobileTabBar-basic.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/MobileTabBar-false.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/MobileTabBar-inner-page.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/MobileTabBar.Link-settings.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/MobileTabBar.Page-settings.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/demos/pages-dynamic-page-schema.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/desktop-mode/Header.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/MobileLayout.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/MobileTabBar.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-providers/MobileProviders.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-providers/context/MobileRoutes.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx, packages/plugins/@nocobase/plugin-mobile/src/server/plugin.ts
Fix bug.
None.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/288
None.
| 🇺🇸 English |      Fix the issue that normal roles enter the mobile page to report no permissions.     |
| 🇨🇳 Chinese |     修复普通角色进入移动端页面报无权限的问题。      |
=> fix(mobile): fix permission

packages/plugins/@nocobase/plugin-user-data-sync/src/server/user-data-resource-manager.ts, packages/plugins/@nocobase/plugin-users/src/server/__tests__/data-sync.test.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts, packages/plugins/@nocobase/plugin-users/src/server/user-data-sync-resource.ts
=> feat: user sync support custom fields and department owner

.github/workflows/changelog-and-release.yml, release.sh, scripts/release/changelogAndRelease.js, scripts/release/writeChangelog.js
=> docs: generate change logs by pull requests

packages/core/database/src/relation-repository/relation-repository.ts, packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-action.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/actions/export-xlsx.ts, packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts
| 🇺🇸 English |    Fixed incorrect export of relational data       |
| 🇨🇳 Chinese |  修复导出关系数据不正确的问题        |
=> fix: export with relation repository

packages/plugins/@nocobase/plugin-field-formula/src/client/components/Formula/Result.tsx, packages/plugins/@nocobase/plugin-field-formula/src/utils/index.ts
| 🇺🇸 English |   formula field adaptation time field        |
| 🇨🇳 Chinese |     公式字段使用日期字段时页面报错      |
=> fix: formula field adaptation time field

packages/plugins/@nocobase/plugin-action-custom-request/src/client/schemaSettings.ts
| 🇺🇸 English |      remove linkageRule for custom request in create form     |
| 🇨🇳 Chinese |    去掉添加数据表单自定义请求按钮的联动规则       |
=> fix: remove linkageRule for custom request in create form

packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
To show all fields available in workflow variables.
Some foreign keys missed in variables list.
None.
None.
| 🇺🇸 English | Fix missed fields in workflow variables. |
| 🇨🇳 Chinese | 修复工作流变量中缺少部分字段可选的问题。 |
=> fix(plugin-workflow): fix missed fields in variable

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |     issue with  custom request refreshDataBlockRequest     |
| 🇨🇳 Chinese |     自定义请求按钮的请求后刷新数据设置不生效      |
=> fix:  issue with custom request  refreshDataBlockRequest

packages/plugins/@nocobase/plugin-backup-restore/src/server/__tests__/cli.test.ts, packages/plugins/@nocobase/plugin-backup-restore/src/server/__tests__/dumper.test.ts, packages/plugins/@nocobase/plugin-backup-restore/src/server/__tests__/index.ts
| 🇺🇸 English |   fix test case errors |
| 🇨🇳 Chinese |  修复测试用例报错  |
=> fix(backup-restore): test case errors

packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts, packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts
Fix parameters processing bug makes request fails.
`.trim()` on non-string typed variables cause error.
None.
None.
| 🇺🇸 English | Fix error when using non-string variable in request parameters. |
| 🇨🇳 Chinese | 修复请求节点参数使用非字符串变量时的问题。 |
=> fix(plugin-workflow-request): fix params processing

packages/core/client/src/system-settings/SystemSettingsShortcut.tsx, packages/plugins/@nocobase/plugin-auth/src/client/pages/AuthLayout.tsx
| 🇺🇸 English |   support line break in system title |
| 🇨🇳 Chinese |  系统标题支持换行  |
=> feat: support line break in system title

packages/core/client/src/schema-component/antd/filter/FilterGroup.tsx, packages/core/client/src/schema-settings/LinkageRules/LinkageRuleActionGroup.tsx, packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx
| 🇺🇸 English |       component display error when switching assignment types in linkage rules    |
| 🇨🇳 Chinese |     修复联动规则中切换赋值类型时组件显示错误      |
=> fix:  issue with select linkage value type

packages/core/client/src/api-client/APIClient.ts, packages/core/client/src/application/Application.tsx, packages/core/client/src/nocobase-buildin-plugin/index.tsx, packages/core/server/src/plugin-manager/options/resource.ts
| 🇺🇸 English | provide more user-friendly application-level error messages |
| 🇨🇳 Chinese | 提供更友好的应用级错误提示 |
=> feat: provide more user-friendly application-level error messages

packages/core/client/src/data-source/components/CollectionDeletedPlaceholder.tsx
=> refactor: collectionNotAllowViewPlaceholder

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
| 🇺🇸 English | default time for display is 00:00:00 |
| 🇨🇳 Chinese |  显示时间时默认时间为 00:00:00        |
=> feat: default time for display is 00:00:00

packages/core/client/src/locale/en_US.json, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/pm/PluginCard.tsx
…is inconsistent
| 🇺🇸 English |  plugins can also be enabled when the plugin dependency version is inconsistent |
| 🇨🇳 Chinese | 插件依赖版本不一致时也可以激活插件 |
=> feat: plugins can also be enabled when the plugin dependency version is inconsistent

packages/core/client/src/schema-component/antd/page/__tests__/usePopupContextInActionOrAssociationField.test.ts, packages/core/client/src/schema-component/antd/page/usePopupContextInActionOrAssociationField.ts, packages/core/client/src/schema-component/hooks/useDesignable.tsx, packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/__tests__/action.test.ts, packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/__tests__/ui-schema-repository.test.ts, packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/actions/ui-schema-action.ts, packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/repository.ts, packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/server.ts
Fix bug.
See code.
None.
| 🇺🇸 English |      Fix the issue that member roles clicking the button reported no permission     |
| 🇨🇳 Chinese |     修复 member 角色点击按钮报无权限的问题      |
=> fix: resolve unauthorized error on button click for normal roles

.github/workflows/manual-build-pro-plugin-image.yml, packages/core/client/src/schema-component/common/utils/uitls.tsx
| 🇺🇸 English |    Support association field preloading in Handlebars templates       |
| 🇨🇳 Chinese |      支持 Handlebars 模板中关系字段的预加载     |
=> refactor: support association field preloading in Handlebars templates

packages/core/client/src/application/schema-initializer/hooks/useSchemaInitializerRender.tsx, packages/core/client/src/modules/popup/OpenModeProvider.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchPopupActionSchemaInitializerItem.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx
| 🇺🇸 English |     Action panel for mobile to use mobile:addBlock      |
| 🇨🇳 Chinese |   操作面板在移动端中使用 mobile:addBlock       |
=> refactor:action panel for mobile to support mobile:addBlock

packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/client/src/schema-component/antd/menu/Menu.tsx, packages/plugins/@nocobase/plugin-action-custom-request/src/client/initializer/CustomRequestInitializer.tsx
| 🇺🇸 English |      Menu modifications do not take effect in real-time     |
| 🇨🇳 Chinese |     修改菜单标题时没有实时生效      |
=> fix: menu modifications do not take effect in real-time

packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts
https://forum.nocobase.com/t/1-3-0-1-3-19-beta/716
| 🇺🇸 English |      Fix error when using linkage rules (NocoBase installed via create-nocobase-app)     |
| 🇨🇳 Chinese |     修复在使用联动规则时报错的问题（通过 create-nocobase-app 安装的 NocoBase）      |
=> fix(create-nocobase-app): fix linkage rules error

packages/core/client/src/index.ts, packages/core/client/src/schema-settings/VariableInput/hooks/index.ts, packages/core/client/src/variables/index.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterForm.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemDesigner.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/utils.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/useVariableOptions.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/index.tsx
| 🇺🇸 English | Support for adding chart blocks in popups/drawers/sub-pages          |
| 🇨🇳 Chinese | 支持在弹窗和子页面中添加图表区块          |
=> feat(data-vi): support for adding chart blocks in popups/drawers/sub-pages

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |     issue with tree table nodes not expanding      |
| 🇨🇳 Chinese |    树表格无法正常展开       |
=> fix: issue with tree table nodes not expanding

packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/variables/utils/isVariable.tsx, packages/core/evaluators/src/utils/index.ts
| 🇺🇸 English |   markdown handlebars rendering issue with this context        |
| 🇨🇳 Chinese |     修复 markdown handlebars 渲染中 this 解析失败      |
=> fix: markdown handlebars rendering issue with this context

packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/interfaces/markdown-vditor.tsx
| 🇺🇸 English |     Support Vidtor when selecting fields in the UI for external data sources      |
| 🇨🇳 Chinese |    在外部数据源中选字段 UI 的时支持 Vidtor        |
=> refactor:  support Vidtor when selecting fields in the UI for external data sources

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
… end date crosses months
| 🇺🇸 English |    issue where the calendar block cannot display correctly when the end date crosses months       |
| 🇨🇳 Chinese |     日历区块结束日期跨月时无法正确显示的问题      |
=> fix: issue where the calendar block cannot display correctly when the end date crosses months

packages/core/database/src/__tests__/filter-target-key/multi-filter-target-key.test.ts, packages/core/database/src/collection.ts, packages/core/database/src/repository.ts
=> fix: count of multi filter target keys

packages/core/evaluators/src/utils/index.ts
| 🇺🇸 English |     fix evaluate server test      |
| 🇨🇳 Chinese |     修复 evaluate 服务端测试用例      |
=> fix: evaluate server test

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> refactor: collection fields action optimization

packages/plugins/@nocobase/plugin-users/src/client/UsersManagement.tsx, packages/plugins/@nocobase/plugin-users/src/client/schemas/users.ts, packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts
The render performance of the user management table is under expectation.
Switch the table component from `Table.Void` to `TableV2`.
| 🇺🇸 English | Optimize performance for rendering the user management table          |
| 🇨🇳 Chinese | 优化用户管理表格的渲染速度          |
=> perf(users): optimize performance for rendering the user management table

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/DataSourceTable.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/schemas/dataSourceTable.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/client/index.tsx
| 🇺🇸 English |  support data source permission tabs extension |
| 🇨🇳 Chinese |  支持数据源权限标签页扩展  |
=> feat: support data source permission tabs extension

packages/core/database/src/interfaces/utils.ts
| 🇺🇸 English | import with checkbox field |
| 🇨🇳 Chinese | 导入支持勾选字段 |
=> fix(action-import): import with checkbox field

packages/core/client/src/schema-initializer/buttons/TabPaneInitializers.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchAction.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx
| 🇺🇸 English |     Error in configuration block under the newly added tab in the action  panel popup action      |
| 🇨🇳 Chinese |      操作面板弹窗中新增标签页下配置区块报错     |
=> fix: error in configuration block under the newly added tab in the action  panel popup action

packages/core/client/src/schema-component/antd/page/index.ts, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/DeleteEvent.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Event.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/initializers/CalendarFormActionInitializers.tsx
| 🇺🇸 English |     Cannot select the option to delete the schedule popup      |
| 🇨🇳 Chinese |       删除日程弹窗选项不能选择    |
=> fix: cannot select the option to delete the schedule in delete event action

packages/core/client/src/modules/blocks/data-blocks/table/tableColumnSettings.tsx
| 🇺🇸 English |   Fix issue where the collection from external  data source does not support sorting on table columns       |
| 🇨🇳 Chinese |  外部数据库数据源表格列头不支持排序的问题        |
=> fix: third party data source should support sortable in table column

packages/plugins/@nocobase/plugin-data-visualization/src/client/block/CardItem.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlock.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockDesigner.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockInitializer.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/AntChart.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/g2plot.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/index.tsx
| 🇺🇸 English | Fix style issues of chart blocks when using dark mode themes           |
| 🇨🇳 Chinese | 修复图表区块在暗黑主题下的样式问题          |
=> fix(data-vi): fix style issues when using dark mode themes

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/collection.ts
Allow user to query all data from a collection.
None.
None.
None.
| 🇺🇸 English | remove the limit of 100 items per page in the query node |
| 🇨🇳 Chinese | 解除查询节点中每页数量最大为 100 的限制 |
=> refactor(plugin-workflow): remove limit of page size in query node

packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useBaseVariable.tsx
| 🇺🇸 English |       Fix for not displaying full fields in variables    |
| 🇨🇳 Chinese |      修复变量中没有显示完整字段的问题     |
=> fix(variable): should show all collection fields

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/schemas/collections.ts
| 🇺🇸 English |     Fix error when dragging to sort collections      |
| 🇨🇳 Chinese |     修复 数据表拖拽排序时报错的问题    |
=> fix: error when dragging to sort collections

packages/core/database/src/database.ts, packages/core/database/src/fields/sort-field.ts
=> fix: scope key error

packages/core/database/src/database.ts, packages/core/database/src/fields/sort-field.ts
Reverts nocobase/nocobase#5314
=> Revert "fix: scope key error"

packages/core/client/src/modules/blocks/data-blocks/grid-card/GridCardActionInitializers.tsx, packages/core/client/src/modules/blocks/data-blocks/list/ListActionInitializers.tsx, packages/core/client/src/modules/blocks/data-blocks/table/TableActionInitializers.tsx, packages/plugins/@nocobase/plugin-action-custom-request/src/client/hooks/useCustomRequestVariableOptions.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/client/schemaSettings.ts, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/initializers/CalendarActionInitializers.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/GanttActionInitializers.tsx, packages/plugins/@nocobase/plugin-kanban/src/client/KanbanActionInitializers.tsx, packages/plugins/@nocobase/plugin-map/src/client/block/MapActionInitializers.tsx
The following is an example of a Table block:
| 🇺🇸 English |      Support for adding custom request buttons to the top of Table, List, Grid Card, Calendar, Gantt, Kanban, and Map     |
| 🇨🇳 Chinese |     支持在表格、列表、网格卡片、日历、甘特图、看板、地图的顶部添加自定义请求按钮      |
=> feat(custom-request): support adding custom request in more places

packages/core/database/src/fields/number-field.ts, packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts
| 🇺🇸 English |    fix export format for decimal type fields  |
| 🇨🇳 Chinese |     修复 decimal 类型字段的导出格式      |
=> fix: export with decimal field

packages/core/client/src/i18n/SwitchLanguage.tsx, packages/core/client/src/index.ts, packages/core/client/src/locale/index.ts, packages/plugins/@nocobase/plugin-auth/src/client/pages/AuthLayout.tsx
| 🇺🇸 English |   Support for switching languages on the login page  |
| 🇨🇳 Chinese |   登录页支持语言切换  |
=> feat: support for switching languages on the login page

packages/core/client/src/schema-component/antd/page/index.ts, packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.Card.tsx
| 🇺🇸 English |       Fix the issue that the popup window could not be opened after clicking on the Kanban card in the embedded page    |
| 🇨🇳 Chinese |      修复在嵌入页面中，点击看板卡片后，无法打开弹窗的问题     |
=> fix(embed): fix issue with unable to open popup in kanban

packages/core/client/src/schema-component/antd/variable/TextArea.tsx, packages/core/client/src/schema-component/antd/variable/Variable.tsx, packages/plugins/@nocobase/plugin-action-custom-request/src/client/hooks/useCustomRequestVariableOptions.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/client/schemas/CustomRequestConfigurationFields.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/server/__tests__/getParsedValue.test.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/server/actions/send.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoMathEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesFormulaEngine.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesMathEngine.test.ts
| 🇺🇸 English |      When configuring Headers and Parameters, support the concatenation of strings and variables     |
| 🇨🇳 Chinese |     在配置 Headers 和 Parameters 的时候，支持使用字符串与变量进行拼接     |
=> feat(custom-request): support concatenation of variables and strings

packages/core/database/src/fields/number-field.ts
=> chore: options from raw type

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
=> fix:  after success setting for the submit button

packages/core/client/src/schema-component/antd/action/Action.Container.tsx, packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx, packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/action/Action.Page.tsx, packages/core/client/src/schema-component/antd/action/utils.ts, packages/core/client/src/schema-items/OpenModeSchemaItems.tsx
| 🇺🇸 English |       Fix the issue of not being able to open sub-pages in embedded pages    |
| 🇨🇳 Chinese |     修复在嵌入页面中无法打开子页面的问题      |
=> fix(embed): fix issue with unable to open subpage

packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/UnEnabledFormPlaceholder.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/hooks/useSubmitActionProps.ts, packages/plugins/@nocobase/plugin-public-forms/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-public-forms/src/server/hook.ts, packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
| 🇺🇸 English |    error feedback when the form does not exist in public forms       |
| 🇨🇳 Chinese |    公开表单中表单不存在时的错误反馈      |
=> refactor:  error feedback when the form does not exist in public forms

packages/core/client/src/global.less, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/styles.ts
| 🇺🇸 English |      Hide scrollbars on mobile     |
| 🇨🇳 Chinese |     隐藏移动端的滚动条      |
=> chore(mobile): hide scrollbar

packages/core/client/src/modules/blocks/data-blocks/details-single/RecordReadPrettyFormBlockInitializer.tsx, packages/core/client/src/modules/blocks/data-blocks/form/RecordFormBlockInitializer.tsx, packages/core/client/src/schema-initializer/items/RecordAssociationFormBlockInitializer.tsx, packages/core/client/src/schema-initializer/items/RecordReadPrettyAssociationFormBlockInitializer.tsx
| 🇺🇸 English |      Fix the issue of abnormal style when creating blocks with data templates in mobile subpages     |
| 🇨🇳 Chinese |     修复移动端子页面中，使用数据模板创建区块时，样式异常的问题      |
=> fix(mobile): fix style issue when adding template in subpage

packages/plugins/@nocobase/plugin-block-workbench/src/client/index.tsx
| 🇺🇸 English |    support configuring the action panel within pop-up       |
| 🇨🇳 Chinese |    支持在弹窗种配置操作面板       |
=> feat: support configuring the action panel within pop-up

Dockerfile.pro
=> fix: incorrect pg_restore in pro image

packages/plugins/@nocobase/plugin-file-manager/src/client/FileStorage.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storage.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/ali-oss.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/local.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/s3.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/tx-cos.tsx
Image process rule is needed for Tencent cloud COS storage engine.
None.
None.
| 🇺🇸 English | Add thumbnail rule for COS storage. |
| 🇨🇳 Chinese | 为 COS 文件存储引擎添加缩略规则参数配置项。 |
=> feat(plugin-file-manager): add thumbnail rule for cos

packages/core/client/src/modules/actions/submit/createSubmitActionSettings.tsx, packages/core/client/src/modules/blocks/data-blocks/form/createFormActionInitializers.tsx, packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/plugins/@nocobase/plugin-action-import/src/client/useImportAction.ts
| 🇺🇸 English |      Workflow: Error when selecting a subform component for a association field during field assignment in the data update node     |
| 🇨🇳 Chinese |    工作流：更新数据节点，字段赋值中关系字段选择子表单组件时报错       |
=> fix:(workflow): error when selecting a subform component for a association field during field assignment in the data update node

packages/plugins/@nocobase/plugin-acl/src/server/__tests__/cluster.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/server.ts
=> fix: sync role snippets

packages/core/client/src/schema-component/antd/page/PagePopups.tsx
| 🇺🇸 English |       Fix the problem that after deleting a tab in a subpage, it does not take effect after opening it again    |
| 🇨🇳 Chinese |     修复在子页面中删除 tab 页后，再次打开后未生效的问题      |
=> fix(subpage): fix the problem of invalid tab deletion

packages/core/client/src/schema-component/antd/page/PagePopups.tsx, packages/core/client/src/schema-component/antd/page/pagePopupUtils.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/__e2e__/popup.test.ts, packages/plugins/@nocobase/plugin-gantt/src/client/__e2e__/utils.ts, packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/Event.tsx
| 🇺🇸 English |       Fix the issue where opening a popup in the Gantt block and then closing it causes the subpage to also close    |
| 🇨🇳 Chinese |     修复在甘特图中打开弹窗，然后再关闭，导致子页面也被关闭的问题      |
=> fix(gantt): fix popup

packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
| 🇺🇸 English |     fixed issue with incorrect results for importing large dates      |
| 🇨🇳 Chinese |   修复导入大日期结果不正确的问题        |
=> fix: import with big date

packages/core/client/src/modules/popup/__e2e__/zIndex.test.ts, packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx, packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/action/Action.Page.tsx, packages/core/client/src/schema-component/antd/action/utils.ts, packages/core/client/src/schema-component/antd/action/zIndexContext.tsx
close #5368
| 🇺🇸 English |       Fix the issue where popups opened in the "Users & Permissions" configuration page are obscured by other popups    |
| 🇨🇳 Chinese |     修复在“用户和权限”配置页打开的弹窗被其它弹窗遮挡的问题      |
=> fix(popup): z-index

packages/core/database/src/query-interface/query-interface.ts
=> chore: catch error when drop view without permission

packages/core/actions/src/__tests__/list-action.test.ts, packages/core/actions/src/actions/list.ts, packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/data-source-manager/src/default-actions/list.ts
=> chore: simple paginate hasNext option

.github/workflows/build-docker-image.yml, Dockerfile, docker/nocobase/docker-entrypoint.sh, storage/.gitignore
=> chore: start up scripts in docker

packages/core/client/src/schema-component/antd/date-picker/__tests__/getDateRanges.test.ts, packages/core/client/src/schema-component/antd/date-picker/util.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts, packages/core/client/src/variables/VariablesProvider.tsx, packages/core/client/src/variables/__tests__/useVariables.test.tsx
| 🇺🇸 English |      Date variables are also not prohibited in create form     |
| 🇨🇳 Chinese |     创建表单中也不禁用日期变量      |
=> feat(variable): do not disable date variables

packages/plugins/@nocobase/plugin-workflow-sql/src/server/SQLInstruction.ts, packages/plugins/@nocobase/plugin-workflow-sql/src/server/__tests__/instruction.test.ts
Fix error when no result when calling stored procedure in SQL instruction.
| 🇺🇸 English | fix error when no result when calling stored procedure in SQL instruction |
| 🇨🇳 Chinese | 修复在 SQL 节点中调用存储过程没有返回结果时导致错误的问题 |
=> fix(plugin-workflow-sql): fix no result when calling stored procedure

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts
When `DB_UNDERSCORED=true` is set in env, date field based schedule workflow will cause app crash.
Also fixed to support other data source.
None.
None.
| 🇺🇸 English | fix date field based schedule trigger caused app crash, and also support other data source |
| 🇨🇳 Chinese | 修复基于时间字段的定时任务导致报错的问题，并支持其他数据库数据源 |
=> fix(plugin-workflow): fix column name caused error when underscored

packages/core/database/src/options-parser.ts
=>  fix: default sort with multi filter target keys

packages/core/client/src/schema-component/antd/association-field/AssociationFieldModeProvider.tsx, packages/core/client/src/schema-component/antd/association-field/__tests__/AssociationFieldModeProvider.test.tsx, packages/core/client/src/schema-component/antd/association-field/index.ts, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx
fix https://github.com/nocobase/nocobase/issues/5372
| 🇺🇸 English |      Fix the rendering error that occurs when displaying file collection relationship fields on mobile devices     |
| 🇨🇳 Chinese |     修复在移动端中，显示文件表关系字段时报渲染错误的问题      |
=> fix(mobile): fix file field rendering error issue

packages/core/client/src/schema-initializer/items/DataBlockInitializer.tsx, packages/core/client/src/schema-initializer/utils.ts
| 🇺🇸 English |      Fix Create Block menu not loading more data collections     |
| 🇨🇳 Chinese |     修复创建区块菜单无法加载更多数据表的问题      |
=> fix(menu): fix menu loading issue

packages/plugins/@nocobase/plugin-calendar/src/locale/zh-CN.ts
=> refactor: optimize calendar block locale

packages/plugins/@nocobase/plugin-action-import/src/client/useShared.ts
| 🇺🇸 English |     fix import error with wps file      |
| 🇨🇳 Chinese |    修复导入 wps 文件报错的问题       |
=> fix: import with wps

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx
| 🇺🇸 English |   Fix issue with clicking settings on public form        |
| 🇨🇳 Chinese |  修复 公开表单的设置点击缺陷        |
=> fix: issue with clicking settings on public form

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts, packages/core/client/src/variables/VariablesProvider.tsx
| 🇺🇸 English |      Fix the issue of not displaying the value in the default value input box     |
| 🇨🇳 Chinese |     修复默认值输入框中不显示值的问题      |
=> fix(defaultValue): fix the issue of not displaying the value in the default value input box

packages/core/database/src/options-parser.ts
=> fix: default sort with multi target keys

packages/core/client/src/schema-component/antd/date-picker/util.ts, packages/core/client/src/variables/__tests__/useVariables.test.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/__e2e__/defaultValue.test.ts
fix https://forum.nocobase.com/t/10-12/1091
| 🇺🇸 English |       Fix the issue of default values not displaying in the chart filter block    |
| 🇨🇳 Chinese |     修复图表筛选区块中不显示默认值的问题      |
=> fix(dateVariable): fix default value issue in chart filter block

packages/core/client/src/modules/actions/update-record/UpdateRecordActionInitializer.tsx, packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaSettings.test.ts
| 🇺🇸 English |    update record automatic close message popup       |
| 🇨🇳 Chinese |    更新数据操作，操作成功后，提示信息默认自动关闭      |
=> refactor: update record automatic close message popup

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx
| 🇺🇸 English |  Unify the text style between list layout and grid layout         |
| 🇨🇳 Chinese |    列表模式与格栅模式文字样式 统一      |
=> style(action-penal): Unify the text style between list layout and grid layout

packages/core/client/src/application/__tests__/utils/remotePlugins.test.ts, packages/core/client/src/application/utils/remotePlugins.ts
| 🇺🇸 English | optimize remote debugging |
| 🇨🇳 Chinese |  优化远程调试         |
=> chore: optimize remote debugging

packages/core/cache/src/cache-manager.ts, packages/core/server/src/locale/locale.ts, packages/plugins/@nocobase/plugin-localization/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-localization/src/server/plugin.ts, packages/plugins/@nocobase/plugin-localization/src/server/resources.ts
| 🇺🇸 English | Fix the issue where translations in the localization plugin do not take effect after publishing          |
| 🇨🇳 Chinese | 修复本地化插件中的翻译发布后不生效的问题  |
=> fix(l10n): issue of publishing locale resources

packages/core/app/client/.umirc.ts, packages/core/client/package.json, packages/core/client/src/data-source/data-block/DataBlockResourceProvider.tsx, packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/index.ts, packages/core/client/src/schema-component/antd/upload/style.ts, packages/core/create-nocobase-app/package.json, packages/core/devtools/umiConfig.js, packages/core/sdk/package.json, packages/core/sdk/src/APIClient.ts, packages/core/server/package.json, packages/plugins/@nocobase/plugin-workflow-mailer/src/server/__tests__/instruction.test.ts, packages/plugins/@nocobase/plugin-workflow-request/package.json, packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts
| 🇺🇸 English |  Support for SSE(Server-Sent Events)  |
| 🇨🇳 Chinese | 支持服务器发送事件（SSE）   |
=> feat: support for server-sent events

packages/core/app/client/.umirc.ts, packages/core/app/client/src/pages/index.tsx, packages/core/cli/src/util.js, packages/core/devtools/umiConfig.js, packages/core/sdk/src/APIClient.ts
To sign user out when closing web page.
```shell
API_CLIENT_STORAGE_TYPE=sessionStorage
```
| 🇺🇸 English | Allows to store client information into sessionStorage by setting `API_CLIENT_STORAGE_TYPE` environment variable          |
| 🇨🇳 Chinese | 支持通过设置环境变量 `API_CLIENT_STORAGE_TYPE` 将客户端信息存储到 sessionStorage          |
=> feat(client): allows to store client information into session storage

packages/core/client/src/schema-component/antd/action/Action.style.ts, packages/core/client/src/schema-component/antd/expand-action/Expand.Action.tsx
=> style: optimize expand/collapse button styles

packages/plugins/@nocobase/plugin-backup-restore/src/server/__tests__/dumper.test.ts, packages/plugins/@nocobase/plugin-backup-restore/src/server/field-value-writer.ts, packages/plugins/@nocobase/plugin-backup-restore/src/server/restorer.ts
=> fix: restore with datetime no tz

packages/core/client/src/schema-component/antd/action/Action.style.ts
=> fix: action button style

packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/utils.ts
Fix missed E2E test case.
E2E test case failed due to component changed.
#5430.
| 🇺🇸 English | fix e2e case failed due to component changed |
| 🇨🇳 Chinese | 修复由于更换组件导致的 E2E 测试不通过 |
=> fix(plugin-file-manager): fix e2e due to component changed

packages/core/client/src/data-source/collection-field-interface/CollectionFieldInterface.ts
| 🇺🇸 English | fixed field component options have not been translated correctly |
| 🇨🇳 Chinese |修复字段组件选项未被正确翻译的问题|
=> fix: field component options has not been translated correctly

packages/core/client/src/data-source/collection-field-interface/CollectionFieldInterface.ts
https://github.com/nocobase/nocobase/pull/5442
#5442 has not been fixed completely.
Don't need changelog as it will be generated from #5442 
=> fix: missing translate for input component option

packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts
Fix legacy error message in request node.
Error message changed into "Invalid URL" when no url provided in configuration.
| 🇺🇸 English | fix legacy error message in request node |
| 🇨🇳 Chinese | 修复请求节点测试功能中的错误消息 |
=> fix(plugin-workflow-request): fix error message for test request node

packages/core/client/src/application/__tests__/Application.test.tsx, packages/core/client/src/data-source/__tests__/collection-field-interface/CollectionFieldInterfaceManager.test.ts
=> fix: unit tests error, caused by #5442

packages/core/client/src/collection-manager/interfaces/properties/index.ts
| 🇺🇸 English |   display reverse association field with disabled editing        |
| 🇨🇳 Chinese |    关系字段里建立了反向关联，配置项显示出来禁止编辑      |
=> refactor: display reverse association field with disabled editing

packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts
| 🇺🇸 English |     use filterable property to control field filtering capability      |
| 🇨🇳 Chinese |      筛选字段通过filterable 判断是否可筛选     |
=> refactor: use filterable property to control field filtering capability

packages/plugins/@nocobase/plugin-map/src/client/block/MapBlock.Settings.tsx
| 🇺🇸 English |   remove zoom level configuration for map fields in table column        |
| 🇨🇳 Chinese |      表格中的地图字段不应该有缩放等级配置项     |
=> fix: remove zoom level configuration for map fields in table column

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/shared.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/hooks/useStorageRules.ts
* Fix file can not be uploaded due to rule hook.
* Remove typo character in component.
| 🇺🇸 English | fix file can not be uploaded due to rule hook. |
| 🇨🇳 Chinese | 修复由于上传规则 hook 改动导致文件无法上传的问题 |
=> fix(client): fix typo in upload component

.github/workflows/deploy-client-docs.yml, packages/core/client/.dumirc.ts
=> chore: upgrade appleboy/scp-action

packages/core/client/src/schema-component/antd/remote-select/ReadPretty.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/Fieldset.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/index.ts, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Add a component to present card layout of a set of fields.
```tsx
<Fieldset>
// other fields.
</Fieldset>
```
| 🇺🇸 English | Add card like fields set component |
| 🇨🇳 Chinese | 增加卡片式表单域集合组件 |
=> feat(plugin-workflow): add component

packages/plugins/@nocobase/plugin-workflow-mailer/src/client/MailerInstruction.tsx
Add placeholder to mailer node.
| 🇺🇸 English | add placeholder to mailer node |
| 🇨🇳 Chinese | 为邮件节点的表单项增加占位提示内容 |
=> fix(plugin-workflow-mailer): fix placeholder of mailer node

packages/core/database/src/__tests__/inhertits/collection-inherits.test.ts, packages/core/database/src/inherited-sync-runner.ts
=> fix: sync event in inherited collection

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/shared.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/hooks/useStorageRules.ts
* fix(client): fix typo in upload component
* fix(plugin-file-manager): fix rule hook
Fix file can not be uploaded due to rule hook.
#5465.
| 🇺🇸 English | fix file can not be uploaded due to rule hook |
| 🇨🇳 Chinese | 修复由于上传规则 hook 改动导致文件无法上传的问题 |
=> fix(client): fix typo in upload component (#5460)

packages/plugins/@nocobase/plugin-multi-app-manager/src/server/server.ts
| 🇺🇸 English |  support for the USE_DB_SCHEMA_IN_SUBAPP environment variable  |
| 🇨🇳 Chinese |  支持 USE_DB_SCHEMA_IN_SUBAPP 环境变量  |
=> feat: support for the USE_DB_SCHEMA_IN_SUBAPP environment variable

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
日历控件，选择slot时展示 Add New 界面
如果有 create 权限 并且定义了 Add New UI，则当点击日历的slot时，
显示 添加 Popup 并 自动带入当前slot的时间范围
（Popup中，通过 设置默认值，选择公式 当前弹窗记录 选择对应字段即可）
之前提交到了[main分支](https://github.com/nocobase/nocobase/pull/5312)，这里改为next分支提交
| 🇺🇸 English | show create popup when select calendar slot |
| 🇨🇳 Chinese | 日历控件，选择slot时展示 Add New 界面 |
- [&check;] All changes have been self-tested and work as expected
=> feat: show create popup when select calendar slot

packages/core/data-source-manager/src/data-source.ts, packages/core/server/src/application.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-source.ts
=> chore: datasource sql logger

packages/plugins/@nocobase/plugin-collection-tree/src/server/__tests__/sync.test.ts, packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts, packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20241022161700-inherit-collection-tree.ts
| 🇺🇸 English | Fix the issue where the path collection for the inheritance tree collection is not automatically created |
| 🇨🇳 Chinese | 修复继承的树表没有自动创建路径表的问题          |
=> fix(tree): issue of creating path collection for inheritance tree collection

packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.Settings.tsx, packages/plugins/@nocobase/plugin-kanban/src/client/KanbanBlockProvider.tsx, packages/plugins/@nocobase/plugin-kanban/src/locale/zh-CN.json
| 🇺🇸 English |   Add support for enabling or disabling drag-and-drop sorting in Kanban block       |
| 🇨🇳 Chinese |    看板区块支持启用或禁用拖拽排序功能       |
=> feat: kanban block support enabling or disabling drag-and-drop sorting 

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/content/initializer.tsx
| 🇺🇸 English |   mobile client support filter form block        |
| 🇨🇳 Chinese |      移动端支持表单筛选区块     |
=> feat: mobile client support filter form block

packages/core/client/src/schema-component/antd/list/List.tsx
| 🇺🇸 English |      pagination issue in list block with simple pagination collection     |
| 🇨🇳 Chinese |     使用简单分页的数据表在列表区块上分页异常      |
=> fix: pagination issue in list block with simple pagination collection

packages/core/client/src/schema-component/antd/checkbox/Checkbox.tsx
| 🇺🇸 English |        show disabled unchecked checkbox for unselected fields   |
| 🇨🇳 Chinese |      勾选字段未勾选时显示禁用的未勾选框    |
=> fix: improve display of unchecked fields

packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
| 🇺🇸 English |     registration ACL snippet for public form      |
| 🇨🇳 Chinese |    公开表单注册acl  snippet  |
=> fix: registration ACL snippet for public form

packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/checkbox/schemaSettings.test.ts
=> fix: checkbox e2e test

.github/workflows/manual-build-pr-docker-image.yml, .github/workflows/manual-build-pro-image.yml, .github/workflows/manual-build-pro-plugin-image.yml, Dockerfile.pro
=> chore: update pro image

packages/core/client/src/api-client/APIClient.ts, packages/core/sdk/src/APIClient.ts
| 🇺🇸 English |   APIClient supports silent mode |
| 🇨🇳 Chinese |  APIClient 支持 silent 模式         |
=> fix(api-client): supports silent mode

packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-source.ts
| 🇺🇸 English |    catch error when create datasource       |
| 🇨🇳 Chinese |    优化外部数据源报错       |
=> chore: catch error when create datasource

packages/core/data-source-manager/src/data-source.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/__tests__/data-sources.test.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-source.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/plugin.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/resourcers/data-sources-collections.ts
| 🇺🇸 English |    Optimize  loading state  of data source     |
| 🇨🇳 Chinese |  优化数据源加载状态         |
=> feat: update datasource loading progress

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/modules/fields/component/Input/inputComponentSettings.tsx, packages/core/client/src/modules/fields/component/Picker/recordPickerComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/PopoverNester/subformPopoverComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |       Fix  issues with deletion action , text ellipsis, and new data display in sub-table    |
| 🇨🇳 Chinese |     修复子表格一次删除了多条数据，超长文本省略设置新添数据不生效等问题       |
=> fix: issues with deletion action , text ellipsis, and new data display in sub-table

packages/plugins/@nocobase/plugin-map/src/client/components/ReadPretty.tsx
=> fix: build test

packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts
Add some log to notification manager.
Add some log to notification manager.
| 🇺🇸 English |     Add some log to notification manager.      |
| 🇨🇳 Chinese |        为通知管理插件增加日志。   |
=> Add some log to notification manager.

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |      Fix the issue where skeleton components in table blocks do not disappear     |
| 🇨🇳 Chinese |     修复表格区块中的骨架屏组件不消失的问题      |
=> fix(Table): fix skeleton component not disappearing

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/ContentConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/Inbox.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/en-US.json, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts
Improve unread message count display.
Improve unread message count display.
| 🇺🇸 English |     Improve unread message count display .     |
| 🇨🇳 Chinese |      优化未读消息UI展示。     |
| 🇺🇸 English |     |
=> refactor(inbox): improve unread message count display

packages/core/client/src/modules/blocks/data-blocks/form/hooks/useDataFormItemProps.ts, packages/core/client/src/schema-settings/LinkageRules/useActionValues.ts
Fix linkage style not updating in form.
Fix linkage style not updating in form.
[#5324](https://github.com/nocobase/nocobase/issues/5324)
| 🇺🇸 English |     Fix linkage style not updating in form.      |
| 🇨🇳 Chinese |     修复联动样式在表单里不更新。      |
=> fix: fix linkage style not updating in form

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/ContentConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/Inbox.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/en-US.json, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts
Improve in-app message UI and add some logs.
Improve in-app message UI and add some logs.
| 🇺🇸 English |    Improve in-app message UI and add some logs.       |
| 🇨🇳 Chinese |    优化站内信界面并增加了一些日志       |
=> chore(plugin-notification-in-app-message): improve UI and add logs

packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
| 🇺🇸 English | Fix errors when updating path collection           |
| 🇨🇳 Chinese | 修复更新路径表时的报错           |
=> fix(tree): fix errors when updating path collection

packages/core/client/src/collection-manager/interfaces/number.ts
| 🇺🇸 English |   numeric precision can be configured to 8 digits  |
| 🇨🇳 Chinese |  数字精确度支持配置 8 位数 |
=> feat: numeric precision can be configured to 8 digits

packages/core/client/src/modules/blocks/data-blocks/form/fieldSettingsFormItem.tsx, packages/core/client/src/modules/blocks/filter-blocks/form/filterFormItemFieldSettings.ts, packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx, packages/core/client/src/schema-items/GeneralSchemaItems.tsx, packages/core/client/src/schema-items/GeneralSettings.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/bulkEditFormItemSettings.ts
| 🇺🇸 English |      restore default value when field title is cleared     |
| 🇨🇳 Chinese |        字段标题清空时恢复为字段标题默认值   |
=> refactor: restore default value when field title is cleared

packages/plugins/@nocobase/plugin-data-source-manager/src/server/plugin.ts
| 🇺🇸 English |  Fix remove data source in failed status         |
| 🇨🇳 Chinese |    修复无法移除失败状态的数据源的问题       |
=> fix: remove data source in failed status

packages/plugins/@nocobase/plugin-notification-manager/src/client/index.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/message/components/MessageConfigForm/index.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/receiver/components/User/UserAddition.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/receiver/components/User/UserSelect.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/receiver/components/User/index.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/collections/messageLog.ts, packages/plugins/@nocobase/plugin-notification-manager/src/index.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/index.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/utils/parseUserSelectionConfig.ts
Add UserSelect and UserAddition components.
Add UserSelect and UserAddition components.
| 🇺🇸 English |     Add UserSelect and UserAddition components to streamline the development of notification channels      |
| 🇨🇳 Chinese |      增加 UserSelect 和 UserAddition 组件，方便在开发通知渠道的时候使用     |
=> feat(notification-manager): add UserSelect and UserAddition components

packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/collections.repository.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/fields/belongs-to-many.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/models/collection.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/server.ts, packages/plugins/@nocobase/plugin-multi-app-share-collection/src/server/__tests__/collection-sync.test.ts
| 🇺🇸 English |     Improve load logic of collection with schema attribute     |
| 🇨🇳 Chinese |   优化含 schema 属性的 collection 的加载方法        |
=> chore: load collection with schema

packages/plugins/@nocobase/plugin-api-keys/src/client/index.tsx
| 🇺🇸 English | Fix the URL path for API keys settings page          |
| 🇨🇳 Chinese | 修复 API keys 设置页面的 URL 路径          |
=> fix(api-keys): fix the URL path for API keys settings page

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |     Fix issue with adding data to sub-table after deletion      |
| 🇨🇳 Chinese |    子表格数据删除数据后添加数据异常     |
=> fix: issue with adding data to sub-table after deletion

packages/plugins/@nocobase/plugin-multi-app-manager/src/server/server.ts
| 🇺🇸 English |   sub-app asynchronous quick start |
| 🇨🇳 Chinese |  子应用异步启动  |
=> fix(multi-app-manager): sub-app asynchronous quick start

packages/core/client/src/application/schema-initializer/components/SchemaInitializerItemSearchFields.tsx
| 🇺🇸 English |    search field should be searched based on the translated text       |
| 🇨🇳 Chinese |     搜索字段应以翻译后文本来搜索      |
=> fix: search field should be searched based on the translated text

packages/core/server/src/sync-message-manager.ts, packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/formatter.test.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/server/__tests__/cluster.test.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/server/__tests__/multiple-apps.test.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/server/models/application.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/server/server.ts
=> fix: start sub app in cluster

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
…association select
| 🇺🇸 English |       Fix filter issue when setting single-select field as title field in association select    |
| 🇨🇳 Chinese |      修复 关系字段下拉选项中设置单选字段为标题字段时筛选不生效的问题   |
=> fix: filter issue when setting single-select field as title field in association select

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |    Style: increase button spacing between rows in compact theme     |
| 🇨🇳 Chinese |   样式优化：紧凑主题下，表格行按钮间距调整     |
=> style: increase button spacing between rows in compact theme

packages/core/client/src/schema-component/antd/action/Action.tsx
…urce
| 🇺🇸 English |    Fix resolve error when configuring fields after adding a new data source       |
| 🇨🇳 Chinese |     添加新数据源后配置新数据字段页面报错      |
=> fix: resolve error when configuring fields after adding a new data source

packages/core/auth/src/auth-manager.ts, packages/core/data-source-manager/src/data-source-manager.ts, packages/core/data-source-manager/src/data-source.ts, packages/core/logger/src/request-logger.ts, packages/core/resourcer/src/action.ts, packages/core/resourcer/src/resourcer.ts, packages/core/server/src/application.ts, packages/core/server/src/helper.ts, packages/core/server/src/index.ts, packages/core/server/src/middlewares/data-template.ts, packages/core/server/src/middlewares/parse-variables.ts, packages/core/utils/src/index.ts, packages/core/utils/src/wrap-middleware.ts, packages/plugins/@nocobase/plugin-acl/src/server/server.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/server.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/plugin.ts, packages/plugins/@nocobase/plugin-field-china-region/src/server/index.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts, packages/plugins/@nocobase/plugin-verification/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
=> chore: add middleware name

packages/core/client/src/block-provider/__tests__/hooks/getAppends.test.ts, packages/core/client/src/block-provider/hooks/index.ts, packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.Card.tsx
| 🇺🇸 English |       Fix error when opening popup in kanban    |
| 🇨🇳 Chinese |     修复在看板中打开弹窗时报错的问题      |
=> fix(kanban): fix incorrect appends parameter issue

packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/utils/package.json, packages/core/utils/src/client.ts, packages/core/utils/src/handlebars.ts, packages/core/utils/src/index.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/utils.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/utils/compile.ts
Support to use handlebars in message content.
| 🇺🇸 English | support to use handlebars in message content |
| 🇨🇳 Chinese | 支持在通知模板中使用 Handlebars 模板引擎 |
=> feat(plugin-notification-manager): support handlebars in notification message

packages/core/database/src/interfaces/boolean-interface.ts, packages/core/database/src/interfaces/multiple-select-interface.ts, packages/core/database/src/interfaces/select-interface.ts, packages/plugins/@nocobase/plugin-action-export/src/locale/en-US.json, packages/plugins/@nocobase/plugin-action-export/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts
| 🇺🇸 English |    Fix export with i18n       |
| 🇨🇳 Chinese |     修复导出过程中的多语言问题      |
=> fix: export with i18n

packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts
Add receivers to notification logs.
| 🇺🇸 English |    Add receivers to notification logs      |
| 🇨🇳 Chinese |        通知日志增加接收人信息   |
=> chore(notification-manager): add receivers to notification logs

packages/plugins/@nocobase/plugin-acl/src/server/middlewares/with-acl-meta.ts
| 🇺🇸 English |    Fix acl meta with multi filter target keys       |
| 🇨🇳 Chinese |     修复联合主键下 ACL 中间件问题      |
=> fix: acl meta with multi filter target keys

packages/core/database/src/interfaces/to-one-interface.ts, packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
| 🇺🇸 English |    fix issue with import belongs to association       |
| 🇨🇳 Chinese |   修复无法导入多对一关联的问题        |
=> fix: import with belongs to associations

packages/core/database/src/collection.ts
=> chore: file collection unavailable action

packages/plugins/@nocobase/plugin-auth/src/server/actions/auth.ts, packages/plugins/@nocobase/plugin-auth/src/server/basic-auth.ts, packages/plugins/@nocobase/plugin-auth/src/swagger/index.ts
| 🇺🇸 English | Fix the issue where users can't change password when signing in with a non-password authenticator          |
| 🇨🇳 Chinese | 修复用户使用非密码认证器登录时无法修改密码的问题          |
=> fix(auth): issue where users can't change password when signing in with a non-password authenticator

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
…ng-type title field
| 🇺🇸 English |       Fix issue with fuzzy search support for association fields with string type title field    |
| 🇨🇳 Chinese |      修复 关系字段标题字段为string 类型时应支持模糊查询     |
=> fix(client): issue with fuzzy search support for association fields with string type title field

packages/core/database/src/interfaces/datetime-no-tz-interface.ts, packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts
=> fix: import with datetime no tz field

packages/core/database/src/database.ts, packages/core/logger/src/request-logger.ts, packages/core/server/src/application.ts
=> feat: database beanchmark

packages/core/client/src/collection-manager/collectionPlugin.ts, packages/core/database/src/database.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/http-api/collections.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/repositories/collection-repository.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/resourcers/collections.ts
| 🇺🇸 English |     refactor the collections:list api  to improve performance       |
| 🇨🇳 Chinese |    重新实现 collections:list 接口以提升性能       |
=> refactor: collections api

packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/channel/components/index.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/channel/schemas/index.ts, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/log/schemas/index.ts
improve notification channel manager UI
| 🇺🇸 English |    improve notification channel manager UI      |
| 🇨🇳 Chinese |   优化通知渠道管理UI        |
=> chore(notification-manager): improve notification channel manager UI

packages/core/database/src/interfaces/to-many-interface.ts, packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts
| 🇺🇸 English |   Fixed the issue that many-to-many relationship data cannot be imported through the id field        |
| 🇨🇳 Chinese |   修复无法通过 id 字段导入多对多关联数据的问题        |
=> fix: import with m2m id field

packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/client/src/schema-component/antd/menu/Menu.tsx
| 🇺🇸 English |  support hiding menu items  |
| 🇨🇳 Chinese |  支持隐藏菜单项   |
=> feat: support hiding menu items

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageList.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/InAppNotificationChannel.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/manager.ts, packages/plugins/@nocobase/plugin-notification-manager/src/server/types.ts
Handlebars template not compiled in `send` API.
| 🇺🇸 English | fix template not compiled in notification api |
| 🇨🇳 Chinese | 修复通知发送 API 中未编译模板的问题 |
=> fix(plugin-notification-manager): fix template compiling

packages/plugins/@nocobase/plugin-workflow-loop/src/server/LoopInstruction.ts
Fix wrongly condition checking in loop node.
| 🇺🇸 English | fix wrongly condition checking in loop node |
| 🇨🇳 Chinese | 修复循环节点条件检查的问题 |
=> fix(plugin-workflow-loop): fix condition checking

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |     Fix align right-fixed column in table      |
| 🇨🇳 Chinese |      修复 表格右固定列未贴边问题     |
=> fix: align right-fixed column in table

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
Support union key in collection event when triggering.
| 🇺🇸 English | support union key in collection event |
| 🇨🇳 Chinese | 数据表事件支持联合主键 |
=> feat(plugin-workflow): support union key in collection event

packages/core/client/src/data-source/collection-field/CollectionField.tsx, packages/core/client/src/data-source/collection-field/CollectionFieldProvider.tsx, packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> feat: support summary props

packages/core/data-source-manager/src/collection.ts, packages/core/data-source-manager/src/types.ts, packages/core/database/src/collection.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-sources-field-model.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/resourcers/data-sources-collections-fields.ts
=> chore: support update field attribute in collection

packages/core/build/src/buildClient.ts, packages/core/build/src/buildEsm.ts, packages/core/build/src/buildPlugin.ts
| 🇺🇸 English | Fixed the issue failing to build the plugin if containing .less file  |
| 🇨🇳 Chinese | 修复含有 .less 文件的插件会构建失败的问题 |
=> fix: build error due to less-loader

packages/core/client/src/schema-settings/LinkageRules/components/LinkageHeader.tsx
| 🇺🇸 English |      Fix issue preventing linkage rule title from being cleared during editing   |
| 🇨🇳 Chinese |    修复联动规则标题编辑时无法清空的问题    |
=> fix: linkage rule title editing issue

.github/workflows/nocobase-test-frontend.yml, packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx
Try fix frontend test failure.
| 🇺🇸 English | fix failure in frontend test CI |
| 🇨🇳 Chinese | 修复 CI 中前端测试失败的问题 |
=> chore(ci): change fe test based on node 20

packages/plugins/@nocobase/plugin-workflow/src/client/AddNodeContext.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesBasicType.test.ts
Node disappears after added condition without branch before it.
1. Add a node in a workflow.
2. Add a condition node before the first node, using no branch mode.
The first node disappeared.
Involved by #5570.
| 🇺🇸 English | fix node disappears after added condition without branch before it |
| 🇨🇳 Chinese | 修复创建非分支条件节点后，之后的节点消失的问题 |
=> fix(plugin-workflow): fix node disappears after added condition without branch before it

packages/core/client/src/block-provider/hooks/index.ts, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx
| 🇺🇸 English |     Fix field assignment to support variable value as 0    |
| 🇨🇳 Chinese |    修复字段赋值支持变量值为 0       |
=> fix: field assignment to support variable value as 0

.github/workflows/release.yml, packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx
| 🇺🇸 English |      Fix linkage rule saving empty value changes to static empty value     |
| 🇨🇳 Chinese |    修复 联动规则赋空值保存后变为静态值空       |
=> fix:  linkage rule saving empty value changes to static empty value

packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockInitializer.tsx
…dding
| 🇺🇸 English |      Fix gantt block template incorrectly calls the calendar block when adding     |
| 🇨🇳 Chinese |      修复甘特图添加区块时模板列表为日历区块的模板
|
=> fix: gantt block template incorrectly calls the calendar block when adding

packages/core/client/src/acl/ACLProvider.tsx
| 🇺🇸 English |      Fix  field permission check not affected by association field context   |
| 🇨🇳 Chinese |   修复 字段权限判断被关系字段上下文影响        |
=> fix: field permission check not affected by association field context

packages/core/client/src/schema-component/common/utils/logic.js
| 🇺🇸 English |    Fix  linkage rule condition with date variable not working       |
| 🇨🇳 Chinese |    修复联动规则中使用日期变量作为条件判断不生效       |
=> fix: linkage rule condition with date variable not working

packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
…there are fewer columns
| 🇺🇸 English |     Fix  issue where right-fixed column does not align to the right when there are fewer columns      |
| 🇨🇳 Chinese |      修复 列数少时右固定列未正确对齐到右边     |
=> fix: issue where right-fixed column does not align to the right when there are fewer columns

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/collection.ts
Remove page limit in query node.
| 🇺🇸 English | remove page limit in query node |
| 🇨🇳 Chinese | 去除工作流查询节点的分页条数限制 |
=> fix(plugin-workflow): fix page limit

packages/core/build/src/buildClient.ts, packages/core/build/src/buildEsm.ts, packages/core/build/src/buildPlugin.ts, packages/core/client/src/application/utils/globalDeps.ts
| 🇺🇸 English | Revert the client build tool from `rspack` back to `vite` to fix the issue where the `yarn dev` command reports an error after running the create-nocobase-app command |
| 🇨🇳 Chinese | 将客户端构建工具由 `rspack` 暂时回退回 `vite`, 修复 `create-nocobase-app` 命令安装后 `yarn dev` 报错的问题 |
=> fix: create-nocobase-app yarn dev error

.env.e2e.example, packages/core/client/src/schema-component/antd/page/index.ts
Export essential hook for other usage.
| 🇺🇸 English | export essential hook |
| 🇨🇳 Chinese | 导出必要的 hook |
=> fix(client): export essential hook

packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx
| 🇺🇸 English |     Fix adjust feedbackLayout to improve validation messaging in sub-table      |
| 🇨🇳 Chinese |    改进 子表格中验证信息的反馈显示方式       |
=> fix: adjust feedbackLayout to improve validation messaging in sub-table

packages/core/server/src/plugin-manager/plugin-manager-repository.ts
| 🇺🇸 English |   Load plugins in dependency order  |
| 🇨🇳 Chinese |   按依赖顺序加载插件 |
=> fix: load plugins in dependency order

packages/core/build/src/buildClient.ts
| 🇺🇸 English | Fix the issue executing `yarn dev` after create-nocobase-app results in an error |
| 🇨🇳 Chinese | 修复 `create-nocobase-app` 后执行 `yarn dev` 报错的问题 |
=> fix: yarn dev error if installed with create-nocobase-app

packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
| 🇺🇸 English |        Fix issue of  label width for association fields in horizontal layouts   |
| 🇨🇳 Chinese |     修复横排布局下关系字段label 宽度异常问题      |
=> fix: issue of  label width for association fields in horizontal layouts

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
…yer sub-form
修复前
修复后
| 🇺🇸 English |     Fix linkage of association data in nested sub-tables within multi-layer sub-form      |
| 🇨🇳 Chinese |     修复 多层子表单下嵌套子表格，关系数据联动异常问题      |
=> fix: linkage of association data in nested sub-tables within multi-layer sub-form

packages/plugins/@nocobase/plugin-file-manager/src/server/storages/s3.ts
…set to true
| 🇺🇸 English |  when the endpoint is not empty, forcePathStyle is set to true |
| 🇨🇳 Chinese | 当 Endpoint 不为空时，forcePathStyle 为 true |
=> fix(file-manager): when the endpoint is not empty, forcePathStyle is set to true

packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
Reverts nocobase/nocobase#5709
=> Revert "fix: issue of  label width for association fields in horizontal layouts"

packages/plugins/@nocobase/plugin-mobile/src/client/mobile/styles.ts
=> fix: mobile Tab text vertical alignment issue

packages/core/lock-manager/package.json, packages/plugins/@nocobase/plugin-field-sort/package.json
Add description for plugin-field-sort.
| 🇺🇸 English | add plugin description |
| 🇨🇳 Chinese | 补充插件描述 |
=> fix(plugin-field-sort): add plugin description

packages/core/client/src/api-client/APIClient.ts, packages/core/client/src/application/Application.tsx, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/pm/PluginManager.tsx, packages/core/server/src/commands/pm.ts, packages/core/server/src/plugin-manager/options/resource.ts
| 🇺🇸 English |  support bulk enabling of plugins in the interface  |
| 🇨🇳 Chinese | 支持在界面上批量激活插件 |
=> feat: support bulk enabling of plugins in the interface

packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx
| 🇺🇸 English |  Fix issue with checkbox alignment in sub-table        |
| 🇨🇳 Chinese |     修复 子表格勾选框内容未对齐问题      |
=> fix: issue with checkbox alignment in sub-table

packages/core/auth/src/auth-manager.ts, packages/plugins/@nocobase/plugin-auth/src/client/basic/Options.tsx, packages/plugins/@nocobase/plugin-auth/src/client/basic/SignUpForm.tsx, packages/plugins/@nocobase/plugin-auth/src/locale/en-US.json, packages/plugins/@nocobase/plugin-auth/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-auth/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-auth/src/server/actions/authenticators.ts, packages/plugins/@nocobase/plugin-auth/src/server/basic-auth.ts, packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
Reverts nocobase/nocobase#5717
=> Revert "feat(basic-auth): allows to add more fields in sign up form"

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/UsersSelect.tsx, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/receiver/components/User/UserSelect.tsx
…lect components
Fix option label not loaded on first render.
| 🇺🇸 English |    Fix selected option label not loaded on first render.       |
| 🇨🇳 Chinese |     修复已选择选项的标签在第一次渲染时未被加载的问题。      |
=> fix(RemoteSelect component): fix selected option label not loaded on first render

packages/core/server/src/plugin-manager/plugin-manager-repository.ts, packages/core/server/src/plugin-manager/plugin-manager.ts
=> fix: continent on error

packages/core/auth/src/auth-manager.ts, packages/plugins/@nocobase/plugin-auth/src/client/basic/Options.tsx, packages/plugins/@nocobase/plugin-auth/src/client/basic/SignUpForm.tsx, packages/plugins/@nocobase/plugin-auth/src/locale/en-US.json, packages/plugins/@nocobase/plugin-auth/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-auth/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-auth/src/server/actions/authenticators.ts, packages/plugins/@nocobase/plugin-auth/src/server/basic-auth.ts, packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
| 🇺🇸 English | Allows to add more fields of user collection in sign up form           |
| 🇨🇳 Chinese | 支持在注册表单中添加更多用户表的字段          |
=> feat(basic-auth): allows to add more fields of user collection in sign up form

packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/Map.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/utils.ts
| 🇺🇸 English |   Fix error when changing zoom levels in Google Maps        |
| 🇨🇳 Chinese |   修复 Google Map 切换缩放等级时报错的问题        |
=> fix: error when changing zoom levels in Google Maps

packages/core/client/src/block-provider/TableSelectorProvider.tsx
| 🇺🇸 English |   Fix foreign key field display issue in the data selector        |
| 🇨🇳 Chinese |   修复 数据选择器未显示外键字段        |
=> fix: foreign key field display issue in the data selector

packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/formatter.test.ts, packages/plugins/@nocobase/plugin-data-visualization/src/server/query-parser/query-parser.ts
| 🇺🇸 English | Fix the issue where getting timezone from `context` incorrectly         |
| 🇨🇳 Chinese | 修复从 `context` 获取时区不正确的问题          |
=> fix(data-vi): issue where getting timezone from context

packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/styles.ts
移动端setting 去掉主题设置
| 🇺🇸 English |  optimize compact theme for mobile         |
| 🇨🇳 Chinese |      移动端紧凑主题下样式优化     |
=> refactor: optimize compact theme for mobile

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |     Fix scrollbar issue when table has few columns with medium size      |
| 🇨🇳 Chinese |    修复表格在中等尺寸时列数较少仍出现滚动条的问题       |
=> fix: scrollbar issue when table has few columns with medium size

packages/core/client/src/data-source/collection-fields-to-initializer-items/utils/type.ts
=> fix: client build error

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
=> fix: build error

packages/core/database/src/__tests__/update-associations.test.ts, packages/core/database/src/update-associations.ts
| 🇺🇸 English |    Fix update hasOne/belongsTo association values without foreign key       |
| 🇨🇳 Chinese |      修复带外键更新关系字段的问题     |
=> fix: update hasOne/belongsTo association values without foreign key

packages/core/database/src/__tests__/update-associations.test.ts, packages/core/database/src/update-associations.ts
=> fix: update association with foreign key

packages/core/client/src/lazy-helper/index.tsx
| 🇺🇸 English | fixed the warning message in React when dynamically loading hooks in the development environment |
| 🇨🇳 Chinese | 修复开发环境中动态加载 hook 时会出现 React 告警消息 |
=> fix: react warning when using uselazy

packages/core/client/src/modules/blocks/data-blocks/details-multi/DetailsBlockInitializer.tsx, packages/core/client/src/modules/blocks/data-blocks/grid-card/GridCardBlockInitializer.tsx, packages/core/client/src/modules/blocks/filter-blocks/collapse/FilterCollapseBlockInitializer.tsx, packages/plugins/@nocobase/plugin-block-iframe/src/client/IframeBlockInitializer.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/workbenchBlockInitializerItem.ts, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/items/CalendarBlockInitializer.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockInitializer.tsx, packages/plugins/@nocobase/plugin-kanban/src/client/KanbanBlockInitializer.tsx
To use icons with more accurate meanings for block initializers.
| 🇺🇸 English | To use icons with more accurate meanings for block initializers |
| 🇨🇳 Chinese | 区块初始化器使用更匹配类型含义的图标 |
=> refactor(client): change block initializers icons

packages/core/database/src/__tests__/fields/datetime-tz.test.ts, packages/core/database/src/update-associations.ts
=> fix: set belongs to many associations

packages/core/cli/src/commands/dev.js, packages/core/cli/src/commands/start.js, packages/core/cli/src/util.js, packages/core/create-nocobase-app/templates/app/package.json.tpl
| 🇺🇸 English |  Restart the process when plugins are added or removed |
| 🇨🇳 Chinese |  添加或移除插件时重启进程 |
=> feat: restart the process when plugins are added or removed

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
| 🇺🇸 English |    Fix select field to display blank when data is empty       |
| 🇨🇳 Chinese |      修复 select 数据为空时应显示空白     |
=> fix: select field to display blank when data is empty

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
| 🇺🇸 English |   Fix field width issue in sub table in horizontal layout      |
| 🇨🇳 Chinese |     修复水平布局时子表格中字段宽度异常      |
=> fix: field width issue in sub table in horizontal layout

packages/core/client/src/modules/popup/__e2e__/schemaInitializer1.test.ts
Fix E2E cases based on changed icons.
| 🇺🇸 English | Fix E2E cases based on changed icons |
| 🇨🇳 Chinese | 修复图标变更后导致的 E2E 用例执行失败 |
=> fix(client): fix e2e cases based on changed icons

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
Fix variable not showing in nodes test modal.
1. Use a scope variable (loop) in a node (request).
2. Open test modal.
| 🇺🇸 English | Fix variable not showing in nodes test modal |
| 🇨🇳 Chinese | 修复节点测试弹窗中变量显示错误的问题 |
=> fix(plugin-workflow): fix test button variable

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/index.tsx
| 🇺🇸 English |     Fix  incorrect display of source key      |
| 🇨🇳 Chinese |    修复 source key 显示不正确       |
=> fix: incorrect display of source key

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
=> fix: tag color

packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx
…s pages
| 🇺🇸 English |     Fix  record picker not displaying selected items when selecting across pages      |
| 🇨🇳 Chinese |     修复 数据选择器在跨页选择数据时无法显示已选项      |
=> fix: record picker not displaying selected items when selecting across pages

packages/core/server/src/gateway/index.ts
=> chore: remove logger in gateway

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx
| 🇺🇸 English |   Fix incorrect parameters passed in table block filtering        |
| 🇨🇳 Chinese |    修复表格区块筛选传参错误       |
=> fix: incorrect parameters passed in table block filtering

packages/core/client/src/schema-settings/VariableInput/hooks/useFormVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useIterationVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useParentIterationVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useRecordVariable.ts
| 🇺🇸 English |      Fix issues where variables cannot be properly used in third-party data source blocks     |
| 🇨🇳 Chinese |     修复一些变量在第三方数据源区块中无法正常使用的问题      |
=> fix(variable): fix issues where variables cannot be properly used in third-party data source blocks

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx
| 🇺🇸 English |     Fix missing date input field in filter operation on mobile      |
| 🇨🇳 Chinese |    修复 移动端筛选操作缺少日期输入框       |
=> fix: missing date input field in filter operation on mobile

.env.example, packages/core/cli/src/commands/pkg.js
| 🇺🇸 English |  optimize the pkg command  |
| 🇨🇳 Chinese |  优化 pkg 命令 |
=> perf: optimize the pkg command

packages/core/client/src/application/schema-initializer/components/SchemaInitializerItemSearchFields.tsx
| 🇺🇸 English |       Optimize recursive logic in useMenuSearch for better performance    |
| 🇨🇳 Chinese |    优化 useMenuSearch 递归逻辑，提升性能      |
=> chore: configure fields support filtering

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Fix async workflow tag disappeared in workflow table.
| 🇺🇸 English | Fix async workflow tag disappeared in workflow table |
| 🇨🇳 Chinese | 修复异步工作流在工作流列表中未展示字段标识 |
=> fix(plugin-workflow): fix sync column tag

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/styles.ts, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/components/MobileDatePicker.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/components/MobilePicker.tsx
| 🇺🇸 English |        Optimize action panel and public form components for mobile adaptation  |
| 🇨🇳 Chinese |     操作面板、公开表单组件优化适配移动端       |
=> refactor: optimize operation panel and public form components for mobile adaptation

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |     Fix scrollbar issue in sub-table with size small under compact theme      |
| 🇨🇳 Chinese |   修复紧凑主题下子表格 size 为 small 时出现滚动条        |
=> fix: scrollbar issue in sub-table with size small under compact theme

packages/core/client/src/api-client/APIClient.ts
| 🇺🇸 English |  Loss of request headers on silent requests |
| 🇨🇳 Chinese | 静默请求时丢失请求头信息  |
=> fix: loss of request headers on silent requests

packages/core/client/src/schema-component/antd/action/ActionBar.tsx
| 🇺🇸 English |      Fix configure action button should be left-aligned     |
| 🇨🇳 Chinese |      修复操作配置按钮未左对齐的问题     |
=> fix: configure action button to be left-aligned

packages/core/test/src/server/mock-server.ts
Allow login with role name in test cases.
| 🇺🇸 English | Allow login with role name in test cases |
| 🇨🇳 Chinese | 支持测试用例中登录方法包含角色名称 |
=> chore(test): add roleName to login in mock server

packages/core/client/src/application/components/AppComponent.tsx
| 🇺🇸 English |  Blank page when user has no role |
| 🇨🇳 Chinese | 用户无角色时页面空白 |
=> fix: blank page when user has no role

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/ContentConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/en-US.json, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/zh-CN.json
Update titles for detail URLs in forms and localization files.
| 🇺🇸 English |     update titles for detail URLs in in-app-message forms and localization files      |
| 🇨🇳 Chinese |    更新站内信详情链接的标题   |
=> chore(notification-in-app-message): update titles for detail URLs in forms and localization files

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
| 🇺🇸 English |      Fix  error when clicking on a blank date in the calendar     |
| 🇨🇳 Chinese |       修复日历点击空白日期时报错的问题    |
=> fix: error when clicking on a blank date in the calendar

packages/core/client/src/schema-component/antd/action/context.tsx
| 🇺🇸 English |      Prevent multiple API calls when closing the popup     |
| 🇨🇳 Chinese |     关闭弹窗时，防止触发多次 API 请求      |
=> fix: prevent multiple requests from being triggered

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
=> fix: select readPretty issue
