packages/plugins/workflow/src/__tests__/collections/comments.ts
packages/plugins/workflow/src/__tests__/collections/posts.ts
packages/plugins/workflow/src/__tests__/collections/tags.ts
packages/plugins/workflow/src/__tests__/execution.test.ts
packages/plugins/workflow/src/__tests__/instructions/calculation.test.ts
packages/plugins/workflow/src/__tests__/instructions/condition.test.ts
packages/plugins/workflow/src/__tests__/instructions/create.test.ts
packages/plugins/workflow/src/__tests__/instructions/destroy.test.ts
packages/plugins/workflow/src/__tests__/instructions/query.test.ts
packages/plugins/workflow/src/__tests__/instructions/update.test.ts
packages/plugins/workflow/src/__tests__/workflow.test.ts
packages/plugins/workflow/src/actions/index.ts
packages/plugins/workflow/src/actions/workflows.ts
packages/plugins/workflow/src/instructions/query.ts
packages/plugins/workflow/src/models/Workflow.ts
packages/plugins/workflow/src/server.ts
packages/plugins/workflow/src/triggers/collection.ts
packages/plugins/workflow/src/triggers/index.ts

* change to multiple instances when init plugin
* use internal event management to toggle hooks
* change `afterCreate`/`afterUpdate` sequelize model events to `afterCreateWithAssociations`/`afterUpdateWithAssociations` db events (fix #384)
* fix test cases

refactor(plugin-workflow): multiple instances and event management (fix #384)

---

.vscode/launch.json
packages/core/cli/src/commands/dev.js
tsconfig.json

* Add Visual Studio Code debug configuration
* Default for start debug server
* Another for temporary single test case
* `tsconfig.json` due to https://github.com/TypeStrong/ts-node/issues/922#issuecomment-673155000
* Fix `PROXY_TARGET_URL` in dev command

chore(debug): add debug config

---

packages/plugins/collection-manager/src/__tests__/field-options/indexes.test.ts
packages/plugins/collection-manager/src/server.ts

Default value of `unique` of a field will be `undefined`, and when update it to `true`, should do migrate.

fix(plugin-cm): fix unique option default value to update

---

packages/core/client/src/schema-component/antd/upload/shared.ts

in customRequest method can't modify form's status(e.g: form.disabled=true ) that will be trigger Upload component（actual Underlying is AjaxUploader component ）'s  componentWillUnmount method which will cause multiple files upload fail

fix(client/upload): fix upload mutiple files always uploading status

---

packages/core/client/src/schema-component/hooks/useFieldComponentOptions.ts

现在所有使用到 FormItem.Designer 的地方都会出现 FieldComponent 这个选项

fix: field component options appears in non-association interface

---

docs/en-US/manual/blocks-guide/charts.md
docs/tr-TR/manual/blocks-guide/charts.md
docs/zh-CN/manual/blocks-guide/charts.md

It displays 404 when opening [https://g2plot.antv.antgroup.com/en/examples/gallery](https://g2plot.antv.antgroup.com/en/examples/gallery).

docs: update G2Plot example url

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

fix(table): make td overflow behavior right (#1392)

---

packages/core/client/src/collection-manager/CollectionManagerProvider.tsx
packages/core/client/src/collection-manager/CollectionManagerShortcut.tsx
packages/plugins/graph-collection-manager/src/client/GraphDrawPage.tsx
packages/plugins/graph-collection-manager/src/client/components/Entity.tsx

fix: repeat request categories when switching between graph interface and collection&fields

---

docs/en-US/manual/blocks-guide/charts.md
docs/tr-TR/manual/blocks-guide/charts.md
docs/zh-CN/manual/blocks-guide/charts.md

- 问题
现在的文档 https://docs.nocobase.com/manual/blocks-guide/charts#video 下的视频需要点开链接，然后打开新的标签页查看视频，比较麻烦
- 解决办法
其实 Markdown 支持 HTML 语法，所以可以直接在 md 中插入 video 标签就可以实现在当前文档中查看视频

docs: transform video link to video tag

---

packages/core/client/src/pm/PluginManagerLink.tsx
packages/core/client/src/schema-component/core/DesignableSwitch.tsx

When mouse hover on the plugin-manage Button and designable-switch Button, it shows title tooltip

fix: plugin-manage and designable-switch add tooltip

---

packages/core/client/src/block-provider/hooks/index.ts

修复： 使用自定义操作提交表单的时候，如果是深层弹窗，提交后只应该关闭当前层，不应该关闭全部弹窗

fix: close the drawer incorrectly after submit

---

packages/core/client/src/schema-component/antd/menu/Menu.tsx
packages/core/client/src/schema-component/common/dnd-context/index.tsx
packages/core/client/src/schema-component/common/sortable-item/SortableItem.tsx

When drag&drop a menu-item, if its parent only have one child, it will remove parent
To fix it, add a param about whether remove its parent
当移动 menu-item 的时候，如果父菜单只有一个元素，移动走了会导致父菜单被删除
加了一个参数判断是否需要删除

fix: fix Menu dismiss on Drag&Drop

---

packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx
packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
packages/core/client/src/schema-settings/hooks/useIsShowMultipleSwitch.ts

https://main.test.nocobase.com/admin/dix4b1lmjhe

fix: fix multi-select field not show 'Allow multiple' switch

---

packages/plugins/workflow/src/server/instructions/query.ts

Remove useless code.
None.
No changes.
No changes.
None.
Query node does not use any `executionId` to avoid duplicated triggers.
Remove useless code.

fix(plugin-workflow): remove useless context option

---

packages/plugins/workflow/src/client/triggers/index.tsx

1. Click "View" workflow on workflows list.
Should not throw error.
```
RefferenceError: Cannot access 'typeTitle' before initialization
```
None.
Maybe workflow not fully loaded.
Check `workflow` variable first before use.

fix(plugin-workflow): fix trigger title when workflow not loaded

---

packages/plugins/workflow/src/client/nodes/aggregate.tsx
packages/plugins/workflow/src/client/nodes/condition.tsx
packages/plugins/workflow/src/client/nodes/index.tsx
packages/plugins/workflow/src/client/nodes/loop.tsx
packages/plugins/workflow/src/client/variable.tsx

1. Create a Loop node in workflow.
2. Create a Calculation node in branch of loop.
3. Click node in branch of loop.
Open configuration drawer normally.
Error raised.
None.
Variable options API bug.
As changes.

fix(plugin-workflow): fix variable api caller in loop

---

packages/core/client/src/locale/en_US.ts
packages/core/client/src/locale/es_ES.ts
packages/core/client/src/locale/ja_JP.ts
packages/core/client/src/locale/pt_BR.ts
packages/core/client/src/locale/ru_RU.ts
packages/core/client/src/locale/tr_TR.ts
packages/core/client/src/locale/zh_CN.ts
packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
packages/core/utils/src/client.ts
packages/core/utils/src/notification.ts

- 数据模板创建后，删除关系字段后无法正常使用报错
1. 先选择关系字段中的关系字段，保存
2. 再去数据表中删除关系字段中的关系字段
- 没有报错，如果模板中的字段已被删除干净，则需要告知用户原因
- 有错误信息
- 因用户删除了对应的字段，导致后端查询不到该字段而产生错误。
1. 前端请求模板数据之前会检查一下模板中的字段是否已被删除
2. 如果已经被删除则会被过滤掉
3. 如果字段已被删除干净，则告知用户需要重新配置模板

fix(Data-template): fix bug when deleting fields

---

packages/plugins/formula-field/src/client/components/Formula/Result.tsx
packages/plugins/formula-field/src/client/components/Formula/index.tsx

#1805
Using dynamic result calculating in all collection including all associating ones.
Change `Formula.Result` component to use only value (read-pretty) in associating collection views.

fix(plugin-formula): use read-pretty component in result

---

packages/core/client/src/block-provider/hooks/index.ts
packages/core/client/src/collection-manager/interfaces/m2m.tsx
packages/core/client/src/collection-manager/interfaces/m2o.tsx
packages/core/client/src/collection-manager/interfaces/o2m.tsx
packages/core/client/src/collection-manager/interfaces/o2o.tsx
packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
packages/core/client/src/schema-component/antd/association-field/Editable.tsx
packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx
packages/core/client/src/schema-component/antd/association-field/Nester.tsx
packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
packages/core/database/src/update-guard.ts
packages/plugins/ui-schema-storage/src/migrations/20230522231231-association-field.ts

refactor: initialization when switching field components

---

.github/workflows/nocobase-test-full.yml
.github/workflows/nocobase-test-lite.yml
jest.config.js
package.json
packages/core/client/src/application/__tests__/__snapshots__/compose.test.tsx.snap
packages/core/client/src/route-switch/__tests__/__snapshots__/RouteSwitch.test.tsx.snap
packages/core/client/src/schema-component/antd/date-picker/__tests__/mapDatePicker.test.ts
packages/core/client/src/schema-component/antd/date-picker/__tests__/mapRangePicker.test.ts
packages/core/client/src/schema-component/hooks/__tests__/designable.test.ts
packages/core/client/tsconfig.json
packages/core/dumi-theme-nocobase/package.json
packages/core/sdk/tsconfig.json
scripts/setupVitest.ts
testUtils.ts
tsconfig.json
vitest.config.ts
yarn.lock

在前端项目中使用 Vitest 替换 Jest 以获取更好的性能和兼容性。
目前前端使用 Jest 时存在兼容性问题，某些时候会无法运行。
- 无改动
- Backend (后端)
- 无改动
- 无需测试
- 没有风险

refactor: front-end testing with vitest

---

packages/core/client/src/locale/en_US.ts
packages/core/client/src/locale/es_ES.ts
packages/core/client/src/locale/ja_JP.ts
packages/core/client/src/locale/pt_BR.ts
packages/core/client/src/locale/ru_RU.ts
packages/core/client/src/locale/tr_TR.ts
packages/core/client/src/locale/zh_CN.ts
packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
packages/core/client/src/schema-settings/DataTemplates/FormDataTemplates.tsx
packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts
packages/core/client/src/schema-settings/SchemaSettings.tsx

原来这里支持最多 3 级的字段选择，现在需要改成可以无限层级选择字段。
用户反映需要多层级选择字段。
- 当用户点击某项关系数据时，异步加载起子节点
- 异步加载可以防止页面卡死
- Backend (后端)
- 后端无改动
主要测试这里是否可以无限层级的展开，并且能正常工作。
- 当用户选择的字段过多时，浏览器会终止请求并报错。
- 因为字段选择器的数据是异步加载的，只有展开父节点的时候子节点才能被选中。
- 无潜在风险。

feat(data-template): support for unlimited levels of fields selection

---

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx
packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx
packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
packages/core/client/src/schema-component/core/SchemaComponentProvider.tsx
packages/core/client/src/schema-items/GeneralSchemaItems.tsx
packages/core/client/src/schema-settings/DataTemplates/FormDataTemplates.tsx
packages/core/client/src/schema-settings/DataTemplates/components/Designer.tsx
packages/core/client/src/schema-settings/SchemaSettings.tsx
packages/core/client/src/schema-settings/hooks/useIsShowMultipleSwitch.ts
packages/core/client/src/schema-templates/BlockTemplateDetails.tsx

- 如下图所示，在 `数据模板` 中支持 `设置数据范围` 和 `设置标题字段`。
- 模板数据列表可能会有很多数据，不利于用户选择。
- 在数据表管理页面配置 `标题字段` 不方便，并且如果要在某些特定的区块使用其它 `标题字段` 则无法实现。
- 新增一个 Designer 组件，与普通表单区块类似。
- 新增的 Designer 组件不可拖动和新增其它字段。
- Backend (后端)
- 无改动
- 暂时没有发现潜在危险。
- 该功能为新增功能，不会对原来的功能造成影响。

feat(data-template): support to set data scope and title field

---

packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
packages/core/client/src/schema-settings/DataTemplates/components/DataTemplateTitle.tsx

如下图所示，如果先输入 `模板标题` 会导致其它选项异常。
1. 打开设置数据模板弹窗
2. 先输入 `模板标题`
3. 再切换 `数据表`
4. 会发现 `模板数据` 还是保持原样，并没有跟着 `数据表` 切换
- 无论是否是先输入 `模板标题` 都不影响其它选项的正常使用
- 参考上面的 `复现步骤`
- 在修改 `模板标题` 的时候破环了原有数据的响应性，导致数据变更之后 UI 没有刷新
- 在 `DataTemplateTitle` 组件中修改 `onChange` 和 `onBlur` 的监听方法，防止破环数据的响应性。
具体变动请看：https://github.com/nocobase/nocobase/pull/1937/files?diff=split&w=0

fix(data-template): fix title input prevented proper data switching

---

packages/core/client/src/block-provider/hooks/index.ts

表格中添加bulk edit -> Form-> 添加关系字段
正常使用
报错，cant not read properties of undefined (read mode) 
schema的‘x-compoent-props'不一定有mode属性
schema['x-component-props'].?mode==='Nester'
使用可选链操作符（Optional Chaining Operator）?.。这样，如果 mode 存在，表达式将返回 mode 的值；如果 mode 不存在，则整个表达式的结果为 undefined。

fix(useAssociationNames): undefined mode in useAssociationNames

---

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx

普通字段不应该有 数据范围和排序规则
应该通过interface来判断关系字段而不是通过type来判断关系字段，行政区划 和附件字段虽然也是关系字段但不应该出现范围配置等关系字段配置

fix(form-item): data scope and sorting rule config should only display in association field

---

packages/core/evaluators/src/server/__tests__/index.test.ts
packages/core/evaluators/src/utils/index.ts

Random key which lead by number in variable path can not be calculated correctly.
`{{a.1b}}`
Could access variable to `{ a: { '1b': 1 } }`.
```
SyntaxError: Invalid or unexpected token
```
None.
Function `replaceNumberIndex` did not handle number lead keys correctly.
Change the regular expression to a more accurate one.

fix(evaluators): fix number lead key in variable path

---

packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx

详情区块中，关系字段树表配置开启后，再次打开配置失效
应该判断关系字段的target表是否是树表
resource -> field -> field.target -> 判断 field.target 是不是树表

fix: treeCollection config in detail block

---

packages/plugins/charts/src/client/hooks/index.ts

创建图表数据源>正常添加图表>删除数据源>图表右上角编辑图表
页面正常
页面报错
设计器弹窗前会从数据源中获取当前数据源中存在的字段，删除数据源后 `fields`变量值可能为 `undefined`
当 `fields` 为 `undefined`时，使用空数组`[]`赋值。
页面正常显示

fix(charts): fields undefined bug

---

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
packages/core/client/src/schema-component/antd/association-field/Nester.tsx
packages/core/client/src/schema-component/common/utils/uitls.tsx

用户反馈，在子表单中设置的默认值不生效：
1. 新增一个 `对多` 关系字段
2. 修改成 `子表单` 模式
3. 在子表单中增加一个字段，然后设置默认值
4. 关闭弹窗再打开会发现刚才设置的默认值没有显示
设置的默认值应该正常显示
默认值没有显示
主要是 null 值导致的字段默认值失效
把占位作用的 `null` 修改成一个空对象

fix: fix default value is invalid in subform

---

packages/core/client/src/schema-items/GeneralSchemaItems.tsx

标题字段关闭后，配置里的标题字段仍显示ka开启
标题隐藏同时标题配置关闭
标题隐藏而标题配置中却是开启的
标题字段配置项取值不对

fix(display-title): display on even after the title configuration is turned off

---

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx

首次保存了字段赋值后，再次打开无法选择变量类型
正常显示变量类型
首次保存了字段赋值后，再次打开无法选择变量类型
变量类型的options获取有问题

fix(assignedField): assignedField can not select dynamicValue

---

.eslintrc
packages/plugins/file-manager/src/client/locale/zh-CN.ts
packages/plugins/file-manager/src/client/schemas/storage.ts
packages/plugins/file-manager/src/server/__tests__/action.test.ts
packages/plugins/file-manager/src/server/__tests__/storages/ali-oss.test.ts
packages/plugins/file-manager/src/server/__tests__/storages/s3.test.ts
packages/plugins/file-manager/src/server/actions/attachments.ts
packages/plugins/file-manager/src/server/actions/index.ts
packages/plugins/file-manager/src/server/collections/storages.ts
packages/plugins/file-manager/src/server/server.ts
packages/plugins/file-manager/src/server/storages/ali-oss.ts
packages/plugins/file-manager/src/server/storages/index.ts
packages/plugins/file-manager/src/server/storages/local.ts
packages/plugins/file-manager/src/server/storages/s3.ts
packages/plugins/file-manager/src/server/storages/tx-cos.ts

Add option for storage to remove file physically or not when destroy attachment record.
The files in storage will not be deleted after attachment record destroyed. And this is a feature request (#1786).
- Add `paranoid` option in storage form.
- Backend (后端)
- Add deletion logics for all builtin storages.
By test cases.
TX-COS not tested due to no account.

feat(plugin-fm): add option for storage to remove file physically or not

---

packages/core/client/src/schema-component/antd/input/Json.tsx
packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx
packages/core/client/src/schema-component/antd/variable/JSONInput.tsx
packages/core/client/src/schema-component/antd/variable/__tests__/variable.test.tsx
packages/plugins/workflow/src/client/nodes/request.tsx

JSON input component content not updated after new value from props.
1. Use a json field in create form.
2. Submit a record with some valid json data.
3. Use data template in the form and select json field, also select the record just submitted.
4. Create a new record and use data template from last submitted record.
JSON field should be with the value from data template.
Value is empty.
N/A.
`JSONInput` is not using `value` prop to react the changing value, due to legacy implementation for validation.
Use uncontrolled value controlling, with `useState`, `useEffect`, and only invoke `onChange` in `onBlur` phase.

fix(client): fix json input component value handling

---

packages/core/client/src/schema-component/antd/page/Page.tsx

页面启用选项卡后删除掉选项页面，刷新浏览器白屏
Object.keys(fieldSchema.properties)方法报错，删掉唯一标签页后，fieldSchema.properties为null

fix: enable tab and deleting tab page  will result in an error

---

packages/core/client/src/schema-component/antd/select/Select.tsx

fix(select):  default value for multiple select cannot be set

---

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx

见下方视频：
https://github.com/nocobase/nocobase/assets/38434641/c48e3459-e9b6-4c4e-8e24-a48573b44cdf
- 缺少 `targetField` 参数
从外面传进来一个 `targetField` 参数
close T-471

fix: fix default value of optional field

---

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx

文章表多对多文件表，文件字段 select 文件之后，不应该把之前已选的文件给移除了

fix(file-manager): do not delete the selected records

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/core/client/src/schema-settings/DataTemplates/FormDataTemplates.tsx
packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts

表现为当设置多个 数据模板 时，有些本该可以被展开的字段无法被展开，只有一条模板数据时没有这个问题。
1. 创建两个数据模板
2. 会发现第二个是正常的
3. 而第一个是有问题的，也就是某些字段无法展开
正常展开
没有展开
发现之前就有这个问题。
是由于获取的 `fields` 数据错误，导致所有 `fields` 值都是最后一个模板的。
1. `onLoadData` 和 `onCheck` 方法改名为 `getOnLoadData` 和 `getOnCheck`
2. 接受当前模板的 `$self` 作为参数（也就是上面说的 fields 的值）
3. 返回一个和之前一样的函数，其 `fields` 的闭包指向参数中传入的值
close T-512

fix(Data-template): fix field cannot be expanded

---

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx

fix: association field cannot enable link in table column

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/core/client/src/schema-settings/VariableInput/hooks/useDateVariable.ts
packages/core/client/src/schema-settings/VariableInput/hooks/useUserVariable.ts
packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts

如视频所示，在字段由 `ID` 改成 `昵称` 的时候，变量 `昵称` 选项被禁用了，这是错误的。
https://github.com/nocobase/nocobase/assets/38434641/ddeae922-40e0-4745-8ed9-1399ae76a855
不应该禁用掉 `昵称` 选项。
`昵称` 选项被禁用掉了。
在 #1880 中 `useCompile` 被修改成具有缓存的功能，以获得更好的性能，但直接导致 `options` 数据一直是之前的老数据，其 `loadChildren` 函数不是最新的，所以才会出现这个 BUG。
1. 重写 `useUserVariable` ，放弃使用 `响应式对象` 方案
2. 因为 `compile` 每次返回的都是同一个对象，所以需要手动更新 `loadChildren` 的值
3. 在每次数据变更时，调用 `setOptions` 用以刷新页面

fix(Varaible): fix option is disabled

---

packages/core/client/src/schema-component/antd/input/Json.tsx

Any JSON field input.
Should represent correct JSON value.
Duplication of stringifying.
Should not invoke `onChange` in `catch` due to invalid.
Remove `onChange` in `catch`.

fix(client): fix onchange mistake

---

packages/core/client/src/schema-component/antd/checkbox/Checkbox.tsx
packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx
packages/core/client/src/schema-component/antd/input/Input.tsx
packages/plugins/formula-field/src/client/components/Formula/Result.tsx

Formula in table field not updated after the row updated.
1. Add a formula field in table.
2. Edit row with related fields, and save.
3. Edited fields updated in table, but formula field remains the value before editing.
Formula field should be same with loaded data.
Not same.
1. Read pretty components not works correctly.
2. Value not showing when delete source and input again with same value.
Effects with value.
1. Add effects.
2. Use ReadPretty components for rendering.

fix(plugin-formula): fix formula field effect and read-pretty component

---

packages/plugins/workflow/src/client/triggers/index.tsx

Occasionally, enter single workflow page.
No error.
Error occurs
None.
```
can't access lexical declaration `variable' before initialization
```
Adjust variable definition.

fix(plugin-workflow): fix occasional error on enter workflow page

---

packages/core/database/src/__tests__/repository.test.ts
packages/core/database/src/__tests__/update-guard.test.ts
packages/core/database/src/repository.ts
packages/core/database/src/update-guard.ts
packages/plugins/workflow/src/client/components/CollectionFieldset.tsx
packages/plugins/workflow/src/client/locale/zh-CN.ts
packages/plugins/workflow/src/client/nodes/update.tsx
packages/plugins/workflow/src/server/Plugin.ts
packages/plugins/workflow/src/server/__tests__/instructions/update.test.ts
packages/plugins/workflow/src/server/instructions/update.ts

add batch logic to `repository.update` for better performance.
Before this PR, `repository.update` only update rows one by one (DB IO), mostly for triggering single model events. But when used on large quantity of data, it will be very slow.
So, we need better performance in such scenario, which only send one IO to DB for multiple records updating, and not triggering single model events.
- Add `individualHooks` in update node configuration in workflow.
- Add linkage for values in update node configuration to skip non-belongsTo association values.
- Backend (后端)
- Add branch logic on `individualHooks` is exact `false` to perform batch updating.
- Fix result value of update node to only numbers.
* Unit cases.
* Benchmark.
Not support `hasOne`, `hasMany` and `belongsToMany` …

refactor(db): add batch logic to update for better performance

---

packages/plugins/workflow/src/client/nodes/index.tsx
packages/plugins/workflow/src/client/style.tsx

Use loop node and do a more than one loop.
Button icon should be on left side and not in absolute position.
Absolute position to right.
None.
Styles.
Adjust style.

fix(plugin-workflow): fix job button style

---

packages/plugins/workflow/src/server/Plugin.ts
packages/plugins/workflow/src/server/Processor.ts
packages/plugins/workflow/src/server/instructions/delay.ts
packages/plugins/workflow/src/server/instructions/loop.ts
packages/plugins/workflow/src/server/instructions/manual/actions.ts
packages/plugins/workflow/src/server/instructions/parallel.ts
packages/plugins/workflow/src/server/instructions/request.ts

Workflow not triggering after some time running. And report transaction error.
Not reproduced.
Should trigger in runtime.
Transaction error: 
~~~
{"level":"error","message":"execution (80854) error: Transaction cannot be committed because it has been finished with state: commit Transaction cannot be committed because it has been finished with state: commit","stack":"Error: Transaction cannot be committed because it has been finished with state: commit\n    at Transaction.commit (/app/nocobase/node_modules/sequelize/lib/transaction.js:41:13)\n    at /app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/Processor.js:147:34\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/Processor.js:41:103)\n    at …

fix(plugin-workflow): fix branch and exit logic

---

packages/core/client/src/schema-component/antd/menu/Menu.tsx

1. 在 `非编辑状态` 下刷新页面
2. 切换到 `编辑状态`
3. 会发现顶部和侧边栏的菜单按钮的 Designer Button 没有显示
显示 Designer Button 
没有显示 Designer Button 
无
在 `useMemo` 中没有依赖 `Designer` 导致 `Designer` 变更时 `items` 值没有更新。
在 `useMemo` 中依赖 `Designer` 即可。

fix: fix designer button does not appear

---

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
packages/plugins/workflow/src/client/WorkflowCanvas.tsx
packages/plugins/workflow/src/client/triggers/index.tsx
packages/plugins/workflow/src/client/triggers/schedule/ScheduleConfig.tsx
packages/plugins/workflow/src/client/triggers/schedule/index.tsx

After re-enter workflow canvas page, the schedule trigger config is not same as submitted before. But after reload whole page it will be correct.
1. Add a schedule type workflow.
2. Modify the trigger configurations and submit.
3. Re-open the trigger configurations panel: correct.
4. Go back to workflows list (browser history back).
5. Re-enter the workflow canvas page submitted before.
6. Open the trigger configurations panel: wrong.
7. Reload page, open the trigger configurations panel: correct.
After history go back and forward, the trigger config should be correct in panel as submitted.
The config remains as old.
None.
Legacy `Form` component in schema component does not handle values correctly.
Migrate to `FormV2` to fix.

fix(plugin-workflow): change to formv2 to avoid values updating issue

---

packages/core/client/src/schema-initializer/buttons/ReadPrettyFormItemInitializers.tsx

Association field initializers in detail block not showing.
1. Create detail block.
2. Hover to "Configure fields".
3. No association field initializers menu.
Association field initializers should show up.
No Association field initializers.
None.
`push([item1, item2])` => `push(item1, item2)`.
As above.

fix(client): fix field initializer in detail block

---

packages/core/client/src/schema-initializer/buttons/TableColumnInitializers.tsx

表格区块无法配置 【显示关联表的字段】
表格区块和详情里的子表格支持配置【显示关联表的字段】,表单中的子表格不支持配置

fix:  association fields cannot config in table

---

packages/core/client/src/schema-component/antd/preview/Preview.tsx
packages/core/client/src/schema-component/antd/upload/Upload.tsx
packages/core/client/src/schema-component/antd/upload/shared.ts
packages/core/client/src/schema-component/antd/upload/style.less

1. 批量上传多张图片
2. 会发现样式问题
- 图片的名字不应该被下面的图片盖住
- 图片上传成功后应该更新状态并显示已上传的图片
- 图片的名字被盖住
- 某些图片上传成功了，但是依然显示 `uploading` 
#1862 
https://github.com/ant-design/ant-design/issues/2423
- #1862 修改了样式，导致图片名称被覆盖
- 一直显示 `uploading` 的问题是因为 antd 的 BUG，导致 `onChange` 方法的 `fileList` 参数的值没有及时的更新，需要 antd 团队修复该问题
- 这个功能之前是好的，现在出问题，怀疑可能跟最近的 `React` 升级到 18 版本有关（未验证）
- 回退样式
- 关于一直显示 `uploading` 的问题
- 首先，使用官方推荐的[方法](https://github.com/ant-design/ant-design/issues/2423#issuecomment-233523579)不能解决这里遇到的问题
- 经测试发现 `onChange` 的 `file` 参数是正确的，所以可以根据 `file` 实时的计算出 `fileList` 的值
- 计算出的 `fileList` 需要通过一个 `useRef` 保存，如果使用 `useState` 同样会有问题
- 在删除图片的时候，同时需要删除 `Ref` 中的值
close T-650

fix(upload): fix the upload status not being updated if the upload was successful

---

packages/core/utils/src/json-templates.ts

Null value becomes `undefined` and cause comparison failure.
1. Create a condition node in workflow.
2. Assign left operand as a nullable variable.
3. Assign right operand as null constant.
4. Use "Equal" method.
5. Submit data contains the null variable (field).
6. Condition result is `false` and workflow fails.
Condition result should be `true`.
Condition result is `false`.
None.
The logic of default assign for `null` value in json-templates is not correct.
Use different way to deal with `undefined` and `null`.

fix(utils): avoid to use default value for null in json-templates

---

packages/plugins/workflow/src/client/triggers/index.tsx

The config form of workflow trigger will be empty after clicked cancel button, and remains empty after reopen.
1. Open trigger config (with data).
2. Click "Cancel" button.
3. Reopen trigger config.
Showing all configuration data.
Showing empty form.
None.
No `initialValue` provided to the form.
Add `initialValue`.

fix(plugin-workflow): fix cancel action on trigger config

---

packages/core/client/src/schema-component/antd/date-picker/__tests__/date-picker.test.tsx
packages/core/client/src/schema-component/antd/date-picker/demos/demo10.tsx
packages/core/client/src/schema-component/antd/date-picker/demos/demo7.tsx
packages/core/client/src/schema-component/antd/date-picker/demos/demo8.tsx
packages/core/client/src/schema-component/antd/date-picker/demos/demo9.tsx
packages/core/client/src/schema-component/antd/date-picker/index.md
packages/core/client/src/schema-component/antd/date-picker/util.ts
scripts/setupVitest.ts

1. 设置 `DatePicker` 的 `showTime` 为 false
2. 选择一个时间
3. 会发现日期所带的时间不是一天中的开始时间
#1558
- 当 `showTime` 为 false 时，`DatePicker` 组件所选择日期中的时间是客户端的当前时间
- 此时日期中的时间应该是一天当中的开始时间
- 在 `DatePicker` 组件中，当检测到 `showTime` 为 false 时，就把日期改为一天中的开始时间
close T-803

fix: fix time zone when showTime is false

---

packages/plugins/workflow/src/client/nodes/manual/WorkflowTodo.tsx

Data scope settings not works on workflow todo list.
1. Set a data scope on workflow todo list block, such as current user.
2. Reload the list.
Todo data should be filtered by the data scope set.
Not filtered.
None.
`WorkflowTodo.Decorator` not applies `params`.
Add `params`.

fix(plugin-workflow): fix data scope on todo table block

---

packages/core/utils/src/json-templates.ts

Fixed type checking based on test cases from original `json-templates`.
Test cases.
Pass all.
String template cases with multiple variables not pass.
#2165.
`undefined` value should be directly returned.
Handle `undefined` in single/multiple variables branches.

fix(utils): fix json-template type checking logic

---

packages/plugins/workflow/src/client/nodes/aggregate.tsx
packages/plugins/workflow/src/client/nodes/calculation.tsx
packages/plugins/workflow/src/client/nodes/create.tsx
packages/plugins/workflow/src/client/nodes/index.tsx
packages/plugins/workflow/src/client/nodes/manual/index.tsx
packages/plugins/workflow/src/client/nodes/query.tsx
packages/plugins/workflow/src/client/variable.tsx

Can not select dynamic expression from directly loaded expression record from query node.
1. Add a query node.
2. Use an expression collection to query.
3. Add a calculation node as downstream.
4. Select dynamic expression.
Query result should be in dynamic expression options list.
Not showing.
#2157.
Type filter hard to handle raw node result as fields.
Refactor `useVariables` API for all instructions, each could define and export correct node option on its own (could be with fake collection).

refactor(plugin-workflow): refactor nodes variable option api

---

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx

filter 参数应该有值
filter 参数为空
#2161 
#2161 把 `field.componentProps?.service?.params?.filter` 修改成了 `fieldSchema?.['x-component-props']?.service?.params?.filter` 以解决变量字符串（包裹在 `{{}}` 中的字符串）被提前解析的问题。但是这里的 `field.componentProps?.service?.params?.filter` 的值是一个 `{{ getFilter($self.componentProps.service.resource, $self.value) }}` 这样的字符串，这个字符串并不是一个变量，进而导致被解析为空。
1. 因 `filter` 参数通常是一个对象
2. 所以当 `filter` 是一个字符串的时候就可以假设这是类似于 `{{ 1 + 1 }}` 的字符串
3. 这个时候需要去 `field.componentProps` 里面去取值，这里面的值是经过编译之后的值
建议回归一下 #2161 @hongboji 
close T-858

fix(data-templates): filter is empty

---

packages/core/client/src/collection-manager/CollectionFieldProvider.tsx

子表重写了父表的可选项字段（select）,子表的数据在父表中显示时该可选项字段无法正常显示（没有显示label）

fix: optional fields of the child collection cannot be displayed correctly in  parent collection

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx

Variable labels not rendering correctly in AssignedField.
1. Add a custom save button in add button form.
2. Go to custom save button assign field value settings.
3. Add a field, and use some variable, save.
4. Reopen the assign field value settings, variable labels is empty.
Variable labels should showing.
Empty labels.
#2157.
Preload condition is not correct.
Revert the condition.
Link T-869.

fix(client): fix variable component for preload label based on value

---

packages/core/client/src/schema-component/antd/input/Json.tsx
packages/core/client/src/schema-component/antd/variable/JSONInput.tsx
packages/core/client/src/schema-component/antd/variable/RawTextArea.tsx
packages/core/client/src/schema-component/antd/variable/Variable.tsx

In some scenario, variable labels will be hard to get, or for the multiline of text template, or JSON, use the raw variable paths text would be more easier.
Textarea for inputing JSON/SQL etc. with variables.
- Move `Variable.InputJSON` main logic into a new component `Variable.RawTextArea`.
- Backend (后端)
1. Body input of HTTP Request node in workflow.
None.

refactor(client): abstract RawTextArea for variable input

---

packages/plugins/workflow/src/server/Plugin.ts
packages/plugins/workflow/src/server/__tests__/Plugin.test.ts
packages/plugins/workflow/src/server/__tests__/instructions/delay.test.ts
packages/plugins/workflow/src/server/__tests__/instructions/request.test.ts
packages/plugins/workflow/src/server/instructions/delay.ts

Execution run duplicated occasionally.
Not reproduced.
No duplicated executions.
Duplicated.
None.
Need `await` to get one unexecuted execution, and on that moment once another `dispatch()` happens, will do same thing.
Change the `executing` flag logic.

fix(plugin-workflow): try to avoid occasionally duplicated executions

---

packages/core/server/src/middlewares/parse-variables.ts
packages/core/utils/src/parse-filter.ts

By using `$date.now` as variable in filter cause server error.
1. Set one field to equal to `$date.now` in any data scope settings.
2. Refresh list.
Filtered as configured conditions.
Showing error.
None.
`$date.now` not implemented in proper place.
Move deprecated `$system.now` to `$date.now`.

fix(db): fix `$date.now` variable

---

packages/plugins/workflow/src/client/nodes/calculation.tsx
packages/plugins/workflow/src/client/nodes/loop.tsx
packages/plugins/workflow/src/client/nodes/update.tsx
packages/plugins/workflow/src/client/variable.tsx

Variable for loop item should be same as loop target item.
1. Add loop node.
2. Add any node which could use variable to the loop.
3. Select scope variable in added node.
"Loop item" should be same level as loop target.
One more level as node id in the variable options.
#2157.
Node variable has been refactored, loop variables missed.
Also refactor loop node on scope variable options.

fix(plugin-workflow): fix loop variable

---

packages/core/database/src/__tests__/repository.test.ts
packages/core/database/src/repository.ts

Batch update in workflow with association filter cause SQL error.
1. Use upload node in workflow, and set to batch mode.
2. Filter set to "Created by / ID" (or some other association / id) equal to a value.
3. Enable workflow and trigger it.
Update in batch should works correctly.
Error:
```
{
"error": {
"name": "SequelizeDatabaseError",
"original": {
"code": "42803",
"file": "parse_agg.c",
"length": 201,
"line": "1413",
"name": "error",
"position": "25",
"routine": "check_ungrouped_columns_walker",
"severity": "ERROR",
"sql": "SELECT \"employee\".\"id\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"createdAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.createdAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"updatedAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.updatedAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" …
```

fix(core): fix batch update query logic

---

packages/plugins/file-manager/src/client/hooks/useUploadFiles.ts

Adjust file size limit on frontend to 1GB, which is default limit on server side.
Frontend upload file size limit is 10MB, not same as on server side.
- Constant on frontend
- Backend (后端)
Test file size.
None.

fix(plugin-fm): adjust upload file size to 1GB which same as default on server side

---

packages/core/client/src/schema-initializer/SchemaInitializer.tsx
packages/core/client/src/schema-initializer/SelectCollection.tsx
packages/plugins/map/src/client/block/MapBlockInitializer.tsx

期望这里的输入框在显示的时候能够自动 focus
没有自动 focus
antd 官方 BUG：https://github.com/ant-design/ant-design/issues/41239
antd v5 版本的 BUG， 原因暂未知
1. 通过 `useRef` 获取 `input` 实例
2. 在 `input` 初次渲染时调用 `input.focus()`
3. 使用 `IntersectionObserver` API 监听 `input` 何时显示
4. 当 `input` 显示时调用 `input.focus`
> 注意：需要当前系统的焦点在浏览器页面中，如果焦点在浏览器外面则**不会触发自动 focus**。等官方修复后可能需要重构。
close T-884

fix: should auto focus in drop-down menu

---

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx
packages/core/client/src/collection-manager/interfaces/createdAt.ts
packages/core/client/src/collection-manager/interfaces/datetime.ts
packages/core/client/src/collection-manager/interfaces/email.ts
packages/core/client/src/collection-manager/interfaces/id.ts
packages/core/client/src/collection-manager/interfaces/input.ts
packages/core/client/src/collection-manager/interfaces/integer.ts
packages/core/client/src/collection-manager/interfaces/number.ts
packages/core/client/src/collection-manager/interfaces/percent.ts
packages/core/client/src/collection-manager/interfaces/phone.ts
packages/core/client/src/collection-manager/interfaces/radioGroup.ts
packages/core/client/src/collection-manager/interfaces/select.ts
packages/core/client/src/collection-manager/interfaces/time.ts
packages/core/client/src/collection-manager/interfaces/types.ts
packages/core/client/src/collection-manager/interfaces/updatedAt.ts
packages/core/client/src/collection-manager/interfaces/url.ts
packages/plugins/formula-field/src/client/interfaces/formula.tsx
packages/plugins/sequence-field/src/client/sequence.tsx

Field/interface extended by plugin should be able to be set as title field.
* Formula field (result)
* Sequence field
- Add `titleUsable` property to interface type.
- Backend (后端)
* Fields configuration in collection
* Association field as select
* FormItem designers
None.

refactor(client): change `isTitleField` check to interface property `titleUsable`

---

packages/plugins/workflow/src/server/__tests__/instructions/request.test.ts
packages/plugins/workflow/src/server/instructions/request.ts

Loop will error when request node inside.
1. Create a loop node, set target as a number.
2. Create a request node inside the loop.
3. Trigger the workflow.
Process normally to end with `RESOLVED` status.
Error occurred in loop node.
https://github.com/nocobase/nocobase/discussions/2235
No `upstreamId` set in pending request running phase.
Add `upstreamId` to save the pending job.

fix(plugin-workflow): fix request node error in loop

---

packages/core/server/src/middlewares/parse-variables.ts

Error thrown on legacy `$system.now` variable.
Linkage rules add any condition with variable of system current time.
Rules run well.
Error thrown in backend.
#2209.
Changes not compatible.
Revert variable in backend back.

fix(middleware): revert now variable back

---

packages/core/client/src/schema-component/antd/action/Action.tsx

工作流 - 执行记录 - 查看
能正常显示icon
显示`[object Object]`
多语言需要修改了`title`为`{t(title || compile(fieldSchema.title))}`
增加title是否为字符串的判断。
Close T-1077

fix(client): using component as action title

---

packages/plugins/data-visualization/src/client/block/ChartBlock.tsx
packages/plugins/data-visualization/src/client/block/ChartBlockInitializer.tsx
packages/plugins/data-visualization/src/client/block/ChartConfigure.tsx
packages/plugins/data-visualization/src/client/renderer/ChartLibrary.tsx
packages/plugins/data-visualization/src/client/renderer/ChartRenderer.tsx
packages/plugins/data-visualization/src/client/renderer/ChartRendererProvider.tsx
packages/plugins/data-visualization/src/client/renderer/library/G2PlotLibrary.tsx

请求只与当前区块相关，没有多余请求
拖拽，配置改变会使当前页面的所有图表区块重新请求
数据请求和图表渲染组件杂糅，而配置和展示共用图表渲染组件，请求判断有问题，导致每次组件重新渲染，都会重复请求。
将请求和图表渲染拆分，优化请求方式。
Close T-786

fix(bi): eliminate redundancy queries

---

packages/plugins/data-visualization/src/server/__tests__/api.test.ts
packages/plugins/data-visualization/src/server/actions/query.ts

使用MySQL，在图表中对日期字段做排序。
返回数据按配置排序
返回数据没有正常排序
处理`orderBy`别名时使用双引号`"`, 在MySQL中被认为是字符串。
https://stackoverflow.com/questions/61467696/why-does-using-or-doesnt-sort-column-aliases-via-order-by-in-mysql
MySQL处理别名时使用<code>`</code>
Close T-1095

fix(bi): orderBy bug under MySQL

---

packages/plugins/theme-editor/README.md
packages/plugins/theme-editor/README.zh-CN.md

[English](./README.md) | 中文
> 当前主题功能是在 antd 5.x 版本的基础上实现的，所以在阅读本文之前最好先阅读一下[定制主题](https://ant.design/docs/react/customize-theme-cn#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98)相关的概念。
目前支持编辑全局范围的 [SeedToken](https://ant.design/docs/react/customize-theme-cn#seedtoken)、[MapToken](https://ant.design/docs/react/customize-theme-cn#maptoken)、[AliasToken](https://ant.design/docs/react/customize-theme-cn#aliastoken)，和支持[切换](https://ant.design/docs/react/customize-theme-cn#%E4%BD%BF%E7%94%A8%E9%A2%84%E8%AE%BE%E7%AE%97%E6%B3%95)为 `暗黑模式` 和 `紧凑模式`。后期有可能会支持[组件级别](https://ant.design/docs/react/customize-theme-cn#%E4%BF%AE%E6%94%B9%E7%BB%84%E4%BB%B6%E5%8F%98%E9%87%8F-component-token)的主题定制。
首先把 NocoBase 更新到最新版本，然后会在[插件管理页面](http://localhost:13000/admin/pm/list/local/)看到 `theme-editor` 的卡片，点击卡片右下角的 `启用` …

docs: add doc for Theme Editor

---

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
packages/core/client/src/schema-component/antd/select/Select.tsx

1. 选择设置一个 `选择` 字段的默认值
2. 保存一个默认值
3. 再次打开，会发现一个空的 tag
tag 不为空
弹窗中的默认值显示为空
#2031 
- defaultValue 没有传到 antd Select 组件内
- 为 antd Select 组件添加 `defaultValue` 属性
close T-1146

fix(default-value): fix tag in RemoteSelect

---

packages/plugins/workflow/src/server/triggers/schedule.ts

Schedule workflow will be triggered multiple times in multi-apps.
1. Add a schedule workflow.
2. Add a sub app.
3. Wait to time for triggering.
Only trigger once.
Workflow will be triggered once in each app.
None.
Schedule manager will start in each app.
Disable timer if app is not main.

fix(plugin-workflow): fix schedule duplicated triggering in multi-apps

---

packages/plugins/workflow/src/client/components/DynamicExpression.tsx

Expression field in sub-form could not use collection field variables.
1. Add a posts collection.
2. Add an expression collection.
3. Add an belongsTo field target on expression collection to posts collection.
4. Add expression field in create/update form, use sub-form component.
5. Select a collection, then select variable.
Variables show up.
No variable.
None.
`useForm()` / `useFormEffects()` in `Expression` component using local path, not nested form path.
Join paths.

fix(plugin-workflow): fix expression field in sub-form

---

packages/plugins/theme-editor/src/client/hooks/useThemeSettings.tsx
packages/plugins/theme-editor/src/client/hooks/useUpdateThemeSettings.tsx

1. 开启主题
2. 鼠标移到用户名称处
不报错
报错
判断是否提供 `CurrentUserProvider` 的逻辑有问题。
仅判断是否存在 `currentUser` 即可，如果为 null 则表示没有提供 `CurrentUserProvider`。
close T-1235

fix(theme-editor): avoid error

---

packages/plugins/workflow/src/client/components/CollectionFieldset.tsx
packages/plugins/workflow/src/client/nodes/update.tsx

Allow system field values to be assigned in create and update node.
`createdBy`, `updatedBy` etc. fields should be able to be assigned.
- Use full fields in values assigning in create and update node configuration.
- Backend (后端)
Test system fields.
`id`, `createdAt` and `updatedAt` can be assigned too.
None.

refactor(plugin-workflow): allow system values to be assigned in create and update node

---

packages/plugins/workflow/src/server/__tests__/instructions/condition.test.ts
packages/plugins/workflow/src/server/instructions/condition.ts

Change `equal` and `not equal` operators to non-strict.
Strict equal/not equal are hard to use in no-code mode. Non-strict will be more useful in common scenarios.
- Backend (后端)
- Condition instruction calculators.
Via cases.
Some strict equal and not equal usage break.
None.

refactor(plugin-workflow): change strict equal and not equal to non-strict

---

packages/plugins/data-visualization/src/client/__tests__/hooks.test.ts
packages/plugins/data-visualization/src/client/hooks.ts

在图表中选择 `所属地区(行政区划) / 省市区名称 `或 `公司近照(附件) / 文件名` 字段
数据展示使用标签名
获取级联关系时只考虑了关系字段，直接从目标中进行获取。而行政区划字段、文件字段的级联字段在`interface.filterable.children`中
从目标表和`interface.filterable.children`中获取级联字段
Close T-784

fix(bi): issue of parsing label of region & file field

---

packages/plugins/workflow/src/client/WorkflowProvider.tsx
packages/plugins/workflow/src/client/schemas/workflows.ts
packages/plugins/workflow/src/locale/zh-CN.ts
packages/plugins/workflow/src/server/actions/workflows.ts

Add manually reload action for synchronization issues of workflows in multi-app.
Toggle any workflows will not be synchronized to other sub-apps.
- Add a global action button for reloading all workflows.
- Backend (后端)
- Add a reload action for workflow resource.
* Multi-app workflows toggle on/off.
None.
None.

feat(plugin-workflow): add reload for multi-app

---

packages/plugins/workflow/src/client/nodes/manual/AssigneesSelect.tsx
packages/plugins/workflow/src/client/variable.tsx

Can not select result of query node which collection target is users.
1. Add a query node, set collection to users.
2. Add a manual node as downstream, try to select assignee from node variables, the query node result is not available.
Could select the query node and ID field.
Not available.
#2192.
Type filter not match.
Change to custom type filter.

fix(plugin-workflow): fix manual assignee select variable type filter

---

packages/plugins/workflow/src/client/WorkflowProvider.tsx
packages/plugins/workflow/src/client/schemas/workflows.ts
packages/plugins/workflow/src/locale/zh-CN.ts
packages/plugins/workflow/src/server/actions/workflows.ts

Change reload api to sync, and fix duplicated listening
* "Reload" is not so accuracy for syncing status.
* Syncing should do toggling off first.
- Locales
- Backend (后端)
- Adjust API
Try triggering after multiple times synced.
None.
None.

refactor(plugin-workflow): change reload api to sync, and fix duplicated listening

---

packages/plugins/workflow/src/client/ExecutionCanvas.tsx
packages/plugins/workflow/src/client/components/StatusIcon.tsx
packages/plugins/workflow/src/client/nodes/index.tsx
packages/plugins/workflow/src/client/style.tsx

Add execution dropdown for quick navigating
In execution page, hard to navigate to previous and newer executions in history.
- Add dropdown to breadcrumb in execution page.
- Backend (后端)
None.
None.

feat(plugin-workflow): add execution dropdown for quick navigating

---

packages/plugins/workflow/src/client/nodes/aggregate.tsx

Cannot select association in aggregate node.
1. Add a workflow which trigger is collection.
2. Add appends association of the collection.
3. Add an aggregate node, and select association from trigger context data.
Could select appended association.
Cannot.
None.
Lazy load of association variable not implemented in aggregate node.
Add lazy load.

fix(plugin-workflow): fix aggregate node association select

---

packages/plugins/workflow/src/client/variable.tsx

Attachment field can not be selected when assigning value from variables in create/update node.
1. Add a posts collection with a cover attachment field.
2. Create a workflow which triggered when posts collection create, and an update node against posts collection.
3. Set update mode to one by one.
4. Set values in update nodes, try to use cover field in trigger context data.
Could set attachment field.
Attachment field is disabled.
None.
Should allow all fields when no types defined.
Change the types matching logic.

fix(plugin-workflow): fix assign attachment value in nodes

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx

Can not open variable list when line wrapping in Variable.TextArea.
1. Create a formula field.
2. Input any expression content more than 1 line.
3. Click "x" button on bottom half.
Variable list should open.
Not open.
After upgrade to Ant Design v5, `Button` in `Compact` got a `height: auto` style, which is not correct in `Variable.TextArea` component.
Add another height style to override.

fix(client): fix select button height in variable textarea

---

packages/core/actions/src/actions/list.ts
packages/core/actions/src/constants.ts
packages/core/actions/src/index.ts
packages/core/actions/src/utils.ts
packages/core/client/src/locale/zh_CN.ts
packages/plugins/localization-management/src/server/actions/localizationTexts.ts
packages/plugins/localization-management/src/server/constans.ts
packages/plugins/workflow/src/client/ExecutionCanvas.tsx
packages/plugins/workflow/src/client/nodes/query.tsx
packages/plugins/workflow/src/client/schemas/collection.ts
packages/plugins/workflow/src/client/style.tsx
packages/plugins/workflow/src/server/__tests__/instructions/query.test.ts
packages/plugins/workflow/src/server/instructions/query.ts

Add sort and pagination to query node params.
For complete query parameters, sort and pagination are very useful.
- Query node config panel
- Backend (后端)
- Expose some util and constants from `@nocobase/actions`
- Query instruction logic for additional params.
Try new params.

feat(plugin-workflow): add sort and pagination to query node params

---

packages/plugins/workflow/src/client/components/CollectionFieldset.tsx

Some hidden field which has no `uiSchema` showing up in value assignment fields list of create/update node.
1. Use create record node.
2. Select "User" collection.
3. Hover to "Add field", check the fields list.
No `appLang`, `systemSettings` etc fields.
Hidden fields showing.
None.
Should do filtering.
Add a filter.

fix(plugin-workflow): fix fields filter in value assignment nodes

---

packages/plugins/workflow/src/client/schemas/workflows.ts

Should not use same form for creating or updating workflow.
* No `enabled` for creating.
* No `type` for updating.
* Hide `useTransaction`.
- Workflow management schema.
- Backend (后端)
None.
Legacy workflows with `useTransaction` open can not close. And can only create new ones.
None.

refactor(plugin-workflow): refactor create/edit workflow form

---

packages/plugins/workflow/src/server/triggers/form.ts

When use form trigger, and bind workflow to default submit button, trigger data is present in execution but some properties can not be access.
Not sure.
Fields of form data could be access.
Fields values in trigger's data but can not access from nodes.
None.
Should do `toJSON()` to the model before triggering.
Add `toJSON()`.

fix(plugin-workflow): fix form trigger data bug

---

packages/plugins/workflow/src/client/triggers/form.tsx
packages/plugins/workflow/src/locale/zh-CN.ts
packages/plugins/workflow/src/server/__tests__/triggers/form.test.ts
packages/plugins/workflow/src/server/triggers/form.ts

Add user variable to form trigger context, allow to use user which submitted form in nodes.
We could use `createdBy`/`updatedBy` in common forms, but can not use them in "directly trigger workflow" button.
- Add user to form trigger context variable select.
- Backend (后端)
- Add current user as `user` to trigger context.
Try "User submitted form" variable in form event.
None.

feat(plugin-workflow): add user variable to form trigger context

---

packages/plugins/workflow/src/client/nodes/aggregate.tsx
packages/plugins/workflow/src/client/nodes/index.tsx
packages/plugins/workflow/src/client/variable.tsx

Can not select next to-many field (which is not in appends) in aggregate association mode.
1. Add posts, categories tables, posts belongs to categories, categories has many posts.
2. Add workflow trigger by posts collection creation, appends category.
3. Add an aggregate node, select association field collection mode.
4. Try to select "Trigger variables / Trigger data / category / posts".
Could select to "... / posts".
Could not.
None.
Types check in variables not only rely on types options, but also checked by next associations.
If provide types option, only rely on types. Otherwise will be checked by next associations.

fix(plugin-workflow): fix variable type check

---

packages/plugins/auth/src/server/__tests__/actions.test.ts
packages/plugins/auth/src/server/basic-auth.ts

1. Use Nocobase of old version that has some users do not have username.
2. Request api `auth:signIn` use old parameters `email` and `password`.
Auth successfully with correct email and password.
Get `password is incorrect` error message.
#2505 
Close T-1533

fix(auth): basic-auth compatibility issue

---

packages/plugins/workflow/src/server/__tests__/instructions/condition.test.ts
packages/plugins/workflow/src/server/instructions/condition.ts

Downstream nodes of condition node duplicately executed.
1. Add a condition node on branch mode.
2. Add any node in each branch.
3. Add any node after branch.
4. Trigger the workflow.
Node after branch should only be executed once.
Twice.
#2510.
End logic of condition instruction is not correct.
Adjust end logic.

fix(plugin-workflow): fix duplicated downstream executions after condition

---

packages/plugins/workflow/src/client/nodes/manual/FormBlockProvider.tsx
packages/plugins/workflow/src/client/nodes/manual/forms/custom.tsx

Hide unused form in manual ui after done.
If multiple forms configured in manual UI, after assignee submitted one of them, others are uselessly to be shown.
- `FormBlockProvider` in manual node
- Backend (后端)
UI.
None.
None.

refactor(plugin-workflow): hide unused form in manual ui after done

---

packages/plugins/theme-editor/src/server/plugin.ts

普通权限的用户无法获取到主题的配置数据。
1. 新建一个普通权限的用户
2. 开启主题插件
3. 刷新页面会报权限错误
默认情况下所有权限的用户都可以使用主题
普通权限的用户使用主题会报权限错误
#2228 
没有处理权限问题
允许所有权限用户使用主题接口
close T-1540

fix(themeEditor): should allow all roles to use

---

packages/plugins/file-manager/src/client/interfaces/attachment.ts

Upload file still in default storage after changed field setting to non-default one.
1. Add an attachment field to a collection.
2. Add the field to any form of the collection.
3. Upload a file through the field.
File should be uploaded to non-default storage.
Still uploaded to default storage.
None.
Typo.
`attachementField` -> `attachmentField`.

fix(plugin-fm): fix attachment field param typo

---

packages/core/client/src/schema-component/antd/action/Action.tsx
packages/core/client/src/schema-component/antd/association-field/InternalPopoverNester.tsx
packages/core/client/src/schema-component/antd/filter/FilterAction.tsx
packages/core/client/src/schema-component/antd/icon-picker/IconPicker.tsx
packages/core/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx
packages/core/client/src/schema-component/antd/popover/Popover.tsx
packages/core/client/src/schema-component/antd/quick-edit/QuickEdit.tsx
packages/plugins/charts/src/client/select/CustomSelect.tsx
packages/plugins/graph-collection-manager/src/client/GraphDrawPage.tsx
packages/plugins/graph-collection-manager/src/client/components/Entity.tsx
packages/plugins/localization-management/src/client/Localization.tsx
packages/plugins/theme-editor/src/client/antd-token-previewer/token-panel-pro/TokenContent.tsx

- 折叠面板筛选区块，点击无效
1. 新建一个 `折叠面板筛选区块`
2. 新建一个 `表格区块`
3. 连接两个区块
4. 点击 `折叠面板筛选区块` 的一个选项，会发现不起作用
https://github.com/nocobase/nocobase/assets/38434641/0faeac5d-7c40-41db-9853-50fd9aa58d19
点击 `折叠面板筛选区块` 选项可以有效进行筛选
https://github.com/nocobase/nocobase/assets/38434641/ca819baf-0e42-40fe-87fd-78fb9853fd93
点击无效
#2586 
`折叠面板筛选区块` 的每一项会被渲染成 `EllipsisWithTooltip` 组件，而 `EllipsisWithTooltip` 组件中使用到了 `Popover`，之前为了解决 #2586 重构了 `Popover` （主要是在外面包一层 div 阻止点击事件向上冒泡），导致这里的点击事件也被阻止向上冒泡，表现出的行为就是点击选项无效。
https://github.com/nocobase/nocobase/blob/4812cc5692675986e95ef92e4f2218b0ffa37ca5/packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.Item.tsx#L143-L149
替换为原生的 antd 的 `Popover` 组件，重命名自定义的 `Popover` 为 `PopoverWithStopPropagation`，这样易于区分，防止出错。同时自查可能出问题的点，并进行了修改。
close T-1806

fix: fix collapsed panels not working when clicked

---

.env.example
packages/core/app/src/config/database.ts

support connect to database server using ssl configuration. through this new env config:
```
DB_DIALECT_OPTIONS_SSL_CA=
DB_DIALECT_OPTIONS_SSL_KEY=
DB_DIALECT_OPTIONS_SSL_CERT=
DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=true
```

feat(database): support ssl config of database

---

packages/plugins/workflow/src/client/nodes/loop.tsx
packages/plugins/workflow/src/client/variable.tsx

Cannot select properties of collection variable in loop scope.
1. Add a collection workflow.
2. Add a loop node, target as trigger data.
3. Add any node in loop, try to use scope variable as any field of the trigger data.
Could select the fields.
Could not.
#2622.
Scope variables not include lazy load variables.
Add lazy load logic to loop node.

fix(plugin-workflow): fix scope variable in loop

---

packages/core/utils/src/__tests__/parse-date.test.ts
packages/core/utils/src/parse-date.ts

修复在数据范围中使用日期的 `季度` 相关的变量时筛选结果不对的问题。
link T-1832

fix: fix quarter variables

---

packages/core/client/src/user/ChangePassword.tsx
packages/core/resourcer/src/__tests__/resourcer.test.ts
packages/core/resourcer/src/resource.ts
packages/plugins/@nocobase/plugin-auth/src/server/__tests__/actions.test.ts
packages/plugins/@nocobase/plugin-auth/src/server/basic-auth.ts
packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
packages/plugins/@nocobase/plugin-auth/src/swagger/index.ts

创建一个新用户，修改密码
正常修改密码
401， 密码不正确
#2634
Close T-1893
切换为用户名注册以后，新用户没有邮箱，旧的changePassword接口仍使用原来的用邮箱查找用户的方式，导致查找不到正确用户。
优先使用用户名查找用户，用户名不存在再用邮箱。

fix(auth): change password issue of basic auth

---

packages/core/client/src/api-client/APIClient.ts
packages/core/client/src/api-client/__tests__/APIClient.test.tsx
packages/plugins/@nocobase/plugin-acl/src/server/__tests__/setCurrentRole.test.ts
packages/plugins/@nocobase/plugin-acl/src/server/__tests__/users.test.ts
packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts

1. 登录一个用户，选择一个角色，比如root，注销后，登录一个没有所选择角色权限的用户，提示"User role not found"，无法登录
2. 登录一个用户，选择一个角色，删除角色，提示"User role not found"
1. 可以正常登录
2. 操作不报错
报错后，无法再操作
Close T-1798
Close T-1835
上一个用户角色遗留在LocalStorage中，没有清除
客户端判断`ROLE_NOT_FOUND_ERR`的错误码，删除LocalStorage中的角色

fix(auth): user role not found

---

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Processor.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/parallel.ts

Looped parallel will return wrong status when one of nodes failed in branch.
1. Add a loop for 2.
2. Add a parallel in loop.
3. Add a condition (`{{$scopes.1.item}} < 1`) as first branch in parallel.
4. Add a query as downstream of condition.
5. Add another copy branch of condition above for parallel.
Workflow fails on second loop due to both conditions fails.
Second parallel passed as succeeded.
#2687.
Logic of `findBranchLastJob` not perfect.
Fix logic of `findBranchLastJob` method.

fix(plugin-workflow): fix parallel bug in loop

---

packages/plugins/@nocobase/plugin-workflow/src/server/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/index.ts

Exporting types lead to building errors.
```
yarn build
```
No error.
```
error TS2614: Module '"@nocobase/plugin-workflow"' has no exported member 'Instruction'. Did you mean to use 'import Instruction from "@nocobase/plugin-workflow"' instead?
```
None.
Types.
Fix types.

fix(plugin-workflow): fix exporting types

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/aggregate.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/create.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/collection.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/form.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

In manual node, assignees cannot use variable.
1. Add a collection trigger workflow.
2. Select any collection in trigger config.
3. Add manual node, try to use trigger variable in assignees field.
Could use `createdBy` field.
No variable to use.
#2492.
Variable type filter logic no completed.
Fix the filter logic.

fix(plugin-workflow): fix assignees and aggregate variable

---

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/form.ts

1. Create a form trigger workflow.
2. Add append association to preload.
3. Try to use the variable field of appended association.
Could get correct variable value.
`undefined`.
None.
Need `toJSON` for execution context variables when result is Model type.
Add `toJSON`.

fix(plugin-workflow): fix context data of form trigger

---

packages/core/client/src/schema-component/antd/page/style.ts

没有标签页的时候，标题的上下左右空间调紧凑了，有标签页的没调，导致不统一。
close T-2128

style: fix PageHeader

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx

Cursor jump to start when insert variable into expression input.
1. Add collection workflow.
2. Select a collection in trigger config.
3. Add a calculation node.
4. Input "1+", then select trigger variable to insert.
Showing: "1+{{trigger/...}}".
Showing: "{{trigger/...}}1+"
#2157.
https://github.com/nocobase/nocobase/commit/c9b726916ce2f5d699674075e2f7d47098184d77#diff-1e4902f03f04232eab38873797c9729ec3139bc455afaf0bd16eadc9fce13fdaR214
Rerendering happened when update `keyLabelMap`.
Remove `keyLabelMap` from use effect dependency.

fix(client): fix rerendering cause range bug

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx

Cursor jump to start when insert variable into expression input.
1. Add collection workflow.
2. Select a collection in trigger config.
3. Add a calculation node.
4. Input "1+", then select trigger variable to insert.
Showing: "1+{{trigger/...}}".
Showing: "{{trigger/...}}1+"
#2157.
https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/variable/TextArea.tsx#L225
Rerendering happened when update `keyLabelMap`, but `setChanged(true)` always invoked when rendering.
Comment `setChanged(true)` out.

fix(client): fix rendering cause range bug

---

packages/core/client/src/schema-initializer/utils.ts

Switch off button in action configuration cause error.
1. Use "Add new" button for a block, and open drawer.
2. Add a form block.
3. Toggle off the "Submit" action button in action configuration menu.
The "Submit" button removed.
Error:
```
react-dom.development.js:4312 Uncaught TypeError: field.setInitialValue is not a function
at utils.ts:766:1
```
None.
Field method not exists on button component.
Add undefined check.

fix(client): fix undefined field method on button

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts

Triggered workflow not executed.
Not found steps.
Pending executions should be processed in queue.
Not executed.
#2775.
Unknown reason workflow has been deleted but queuing execution of it remains.
Exclude executions not associated with workflow in queue.

fix(plugin-workflow): ignore queuing executions which workflow has been deleted

---

packages/core/client/src/schema-component/antd/action/Action.tsx

Warning in console.
1. Use "Add new" popup
2. Add a form.
No warning.
Warning on `openSize`.
None.
Passing all props to children.
Pick props.

fix(client): fix action component warning

---

packages/plugins/@nocobase/plugin-auth/src/client/AuthPluginProvider.tsx
packages/plugins/@nocobase/plugin-auth/src/client/AuthProvider.tsx
packages/plugins/@nocobase/plugin-auth/src/client/index.tsx
packages/plugins/@nocobase/plugin-cas/src/client/SigninPage.tsx
packages/plugins/@nocobase/plugin-cas/src/server/actions/service.ts
packages/plugins/@nocobase/plugin-oidc/src/client/OIDCButton.tsx
packages/plugins/@nocobase/plugin-oidc/src/server/actions/redirect.ts
packages/plugins/@nocobase/plugin-saml/src/client/SAMLButton.tsx
packages/plugins/@nocobase/plugin-saml/src/server/actions/redirect.ts

Use a global Provider to handle the `token` and `authenticator` parameters, writing them to LocalStorage when the router contains these parameters.
Write the token to LocalStorage directly after a successful sign-in, without redirecting to `/signin` first.
- Add `AuthProvider`
- Backend (后端)
- Navigate to `/admin` directly if sign in successfully
Close T-2227

feat(auth): add global auth token provider

---

packages/core/client/src/schema-component/antd/action/Action.Drawer.style.ts
packages/core/client/src/schema-initializer/buttons/TableSelectorInitializers.tsx
packages/core/client/src/schema-initializer/items/DataBlockInitializer.tsx
packages/core/client/src/schema-initializer/items/FilterBlockInitializer.tsx
packages/core/client/src/schema-initializer/items/FilterCollapseBlockInitializer.tsx
packages/core/client/src/schema-initializer/items/FilterFormBlockInitializer.tsx
packages/core/client/src/schema-initializer/items/TableSelectorInitializer.tsx
packages/core/client/src/schema-initializer/utils.ts
packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/migrations/20231015125000-support-filter-blocks-in-select-record-drawer.ts

feat: support filter blocks in select record drawer

---

packages/plugins/@nocobase/plugin-sequence-field/src/client/sequence.tsx

Add sequence field pattern throwing error.
1. Add sequence field.
2. Add pattern row.
Pattern row added.
Error thrown.
None.
The result of `ArrayTable.useRecord()` is `undefined`, not reasonable.
Use `form.values` instead.

fix(plugin-sequence): avoid invalid value from `ArrayTable.useRecord()`

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx

After modified expression then save formula field, error thrown.
1. Add formula field.
2. Modify expression.
3. Save field.
To show normal fields list.
Error thrown.
#2785.
`changed` branch logic should avoid new empty value to cause setting range.
Add `children.length` check.

fix(client): fix varaible textarea setRange bug

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/form.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts
packages/plugins/@nocobase/plugin-workflow/src/server/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/form.ts

Add `actionTriggerable` property for trigger configurations.
Combine any types workflow support `actionTriggerable: true` in UI.
- Trigger type definition.
- Bind workflow UI logic.
- Backend (后端)
- Form trigger middleware logic.
* UI
Compatible with configured binding action.
None.

refactor(plugin-workflow): add property to determine workflow type triggerable on ui

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/aggregate.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

When there are cycling associations, switch aggregate mode to association will cause stack overflow.
1. Add posts collection (has `createdBy`).
2. Add posts association to users.
3. Add a workflow with collection trigger on new post.
4. Add an aggregate node and switch to association type target.
Could continue to select field.
Dead cycle cause stack overflow.
Also fix T-1509.
Cycling association.
Add `depth` to not to detect possible types of variable.

fix(plugin-workflow): fix cycling association stackoverflow

---

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/schedule.ts

Schedule workflow is disabled under sub apps.
1. Enable multi-app plugin and add a sub app.
2. Add a schedule workflow to the sub app on some time, wait for triggering.
Schedule workflow in sub app should be triggered.
Not triggered.
None.
Schedule workflows in sub apps are restricted.
Change condition to restrict only when multi-app-share-collection plugin enabled.

fix(plugin-workflow): fix schedule workflow under normal multi-apps

---

packages/plugins/@nocobase/plugin-workflow/src/client/ExecutionCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/components/ValueBlock.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/aggregate.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/create.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/loop.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/DetailsBlockProvider.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/workflows.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/aggregate.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/calculation.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/manual.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/query.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/update.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts
packages/plugins/@nocobase/plugin-workflow/src/server/collections/flow_nodes.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20230221162902-jsonb-to-json.ts
packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20230809113132-workflow-options.ts
packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20231024172342-add-node-key.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts

Change `$jobsMapByNodeId` to `$jobsMapByNodeKey` in variable context.
If use `uiSchemaStorage` to persist UI configuration, then change the variable references when duplicating workflow will be very tedious.
- Variables in workflow context.
- Backend (后端)
- Variables in workflow context.
- Migrations.
* Migrations.
* Revision.
* Manual node.
Migrations.
None.

refactor(plugin-workflow): change to use node key for variables

---

packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20231024172342-add-node-key.ts

Migration for adding `key` field to `flow_nodes` cause error.
1. Use table prefix in `.env`.
Migrated.
Error thrown.
#2909.
Not considered table prefix.
Fix table prefix logic.

fix(plugin-workflow): fix migration

---

packages/plugins/@nocobase/plugin-workflow/src/client/CanvasContent.tsx

Miss margin between alert and trigger card in workflow canvas.
1. Open an executed workflow.
There should be a little distance between alert bar and trigger card.
They are clinging.
#2951.
No margin.
Add margin.

fix(plugin-workflow): fix canvas style

---

packages/core/client/src/__tests__/e2e/menu.test.ts
packages/core/client/src/__tests__/e2e/page.test.ts
packages/core/client/src/block-provider/BlockProvider.tsx
packages/core/client/src/collection-manager/action-hooks.ts
packages/core/client/src/schema-component/antd/form-v2/Form.tsx
packages/core/client/src/schema-component/antd/form-v2/utils.tsx
packages/core/client/src/schema-settings/SchemaSettings.tsx

close T-2453
主要是因为使用了 `useCollectionFilterOptions` 这个 hook，其计算量会随着表字段数量的增加而增加，进而导致了卡顿。解决方法是，只有在需要计算的时候才会计算，避免重复计算。
在 `autorun` 中依赖了 field.value 的值，又因为在 `autorun` 中会修改 field.value 的值，所以会导致死循环。

perf: avoid page lag or stuttering

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/loop.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

Can not use collection variable from inner loop target.
1. Add 3 collections as A --(hasMany)-> B --(hasMany)-> C.
2. Add collection workflow and use collection A to trigger, append association B and B.C.
3. Add a loop(1) with target as `A.B`.
4. Add another loop(2) inside loop(1) with target as `{loop1.target}.C`.
5. Add a calculation node inside loop(2).
6. Try to select `{loop2.target.someField}`.
Could select `C.field` from `loop2.target`.
No sub-list for `{loop2.target}` fields.
None.
Need recursive loop variable options.
Add recursive loop variable options.

fix(plugin-workflow): fix loop scope variable

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/form.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx

Add extensibility to triggers to bind in action buttons.
Some triggers can only be bound to action conditionally.
- Workflow section in `Action.Designer`.
- Trigger option.
- Backend (后端)
None.
None.
None.

refactor(plugin-workflow): change `actionTriggerable` to function `useActionTriggerable`

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx

When changed some field value in trigger or node configuration and close without save, the values changed remain in the drawer when reopened.
1. Add a collection workflow.
2. Open trigger configuration.
3. Select some collection.
4. Close drawer without saving.
5. Reopen the configuration.
The collection field should be empty as not selected.
Collection has value.
#2978.
Reset logic not completed.
Fix the form and reset logic.

fix(plugin-workflow): fix configuration drawer close logic

---

packages/core/client/src/block-provider/BlockProvider.tsx
packages/core/client/src/schema-component/antd/form-v2/utils.tsx
packages/core/client/src/variables/VariablesProvider.tsx
packages/core/client/src/variables/__tests__/utils/getPath.test.ts
packages/core/client/src/variables/__tests__/utils/getVariableName.test.ts
packages/core/client/src/variables/__tests__/utils/isVariable.test.ts
packages/core/client/src/variables/utils/isVariable.tsx

close T-2506
- 在进行变量解析的时候，存在这种格式的变量：{{ $nRecord.cc-name }}
- 在进行 isVariable(variableString) 判断的时候，把上面的变量字符串识别成了非变量
- 导致没走解析的流程，直接把变量字符串返回了

fix: fix regular of variable

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx

Workflow title in binding workflow configuration not showing
1. Add a form workflow with a collection and enabled it.
2. Add binding workflow to the form of the collection.
3. Reopen the binding configuration.
Workflow configured should show title.
Not showing.
None.
Usage of `RemoteSelect` component.
Add `manual={false}`.

fix(plugin-workflow): fix workflow title in binding workflow configuration not showing

---

packages/core/client/src/schema-component/antd/upload/shared.ts
packages/plugins/@nocobase/plugin-error-handler/src/server/error-handler.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts

No error when upload file failed.
1. Configure an Ali-oss storage with wrong key pair.
2. Upload a file to the storage.
Can not upload, but notify in backend error message.
No error message.
#2947.
No logging for uncaught error.
Add logging.

fix(plugin-fm): fix error log

---

packages/core/client/src/schema-component/antd/action/Action.tsx
packages/core/client/src/schema-component/antd/icon-picker/IconPicker.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/ExecutionCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/SchemaConfig.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/WorkflowTodoBlockInitializer.tsx

Manual node view configuration button should not be disabled after executed.
1. Add manual node.
2. Trigger the workflow.
3. Reopen the workflow and the manual node configuration.
Could view UI configurations via "View configurations" button.
Can not.
None.
All form are disabled because workflow executed.
Add `disabled` property to the button.

fix(plugin-workflow): client minor fixes

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

`<Variable.Input />` showing no `border-radius` on right side when disabled.
1. Make a field with variable disabled.
Should show same `border-radius` as left side.
Rectangle.
None.
Hidden "x" button under `<Space.Compact>`.
Show "x" button when disabled.

fix(client): fix variable input style when disabled

---

packages/core/client/src/collection-manager/templates/components/sql-collection/FieldsConfigure.tsx

1. New sql collection
2. Enter a SQL statement that select a boolean field. E.g. `select * from users left join roles_users on users.id=roles_users.user_id left join roles on roles.name=roles_users.role_name`
3. Submit
Submitted successfully.
It occurred error "field type null is not supported".
Close T-2618
The field interface inference was wrong.
```ts
if (typeof value === 'boolean') {
return 'boolean';
}
```
```ts
if (typeof value === 'boolean') {
return 'checkbox';
}
```

fix(cm): sql collection creation issue

---

packages/core/client/src/block-provider/hooks/index.ts
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/form.tsx

Cannot get variable assigned value from parent record in form workflow.
1. Add a form workflow.
2. Bind the workflow form an associating collection sub-table creation form on "Submit to workflow" button.
3. Add assigned value with variable pointing to parent record of associating collection.
4. Submit the form and trigger workflow.
Could get parent record value in context.
Could not.
None.
Variable values not parsed before submit.
Use abstracted value collecting method to do same parsing as creating record.

fix(plugin-workflow): fix form event parse variables

---

packages/plugins/@nocobase/plugin-workflow/src/server/instructions/condition.ts

Nested condition branches will be jumped.
1. Use PG@11.
2. Add a condition node (1) with `1 = 0` (to `false`).
3. Add another condition in falsy branch of node (1), with falsy calculation too.
4. Add any node as direct downstream of node (1).
Node (2) should be executed.
Node (2) is not executed.
#3082.
Logic of `branchIndex` goes to `null`.
Fix `branchIndex` logic.

fix(plugin-workflow): fix condition branch node finding logic (fix #3082)

---

packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx

Could not filter collection when letters case not match.
1. Create a collection workflow.
2. Select a created collection with name.
Input `post` could match `Post` as name.
Could not.
None.
Case sensitive in component filter.
Add `.toLowerCase()`.

fix(client): allow match query case insensitive

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/destroy.tsx

Locale of destroy node not rendering correctly.
1. Add a destroy node in workflow.
2. Open destroy node configuration panel and then submit without any input.
Validation error showing correctly.
Filter validation error is not translated.
None.
Should not use uncompiled raw string in validation.
Use `lang()` instead.

fix(plugin-workflow): fix destroy node locale

---

packages/plugins/@nocobase/plugin-workflow-manual/src/client/index.ts

Workflow todo initializer missed.
Open block initializer and try to find "Workflow todos".
Should be in initializers menu.
Not exists.
#3115.
Forgot to add components.
Add components.

fix(plugin-workflow-manual): fix initializer

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemDesigner.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemInitializers.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/utils.ts

1. Enable filter block in a chart block
2. Add a formula field as filter field
Formula field can be used as a filter field.
Formula component can not be used in filter block.
Determine the actual field type of a formula field and its corresponding field interface, use the correct component.

fix(bi): error when using formula field as filter field

---

packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts
packages/core/client/src/variables/VariablesProvider.tsx
packages/core/client/src/variables/__tests__/useVariables.test.tsx

close T-2766
在一个页面中通过使用 `local variables` 影响了 `global variables` 的值，导致在其它页面通过 `global variables` 获取到了错误的值。修复方法是：`local variables` 与 `global variable` 完全隔离，不相互影响。

fix(variable): local variables should not affect global variables

---

packages/core/client/src/schema-component/antd/action/Action.Drawer.style.ts

close T-2797
多层级打开 Drawer 组件时，其会覆盖 Dialog。
这是在升级 antd 之后产生的问题，主要是这个 PR 的改动造成的：https://github.com/ant-design/ant-design/pull/45911

fix(drawer): fix z-index

---

packages/core/database/package.json
packages/core/database/src/__tests__/operator/array-operator.test.ts
packages/core/database/src/operators/array.ts

close T-2803
**需求：$anyOf 和 $noneOf 需要支持非数组的值。**
比如下图中的一个多选字段，选择的操作符为**包含**（$anyOf），要匹配包含**当前角色**，而当前角色是一个字符串，这样设置其实是合理的，但是现在会报错。
解决方法就是：把值都转换为数组之后再进行处理。

feat: the $anyof and $noneOf operators should support non-array values

---

packages/core/client/src/schema-component/antd/action/Action.Link.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.tsx

Refactor components:
1. `TableV2`: allow to use fixed layout for column width.
2. `Action.Link`: Allow pass `className` in.
1. Column in `Table` need fixed width.
2. `Action.Link` need custom style.
- TableV2
- Action.Link
- Backend (后端)
Table column width when `tableLayout` passed to Table component.
Uncertain.
None.

refactor(client): allow fixed layout table and action link class

---

packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/index.ts

Page crash when add expression field in expression collection form.
1. Add an expression collection.
2. Add a form for the collection.
3. Add expression field to the form.
Expression field added.
Page crash.
None.
Missed component when split plugins.
Add missed component.

fix(plugin-workflow-dynamic-calculation): fix missed component

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/RadioWithTooltip.tsx

Add space control to `RadioWithTooltip`.
When text is too long, should be able to be placed vertically.
- Workflow component.
- Backend (后端)
None.
None.
None.

feat(plugin-workflow): add space control to RadioWithTooltip

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/collections/executions.ts

Occasionally workflow dispatch stops.
1. Make multiple triggering of multiple workflows.
2. Disable some workflow which has queueing executions.
All queueing executions of enabled workflows should be dispatched and processed.
The queueing executions block all processing.
#3221.
Enabled checking logic bug.
Fix enabled checking.

fix(plugin-workflow): queueing execution of disabled workflow block dispatching

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts

Unimplemented trigger type throwing error which blocking app start.
1. Some dirty data with not enabled trigger plugin (form trigger).
Trigger not works but app goes on.
App stuck.
#3191.
Dirty data.
Defend unknown types.

fix(plugin-workflow): defend unimplemented trigger type

---

packages/core/app/client/public/global.css

close T-2838
antd 组件的层级有问题，有的弹窗是 1000 有的是 1200，会导致弹窗被覆盖的问题。弹窗这里使用同一个值是比较合理的。

fix: z-index should be the same value

---

.vscode/launch.json
packages/core/cli/src/commands/dev.js

Add inspect argument for attaching to debug port.
When using VSCode developing over remote development server, need the server running under debug mode (with `--inspect`), and could use VSCode to attach to the debug port.
* `.vscode/launch.json`
* `dev.js`
None.
None.
None.

chore(vscode): add inspect argument for attaching to debug port

---

packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts

1. 使用 MySQL 数据库
2. 新增图表，使用整数类型字段作为度量，并选择求和作为聚合方式
3. 配置折线图
MySQL 将聚合后的 `bigInt` 字段返回成了 `string`
对数字字段统一处理类型

fix(bi): axis numbers are out of order when the database returns numeric values as strings

---

.github/workflows/nocobase-test-backend.yml
packages/plugins/@nocobase/plugin-workflow-delay/src/server/__tests__/instruction.test.ts

MySQL 8.3 (used in CI image as '8', update at Jan 19, 2024 at 3:03 pm on docker hub) cause some test cases failed with error:
~~~
Cannot create a JSON value from a string with CHARACTER SET 'binary'. Cannot create a JSON value from a string with CHARACTER SET 'binary'.
sql:
INSERT INTO `jobs` (`id`,`createdAt`,`updatedAt`,`executionId`,`nodeId`,`nodeKey`,`upstreamId`,`status`,`result`) VALUES (DEFAULT,?,?,?,?,?,?,?,?);
~~~
Run test of these files:
* packages/plugins/@nocobase/plugin-workflow-delay/src/server/\_\_tests\_\_/instruction.test.ts
* packages/plugins/@nocobase/plugin-workflow-manual/src/server/\_\_tests\_\_/instruction.test.ts
Could pass.
Throw error about JSON field.
None.
Not sure for now. Only happens in the cases, can not make a simple small reproduction.
Limit CI MySQL …

test: mysql version bug

---

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts

Should not pass transaction to sync trigger.
None.
No transaction in async triggering.
Reusing committed transaction.
None.
Mistaken using transaction.
Do not use transaction in async triggering.

fix(plugin-workflow): fix sync collection trigger transaction

---

packages/core/client/src/locale/cron/zh_CN.json
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/locale/Cron.zh-CN.ts

Locale of Cron component is wrong when DOM and DOW both present.
1. Use advance repeat mode in schedule workflow configuration.
Show "或者" in Chinese.
Showing "并且".
None.
None.
Change language in locale.

fix(client): fix cron locale when DOM and DOW both present

---

packages/plugins/@nocobase/plugin-workflow-test/src/server/triggers.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/CreateInstruction.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/DestroyInstruction.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/UpdateInstruction.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts

Cycling triggering cause dead loop between collection events.
1. Create event on collection1 with a create node to create data on collection2;
2. Create event on collection2 with a create node to create data on collection1;
3. Trigger one of events.
Only trigger once for each event.
Dead loop.
None.
Not considered cycling event on different collections.
Add stack to check event validity.

fix(plugin-workflow): fix collection cycling triggering

---

packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/end.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/EndInstruction.ts

End node doesn't end process when set to success.
1. Add any node (1).
2. Add end node (2) before the node (1).
3. Trigger the workflow.
Node 1 should not be executed.
Node 1 executed.
None.
Exit logic is not completed.
Fix exit logic.

fix(plugin-workflow): fix end logic when success

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/core/client/src/schema-component/antd/variable/VariableSelect.style.ts
packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoFormulaEngine.test.ts
packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/BranchIntoYesAndNoMathEngine.test.ts
packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesFormulaEngine.test.ts
packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/conditionNode/continueWhenYesMathEngine.test.ts

IME state not correct under Edge.
1. Use `Variable.TextArea` component to input Chinese.
Value changed to new state.
Value no changed.
None.
IME state not correct.
Use modern IME API `onCompositionStart` / `onCompositionEnd` events to listen IME state.

fix(client): fix variable textarea ime state under edge

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts

Context should be passed into processor instance.
1. Trigger workflow with specific context object.
2. To use the context object from `processor.options.xxx` in instructions.
Could access `xxx`.
Throws error.
None.
Not passed the instance to `createProcessor`.
Pass the instance.

fix(plugin-workflow): fix processor options to pass any context

---

packages/core/server/src/middlewares/data-wrapping.ts

No message passed after update record.
1. Use middleware to inject `state.messages` to context.
2. Update a record which run the middleware.
`messages` should present in body.
No messages.
None.
Update result is array, and is returned before messages handling.
Adjust branch logic.

fix(server): fix messages in data-wrapping

---

packages/plugins/@nocobase/plugin-workflow-form-trigger/src/server/FormTrigger.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts

Missed new properties in workflow revision.
1. Create a workflow with `sync` property set to `true`.
2. Revision the workflow.
`sync` property in new revision should be `true`.
`false`
None.
Missed properties.
Add properties.

fix(plugin-workflow): fix revision with new properties

---

packages/core/client/src/schema-component/antd/form-v2/utils.tsx
packages/core/evaluators/src/server/__tests__/index.test.ts
packages/core/evaluators/src/utils/index.ts
packages/plugins/@nocobase/plugin-formula-field/src/server/formula-field.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/calculation.test.ts

Formula field name with dash will not get correct result.
1. Add a formula field with name 'a-a';
2. Input any value for expression;
3. Create a record on that collection;
Formula field should has value.
Value is null.
None.
Not considered field name with dash.
Refactor and simplify `evaluate` function.

fix(core): refactor evaluate to support dash in key path

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/utils.ts

1. Create a chart block
2. Add filter block of chart block
3. Add a field with type of date
4. Set default value of the field as "Today" variable 
The default value of the field is `YYYY-MM-DDT00:00:00.000Z` to `YYYY-MM-DDT23:59:59.000Z`
The default value of the field is `YYYY-MM-DDT00:00:00.000Z` to `YYYY-MM-DDT00:00:00.000Z`
Conversion error
use `toISOString()`

fix(bi): parse issue of date variables

---

packages/core/client/src/schema-component/antd/filter/Filter.tsx

Filter field value of nodes cleared after open and just close drawer.
1. Add a query or update node.
2. Add a filter and save.
3. Reopen the node configuration drawer.
4. Close it.
5. Reopen it.
Filter value should be persisted in UI.
Filter value disappeared.
#3529.
Undefined `defaultValue` assigned to `initialValue` in filter component.
Check if undefined.

fix(client): fix filter default value

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-static.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/StaticScheduleTrigger.ts

Event not removed when turn off static schedule trigger.
1. Add a static time trigger workflow which starts on some future time.
2. Turn on the workflow.
3. Turn off the workflow.
Not triggering.
Triggered.
#3594.
Not cleared scheduled timers.
Clear all the timers related to the workflow.

fix(plugin-workflow): fix off static schedule trigger

---

packages/core/client/src/schema-component/antd/appends-tree-select/AppendsTreeSelect.tsx
packages/plugins/@nocobase/plugin-snapshot-field/src/client/interface.ts
packages/plugins/@nocobase/plugin-workflow-form-trigger/src/client/FormTrigger.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/schemas/collection.ts

Can not select deep appends in workflow triggers.
1. Create a collection trigger workflow with any collection.
2. Try to select appends field under "Created by" field.
Could show the sub-tree and select.
Not showing.
None.
`useCollection` API mistaken changed.
Change the API back.

fix(client): fix mistaken changed api

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-static.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/StaticScheduleTrigger.ts

Repeat as number in schedule trigger works not correctly.
1. Create a schedule trigger with repeat as 10min.
Triggers every 10min from start time.
Triggers time is in chaos.
#3594.
Calculation of repeat time is not correct.
Fix repeat calculation.

fix(plugin-workflow): fix schedule repeat logic

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/migrations/20240227172623-change-name.ts
packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20231122143143-split-to-plugins.ts

Migration version not matching.
1. `yarn nocobase upgrade` after v0.20.0-alpha.6
Upgraded.
Throwing error.
None.
Migration not executed due to version mismatch.
Change the version number in migration.

fix(plugin-workflow-action-trigger): fix migration

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/__tests__/trigger.test.ts

Record trigger workflow with appends not loaded.
1. Add action workflow with appends data (like createdBy).
2. Use "Submit to workflow" button in data table action column.
3. Check context data in triggered workflow.
Appends data should be in context data as a full record.
Not exists as a full record.
#3657.
Not loaded in "Submit to workflow" trigger mode.
Add load logic.

fix(plugin-workflow-action-trigger): fix appends loading

---

packages/core/client/src/collection-manager/action-hooks.ts
packages/core/client/src/collection-manager/index.tsx
packages/core/client/src/collection-manager/utils.ts
packages/core/client/src/locale/zh-CN.json
packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx
packages/core/data-source-manager/src/index.ts
packages/core/data-source-manager/src/utils.ts

Refactor and add component for compatibly supporting data source select.
For compatibly supporting data source select
- Frontend
- `<DataSourceCollectionCascader />`
- `parseColelctionName()`
- Backend
- `parseColelctionName()`
None.
None.
None.

refactor(client): add component to support data source select

---

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts

Occasionally duplicated triggering on schedule workflow.
1. Add a date field based schedule workflow and enable it.
2. Disable it and enable again.
Only trigger once on one time.
Triggered twice.
#3594.
Event is not match to the add one when remove.
Fix event key.

fix(plugin-workflow): fix duplicated triggering schedule event

---

packages/presets/nocobase/src/client/index.ts

The issue related is: https://github.com/nocobase/nocobase/issues/3721
When timezone is negative, like Brazilian (UTC -3), the header `X-Timezone` is `--3:00`.
This fix solve the issue ensuring the variable is positive before pad `0` and append `-`

fixing timezone header when it is negative value

---

packages/plugins/@nocobase/plugin-cas/src/server/actions/service.ts
packages/plugins/@nocobase/plugin-oidc/src/server/actions/redirect.ts
packages/plugins/@nocobase/plugin-saml/src/server/actions/redirect.ts

1. Deploy NocoBase using subpath
2. Configure SSO auth and attempt to sign in
Sign in successfully.
Redirect URL missed subpath.
Prefix of redirect URL is wrong.
Add subpath to redirect URL.

fix(auth): sso auth bug when deploying with subpath

---

packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts

Field label not translated.
1. Add a file template table.
2. Configure fields.
`Path` and other field translated.
None.
Missed `NAMESPACE`.
Add `NAMESPACE`.

fix(plugin-file-manager): fix storage locale on file template table header

---

packages/plugins/@nocobase/plugin-users/src/server/__tests__/model.test.ts
packages/plugins/@nocobase/plugin-users/src/server/models/UserModel.ts
packages/plugins/@nocobase/plugin-users/src/server/server.ts
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts

Add model method `.desensitize()` to filter hidden field.
`password` and `resetToken` field should be hidden when output or save to cache.
- Frontend
- Backend
- Add `UserModel` class and `.desensitize()` method.
None.
None.
None.

feat(plugin-user): add model method desensitize() to filter hidden field

---

packages/plugins/@nocobase/plugin-acl/src/client/RolesManagement.tsx
packages/plugins/@nocobase/plugin-acl/src/client/RolesMenu.tsx
packages/plugins/@nocobase/plugin-acl/src/client/hooks/load-more-observer.ts

1. Users & Permissions - Roles & Permissions
2. Add more than 20 (default pageSize) roles
3. Scroll the role menu list
It would load more roles.
It only displayed one page.
Close T-3640
`pagination=false` is an invalid params.
Use `pagenate=false` instead.
Or 
✅ Load next page automatically when scroll to the bottom.

fix(acl): role menu list only displays one page

---

packages/plugins/@nocobase/plugin-acl/src/client/RolesMenu.tsx
packages/plugins/@nocobase/plugin-users/src/client/RoleUsersManager.tsx

1. Users & Permissions - Roles & Permissions
2. Select first role by clicking it
3. Select second role
4. Add users to the role
Added successfully.
The users are added to the first selected role.
It did not retrieve the latest role from context when adding users.
Get the latest role from context.

fix(acl): bug when adding users to roles

---

packages/core/client/src/collection-manager/hooks/useCollectionManager_deprecated.ts
packages/core/client/src/schema-component/antd/action/Action.Designer.tsx

Error occurs when hover on "Reject" button in custom form in manual node.
1. Add a manual node in workflow.
2. Add a custom form in UI configuration.
3. Add a "Reject" button in action bar.
4. Hover on the button settings menu.
Show the settings menu.
Throws error.
Link T-3665.
Undefined reference.
Add possible undefined check.

fix(client): fix action designer error occured in custom form

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx

Should not use string template engine for calculation in condition node.
1. Add a condition node.
2. Check calculation engines.
String template should not be present.
String template is present.
None.
String result is not related to logic checking.
Remove it.

fix(plugin-workflow): remove string template in condition calculation

---

packages/core/cli/src/commands/e2e.js
packages/core/cli/src/commands/p-test.js

close T-3682
```bash
yarn e2e p-test
```
```bash
yarn e2e p-test --match 'packages/**/{plugin-workflow,plugin-workflow-*}/**/__e2e__/**/*.test.ts'
```
```bash
yarn e2e p-test --ignore 'packages/**/{plugin-workflow,plugin-workflow-*}/**/__e2e__/**/*.test.ts'
```

chore: add options for matching and ignoring test files in p-test

---

packages/plugins/@nocobase/plugin-workflow-parallel/src/locale/zh-CN.json

"Mode" is missed in locale file.
1. Add parallel node.
2. Change language to Chinese.
"Mode" should be translated.
None.
Locale missed when split plugins.
Add missed translation to plugin.

fix(plugin-workflow-parallel): fix locale

---

packages/core/client/src/schema-component/antd/filter/DynamicComponent.tsx

When use dynamic component in filter, the disabled property is not correct.
1. Create a query node in workflow with variable in a filter.
2. Trigger the workflow.
3. Reopen the query node in the executed workflow.
4. Check the filter.
All field in the filter should be disabled due to the workflow is executed.
The variable part is not disabled.
None.
No disabled property control in `renderSchemaComponent()`.
Add `x-disabled` to the dynamic component.

fix(client): fix diabled in filter dynamic component

---

packages/core/evaluators/src/utils/__tests__/appendArrayColumn.test.ts
packages/core/evaluators/src/utils/index.ts

Deep array should be flatten.
```
const scope = appendArrayColumn({ a: [{ b: [{ c: 1 }, { c: 2 }] }, { b: [{ c: 3 }, { c: 4 }] }] }, 'a.b.c');
get(scope, 'a.b.c');
```
```
[1, 2, 3, 4]
```
```
[{ b: [{ c: 1 }, { c: 2 }] }, { b: [{ c: 3 }, { c: 4 }] }]
```
None.
Array not flatten.
Flat array.

fix(evaluators): fix array flatten

---

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/hooks/useRefreshActionProps.ts
packages/plugins/@nocobase/plugin-workflow/src/client/schemas/executions.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json

Add sync action button on workflow list.
Can only restart apps when workflow updated in multiple apps environment.
- Frontend
- Workflow list schema and scope.
- Backend
None.
None.

feat(plugin-workflow-sync): add sync when multi-app-share-collection enabled

---

packages/plugins/@nocobase/plugin-auth/src/client/pages/AuthLayout.tsx

Enter `/signup?name=basic` with url directly
It shows up sign up page.
It shows up not found page.
The request of `authenticators:publicList` is loading when the page showing up.
Return `<Spin />` instead of the sign up page if the status of the request is loading.

fix(auth): sign up page not found when entering with url directly

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json

Adjust locale.
To explain "Submit to workflow" button can only be used for "Post-action event".
- Frontend
- Backend
None.
None.
None.

fix(plugin-workflow): adjust locale

---

packages/core/server/src/application.ts

The runAsCLI function's argument: 'options' is an optional argument.
However, there were instances where it was being treated as a regular argument, which was causing errors.
I have changed it to be nullable.
yarn run:example app/single-app start
example starts.
error occurred.
```
TypeError: Cannot read properties of undefined (reading 'reqId')
at AsyncEmitter.runAsCLI (c:\nocobase\packages\core\server\src\application.ts:734:17)
at Database (c:\nocobase\examples\index.ts:9:7)
at Object.<anonymous> (c:\nocobase\examples\index.ts:14:1)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Object.j (C:\nocobase\node_modules\@umijs\plugin-run\node_modules\tsx\dist\cjs\index.cjs:1:1197)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load …
```

fix(server): `Cannot read properties of undefined (reading 'reqId')` error when using `runAsCLI` without `option` argument

---

packages/plugins/@nocobase/plugin-theme-editor/src/server/builtinThemes.ts

close T-4074
实际表现是页面中的普通文字的字号会是 14。

chore(Theme): set the default font size of the Compact theme to 16

---

packages/core/evaluators/src/server/__tests__/index.test.ts
packages/core/evaluators/src/utils/formulajs.ts

1. Use a number greater than 32 bit integer in formula.js calculation.
2. Execute the calculation.
The number should be output as same input.
`NaN`.
None.
`ROUND()` function in formula.js is not same function as `round()` in math.js, which produce `NaN`.
Use `round()` in math.js instead.

fix(core): fix round bug in formula evaluator

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-static.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts

Duplicated triggering schedule event in multiple applications with shared collections.
1. Use multiple application plugin and share collection plugin.
2. Create a workflow on static time and enable it.
The workflow should only be triggered once on the static time.
Triggered as many times as amount of applications (including sub-apps).
None.
Need triggering validation.
Add time string based validation.

test(plugin-workflow): add test case for duplicated triggering schedule workflow

---

packages/core/client/src/schema-component/antd/card-item/CardItem.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.tsx
packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.tsx

> 页面地址：[https://main.test.nocobase.com/admin/4y6tv4btv0p](https://main.test.nocobase.com/admin/4y6tv4btv0p)
在页面渲染完成后，CPU 依然是满负荷状态，并且一直持续下去：
经过 Performance 面板分析后发现，页面一直在进行 `重新计算样式` 和 `绘制` 的过程，并且和动画有关。
由于这里加的有 `骨架屏` 的效果，所以怀疑是骨架屏动画影响的。在去除骨架屏动画后，页面恢复正常：

perf: remove all Skeleton animation

---

packages/core/evaluators/src/utils/__tests__/appendArrayColumn.test.ts
packages/plugins/@nocobase/plugin-workflow-manual/src/server/ManualInstruction.ts
packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/assignees.test.ts
packages/plugins/@nocobase/plugin-workflow-manual/src/server/actions.ts

Can submit on manual node todo when using to-many assignees.
1. Create a manual node, set assignees to "Trigger / Trigger data / \<Some to many field\> / CreatedById".
2. Trigger the workflow, and go to todo panel.
3. Submit the form configured in manual node.
Pass the manual node.
`403`.
None.
Assignees should be flatten.
Flatten assignees array.

fix(plugin-workflow-manual): fix assignees parsing bug

---

packages/plugins/@nocobase/plugin-workflow-manual/src/server/ManualInstruction.ts
packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/assignees.test.ts

Allow pass node when no assignee
1. Create manual node without assignee.
2. Trigger the workflow.
Execution should be resolved.
Pending.
None.
Not skipped scenario of none assignee.
Make the node as resolve when no assignee.

fix(plugin-workflow-manual): allow pass node when no assignee

---

packages/plugins/@nocobase/plugin-workflow/src/client/ExecutionCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx

Show workflow key as tooltip on title.
Workflow key will be useful when trigger workflow over HTTP API, administrator need to get it from UI.
- Frontend
- Workflow canvas.
- Backend
None.
None.

feat(plugin-workflow): show workflow key as tooltip on title

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/client/ActionTrigger.tsx

Fix locales.
Bind custom action trigger workflow.
Hint translated.
None.
Wrong namespace.
Fix namespace.

fix(plugin-workflow-custom-action-trigger): fix locales

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts

Support "application/x-www-form-urlencoded" for "Content-Type".
For legacy HTTP API services.
- Frontend
- Add `contentType` option for request node.
- Change `Variable.Input` to `Variable.TextArea` for values options.
- Backend
- Support `contentType` option for request node.
Through cases.
None.

feat(plugin-workflow-request): support "application/x-www-form-urlencoded" type

---

packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/AggregateInstruction.tsx

Association field can not be selected in aggregate node.
1. Make 2 collection with many-to-many relationship.
2. Create a workflow and an aggregate node.
3. Select the association collection from one to another.
4. Select the association field to aggregate.
The association field could be selected.
The field list is empty.
None.
Data source parsing incorrectly.
Fix the data source parsing.

fix(plugin-workflow-aggregate): fix association field select

---

packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts

"Ignore failure" of request node not works in sync workflow.
1. Create a sync workflow.
2. Create a request node (1), point to a 404 URL, and enable "Ignore failure" option.
3. Create another node (2) as downstream of the request node.
Node (2) should be executed.
Not executed, and execution exited as failure.
#4333.
`ignoreFail` not implemented in sync mode.
Add implementation in sync mode.

fix(plugin-workflow-request): fix ignoreFail in sync mode

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx

Value fields (header / params) overflowing when text too long.
1. Create a request node in workflow.
2. Add a header row and input a piece of long text in value field.
Text should wrap to new line.
Input box width overflowing.
#4334.
Some component style not controlled well like `Variable.TextArea`.
Fix the styles.

fix(plugin-workflow-request): fix value fields overflowing

---

packages/core/logger/src/request-logger.ts
packages/core/logger/src/system-logger.ts
packages/core/server/src/application.ts
packages/core/server/src/helper.ts

After an app is destroyed, the opened log file streams should be closed. fix T-4302

fix(logger): should close log stream after destroying app

---

packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/queryRecordNode/QueryRecord.test.ts
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/schemas/collection.ts
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/query.test.ts

Change multiple checkbox to radio group and descriptions.
The description of multiple record for query node is confusing (#4407).
- Frontend
- Query node configuration UI.
- Backend
None.
None.

refactor(plugin-workflow): adjust multiple option in query node

---

packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts

Allow to use response variables:
- Status code
- Data payload
- Response headers
After unified response structure, status code will be very useful for checking logic in workflow (when `ignoreFail` configured).
- Frontend
- Change `useVariable` in new request node (ignored legacy `onlyData`).
- Backend
None.
None.

feat(plugin-workflow-request): allow to use response variables

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/CollectionFieldset.tsx

1. Add a create or update node in workflow.
2. Add an association field (belong to) in value fields set.
3. Input anything, then clear content.
4. Save node.
5. Trigger the workflow.
Association field value updated to `null`.
Error thrown:
```json
{
"message": "invalid input syntax for integer: \"\"",
"stack": "Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.update (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:12)\n    at async model.save (/app/nocobase/node_modules/sequelize/lib/model.js:2490:35)\n    at async …
```

fix(plugin-workflow): fix empty value in create and update node association values

---

packages/core/client/src/schema-settings/SchemaSettingsDataScope.tsx
packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx
packages/core/client/src/schema-settings/VariableInput/hooks/useDateVariable.ts
packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts

close T-4067
- When setting default values for form fields, options that don't match will be disabled to prevent errors.
- When setting the data scope, the date variable is not disabled to ensure it can be selected.
- The date variables in expressions remain unchanged.

chore: avoid misoperation of date variables

---

packages/plugins/@nocobase/plugin-action-export/src/client/useExportAction.tsx

fix: export action missing data scope filter

---

packages/core/client/src/schema-component/antd/form-v2/utils.tsx

fix:  numeric field display issue in form linkage rule

---

packages/core/client/src/collection-manager/hooks/useCollectionManager_deprecated.ts
packages/core/client/src/collection-manager/mixins/InheritanceCollectionMixin.ts
packages/core/client/src/data-source/utils.ts
packages/core/client/src/modules/blocks/data-blocks/table/TableColumnInitializers.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
packages/core/client/src/schema-initializer/utils.ts
packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts
packages/plugins/@nocobase/plugin-audit-logs/src/client/initializers/AuditLogsTableColumnInitializers.tsx

refactor: remove all frontend checks for isForeignKey

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterVariableInput.tsx

fix(data-vi): field component invisible when setting default value for filter field

---

packages/plugins/@nocobase/plugin-acl/src/server/__tests__/setCurrentRole.test.ts
packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts

fix(acl): use default role when `x-role` does not belong to the current user

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx

Border and other style of Variable.TextArea disappeared.
1. Add a calculation node in workflow.
2. Open node configuration drawer.
The input text area should has border and other styles.
Styles disappeared.
None.
https://github.com/nocobase/nocobase/commit/49d0082b16460768a5aeab7a457f7d42b4014ab7#diff-015b8e211b486e3d5847258410762fc9da59abfc28055848abf1bc9dde29003bR238
Add `useInputStyle('ant-input')` for custom component.

fix(client): fix Variable.TextArea style

---

packages/core/client/src/schema-component/antd/appends-tree-select/AppendsTreeSelect.tsx

Can not select deep associations in AppendsTreeSelect component.
1. Add an external PG datasource.
2. Add a collection workflow using collection from the datasource.
3. Try select associations more than 1 level for the preload associations select.
Could select.
Could not.
None.
Legacy API does not support multiple data source.
Migrate legacy API to new ones in the component.

fix(client): fix deep association select in AppendsTreeSelect component

---

packages/core/utils/package.json
packages/core/utils/src/__tests__/json-templates.test.ts
packages/core/utils/src/json-templates.ts

Multiple variables in a string not parsed correctly.
```
parse({ str: '{{a}},{{b}}' })({ a: 'a', b: 'b' });
```
```
{ str: 'a,b' }
```
```
{ str: 'b' }
```
None.
json-templates bug.
Update code to latest version.

fix(utils): fix json-templates

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
packages/core/client/src/schema-component/hooks/useDesignable.tsx
packages/core/client/src/schema-initializer/buttons/RecordBlockInitializers.tsx
packages/core/client/src/schema-initializer/utils.ts

fix(client): fix the issue where adding block templates in the popup does not display

---

packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/storages/ali-oss.test.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/storages/s3.test.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/storages/tx-cos.test.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/ali-oss.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/s3.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/tx-cos.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/utils.ts

Error thrown when deleting file of COS.
1. Create a COS storage.
2. Create a file collection which storage set to the COS.
3. Upload a file on the table.
4. Delete the file in the table row.
File deleted.
Error thrown:
```
{"log":"TypeError [ERR_INVALID_ARG_TYPE]: The \"cb\" argument must be of type function. Received undefined\n","stream":"stderr","time":"2024-05-30T05:02:30.36958009Z"}
{"log":"    at makeCallback (node:fs:185:3)\n","stream":"stderr","time":"2024-05-30T05:02:30.369618976Z"}
{"log":"    at Object.unlink (node:fs:1863:14)\n","stream":"stderr","time":"2024-05-30T05:02:30.369624558Z"}
{"log":"    at COSStorage._removeFile (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/multer-cos/index.js:36:5610)\n","stream":"stderr","time":"2024-05-30T05:02:30.36 …
```

fix(plugin-fm): fix delete file error of cos

---

packages/plugins/@nocobase/plugin-file-manager/src/client/FileSizeField.tsx
packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/tx-cos.ts

When set path, upload cause error.
1. Create a COS storage with path like "abc".
2. Create a file collection use the COS storage.
3. Upload a file to the file collection.
File uploaded.
Error thrown.
```
app_1  | TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
app_1  |     at makeCallback (node:fs:185:3)
app_1  |     at Object.unlink (node:fs:1863:14)
app_1  |     at COSStorage._removeFile (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/multer-cos/index.js:36:5610)
app_1  |     at WriteStream.<anonymous> (/app/nocobase/node_modules/@nocobase/plugin-file-manager/dist/node_modules/multer-cos/index.js:36:5413)
app_1  |     at WriteStream.emit (node:events:531:35)
app_1  |     at WriteStream.emit (node:domain:488:12) …
```

fix(plugin-fm): fix cos path error

---

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx

Workflow versions dropdown overflow.
1. Add a lot of versions for a workflow more than one screen.
2. Open the versions dropdown.
Scroll bar in the dropdown.
No scroll bar in dropdown, and page overflowed.
None.
No height limit for the versions dropdown.
Add `max-height` for the dropdown.

fix(plugin-workflow): fix workflow versions dropdown overflow

---

packages/core/client/src/schema-component/antd/upload/shared.ts

Page crashes when upload meet 413 in local development.
1. Start development server and client separately.
2. Upload a file more than 10mb.
Success or error shown on page.
Page crashes.
None.
Using property of undefined object.
Add undefined check.

fix(plugin-fm): fix page crash when 413 in local dev

---

packages/core/client/src/schema-component/antd/action/Action.tsx

Fix waring props in Action component.
1. Add any action button to UI.
No warnings.
Warning in console:
```
index.js:1 Warning: React does not recognize the `refreshDataBlockRequest` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `refreshdatablockrequest` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
at a
at Sortable (http://localhost:13001/p__index.async.js:106838:25)
at SortableProvider (http://localhost:13001/p__index.async.js:106813:18)
at wrappedComponent (http://localhost:13001/vendors-node_modules_ant-design_icons_es_index_js-node_modules_ant-design_pro-layout_es_compo-b172cd.async.js:179875:83)
at ActionContextProvider …
```

fix(client): fix waring props

---

packages/core/client/src/schema-component/antd/upload/Upload.tsx

Can not select file when attachment field set to not allowing multiple files.
1. Add an attachment field without allowing multiple files.
2. Add the field to a form.
Could use the uploader to upload file.
Uploader component disappears.
None.
Selectable logic incorrect.
Fix the selectable logic.

fix(client): fix attachment component

---

packages/core/client/src/system-settings/SystemSettingsShortcut.tsx

Logo upload rule not correct in system settings.
1. Go to system settings.
2. Remove current logo.
3. Mouse hover on logo upload component.
Size rule shows correctly.
Warning in console tells hooks not exists.
None.
Wrong hook name.
Fix hook name.

fix(client): fix upload logo in system settings

---

packages/core/client/src/schema-component/antd/action/Action.tsx

Auto refresh after action not works.
1. Add an create form.
2. Submit form to create data.
Parent block refresh after submitted.
Not refresh.
#4562.
`props` not equal to `field['x-component-props']`.
Revert the property back.

fix(client): fix action props

---

packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Map.tsx

fix(map): amap reset

---

packages/core/client/src/schema-settings/VariableInput/hooks/index.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterVariableInput.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/useVariableOptions.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRendererProvider.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts

feat(data-vi): support for using url params and current role variables

---

packages/core/client/package.json
packages/core/client/src/schema-component/antd/input/Json.tsx
packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx
packages/core/client/src/schema-component/antd/input/demos/new-demos/json.tsx
packages/core/client/src/schema-component/antd/input/demos/new-demos/json5.tsx
packages/core/client/src/schema-component/antd/input/index.en-US.md
packages/core/client/src/schema-component/antd/input/index.md

Allow client values of JSON5 for FormInput JSONTextArea. Persisting is kept in valid JSON.
The old JSON Input Field did not allow JSON5 (Human friendly JSON) input. Advanced chart configuration for example was painfully when validated for raw JSON.
- Frontend
- Component schema of JSONTextArea adjusted to validate by JSON 5 when input is changed. State value is parsed to JSON. 
- Additional boolean prop `json5` introduced (default=true) to disable this behaviour

feat(client): allow JSON5 value in Form Input of type JSONTextArea

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Text overflow in `Variable.Input` component when name of variables is very long, and width of component is limited.
1. Layout 2 `Variable.Input` in a row, and limit column width.
2. Select a long variable.
Variable name should not overflow, but be wrapped.
Overflowing.
None.
`white-space: nowrap`.
Remove the style line.

fix(client): fix text wrap in variable input

---

packages/presets/nocobase/src/server/index.ts

Unpublished plugin is using wrong version.
1. Use main (x > v1.0.1-alpha.1) image.
2. Change to latest (v1.0.1-alpha.1) image.
App start normally.
Error thrown:
```
{"level":"error","message":"ENOENT: no such file or directory, realpath '/app/nocobase/node_modules/@nocobase/plugin-workflow-mailer/package.json'","stack":"Error: ENOENT: no such file or directory, realpath '/app/nocobase/node_modules/@nocobase/plugin-workflow-mailer/package.json'","meta":{},"module":"application","submodule":"","method":"","app":"app1","reqId":"0976f257-64e9-41ab-9b70-d14c17302aac","dataSourceKey":"main","timestamp":"2024-06-11 04:56:59"}
```
[#4618](https://github.com/nocobase/nocobase/discussions/4618)
Wrong version number specified.
Remove version number.

fix(preset): fix plugin-workflow-mailer version

---

packages/core/client/src/schema-component/antd/upload/Upload.tsx

Set upload field invalid when uploading is not completed to avoid submit.
1. Add an attachment field to a form block.
2. Upload a big file.
3. Click submit before uploading completed.
Form should not be submitted.
Form is submitted without attachment data.
Link T-4538.
Miss field feedback when uploading.
Add validation feedback.

fix(plugin-fm): set invalid when uploading is not completed to avoid submit

---

packages/plugins/@nocobase/plugin-file-manager/src/server/migrations/20240613110121-fix-schema-in-field.ts

Upload file in a legacy attachment field meet error.
1. Use version older than v1.0.0-alpha.16.
2. Add an attachment field in a collection.
3. Add a form to add new record and add the attachment field.
4. Upgrade version to newer.
5. Try upload file in the form field.
File uploaded successfully.
Error thrown:
`404` on `/api`.
#4118.
Link T-4544.
Default UI schema in field options not migrated.
Add migration.

fix(plugin-fm): add migration for fixing new added legacy attachment field

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/create.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/update.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20240613222612-fix-assign-field-config.ts

1. Use version v1.0.1-alpha.1.
2. Add a create/update node.
3. Set a field for values.
4. Upgrade to v1.2.3-alpha
5. Reopen the node.
Assign field value configuration component still show in legacy node.
Changed to new schema component.
None.
Incorrect reaction logic.
Add a new flag to determine reaction logic.

fix(plugin-workflow): fix incorrectly schema reaction

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/useVariableOptions.ts

1. Add a chart block
2. Add a custom filter field for charts
3. Set filter field value and filter
The filter condition is supposed to be appended to the query
The filter condition is not applied
The custom filter field variables should not be parsed in the inner filter.
Skip the custom filter field variables when parsing the inner filter conditions.

fix(data-vi): custom filter conditions are not applied

---

packages/core/client/src/collection-manager/collectionPlugin.ts
packages/core/client/src/collection-manager/templates/index.tsx
packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/ExpressionCollectionTemplate.ts
packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/index.ts

Move collection template to plugin and remove sort field.
Collection template managed by plugin should not be placed in core package.
- Frontend
- Expression collection template.
- Remove default sort field of expression collection.
- Fix Variable.TextArea.ReadPretty style.
- Backend
None.
None.
None.

refactor(plugin-workflow-dc): move collection template to plugin and remove sort field

---

packages/core/client/src/schema-component/antd/upload/Upload.tsx
packages/core/client/src/schema-component/antd/upload/style.ts

Fix upload progress style
1. Upload a big file.
Progress bar showing correctly when uploading.
Width is 2px.
#4118.
`size={2}` cause this.
Change back to `strokeWidth`.

fix(client): fix upload progress style

---

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/RepeatField.tsx

Fix locale key usage from localstorage.
1. Use BASE_PATH.
2. Enable multi-app.
3. Configure repeat field in schedule trigger.
Field languages could be translated base on locale user set.
None.
Locale key from localstorage is based on BASE_PATH.
Use the key provided by APIClient.

fix(plugin-workflow): fix locale key usage from localstorage

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/StatusButton.tsx

Fix client warning in execution canvas.
1. Go to any execution canvas with at least one executed node.
No waring in console.
Warning.
None.
Non-DOM properties passed to DOM element.
Do not pass.

fix(plugin-workflow): fix client warning

---

packages/core/client/src/schema-component/hooks/useBlockSize.ts

While using sub-table component to represent one-to-many field in manual node block or assign field values in create/update node, error thrown.
1. Manual node:
1. Add a data block with an one-to-many field in manual UI configuration.
2. Switch the component of the field from title to sub-table.
2. Create/update node:
1. Add a create/update node.
2. Add an one-to-many field into assign value block.
3. Switch the component of the field from select to sub-table.
Showing sub-table.
Error thrown:
```
TypeError: Cannot read properties of null (reading 'data')
useTableHeight
.nocobase/packages/core/client/src/schema-component/hooks/useBlockSize.ts:94:10
91 | const schema = useFieldSchema();
92 | const heightProps = tableHeightProps || blockHeightProps;
93 | const pageFullScreenHeight = …
```

fix(client): fix undefined context

---

packages/core/client/src/schema-component/antd/action/ActionBar.tsx
packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx

优化使用区块模板时的显示
没有安装多数据源时： 表名  ； 引用模板： 模板名
安装了多数据源时：数据源 > 表名 ； 引用模板：模板名
- Frontend
- Backend

fix: optimize block template description

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/AssignedFieldsFormSchemaConfig.tsx

Fix designable of assign fields in create/update node.
1. Add an update node and configure some fields to assign values.
2. Trigger the workflow.
3. Review the node configuration of executed workflow.
Assign values fields should not be designable after executed.
Designable.
None.
Designable logic.
Use `nodeForm.disabled` to calculate designable.

fix(plugin-workflow): fix designable of assign fields in create/update node

---

packages/plugins/@nocobase/plugin-workflow/src/client/AddButton.tsx
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/nodes.test.ts

Add loading for adding node.
Small possibility no reaction from server when adding node for a while, and quickly add another node, newly added node will be lost from the canvas but exist in data.
No un-fully-linked node.
Un-fully-linked node exists.
None.
Need waiting for response from server.
Add loading status for button of adding node.

fix(plugin-workflow): add loading for adding node

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/workflows.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts

Duplicated sync workflow becomes async.
1. Create a sync workflow.
2. Duplicate it to a new one in workflows list.
New workflow should be sync as the original one.
It becomes async.
None.
Sync value missed in duplication action.
Use sync field for both type or revision.

fix(plugin-workflow): fix duplicating sync workflow

---

packages/core/client/src/schema-component/antd/upload/Upload.tsx
packages/core/client/src/schema-component/antd/upload/shared.ts

Size hint of legacy attachment field shows 1GB, but can not upload greater than 20MB.
1. Use version before v1.0.0-alpha.17.
2. Add some attachment field based on default local storage.
3. Upgrade to latest version.
4. Hover to the upload component and check the hint.
20MB by default when no rules configured.
Showing 1GB but can not upload greater than 20MB.
#4118.
Default size limit in client is not same as in server.
Change client default size hint to be same as server (20MB).

fix(client): fix default size hint of upload component

---

packages/core/client/src/collection-manager/Configuration/EditFieldAction.tsx
packages/core/client/src/collection-manager/interfaces/properties/index.ts

…ncrement
- Frontend
- Backend

refactor: integer fields with primary selected will auto-check auto increment

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

表格checkbox会在数据大于10的时候无法对齐
当表格数据多与10条时 点击rowSection全选表格数据
checkbox都在同一列对齐
9-10开始会错位
表格显示rowSelection时因为tableIndex从9-10这种位数变化会引起宽度变化 float:left导致checkbox没有对齐
只有在显示tableIndex时再添加float:left样式

fix: checkbox style is not aligned when selecting the table

---

packages/plugins/@nocobase/plugin-workflow-mailer/src/server/MailerInstruction.ts

Mail sending failed in sync mode.
1. Add a sync workflow (post-action).
2. Add a mailer node and configure it correctly.
3. Trigger the workflow.
Mail sent successfully.
Failed with error indicates configuration incorrectly.
None.
Payload is not same in sync mode.
Use same payload in each mode.

fix(plugin-workflow-mailer): fix payload in sync mode

---

packages/core/client/src/locale/en_US.json
packages/core/client/src/locale/zh-CN.json
packages/core/client/src/schema-component/antd/icon-picker/IconPicker.tsx
packages/core/client/src/schema-component/antd/icon-picker/__tests__/icon-picker.test.tsx
packages/core/client/src/schema-component/antd/icon-picker/index.en-US.md
packages/core/client/src/schema-component/antd/icon-picker/index.md

- Adds the ability for the user to search for icons
- Increase the UX by increasing the icon sizes and add a title tag to display the icon name on mousehover
- No way to search for a specific icon in icon-select popover
- To small icons make it hard to spot the correct item
- Frontend
- Add input of type search to icon-select popover
- Filter the available icons by comparing search input with icon name
- Debounce the icon search filter to maintain performance on weak client devices
- Add title tag to icon component wrapper element

 feat(client): add searchbar and increase ux of select popover in icon-picker component

---

packages/core/utils/src/parse-filter.ts
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/ko_KR.json
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/function.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/functions/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/index.ts

Add date range options to system variables in workflow context.
Date range variables in data block filter is convenient to use. It will also be useful in workflow nodes.
- Frontend
- Backend
Through test cases.
Date range variables can not be used for operators other than "is".

feat(plugin-workflow): add date range options to system variables

---

packages/core/database/src/__tests__/target-key.test.ts
packages/core/database/src/update-associations.ts
packages/core/database/src/update-guard.ts

| 🇺🇸 English |   An error occurs when saving if the target key in a o2m assocation is not an ID  |
| 🇨🇳 Chinese |  一对多关系的 target key 不为 ID 时，保存时报错    |

fix: target key value is empty

---

packages/core/client/docs/en-US/core/ui-schema/demos/schema-settings-components-item.tsx
packages/core/client/docs/zh-CN/core/ui-schema/demos/schema-settings-components-item.tsx
packages/core/client/src/application/schema-initializer/components/SchemaInitializerItem.tsx
packages/core/client/src/application/schema-initializer/components/SchemaInitializerSwitch.tsx
packages/core/client/src/application/schema-initializer/components/style.ts
packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/core/client/src/schema-settings/SchemaSettings.tsx
packages/core/client/src/schema-settings/demos/built-type.tsx

Some settings item need to be conditionally disabled, rather than add one more different settings.
Add `disabled` option to props of SchemaSettingsItem
None.
| 🇺🇸 English | Add `disabled` option to props of SchemaSettingsItem |
| 🇨🇳 Chinese | 为 SchemaSettingsItem 组件的传入属性增加 `disabled` 选项 |

feat(client): add `disabled` option to props of SchemaSettingsItem

---

packages/core/client/src/schema-component/antd/date-picker/__tests__/util.test.ts
packages/core/client/src/schema-component/antd/date-picker/util.ts

Fix output time in date-picker in date-only mode
1. Create a datetime field.
2. Pick a date.
3. Open show time option in component setting.
Time part should be '00:00:00'.
Time part is '08:00:00'.
None.
Using GMT as default output.
Use local timezone.

fix(client): fix output time in date-picker in date-only mode

---

packages/core/client/src/schema-component/common/utils/logic.js

…le under m2o association field
| 🇺🇸 English |       Ineffective condition checks when using checkbox fields under many-to-one association fields as linkage rule conditions.    |
| 🇨🇳 Chinese |     使用多对一关系字段下的复选框字段为联动规则条件时判断无效      |

fix:  checkbox field as ineffective linkage rule conditions under many-to-one association field

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

The default cell style should not be reset.
close T-4735
| 🇺🇸 English |      Fix styling issue with fixed columns.     |
| 🇨🇳 Chinese |      修复 table 固定列的样式问题。     |

fix(Table): fix styling issue with fixed columns

---

packages/core/client/src/route-switch/antd/admin-layout/index.tsx
packages/core/client/src/schema-component/core/RemoteSchemaComponent.tsx

1. Open a NocoBase page in Safari.
2. Select two slightly more complex pages and switch back and forth.
3. There is a certain chance that this issue will occur.
https://github.com/nocobase/nocobase/assets/38434641/98a062f4-0e4f-4c5f-ab62-023ba2c38501
merge https://github.com/nocobase/pro-plugins/pull/138
| 🇺🇸 English |      Fix the issue that the page does not refresh after switching menus in Safari.     |
| 🇨🇳 Chinese |     修复在 Safari 中，切换菜单后页面不刷新的问题。      |

fix(Safari): resolve issue with menu page not refreshing in Safari

---

packages/core/test/src/server/index.ts
packages/plugins/@nocobase/plugin-data-visualization/package.json
packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/external-data-source.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/mock-data-source.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/query.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts

In the data visualization plugin, when a non "root" role with "view" permissions querying data from an external data source, a "No permissions" error occurs.
1. Connect to an external data source.
2. Switch to a non "root" role with "view" permissions for the data source.
3. Querying data from the data source in the data visualization plugin.
The data visualization plugin did not use the corresponding ACL instance of the data source when checking permissions.
fix T-4804
| 🇺🇸 English | Fix the permission issue when using external data sources in data visualization plugin         |
| 🇨🇳 Chinese | 修复数据可视化插件连接外部数据源时的权限判断问题          |

fix(data-vi): fix the permission issue when using external data sources in data-vi plugin

---

packages/core/client/src/application/schema-initializer/components/SchemaInitializerSelect.tsx
packages/core/client/src/schema-items/OpenModeSchemaItems.tsx

| 🇺🇸 English |The Kanban block initializer `openMode` and `Pop size` should not be closed after clicking on them |
| 🇨🇳 Chinese |看板区块 `打开方式` 和 `弹窗尺寸` 点击后不应该关闭 |

fix: initializer select close

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

…ables
| 🇺🇸 English |       association field data scope settings in sub-tables not taking effect in real-time    |
| 🇨🇳 Chinese |      子表格中关系字段数据范围设置未实时生效     |

fix: real-time update issue for association field data scope in sub-table

---

packages/core/client/src/block-provider/FormBlockProvider.tsx
packages/core/client/src/modules/blocks/data-blocks/form/hooks/useEditFormBlockProps.ts

Fix bug caused by #4876.
Only the Edit Form block needs to be cleared out of the defaults at the beginning.
None.
https://github.com/nocobase/nocobase/blob/819163689174b1a7b15a737863aeb28fa8826b9f/packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaInitializer.test.ts#L180-L209
| 🇺🇸 English |      Field defaults should not be cleared after submitting data on a page form     |
| 🇨🇳 Chinese |     页面表单提交数据后，不应该清空字段默认值      |

fix: default values for fields should not be cleared after submission

---

packages/core/client/src/collection-manager/interfaces/unixTimestamp.tsx
packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx
packages/core/client/src/schema-component/antd/form-item/FormItem.tsx

| 🇺🇸 English |       image style issues in rich text field    |
| 🇨🇳 Chinese |       富文本字段中的大图片导致样式撑开   |

fix: image style issues in rich text field

---

packages/core/test/src/server/mock-cluster.ts

Simplify the API of `MockCluster`.
Old:
```ts
new MockCluster({
script: 'xxx.ts',
config: {
env: {}
},
instances: 2,
plugins: [],
});
```
New
```ts
new MockCluster('xxx.ts', {
env: {}
instances: 2,
plugins: [],
});
```
As above exmaple.
| 🇺🇸 English | Change mock cluster constructor arguments |
| 🇨🇳 Chinese | 调整集群模拟类初始化参数 |

refactor(test): change mock cluster constructor arguments

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

Formula fields do not trigger calculations if they are not rendered. That's why you can't use "lazy rendering" in subforms.
- If it is a subTable, it is not lazily rendered.
close T-4889
None.
| 🇺🇸 English |      Fix the problem that the values of formula fields are not updated in real time.     |
| 🇨🇳 Chinese |     修复公式字段的值不实时更新的问题。      |

fix(subTable): ensure real-time update of formula field values

---

packages/core/client/src/collection-manager/templates/components/PresetFields.tsx
packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/collection-template/general2.test.ts

| 🇺🇸 English |   Set autoGenId default value to false when creating data tables        |
| 🇨🇳 Chinese |   创建数据表时autoGenId 默认值应该为 false     |

fix: autoGenId default value  should be false when adding collection

---

packages/core/client/src/schema-initializer/items/InitializerWithSwitch.tsx
packages/core/client/src/schema-initializer/utils.ts
packages/core/client/src/schema-settings/SchemaSettings.tsx

Fix T-4585
See code, it's very simple.
close T-4585
| 🇺🇸 English |      Form fields should be cleared of their default values immediately after they are deleted.     |
| 🇨🇳 Chinese |     表单字段被删除后，应该立即清空其默认值。      |

fix: clear default value immediately after field deletion

---

packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx

Prevent issues with URL changes when clicking on a association field that is not configured for a popup window.
- If the Schema of the current association field contains a properties attribute, it indicates that a popup has already been configured.
close T-4794
| 🇺🇸 English |        When a  association field is not configured with a popup window, the URL should not change when clicked.   |
| 🇨🇳 Chinese |     关系字段未配置弹窗时，点击后 URL 不应该发生变化。      |

fix: prevent URL change on clicking unconfigured association field

---

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
packages/core/client/src/schema-component/antd/select/demos/new-demos/null-option.tsx
packages/core/client/src/schema-component/antd/select/utils.ts

Option with `null` value could not be shown in read-pretty mode.
In some data, the options will contain null value. But by default the option with null value could not be shown in read-pretty mode.
None.
| 🇺🇸 English | Allow select to show null option as tag in read pretty mode if configured |
| 🇨🇳 Chinese | Select 组件在阅读友好模式下可以显示 value 为 null 的选项标签。 |

refactor(client): allow select to show null option as tag in read pretty mode if configured

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-date-field.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts

Fix error occurs in schedule event on date field.
In configuration panel of schedule event on date field, with repeat option, and by default the "Ends on" option is set to empty object (`{}`). This cause error when related data record creating/updating.
None.
None.
| 🇺🇸 English | Fix schedule event on date field. |
| 🇨🇳 Chinese | 修复基于时间字段定时任务在未设置结束时间时的错误。 |

fix(plugin-workflow): fix schedule event on date field

---

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/collection.tsx
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts

Condition configuration in destroy collection event not works and makes user confuse.
Condition is implemented as a re-querying after event in before versions, which can not work with destroy event.
So we hide the condition configuration for now.
None.
| 🇺🇸 English | Hide condition configuration in destroy collection event. |
| 🇨🇳 Chinese | 在数据表事件配置中，隐藏删除事件的条件配置项。 |

fix(plugin-workflow): hide condition configuration in destroy collection event

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Fix minors bug in `Variable.Input` component.
1. `undefined` key appears in constant options.
2. `undefined` constant component.
None.
None.
| 🇺🇸 English | Fix constant type in `Variable.Input`. |
| 🇨🇳 Chinese | 修复变量选择组件中常量类型的问题。 |

fix(client): fix variable input value type

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/client/ActionTrigger.tsx
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx

The workflow binding settings missed when migrated to new button settings.
Delete action button should be able to bind workflows.
None.
None.
| 🇺🇸 English | Fix delete action button to bind pre-action workflow. |
| 🇨🇳 Chinese | 修复删除按钮无法绑定操作前事件的问题。 |

fix(plugin-workflow): fix delete action button to bind pre-action workflow

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/executions.test.ts

Admin role with workflow plugin permission can not delete executions, API report "No permissions".
Permission of deleting executions is not included in snippets.
[Admin清空-工作流-执行历史提示失败无权限](https://forum.nocobase.com/t/admin/78)
None.
| 🇺🇸 English | Fix admin role with workflow plugin permission can not delete executions. |
| 🇨🇳 Chinese | 修复 admin 角色拥有工作流插件权限的情况下无法删除执行记录的问题。 |

fix(plugin-workflow): fix admin role with workflow plugin permission can not delete executions

---

packages/core/client/src/schema-component/antd/filter/FilterAction.tsx
packages/core/client/src/schema-component/antd/filter/__e2e__/FilterAction.test.ts
packages/core/client/src/schema-component/antd/filter/__e2e__/templates.ts

This is a bug.
Use `DatePickerProvider` in FilterAction component to set utc to false.
close T-4935
see: https://github.com/nocobase/nocobase/blob/7dcaa3f32af830eeca8531b60a951b36916ecbb7/packages/core/client/src/schema-component/antd/filter/__e2e__/FilterAction.test.ts#L14-L32
| 🇺🇸 English |       the date string in filter should not be UTC.    |
| 🇨🇳 Chinese |     筛选条件中的日期不应该带上时区。      |

fix: the date string in filter should not be UTC

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx

Validation on formula expression with variable, for example: `SUBSTITUTE({{$context.data.title}}, '1', '2')` will not pass, although it is correctly.
The validation is based on replacement variables to number `1`. Number type in some function will cause error. So try to use string `"1"` as replacement to adapt more scenario.
None.
None.
| 🇺🇸 English | Fix formula validation for expression. |
| 🇨🇳 Chinese | 修复计算表达式预验证错误。 |

fix(plugin-workflow): fix formula validation for expression

---

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts

Collection events trigger in uncommitted transaction will cause data inconformity.
1. Create a async collection event on new record created.
2. Create a destroy node to delete the newly created record.
3. Import some records to the collection to trigger the workflow.
The imported data remains not deleted by workflow.
None.
None.
| 🇺🇸 English | Fix collection event triggers in async mode before transaction committed. |
| 🇨🇳 Chinese | 修复数据表事件在事务未提交之前就触发的问题。 |

fix(plugin-workflow): fix collection event triggers in async mode before transaction committed

---

packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowTodo.tsx
packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/SchemaConfig.tsx
packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/forms/update.tsx

Assign field value not works in action buttons of manual node.
1. Support assign field value for all action buttons.
2. Fix assign field value in submit function.
None.
| 🇺🇸 English | Fix assign field value for all action buttons of manual node. |
| 🇨🇳 Chinese | 修复人工节点中所有操作按钮的字段赋值配置。 |

fix(plugin-workflow-manual): fix assign field value for all action buttons of manual node

---

packages/core/client/src/collection-manager/interfaces/input.ts

| 🇺🇸 English | Remove leading and trailing spaces from the string during mandatory field validation  |
| 🇨🇳 Chinese |  字段必填验证时过滤掉字符串的两端空格  |

fix: remove leading and trailing spaces from the string during mandatory field validation

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-date-field.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts

Fix the issue where scheduled event based on date fields could still be triggered after being disabled.
1. Create a schedule event on date field mode.
2. Set start from option to `createdAt` field of a collection.
3. Enable the workflow.
4. Trigger it by creating a record for 1st time.
5. Disable the workflow.
6. Trigger it by creating a record for 2nd time.
None.
None.
| 🇺🇸 English | Fix the issue where scheduled tasks based on time fields could still be triggered after being disabled. |
| 🇨🇳 Chinese | 修复基于时间字段的定时任务禁用后仍能触发的问题。 |

fix(plugin-workflow): fix event key in date field schedule mode

---

packages/core/client/src/schema-component/common/utils/uitls.tsx
packages/plugins/@nocobase/plugin-block-iframe/src/client/schemaSettings.tsx

| 🇺🇸 English |       Iframe HTML Template engine is missing default value    |
| 🇨🇳 Chinese |   iframe HTML 模版引擎 缺失默认值        |

fix:  iframe HTML Template engine default value

---

packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx

| 🇺🇸 English |      allowMultiple should not appear on read-only association fields     |
| 🇨🇳 Chinese |     允许添加/关联多条 配置项不应出现在只读关系字段上      |

fix: allowMultiple should not appear on read-only association fields

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Before null option and field component (children) both supported, clear selected variable will show original field component.
But after null option added, it becomes null component, should do another select to constant component.
1. Use assign field value and add some field.
2. Select some variable available.
3. Clear the variable to input constant.
None.
None.
| 🇺🇸 English | Show original field input component in variable component after cleared variable selected. |
| 🇨🇳 Chinese | 在变量组件中删除所选变量后，恢复默认的常量输入组件。 |

fix(client): show original field input component after cleared variable

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

…eme style without adaptation
| 🇺🇸 English |     compact theme styling issue with quick add button for association fields in form      |
| 🇨🇳 Chinese |     表单中关系字段快捷添加按钮在紧凑主题样式缺陷      |

fix:compact theme styling issue with quick add button for association fields in form

---

packages/core/client/src/schema-settings/VariableInput/hooks/useBaseVariable.tsx
packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts

Since you can't get the field information from the chinaRegions collection, you can't get children for the chinaRegions field in the variable menu. As a result, the chinaRegions field can only be displayed as a normal option, not as a submenu.
if the field is a chinaRegions, return a normal option.
close T-5011
None.
| 🇺🇸 English |      Should not disable the  chinaRegions field in the variable menu.    |
| 🇨🇳 Chinese |     修复在变量菜单中选中行政区划字段后，该字段变为禁用状态的问题。     |

fix(variable): the chinaRegions field should not be a submenu

---

packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/AggregateInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/AggregateInstruction.ts

Aggregate functions are only implemented on the data source of type database.
Data sources should be filtered and only reserved of type database.
None.
None.
| 🇺🇸 English | Limit aggregate instruction to only work on db data source. |
| 🇨🇳 Chinese | 限制聚合查询节点仅支持在数据库类型的数据源上使用。 |

fix(plugin-workflow-aggregate): limit aggregate instruction to only work on db data source

---

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/schemas/scopes.tsx

… data scope configuration
| 🇺🇸 English |   disable edit and delete button for all records and own record in data scope configuration        |
| 🇨🇳 Chinese |   权限配置中的数据范围，所有记录和自己的记录禁用编辑和删除按钮        |

fix: disable edit and delete button for all records and own record in data scope configuration

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/core/client/src/schema-component/antd/variable/index.en-US.md
packages/core/client/src/schema-component/antd/variable/index.md

When using `Variable.Input`, whether to parse a date string is hard to decide. So we add an option for developers to determine it selves.
Could use this:
```diff
<Variable.Input
+   parseOptions={{
+       stringToDate: true
+   }}
/>
```
None.
| 🇺🇸 English | Add parse options for variable input. |
| 🇨🇳 Chinese | 对变量组件新增值解析选项。 |
| 🇺🇸 English | [Variable.Input](https://client.docs.nocobase.com/components/variable/#variableinput) |
| 🇨🇳 Chinese | [变量选择器](https://client.docs-cn.nocobase.com/components/variable#variableinput) |

feat(client): add parse options for variable input

---

packages/core/client/src/data-source/collection/Collection.ts
packages/core/client/src/modules/actions/add-new/__e2e__/inherit.test.ts
packages/core/client/src/modules/actions/add-new/__e2e__/templates.ts
packages/core/client/src/schema-component/antd/page/PagePopups.tsx
packages/core/client/src/schema-component/antd/page/pagePopupUtils.tsx
packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx

Fix BUG.
#4706 assumed that all buttons would have only one collection associated with them. 
However, the "Add new" button may be associated with more than one collection at the same time (e.g., a block in an inheritance collection), and it is not possible to save the collection parameter to the button Schema's "x-action-context" of the button's schema. This is because "x-action-context" can only hold one colelction.
The solution is to save the collection in the URL.
https://github.com/nocobase/nocobase/pull/4706
close T-5084
See E2E.
| 🇺🇸 English |      Fix 'Add new' button for inherited blocks.     |
| 🇨🇳 Chinese |     修复继承区块的添加按钮。      |

fix(inherit): fix 'Add new' button for inherited collectons

---

packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/belongs-to-array-field.test.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/hooks/create-foreign-key.ts

When creating a m2m array field, the name of the foreign key must not be the same as the name of the field.
Add naming collision check.
| 🇺🇸 English | Add naming collision check between the foreign key and field name when creating m2m array fields |
| 🇨🇳 Chinese | 创建多对多（数组）字段时，增加字段和外键的命名冲突检查          |

fix(database): check naming collision when creating m2m array fields

---

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx

| 🇺🇸 English |      html rendering in markdown block      |
| 🇨🇳 Chinese |    html样式在markdown中不生效       |

fix: html syntax rendering in markdown block

---

packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/Edit.tsx

The default upload file size limit of Vditor is 10MB.
Set the maximum size of upload file in Markdown (Vditor) field to the same size limit as file storage.
| 🇺🇸 English | Set the maximum size of upload file in Markdown (Vditor) field to the same size limit as file storage. |
| 🇨🇳 Chinese | 将 Markdown (Vditor) 字段的上传文件体积限制设置为文件存储器支持的文件体积上限。           |

fix: increase the upload file size limit of field-markdown-vditor

---

packages/core/client/src/application/schema-settings/utils/createModalSettingsItem.tsx
packages/core/client/src/modules/actions/link/customizeLinkActionSettings.tsx
packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/types/MobileTabBar.Link/SchemaSettingsActionLinkItem.tsx
packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/types/MobileTabBar.Link/settings.tsx

Fix BUG.
The configuration data of the mobile menu is not stored in the Schema, which is different from the desktop. Therefore, it is better not to reuse the desktop components here on mobile to avoid the increase of code complexity.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/tabs/fmvu0hrcp8m/popups/z7tn73yxs73/filterbytk/40
None.
| 🇺🇸 English |      Fixed an issue where the Link button could not be edited properly.     |
| 🇨🇳 Chinese |     修复不能正常编辑 Link 按钮的问题。      |

fix(mobile): fix 'Edit link' setting

---

packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/DynamicCalculation.tsx
packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow/src/client/AddButton.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx

Calculation nodes grows and should not be put in "Control" group.
Move "Calculation" and "Dynamic expression calculation" node into new group named "Calculation".
None.
| 🇺🇸 English | Add "Calculation" nodes group. |
| 🇨🇳 Chinese | 增加“运算”节点组。 |

refactor(plugin-workflow): add calculation nodes group

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/antd/components/Statistic.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/antd/statistic.ts

Allow to set a fixed link for statistic charts.
https://github.com/user-attachments/assets/fb7a43de-9e34-45b4-9db4-86babddfb8ff
| 🇺🇸 English | Allow to set a fixed link for statistic chart       |
| 🇨🇳 Chinese | 支持给统计数值图设置一个固定连接          |

feat(data-vi): allow to set link for statistic chart

---

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx

| 🇺🇸 English |   the selected data in the sub table is overwritten by default values        |
| 🇨🇳 Chinese |    子表格中选过来的数据被默认值覆盖       |

fix: the selected data in the sub table is overwritten by default values

---

packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockProps.tsx

排序：
setting设置的排序是默认排序，表头那里是临时的，页面刷新之后就会回到默认值，点了表头就按表头的字段排序，不传seting的sort
表头 number 点第一下：number 字段正序*
点第二下：number 字段倒序** **
点第三下：按 settings 默认值来* ** ** 如果这时候同时翻页了，sort 信息要保留
只有刷新页面表头的sort才会去掉
| 🇺🇸 English |   sorting of Table block data        |
| 🇨🇳 Chinese |     表格区块的排序功能优化      |

refactor: sorting of Table block data

---

packages/core/client/src/application/hooks/index.ts
packages/core/client/src/application/hooks/useRouterBasename.ts
packages/core/client/src/block-provider/hooks/index.ts
packages/core/client/src/schema-component/antd/page/Page.tsx
packages/core/client/src/schema-component/antd/page/PagePopups.tsx
packages/core/client/src/schema-component/antd/page/__tests__/page.test.tsx

Fix BUG.
When using the `navigate` method to switch pages, the `basename` of the router should be removed.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/tabs/fmvu0hrcp8m/popups/z7tn73yxs73/filterbytk/109
None.
| 🇺🇸 English |       Fix the problem that the tab page cannot be switched properly.    |
| 🇨🇳 Chinese |      修复无法正常切换 tab 页的问题。     |

fix: resolve tab switching issue

---

packages/core/client/src/index.ts
packages/core/client/src/modules/actions/add-child/CreateChildInitializer.tsx
packages/core/client/src/modules/actions/add-new/CreateActionInitializer.tsx
packages/core/client/src/modules/actions/view-edit-popup/PopupActionInitializer.tsx
packages/core/client/src/modules/actions/view-edit-popup/UpdateActionInitializer.tsx
packages/core/client/src/modules/actions/view-edit-popup/ViewActionInitializer.tsx
packages/core/client/src/modules/popup/PopupContextProvider.tsx
packages/core/client/src/modules/popup/usePopupUtils.ts
packages/core/client/src/schema-component/antd/action/Action.tsx
packages/core/client/src/schema-component/antd/association-field/InternalTag.tsx
packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
packages/core/client/src/schema-component/antd/page/PagePopups.tsx
packages/core/client/src/schema-component/antd/page/__tests__/PagePopups.test.tsx
packages/core/client/src/schema-component/antd/page/pagePopupUtils.tsx
packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.Card.tsx
packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.tsx
packages/plugins/@nocobase/plugin-kanban/src/client/__e2e__/templates.ts
packages/plugins/@nocobase/plugin-kanban/src/client/__e2e__/url.test.ts

To enable the ability to open the contents of a Kanban board using a URL.
1. Refactored Kanban to reduce the context dependency of Kanban popups.
2. Special handling of Kanban's popups to accommodate the popup logic in the core.
https://tasks.aliyun.nocobase.com/admin/sufipoe9knc/popups/d2ft67lc839/filterbytk/3/popups/k76nupt79wc/filterbytk/68
| 🇺🇸 English |      Supports opening content in a Kanban board directly from a URL.     |
| 🇨🇳 Chinese |     支持通过 URL 直接打开看板中的内容。      |

feat(kanban): add support for opening via URL

---

packages/core/client/src/schema-component/antd/upload/shared.ts

Allow `.ico` and other image file could be show as original image in upload component.
1. Upload an `.ico` file to logo in system settings page.
None.
None.
| 🇺🇸 English | Fix image file preview in upload list. |
| 🇨🇳 Chinese | 修复图片类型在上传组件中的预览问题。 |

fix(client): fix upload preview image

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/bar.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/dualAxes.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/pie.ts

Forgot to add size settings for some chart types.
Add size settings for pie, bar and dualAxes.
| 🇺🇸 English | Add size settings for chart types: pie, bar and dualAxes          |
| 🇨🇳 Chinese | 给以下图表类型添加尺寸设置：饼图、条形图和双轴图           |

fix(data-vi): add size settings for pie, bar and dualAxes

---

packages/core/client/src/filter-provider/__tests__/utiles.test.ts
packages/core/client/src/filter-provider/utils.ts
packages/core/client/src/schema-component/antd/filter/__tests__/useFilterActionProps.test.ts

Fix BUG.
You should to see the code, only one line changes.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/166
None.
| 🇺🇸 English |      Fix an issue where filter blocks could not filter 0 values.     |
| 🇨🇳 Chinese |     修复筛选区块无法筛选 0 值的问题。      |

fix(filter): should not filter out zero

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/__tests__/utils.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/utils.ts

The tooltips of charts can not map enum labels when the field values are integers.
When mapping enum labels for chart tooltips, attempt to transform the values to string.
| 🇺🇸 English | Fix the issue of mapping labels when the enum field values are integers in charts.        |
| 🇨🇳 Chinese | 修复图表中枚举字段值为整数时无法映射成枚举标签的问题          |

fix(data-vi): allow to map integer enum value

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Allow to configure properties for constant component in `Variable.Input`.
```diff
{
type: 'string',
'x-component': 'Variable.Input',
'x-compoennt-props': {
useTypedConstant: [
'string',
-     'number',
+     [
+       'number',
+       {
+         precision: 0,
+       }
+     ]
+   ]
}
}
```
None.
None.
| 🇺🇸 English | Add constant props api for variable input. |
| 🇨🇳 Chinese | 为变量组件添加使用基于类型常量时组件的 `props` API |

feat(client): add constant props api for variable input

---

packages/plugins/@nocobase/plugin-workflow-parallel/src/server/ParallelInstruction.ts

Fix dead lock when using parallel node in mysql.
```
2024-08-23 09:55:32 [info]  execution of workflow 6 created as 14        
2024-08-23 09:55:32 [info]  execution (14) starting...                   
2024-08-23 09:55:32 [info]  execution (14) run instruction [parallel] for node (21) 
2024-08-23 09:55:32 [debug] config of node                               data={"mode":"any"}
2024-08-23 09:55:32 [info]  execution (14) run instruction [condition] for node (22) 
2024-08-23 09:55:32 [debug] config of node                               data={"engine":"basic","calculation":{"group":{"type":"and","calculations":[{"operands":["{{$context.data.id}}","10000"],"calculator":"equal"}]}},"rejectOnFalse":true}
2024-08-23 09:55:32 [info]  execution (14) run instruction [condition] for node (22) finished …
```

fix(plugin-workflow-parallel): fix missed transaction causing dead lock in mysql

---

packages/plugins/@nocobase/plugin-workflow-mailer/src/client/MailerInstruction.tsx

Allow host fields of mailer node to use variables.
None.
| 🇺🇸 English | Allow to use variables for host fields of mailer node configuration. |
| 🇨🇳 Chinese | 支持邮件节点中主机相关字段使用变量。 |

feat(plugin-workflow-mailer): add variables

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Show constant options correctly when field names configured.
1. Add custom request action for a record.
2. Open configuration of the custom request action button.
3. Add a variable in params.
4. Try to select typed constant to input.
None.
None.
| 🇺🇸 English | Fix field names of variable input. |
| 🇨🇳 Chinese | 修复变量组件的字段名称问题。 |

fix(client): fix field names of variable input

---

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-edit/bulkEditForm.test.ts
packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/component/BulkEditField.tsx

| 🇺🇸 English |    bulk edit set remainsTheSame as default value       |
| 🇨🇳 Chinese |      批量更新，默认值应该是“保持不变”     |

refactor:  set remainsTheSame as the default value for field editing in bulk editing action

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

以下为修改后的效果
| 🇺🇸 English |    The data scope of association field in sub form should be linked. when switching option, the linked association field should be cleared      |
| 🇨🇳 Chinese |      子表单中关系字段数据范围联动，切换选项时，联动的关系字段清空选项     |

fix: association select data scope linkage should be  supported in  sub-form

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

| 🇺🇸 English |     association select data scope linkage should support edit form      |
| 🇨🇳 Chinese |     在编辑表单中， 关系字段的数据范围联动,选项切换时，目标关系字段应清空值而不是显示为初始值     |

fix: association select data scope linkage should be supported in the edit form

---

packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts

… to number
The values of decimal fields in chart query are not casted into number type.
Add `decimal` type to the auto cast type list.
| 🇺🇸 English | Fixed the issue where `decimal` field values in chart query results are not cast into number type automatically          |
| 🇨🇳 Chinese | 修复图表查询结果中 `decimal` 字段值没有自动转换成数字类型的问题          |

fix(data-vi): cast the values of decimal fields from type string to number

---

packages/core/client/src/modules/fields/component/Picker/TableSelectorInitializers.tsx

…ot 'Add Text'
| 🇺🇸 English |     issue in  data selector other block  should display  Markdown, not 'Add Text'        |
| 🇨🇳 Chinese | 关系的数据选择器弹窗中其他区块应显示 Markdown，不是 Add Text      |

fix: issue in  data selector other block  should display  Markdown, not 'Add Text'

---

packages/core/client/src/block-provider/hooks/index.ts
packages/core/client/src/schema-component/antd/association-field/hooks.ts

Fix bug.
In the Association field of the Collapse block, there is no parsing of variables in the data scope. So, parsing the variables is fine.
https://tasks.aliyun.nocobase.com/admin/ugmnj2ycfgg/popups/1qlw5c38t3b/puid/dz42x7ffr7i/filterbytk/271
close #5119 
None.
| 🇺🇸 English |       Fix an issue where using variables in data scope reported an error.    |
| 🇨🇳 Chinese |      修复数据范围中使用变量报错的问题。     |

fix(Collapse): resolve error when using variables in data scope

---

packages/core/client/src/route-switch/antd/admin-layout/index.tsx

If no logo is uploaded, the system title will be displayed.
| 🇺🇸 English |    Display system title when logo is missing.       |
| 🇨🇳 Chinese |    当缺少 logo 时，显示系统标题。       |

feat(client): display system title when logo is missing

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/__tests__/utils.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/utils.ts

When aggregating select fields, it got a option label instead of a numeric value.
When aggregating select fields, if the result matches one of the option values coincidentally, it returns the option label instead of the correct result value.
https://forum.nocobase.com/t/topic/693
https://forum.nocobase.com/t/topic/593
| 🇺🇸 English | Fixed the issue of getting wrong value when aggregating select fields            |
| 🇨🇳 Chinese | 修复聚合选项字段时，获取结果不正确的问题          |

fix(data-vi): issue of getting wrong value when aggregating select fields

---

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/schemas/dataSourceTable.ts

Will improve performance when there are many datasource tables in roles/permission page
Before the fix, this warning will be shown in the browser's console, this kind of warning indicate pential performance issue.
| 🇺🇸 English | Fixed incorrect `rowKey` of the datasource table in `Users & Permissions` page          |
| 🇨🇳 Chinese |修复`用户和权限`设置页面中数据源表格`rowKey`不正确问题 |

fix: incorrect rowkey in datasource permission table

---

packages/plugins/@nocobase/plugin-users/src/client/schemas/users.ts

The default phone validation is only applicable for China mainland.
Remove phone validation when editing user phones in user management.
| 🇺🇸 English | Remove phone format validation when editing user phones in user management            |
| 🇨🇳 Chinese | 移除在用户管理中编辑用户资料时的手机号格式验证          |

fix(users): remove phone validation when editing user phones in user management

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json

Trigger type column showing wrong text after new workflow created.
Also add hint on job button in execution history.
None.
| 🇺🇸 English | Fix trigger type column showing wrong text after new workflow created |
| 🇨🇳 Chinese | 修复创建工作流后类型列展示错误文字的问题 |

fix(plugin-workflow): fix trigger type column showing wrong text after new workflow created

---

packages/plugins/@nocobase/plugin-field-m2m-array/src/server/belongs-to-array-field.ts

It occurred error "ARRAY is missing type definition for its values." when setting uid field as target key for a many to many (array) field.
It should map `uid` field type to `string`.
| 🇺🇸 English | Fix the error where setting a field of `uid` type as target key for a many to many (array) field |
| 🇨🇳 Chinese | 修复将 `uid` 类型的字段设置为多对多（数组）字段的目标键时出现的报错          |

fix(mbm): issue of setting uid target key for m2m array field

---

packages/core/client/src/block-provider/DetailsBlockProvider.tsx

Fix bug.
The issue occurs in the following two lines of code:
```ts
ctx.form.setInitialValues(data || {});
ctx.form.setValues(data || {});
```
Calling these two lines simultaneously may cause an internal infinite loop problem in Formily. The solution is to remove the second line: `ctx.form.setValues(data || {});`.
The reason for keeping `ctx.form.setInitialValues(data || {});` is that this part is mainly responsible for initializing the form values of the details block, so it's more appropriate to only set its initial values.
None.
| 🇺🇸 English |       Fix the "Maximum call stack size exceeded" error that occurs in the details block    |
| 🇨🇳 Chinese |      修复在详情区块中出现的 “Maximum call stack size exceeded” 错误     |

fix(defails): avoid infinite loop

---

packages/plugins/@nocobase/plugin-field-m2m-array/src/server/hooks/before-destroy-foreign-key.ts

It occurred error when deleting a collection contains many to many (array) fields.
It should check if the collection exists when triggering `beforeDestoryForeignKey` hook of many to many (array) fields.
| 🇺🇸 English |  Fix the error when deleting a collection contains m2m array fields          |
| 🇨🇳 Chinese | 修复删除包含多对多（数组）字段的数据表时出现的错误          |

fix(mbm): fix the error when deleting a collection contains m2m array fields

---

packages/core/client/src/modules/popup/__e2e__/subPage.test.ts
packages/core/client/src/schema-component/antd/page/pagePopupUtils.tsx
packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowManualProvider.tsx

Fix bug.
Previously, `navigate(-1)` was used to close the popup. If the previous history record still displayed the current popup, calling `closePopup` would not correctly close the popup. Although the popup was indeed closed, it would be found that it couldn't be opened the next time you tried to open the popup.
https://github.com/user-attachments/assets/98cbc279-c22a-4d2b-8be3-de055b3661db
Now, the `navigate(-1)` approach has been removed to prevent this situation from occurring:
https://github.com/user-attachments/assets/71228283-4247-4d89-814f-69fc299b77bd
| 🇺🇸 English |       Fix URL anomalies caused by using popups together with Link buttons    |
| 🇨🇳 Chinese |      修复因弹窗与 Link 按钮一起使用，所导致的 URL 异常的问题     |

fix(popup): fix URL anomalies caused by using popups together with Link buttons

---

packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts

To support XML and plain text in request content-type.
None.
None.
None.
| 🇺🇸 English | Add XML and text to `Content-Type` support list of request node. |
| 🇨🇳 Chinese | 对请求节点的 `Content-Type` 配置增加 XML 和简单文本类型支持。 |

feat(plugin-workflow-request): add xml and text to content type select

---

packages/plugins/@nocobase/plugin-action-custom-request/src/client/components/CustomRequestActionDesigner.tsx
packages/plugins/@nocobase/plugin-action-custom-request/src/client/hooks/useCustomRequestVariableOptions.ts
packages/plugins/@nocobase/plugin-action-custom-request/src/server/actions/send.ts

The `API token` variable is also required when configuring custom requests.
| 🇺🇸 English |      Support for API token variables in the "Custom Request Button" configuration     |
| 🇨🇳 Chinese |     自定义请求按钮的配置中，支持使用 API token 变量      |
| 🇺🇸 English |  [Custom request](https://docs.nocobase.com/handbook/action-custom-request)    |
| 🇨🇳 Chinese |  [自定义请求-变量](https://docs-cn.nocobase.com/handbook/action-custom-request#%E5%8F%98%E9%87%8F)  |

feat(custom-request): add support for API token variable

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

before
after
| 🇺🇸 English |      column width issue with scroll.y when table has no data     |
| 🇨🇳 Chinese |     表格没有数据时且设置了区块高度时无法设置列宽      |

fix: column width issue with scroll.y when table has no data

---

packages/core/client/src/collection-manager/interfaces/uuid.ts
packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx

| 🇺🇸 English |      Selecting options with the data record selector has no effect on multi association fields     |
| 🇨🇳 Chinese |     对多关系字段使用数据选择器勾选无效果      |

fix:  issue with recordPicker rowSelection 

---

packages/core/evaluators/src/utils/__tests__/mathjs.test.ts
packages/core/evaluators/src/utils/mathjs.ts

Fix error caused by `Matrix` type from mathjs.
Transform any `Matrix` output to common `Array`.
None.
None.
| 🇺🇸 English | Fix error caused by `Matrix` type from mathjs |
| 🇨🇳 Chinese | 修复 Math.js 计算输出矩阵类型导致的问题 |

fix(evaluators): fix mathjs matrix output type

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

This problem is caused by the table cell using lazy rendering. The solution is to not use lazy rendering for the first 20 rows of the table. Beginning with row 21, use lazy rendering.
For each line, a blank space will be displayed first, followed by the content:
After the fix:
| 🇺🇸 English |      Fix the problem of blank rows at the beginning of a table block     |
| 🇨🇳 Chinese |     修复表格区块在一开始出现空白行的问题      |

fix(Table): prevent empty lines at the beginning

---

packages/core/client/src/acl/Configuration/StrategyActions.tsx
packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/StrategyActions.tsx

Before the fix:
| 🇺🇸 English |Fix incorrect `rowKey` of the `General action permissions table` in Users & Permissions page|
| 🇨🇳 Chinese |修复用户和权限设置页面中`通用操作权限表格`的`rowKey`不正确问题|

fix: missing rowkey in actions permissions table

---

packages/core/client/src/block-provider/hooks/index.ts
packages/core/client/src/modules/blocks/data-blocks/form/__tests__/fieldSettingsFormItem.test.tsx
packages/core/client/src/modules/blocks/filter-blocks/collapse/filterCollapseItemFieldSettings.ts
packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.Item.tsx
packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.tsx
packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/core/client/src/schema-component/antd/variable/style.ts
packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx
packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx

| 🇺🇸 English |      Support setting default values for fields in the Collapse block. Fields with default values will automatically trigger a filtering action on initial render     |
| 🇨🇳 Chinese |     支持在折叠面板区块中为字段设置默认值，有默认值的字段会在首次渲染时自动触发一次筛选动作      |

feat(Collapse): support to set default value

---

packages/core/client/src/schema-component/common/utils/uitls.tsx

| 🇺🇸 English |  markdown report error with using `#each` in handlebars         |
| 🇨🇳 Chinese |    markdown 的handlebars 模板使用#each 渲染数组数据时数据没有正常显示 |

fix: markdown report error with using `#each` 

---

packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts
packages/plugins/@nocobase/plugin-action-export/src/server/xlsx-exporter.ts

I would like to add some extral logic when rendering cell in export action. But this can't be done for the fields in the referenced table due to this bug.
| 🇺🇸 English |Fix fields from assicated tables are not processed by the field interface|
| 🇨🇳 Chinese |修复导出操作时，关联表中的字段未执行interface渲染逻辑|

fix: during export action, fields from referenced tables are not rendered by field interface

---

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts

When processing node type not registered to workflow, there will be error. Need to track this error.
```
{"level":"error","message":"execution (945) error: Cannot read properties of undefined (reading 'run') Cannot read properties of undefined (reading 'run')","stack":"TypeError: Cannot read properties of undefined (reading 'run')
at Processor.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:195:28)
at Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:188:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:136:7)
at async PluginWorkflowServer.process …
```

fix(plugin-workflow): track error when instruction not exist

---

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts

Some field deleted but configured in workflow changed fields before, will cause error when triggering.
1. Add collection workflow which triggers on record update.
2. Add a field to changed fields.
3. Remove the field from collection configuration.
4. Trigger the workflow.
None.
None.
| 🇺🇸 English | fix non-existed field in collection trigger causes error |
| 🇨🇳 Chinese | 修复数据表事件中发生改变的字段被删除后报错的问题 |

fix(plugin-workflow): fix non-existed field in collection trigger causes error

---

packages/core/client/src/modules/actions/save-record/customizeSaveRecordActionSettings.tsx
packages/core/client/src/modules/actions/submit/createSubmitActionSettings.tsx
packages/core/client/src/modules/actions/submit/updateSubmitActionSettings.tsx
packages/plugins/@nocobase/plugin-action-bulk-update/src/client/BulkUpdateAction.Settings.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/settings/customizeSubmitToWorkflowActionSettings.tsx

| 🇺🇸 English |    Fix missing afterSuccess configuration for the submit action     |
| 🇨🇳 Chinese |    提交按钮缺少“提交成功后”的配置项       |

fix:  missing afterSuccess configuration for the submit action

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx

Allow not to use null option in `Variable.Input`.
Add a `nullable` option for the component.
Example:
```diff
<Variable.Input
scope={yourScope}
+   nullable={false}
/>
```
None.
None.
| 🇺🇸 English | Add `nullable` option for `Variable.Input` component |
| 🇨🇳 Chinese | 为 `Variable.Input` 组件增加 `nullable` 的选项参数 |

refactor(client): add nullable option for variable input component

---

packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx

| 🇺🇸 English |      Fix the problem that the Add Block menu cannot be displayed after opening a subpage with more than 3 levels on the mobile     |
| 🇨🇳 Chinese |     修复在移动端中，打开 3 层以上子页面后，无法显示添加区块菜单的问题      |

fix(mobile): correct z-index

---

packages/core/client/src/modules/actions/__e2e__/submit/refreshData.test.ts
packages/core/client/src/modules/actions/__e2e__/submit/templates.ts
packages/core/client/src/schema-component/antd/action/context.tsx

| 🇺🇸 English |      Fix the issue of not refreshing the page block data when closing a subpage via the page menu     |
| 🇨🇳 Chinese |     修复通过页面菜单关闭子页面时，不刷新页面区块数据的问题      |

fix: refresh block data when closing sub-page by clicking page menu

---

Dockerfile.pro

fix: pg client not installed correctly in pro image

fix: pg client not installed correctly in pro image

---

packages/core/client/src/locale/zh-CN.json
packages/core/client/src/schema-component/antd/upload/Upload.tsx
packages/core/client/src/schema-component/antd/upload/index.ts
packages/core/client/src/schema-component/antd/upload/shared.ts

To make file previewer to be extensible.
Example for video file:
```tsx
import { Plugin, attachmentFileTypes } from '@nocobase/client';
class MyPlugin extends Plugin {
load() {
attachmentFileTypes.add({
match(file) {
return file.name.endsWith('.mp4');
},
Previewer({ index, list, onSwitchIndex }) {
const { t } = useTranslation();
const onClose = useCallback(() => {
onSwitchIndex(null);
}, [onSwitchIndex]);
return (
<Modal
open={index != null}
title={list[index].title}
onCancel={onClose}
footer={[
<Button key="close" onClick={onClose} style={{ textTransform: 'capitalize' }}>
{t('Close')}
</Button>,
]}
width={'85vw'}
centered={true}
>
<video
src={list[index].url}
controls
style={{
width: '100%',
height: '100%',
}}
/>
</Modal>
);
},
});
}
}
export default MyPlugin;
```
#5230.
| Language   | …

refactor(client): add attachment file type registry

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Fix page crash when input boolean constant in `Variable.Input` component.
| 🇺🇸 English | fix page crash when input boolean constant in `Variable.Input` component |
| 🇨🇳 Chinese | 修复变量组件中选择输入布尔值常量导致页面崩溃的问题 |

fix(client): boolean type crash in variable input

---

packages/core/client/src/data-source/data-block/DataBlockProvider.tsx
packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/FormBlockProvider.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/components/AssignedFieldsFormSchemaConfig.tsx

Fix block crash in field configuration of create/update node.
1. Add a create/update node to a workflow.
2. Select a collection with association field.
3. Add an association field.
4. Try to switch its component to sub-form or others.
Involved by #5159.
None.
| 🇺🇸 English | fix switching component of association field in assigned fields caused page crash in create/update node |
| 🇨🇳 Chinese | 修复新增、更新节点中配置关系字段赋值时切换组件导致的页面崩溃 |

fix(plugin-workflow): fix field crash in block

---

packages/plugins/@nocobase/plugin-file-manager/src/client/FileStorage.tsx

Fix page crash when edit storage.
Storage configuration fields key changed, but not changed completed in code.
None.
| 🇺🇸 English | fix page crash when edit storage in file manager |
| 🇨🇳 Chinese | 修复文件管理器编辑存储引擎时的页面错误 |

fix(plugin-file-manager): fix storage configuration error

---

packages/plugins/@nocobase/plugin-action-custom-request/src/client/components/CustomRequestAction.tsx

Allow `CustomRequestAction` in `@nocobase/plugin-action-custom-request` to support `x-use-component-props` property.
| 🇺🇸 English | allow `CustomRequestAction` to support `x-use-component-props` |
| 🇨🇳 Chinese | `CustomRequestAction` 组件支持 `x-use-component-props` 配置解析 |

fix: component CustomRequestAction support x-use-component-props

---

packages/core/client/src/schema-component/antd/filter/__tests__/useOperators.test.ts
packages/core/client/src/schema-component/antd/filter/useOperators.ts

在表格区块中，operator's visible函数会生效，会过滤掉visible() 为false的operators.
然而在筛选区块中，却不支持，我们应当使其表现一致。
In the table block's filter, we are respecting the filter operator's visible function.
But in the filter block, operator's  visible will not take effect. 
I think we should make it consitent.
| 🇺🇸 English | support showing dynamic filter operators based on field's properties in filter form block |
| 🇨🇳 Chinese | 支持在筛选区块根据字段属性动态显示过滤运算符 |

feat: support field's dynamic filter operators in filter form block

---

packages/core/client/src/schema-component/antd/upload/shared.ts

Thumbnail of PDF file is not showing as placeholder by default.
1. Upload a PDF file to attachment field.
2. View the thumbnail in field items.
Involved by #5313.
None.
| 🇺🇸 English | fix wrongly thumbnail previewing when file type is not supported by default |
| 🇨🇳 Chinese | 修复上传文件中非默认支持的文件类型缩略图显示异常的问题 |

fix(client): fix wrongly thumbnail previewing when file type is not supported by default

---

packages/core/client/src/schema-component/antd/action/Action.style.ts
packages/core/client/src/schema-component/antd/action/Action.tsx

| 🇺🇸 English |   style optimization for  centering icon when action buttons use icon-only     |
| 🇨🇳 Chinese |  操作按钮单独使用图标时，图标居中         |

style: center icon when action buttons use icon-only

---

packages/core/client/src/data-source/collection/Collection.ts
packages/core/client/src/data-source/collection/CollectionManager.ts
packages/core/client/src/schema-component/antd/appends-tree-select/AppendsTreeSelect.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

| 🇺🇸 English |  Workflow node variables do not display inherited collection fields  |
| 🇨🇳 Chinese |  工作流节点变量不显示继承表字段         |

fix(workflow): workflow node variables do not display inherited collection fields 

---

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/update.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json

Need to explain why association fields are not updated in batch mode.
In batch mode of update node, only update the fields in self collection.
#5406.
| 🇺🇸 English | add association field related hint to the batch mode of update node |
| 🇨🇳 Chinese | 对更新数据节点的批量模式增加关于关系字段的提示 |

fix(plugin-workflow): fix hint of update node

---

packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts

To load more storages in file collection template configuration.
Currently, only load 20 items.
#5428.
| 🇺🇸 English | remove the 20 items limit of loading storages in file template collection configuration |
| 🇨🇳 Chinese | 移除文件表选择存储空间时仅加载 20 个的限制 |

fix(plugin-file-manager): fix storage field in template to load more storages

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/core/client/src/schema-component/antd/variable/RawTextArea.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
packages/plugins/@nocobase/plugin-workflow-request/src/server/__tests__/instruction.test.ts
packages/plugins/@nocobase/plugin-workflow-sql/src/client/SQLInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-sql/src/server/SQLInstruction.ts
packages/plugins/@nocobase/plugin-workflow-sql/src/server/__tests__/instruction.test.ts
packages/plugins/@nocobase/plugin-workflow-test/src/server/instructions.ts
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/nodes.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/nodes.ts
packages/plugins/@nocobase/plugin-workflow/src/server/instructions/index.ts

The test procedure of a workflow is a little tedious for now. To test one node, round and round workflow version duplication needs to be created and triggered.
* Add a global test button for nodes (which implemented).
* Make HTTP request node and SQL action node testable first.
* Also add the consolidated API for nodes to add test function.
None.
| 🇺🇸 English | Add test run button for workflow nodes, and API to implement the test function |
| 🇨🇳 Chinese | 为工作流的节点增加测试执行按钮，及实现测试功能的接口 |

feat(plugin-workflow): add test run for nodes

---

packages/core/client/src/modules/blocks/data-blocks/table/tableColumnSettings.tsx

| 🇺🇸 English |       allow table column title to be reset to default    |
| 🇨🇳 Chinese |    表格列标题一旦自定义之后，清空后恢复默认值       |

fix: allow table column title to be reset to default

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

…e in nested sub-table
| 🇺🇸 English |   Fix data clearing bug when selecting association data with data scope in nested sub-tables        |
| 🇨🇳 Chinese |   多层关系下的子表格中关系字段设置数据范围后，选择关系数据后其他行记录被清空        |

fix: data clearing bug when selecting association data with data scope in nested sub-tables

---

packages/core/client/src/schema-component/antd/table-v2/Table.tsx

The background color of table selected row is not same as Ant design component as default.
| 🇺🇸 English | fix selected background color of table row |
| 🇨🇳 Chinese | 修复表格行选中时的背景颜色 |

fix(client): fix selected background color of table row

---

packages/plugins/@nocobase/plugin-file-manager/src/client/hooks/useStorageRules.ts

Reduce useless hooks calling backend API causing performance issue.
Attachment field needs rules from storage when editable. But it is not needed in read-pretty mode.
| 🇺🇸 English | fix calling storage rule hook on read-pretty fields |
| 🇨🇳 Chinese | 屏蔽阅读模式下附件字段对存储规则不必要的查询 |

fix(plugin-file-manager): fix calling storage rule hook on read-pretty fields

---

packages/core/client/src/collection-manager/interfaces/id.ts
packages/core/client/src/collection-manager/interfaces/nanoid.ts
packages/core/client/src/collection-manager/interfaces/uuid.ts

| 🇺🇸 English |      adjust supported availableTypes for uuid, nano, and id to exclude string     |
| 🇨🇳 Chinese |     调整 interface uuid、 nano、 id支持的数据类型 ，不应支持string     |

fix: adjust supported availableTypes for uuid, nano, and id to exclude string

---

packages/plugins/@nocobase/plugin-field-formula/src/client/components/Formula/Result.tsx

多层表格嵌套时，公式计算结果错误。
如图的表单，使用了多层表单/表格嵌套
3级子表格，公式配置为=3级表格的desc字段
前端实际计算时使用了2级表格的desc字段，
如果2级没有desc字段，则3级的这个公式结果会为空。
（服务端保存时使用了当前记录做计算无此问题）
涉及多层嵌套，公式字段的路径变成了类似todos.0.sub_todos.0.desc
故修改公式计算时获取scope的方法，使用全路径查找，返回最底层的sub_todos,而不是顶层的todos
| 🇨🇳 Chinese | 修复 多层表格嵌套时，公式计算结果的错误 |

fix(formula): scope calc bug if field name like task.todos.0.sub_todos.0.desc

---

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx

| 🇺🇸 English |     variable value is lost after refreshing markdown block popup      |
| 🇨🇳 Chinese |    markdown 区块弹窗刷新后变量值丢失的问题       |

fix: variable value is lost after refreshing markdown block popup

---

packages/core/client/src/schema-component/antd/grid/Grid.tsx

fix: Grid.Col displayName correct

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json

Simplify the hint of which workflows could be selected when binding to a button.
| 🇺🇸 English | Adjust hint in configuration panel of binding workflow to a button |
| 🇨🇳 Chinese | 调整绑定工作流配置面板中的提示文案 |

fix(plugin-workflow): fix locale of binding workflow on button

---

packages/core/client/src/modules/blocks/index.ts
packages/plugins/@nocobase/plugin-file-manager/src/client/hooks/useUploadFiles.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/action.test.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/collections/files.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/collections/users.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/index.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts

Fix upload and destroy file record within an association.
In a has-many block of files:
1. The uploaded file will not be associated with the parent record.
2. Can not delete a file in the block by checked rows and delete button.
| 🇺🇸 English | fix upload and destroy file record within an association block |
| 🇨🇳 Chinese | 修复文件表在关联区块内无法上传和删除记录的问题 |

fix(plugin-file-manager): fix upload and destroy file record within an association

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts

When paste content into Variable.TextArea, special white space character `\x160` appears, and makes server logic failed.
1. Create a HTTP request node in workflow.
2. Add a header item with name as "Authorization".
3. Input "Bearer " (with the normal space), then paste the correct token text content into the input box.
4. Test the request node with test button.
5. API will return a failure status due to the token not match.
| 🇺🇸 English | fix special white space appears when paste content into variable textarea caused issue |
| 🇨🇳 Chinese | 修复变量文本输入框中在粘贴时可能产生非标准空格导致服务端逻辑错误的问题 |

fix(client): fix special white space appears when paste content

---

packages/core/client/src/block-provider/FormBlockProvider.tsx

| 🇺🇸 English |      In non-config mode, display only the current collection  in the edit form.     |
| 🇨🇳 Chinese |      在非配置状态下，编辑表单应只显示本表区块     |

fix: limit editing to current collection form block  in non-config mode

---

packages/core/server/src/application.ts

| 🇺🇸 English |   App's afterLoad event wasn't triggered after installation   |
| 🇨🇳 Chinese |   应用安装后未触发 app 的 afterLoad 事件  |

fix: app's afterLoad event wasn't triggered after installation

---

packages/core/client/src/variables/utils/getAction.tsx
packages/core/database/src/operators/string.ts

| 🇺🇸 English | Fix the issue where string operators "contains" and "does not contain do not properly handle `null` values |
| 🇨🇳 Chinese | 修复字符串操作符”包含“和”不包含“没有正确处理 `null` 值的问题          |

fix(client): string operators "contains/does not contains" should handle `null` value

---

packages/plugins/@nocobase/plugin-collection-tree/src/server/__tests__/path.test.ts
packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts

| 🇺🇸 English | Fix the issue where node paths are not updated when disassociate children |
| 🇨🇳 Chinese | 修复解除关联子节点，节点路径没有更新的问题           |

fix(tree): issue where paths are not updated when disassociate children

---

packages/plugins/@nocobase/plugin-notification-email/src/client/ContentConfigForm.tsx

Fix `ContentConfigForm` using local path in dynamic form.
`dependencies: ['contnetType']` => `dependencies: ['.contnetType']`.
| 🇺🇸 English | fix reaction field path in dynamic form of email notification |
| 🇨🇳 Chinese | 修复 Email 通知渠道动态表单联动规则路径问题 |

fix(plugin-notification-email): fix form reaction based on local path

---

packages/plugins/@nocobase/plugin-notification-manager/src/client/index.tsx

Expose a hook for get all registered notification types.
| 🇺🇸 English | add API of notification manager plugin for getting all registered types |
| 🇨🇳 Chinese | 增加通知插件获取所有已注册通知类型的接口 |

refactor(plugin-notification-mananger): add types data hook api

---

packages/plugins/@nocobase/plugin-notification-email/src/server/mail-server.ts

To query users by ids correctly.
| 🇺🇸 English | fix the query for users by ids in email notification |
| 🇨🇳 Chinese | 修复基于用户 ID 发送 email 通知的查询 |

fix(plugin-notification-manager-email): fix user query by ids

---

packages/core/client/src/collection-manager/interfaces/index.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/client/mbm.ts

| 🇺🇸 English |  Fix the issue where select component for a many to many (array) field has only one option         |
| 🇨🇳 Chinese | 修复多对多（数组）字段的选择组件只有一个选项的问题           |

fix(m2m-array): issue where select component for a m2m array field has only one option

---

packages/core/database/src/collection.ts

| 🇺🇸 English |      fix wrong primaryKeyField value in sequelize when works with multi filter target keys     |
| 🇨🇳 Chinese |    修复联合主键中 sequelize primaryKeyField 属性读取错误的问题       |

fix: sequelize primary key field with multi filter target keys

---

packages/core/client/src/modules/actions/view-edit-popup/PopupActionInitializer.tsx
packages/core/client/src/modules/blocks/data-blocks/table/TableActionInitializers.tsx

The configuration actions of the table component cannot meet the requirements, and new actions need to be added
The data source in the table is other collections. After adding a pop-up window, you can select other collections and execute business logic through custom requests or workflows
| 🇺🇸 English |  [table] Add 'popup' action to configure actions         |
| 🇨🇳 Chinese | [表格] 配置操作中增加‘打开弹窗’按钮           |

feat: table block support popup action

---

packages/core/client/src/acl/ACLProvider.tsx

… collection field permissions
| 🇺🇸 English |     permission for the association table field in the table is based on the permission of the corresponding association field     |
| 🇨🇳 Chinese |      表格中关系表字段权限为该关系字段的权限     |

fix: validate association field permissions when checking association collection field

---

packages/core/client/src/collection-manager/interfaces/o2m.tsx
packages/core/client/src/collection-manager/interfaces/o2o.tsx

Support file collection as target of one-to-many association.
| 🇺🇸 English | support file collection as target of one-to-many association |
| 🇨🇳 Chinese | 支持一对多关系使用文件表 |

fix(client): support file collection as target of one-to-many association

---

packages/core/client/src/data-source/__tests__/collection/Collection.test.tsx
packages/core/client/src/data-source/collection/Collection.ts
packages/core/client/src/data-source/collection/CollectionManager.ts

Support `getFilterTargetKey()` from `Collection` class.
| 🇺🇸 English | support `getFilterTargetKey()` from `Collection` class |
| 🇨🇳 Chinese | 在 `Collection` 类中支持 `getFilterTargetKey()` 方法 |

refactor(client): move getFilterTargetKey api to collection

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/ContentConfigForm.tsx

Support to define different delimiters of variable expression other than `{{` and `}}`.
```diff
<Variable.TextArea
+   delimiters={['{{{', '}}}']}
/>
```
| 🇺🇸 English | support delimiters properties for variable expression component |
| 🇨🇳 Chinese | 为变量表达式输入组件增加定界符配置项 |

feat(client): add delimiters props to variable text

---

packages/core/evaluators/src/client/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx

Use Formula.js as default evaluator.
| 🇺🇸 English | use Formula.js as default evaluator in calculation node |
| 🇨🇳 Chinese | 将运算节点的默认计算引擎更换为 Formula.js |

fix(evaluators): change formula.js to default calculation engine

---

packages/core/client/src/modules/blocks/data-blocks/table-selector/__e2e__/schemaInitializer.test.ts
packages/core/client/src/modules/blocks/data-blocks/table/TableActionColumnInitializers.tsx
packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaInitializer.test.ts
packages/core/client/src/modules/blocks/data-blocks/table/tableColumnSettings.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
packages/core/client/src/schema-component/antd/table-v2/Table.tsx

| 🇺🇸 English |   adjust default column width to 100 in table   block     |
| 🇨🇳 Chinese |    表格column 默认宽度调整为100       |

refactor: adjust default column width to 100 in table

---

packages/core/client/src/schema-component/antd/filter/FilterAction.tsx
packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts

| 🇺🇸 English |      Fix  reset issue that reverts filter button title to default     |
| 🇨🇳 Chinese |      修复筛选按钮重置后标题恢复为默认名称的问题     |

fix: reset issue that reverts filter button title to default

---

packages/core/client/src/collection-manager/interfaces/o2o.tsx
packages/plugins/@nocobase/plugin-field-m2m-array/src/client/mbm.ts

Support o2o and m2m (array) to use file collection
| 🇺🇸 English | support one-to-one and many-to-many (array) field to use file collection |
| 🇨🇳 Chinese | 一对一字段和多对多（数组）字段支持选择文件表 |

fix(client): support o2o and m2m (array) to use file collection

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/dualAxes.ts

| 🇺🇸 English | Fix the issue where data transformations do not work on tooltip in dual-axes charts          |
| 🇨🇳 Chinese | 修复双轴图中数据转换没有对 tooltip 生效的问题          |

fix(data-vi): issue where data transformations do not work on tooltip in dual-axes charts

---

packages/core/client/src/schema-component/antd/action/Action.tsx
packages/core/client/src/schema-component/antd/page/index.ts
packages/core/client/src/schema-component/antd/table-v2/Table.tsx

* Allow to pass `openSize` in to internal button in `Action`.
* Export `useCurrentPopupContext()` hook for getting popup params.
* Fix `columnHidden` props caused warning.
| 🇺🇸 English | adjust some api of client core, and fix warning |
| 🇨🇳 Chinese | 调整部分前端内核的接口，并修复警告 |

fix(client): fix components

---

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx

…on  fields
| 🇺🇸 English |      style issue when using long text as the title field in association field      |
| 🇨🇳 Chinese |      修复关系字段使用超长文本作为标题时的样式问题     |

fix: style issue when using long text as the title field in association field

---

packages/core/client/src/schema-component/antd/upload/shared.ts

Fix file type matching when file or property is null
| 🇺🇸 English | fix file type matching when file or property is null |
| 🇨🇳 Chinese | 修复当文件或特定属性为空时文件类型匹配的报错 |

fix(client): fix file type matching when file or property is null

---

packages/core/database/src/relation-repository/multiple-relation-repository.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/issues.test.ts

| 🇺🇸 English | Fix the issue where retrieving records in an association collection with many to many (array) fields causes an error          |
| 🇨🇳 Chinese | 修复在获取含有多对多（数组）字段的关联表记录时报错的问题          |

fix(m2m-array): error when retriving association records with m2m array field

---

packages/core/utils/src/date.ts
packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx

| 🇺🇸 English |    fix: use desktop components for select in mobile configuration mode & fix error when using variables as default values in datePicker       |
| 🇨🇳 Chinese |      移动端配置态的时候 select 还是使用桌面组件& 修复日期组件使用变量作为默认值时报错     |

fix: use desktop components for select in mobile configuration mode & fix error when using variables as default values in datePicker

---

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx

…ting existing data only
| 🇺🇸 English |        fix: style issue on mobile when subtable is configured to allow select data only   |
| 🇨🇳 Chinese |    修复：移动端配置子表格仅允许选择已有数据时样式异常       |

fix: style issue on mobile when subtable is configured to allow select data only

---

packages/core/build/src/buildPlugin.ts

| 🇺🇸 English | Fix the issue where yarn dev reports an error when there are already built plugins in the system |
| 🇨🇳 Chinese | 修复当系统中存在已经构建过的插件时，运行 yarn dev 报错的问题 |

fix: yarn dev will throw errors if loading released plugins

---

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calender.Settings.tsx
packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/items/CalendarBlockInitializer.tsx

… block
| 🇺🇸 English |      Fix missing date field options with and without timezone in calendar block     |
| 🇨🇳 Chinese |     修复日历区块中日期字段选项缺失无时区和含时区字段      |

fix：missing date field options with and without timezone in calendar block

---

packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

System function as variable in workflow could be extended on server side, but not client side.
```ts
// Single
pluginWorkflowClient.registerSystemVariable({
key: 'someVariable',
label: `{{t("Some variable", { ns: "YourNamespace" })}}`,
value: 'someVariable',
});
// Group
pluginWorkflowClient.registerSystemVariable({
key: 'someGroup',
label: `{{t("Some group", { ns: "YourNamespace" })}}`,
value: 'someGroup',
children: [
{ key: 'a', label: 'A', value: 'a' },
{ key: 'b', label: 'B', value: 'b' },
]
});
```
| 🇺🇸 English | support to register system variables in client |
| 🇨🇳 Chinese | 支持在前端扩展工作流的系统变量 |

refactor(plugin-workflow): support to register system variables in client

---

packages/core/client/src/schema-component/antd/tabs/Tabs.tsx
packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/mobile-action-page/MobileTabsForMobileActionPage.tsx

Support to hide `TabPane` with dynamic property `hidden`.
Tab is not needed to be render based on some conditions.
| 🇺🇸 English | Support dynamic property `hidden` for component `Tabs.TabPan` to control rendering |
| 🇨🇳 Chinese | `Tabs.TabPane` 组件支持用于控制是否渲染的动态属性 `hidden` |

chore(client): support hidden property for component `Tabs.TabPane`

---

packages/core/client/src/schema-settings/SchemaSettings.tsx
packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/templates.ts
packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/zIndex.test.ts

| 🇺🇸 English |       Fix the issue where the 'Assign field values' modal is obscured on the mobile configuration page    |
| 🇨🇳 Chinese |     修复在移动端配置页，字段赋值的弹窗被遮挡的问题      |

fix(zIndex): fix the issue of modal being obscured

---

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx

…an across month
| 🇺🇸 English |       Fix events not display in calendar block when start and end dates span across months    |
| 🇨🇳 Chinese |    修复 日历区块开始日期和结束日期跨月后不显示事件       |

fix: events not display in calendar block when start and end dates span across months

---

packages/core/client/src/schema-component/antd/form-v2/Form.tsx

| 🇺🇸 English |      Fix subtable label minimum width issue in horizontal mode     |
| 🇨🇳 Chinese |      修复表单横排模式下子表格的 label 宽度的问题     |

fix:  unable to set minimum width for subtable labels in horizontal mode

---

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageList.tsx
packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/InAppNotificationChannel.ts

Remove in-app message title string slicing logic.
| 🇺🇸 English |    Remove in-app message title string slicing logic.      |
| 🇨🇳 Chinese |   移除站内信消息标题字符串截取逻辑。         |

fix(plugin-notification-in-app-message): remove in-app message title string slicing logic

---

packages/core/client/src/schema-component/antd/variable/Input.tsx

Not to use `Null` component when set `nullable: false` and show origin component.
| 🇺🇸 English | support variable input component to use custom component when `nullable` is set to `false` |
| 🇨🇳 Chinese | 支持变量组件在设置 `nullable` 为 `false` 时使用既有的自定义组件 |

fix(client): use children component when nullable is false

---

packages/core/client/src/schema-initializer/utils.ts

| 🇺🇸 English |     Fix issue with association fields affecting each other when  multiple association fields has the same target collection      |
| 🇨🇳 Chinese |     修复多个关系字段关联同一张表时，设置关系表字段时互相影响的问题      |

fix:  issue with association fields affecting each other when  multiple association fields has the same target collection

---

packages/core/cli/src/commands/start.js

| 🇺🇸 English |  Daemon mode does not delete sock files   |
| 🇨🇳 Chinese |  Daemon 模式不删除 sock 文件  |

fix(cli): daemon mode does not delete sock files

---

packages/core/client/src/formily/NocoBaseRecursionField.tsx
packages/core/client/src/index.ts
packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemInitializers.tsx
packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterVariableInput.tsx

| 🇺🇸 English | Fix the issue where filter field components of chart blocks not rendering          |
| 🇨🇳 Chinese | 修复图表区块的筛选字段组件没有渲染的问题           |

fix(data-vi): issue where filter field components of chart blocks not rendering

---

packages/core/client/src/block-provider/hooks/index.ts

| 🇺🇸 English | fix incorrect highlight style of the link button |
| 🇨🇳 Chinese | 修复链接按钮高亮样式不正确的问题 |

fix: cannot set highlight style for link action button

---

packages/core/client/src/block-provider/DetailsBlockProvider.tsx
packages/core/client/src/block-provider/FormBlockProvider.tsx
packages/core/client/src/block-provider/TableBlockProvider.tsx
packages/core/client/src/block-provider/TemplateBlockProvider.tsx
packages/core/client/src/variables/VariablesProvider.tsx
packages/core/test/src/e2e/e2eUtils.ts

| 🇺🇸 English |       Fix the issue where association field values are empty in block templates. Fix the problem where block data scope using variables don't work properly in third-party data sources    |
| 🇨🇳 Chinese |     修复区块模板中，关系字段值为空的问题。修复第三方数据源的区块数据范围，使用变量时，不能正常工作的问题      |

fix: fix the issue where association field values are empty in block templates

---

packages/core/build/src/buildPlugin.ts

| 🇺🇸 English | Fixed incorrect caching of frontend js files after plugin build |
| 🇨🇳 Chinese | 修复插件构建后前端 js 文件错误缓存的问题 |

fix: async chunk has been cached incorrectly

---

packages/plugins/@nocobase/plugin-notification-manager/src/collections/channel.ts
packages/plugins/@nocobase/plugin-notification-manager/src/locale/en-US.json
packages/plugins/@nocobase/plugin-notification-manager/src/locale/zh-CN.json

Fix notification channel name can not be edit when creating on demo site.
| 🇺🇸 English |    Fix notification channel name can not be edit when creating on demo site.       |
| 🇨🇳 Chinese |      修复了在新增通知渠道时不能编辑渠道名的问题。     |

fix(plugin-notification-manager):  notification channel name can not be edit when creating on demo site

---

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx
packages/core/database/src/relation-repository/single-relation-repository.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/issues.test.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/m2m-array-bigint-api.test.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/m2m-array-string-api.test.ts
packages/plugins/@nocobase/plugin-field-m2m-array/src/server/belongs-to-array-field.ts

| 🇺🇸 English | Fix the issue where updating m2m array fields in single relation collection does not take effect          |
| 🇨🇳 Chinese | 修复更新对一关联表中多对多（数组）字段不生效的问题          |

fix(m2m-array): issue where updating m2m array fields in single relation collection

---

packages/plugins/@nocobase/plugin-data-visualization/src/server/formatter/mysql-formatter.ts

| 🇺🇸 English | Fix the issue when formatting timezone-aware date fields in MySQL        |
| 🇨🇳 Chinese | 修复在 MySQL 中格式化带时区的日期字段的问题         |

fix(data-vi): fix the issue when formatting timezone-aware date fields in MySQL

---

packages/core/client/src/locale/zh-CN.json
packages/core/client/src/schema-component/antd/association-field/SubTable.tsx

fix: adjust empty state text for subtable in read-pretty  mode

---

packages/plugins/@nocobase/plugin-user-data-sync/src/server/__tests__/api.test.ts
packages/plugins/@nocobase/plugin-user-data-sync/src/server/actions/user-data.ts
packages/plugins/@nocobase/plugin-user-data-sync/src/server/plugin.ts
packages/plugins/@nocobase/plugin-user-data-sync/src/server/user-data-resource-manager.ts

| 🇺🇸 English | Skip unsupported data types during synchronization instead of throwing an error.          |
| 🇨🇳 Chinese | 同步数据时跳过不支持的数据类型，而不是直接报错。          |

fix(user-data-sync): skip unsupported data types during synchronization instead of throwing an error

---

packages/core/client/src/schema-component/antd/filter/FilterItem.tsx

Fix wrong position style of `FilterItem` component.
https://github.com/nocobase/nocobase/pull/4945/files#diff-24b504b5bd94ceb6405450ef898f8a0cd013eeaaac967f1873da746a655b1162R93
| 🇺🇸 English | Fix wrong position style of `FilterItem` component |
| 🇨🇳 Chinese | 修复筛选组件样式错位问题 |

fix(client): fix filter component style

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts

Fix transaction timeout when deleting execution automatically.
#5854.
| 🇺🇸 English | Fix transaction timeout when deleting execution automatically |
| 🇨🇳 Chinese | 修复自动删除执行记录时事务超时的问题 |

fix(plugin-workflow): fix transaction when delete execution after processed

---

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx

…ion mode when using file select
| 🇺🇸 English |    Fix issue where file table selector is not display in non-configuration mode when using file select       |
| 🇨🇳 Chinese |    修复关联文件表，使用数据选择器时在配置模式下显示文件表区块，非配置模式下未显示的问题       |

fix: issue where file table selector is not display in non-configuration mode when using file select

---

packages/core/client/src/schema-component/antd/action/hooks.ts
packages/plugins/@nocobase/plugin-users/src/client/UsersManagement.tsx

| 🇺🇸 English | Fix the issue where the form is not reset after adding or editing a user in user management.          |
| 🇨🇳 Chinese | 修复用户管理中添加或修改用户后表单没有被重置的问题 。         |

fix(users): the form should be reset after adding or editing a user in the user management

---

packages/plugins/@nocobase/plugin-users/src/client/UsersManagement.tsx

| 🇺🇸 English |  Fix the issues where pagination settings are reset after editing and submitting user profiles on the user management  following a page switch or a change of page size. |
| 🇨🇳 Chinese |  修复用户管理页面翻页或修改分页数量后，编辑用户资料并提交，分页设置会被重置的问题。         |

fix(users): refresh issue after editing user profiles

---

packages/core/client/src/formily/NocoBaseRecursionField.tsx
packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/createdAt/schemaInitializer.test.ts

| 🇺🇸 English |        Fix the issue where system fields in the filter form block cannot be edited   |
| 🇨🇳 Chinese |      修复筛选表单中的系统字段无法编辑的问题     |

fix(NocoBaseRecursionField): ignore x-read-pretty when merging schemas

---

packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/issues.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/query.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts

| 🇺🇸 English | Fix the error when filtering with nested many to many associations in chart query.         |
| 🇨🇳 Chinese | 修复在图表查询中使用嵌套的多对多关系进行过滤时的报错。          |

fix(data-vi): query error when filtering with nested m2m associations

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-date-field.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts

Fix schedule trigger on date field without timezone.
| 🇺🇸 English | Fix schedule trigger on date field without timezone |
| 🇨🇳 Chinese | 修复定时任务使用无时区字段存在错误的问题 |

fix(plugin-workflow): fix schedule trigger on date field without tz

---

packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/defineMyInAppChannels.ts

Fix the bug in the in-app messaging feature where filtering unread messages is not functioning correctly due to interference with other user data.
Fix the bug in the in-app message feature where filtering unread channels is not functioning correctly due to interference with other user data.
| 🇺🇸 English |  Fix the bug in the in-app message feature where filtering unread channels is not functioning correctly due to interference with other user data.         |
| 🇨🇳 Chinese |   修复应用内消息功能中的一个错误，该错误导致筛选未读频道时，由于其他用户数据的干扰而无法正常工作。        |

fix(notification-in-app-message): include user ID filter in in-app channels query

---

packages/core/client/src/formily/NocoBaseReactiveField.tsx

| 🇺🇸 English |       Fix the issue where the delete button is disabled in the block template management page    |
| 🇨🇳 Chinese |     修复区块模板管理页面中，删除按钮被禁用的问题      |

fix(NocoBaseReactiveField): remove disable and readOnly

---

packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/FormBlockProvider.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/components/DetailsBlockProvider.tsx

Fix sub-details block throwing error in manual node UI configuration.
```
useRerenderDataBlock() must be used within a DataBlockProvider
```
#5366.
| 🇺🇸 English | Fix sub-details block throwing error in manual node UI configuration |
| 🇨🇳 Chinese | 修复关系字段子详情区块在人工节点界面配置中报错 |

fix(plugin-workflow-manual): fix details block context

---

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
packages/core/utils/src/date.ts

… when showTime=true is set
| 🇺🇸 English |    Fix date range picker in filter form/action not showing time picker when showTime is set       |
| 🇨🇳 Chinese |      复 筛选表单/筛选操作中日期范围选择器设置 showTime=true 时未显示时间     |

fix:  date range picker in filter form/action not showing time picker when showTime is set

---

packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/collections.repository.test.ts
packages/plugins/@nocobase/plugin-data-source-main/src/server/server.ts

| 🇺🇸 English |    Added name conflict validation to prevent users from creating Collections with the same name as system Collections |
| 🇨🇳 Chinese | 新增名称冲突校验，防止用户创建与系统 Collection 同名的 Collection      |

fix: prevent creation of collection with existing name

---

packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

Fix `onChange` not works in `WorkflowVariableWrapper` component.
| 🇺🇸 English | Fix `onChange` not works in `WorkflowVariableWrapper` component |
| 🇨🇳 Chinese | 修复 `WorkflowVariableWrapper` 组件中值变更失效问题 |

fix(plugin-workflow): fix variable compoent onchange

---

packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/migrations/update-bigint-to-unixtimestamp.test.ts
packages/plugins/@nocobase/plugin-data-source-main/src/server/migrations/20241230000001-update-bigint-to-unixtimestamp.ts

| 🇺🇸 English |   Fix legacy support issues with the unixTimestamp field.        |
| 🇨🇳 Chinese |  修复旧版 unixTimestamp 字段的支持问题        |

chore: migrate old version unixtimestamp fields

---

packages/core/server/src/gateway/index.ts

| 🇺🇸 English | Fixed a potential app crash during backup restoration |
| 🇨🇳 Chinese | 修复还原备份时可能出现的应用崩溃问题 |

fix: crash if application db table not existing

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockProvider.tsx

| 🇺🇸 English | Fixed the issue where "current popup variables" used on charts in subpages became empty after refreshing the page          |
| 🇨🇳 Chinese | 修复在子页面的图表中使用“上级弹窗变量”时，刷新页面后变量失效的问题  |

fix(data-vi): "Current popup record" variable issue

---

packages/core/client/src/modules/blocks/data-blocks/details-single/ReadPrettyFormItemInitializers.tsx
packages/plugins/@nocobase/plugin-kanban/src/client/Kanban.Card.Designer.tsx

| 🇺🇸 English |    Fix parent collection fields not loaded in the kanban       |
| 🇨🇳 Chinese |    修复看板未加载数据表的父表字段       |

fix: parent collection fields not loaded in the kanban

---

packages/core/client/src/schema-component/antd/action/Action.Page.style.ts
packages/core/client/src/schema-component/hooks/useBlockSize.ts

| 🇺🇸 English |       Fix scrollbar issue when setting full height for data block in subpage    |
| 🇨🇳 Chinese |       修复 数据区块在子页面中设置全高时出现滚动条    |

fix: scrollbar issue when setting full height for data block in subpage

---

packages/core/client/src/collection-manager/Configuration/components/index.tsx
packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/index.tsx

| 🇺🇸 English |  Fix  resolve issue where targetKey can't select NanoID field in one-to-many         |
| 🇨🇳 Chinese |    修复一对多关联的 targetKey 无法选择 NanoID 字段       |

fix: o2m support set nanoid as targetKey

---

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
packages/core/utils/src/date.ts

| 🇺🇸 English |   Set default end time for time scope component in filter block to 23:59:59"        |
| 🇨🇳 Chinese |    筛选区块中时间范围的结束时分秒默认到 23:59:59     |

refactor(client): set default end time for time range in filter block to 23:59:59"

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx

Allow to sort workflows when binding to action button.
| 🇺🇸 English | Allow to sort workflows when binding to action button |
| 🇨🇳 Chinese | 支持绑定工作流时进行排序 |

feat(plugin-workflow): allow to sort workflows when binding to action button

---

packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
packages/plugins/@nocobase/plugin-workflow-test/src/server/instructions.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-static.test.ts

Add defensive code to avoid duplicate triggering.
* Raise transaction isolation level to repeatable-read when fetching next queueing execution.
* Check event key in events cache.
| 🇺🇸 English | Add defensive logic to avoid duplicate triggering |
| 🇨🇳 Chinese | 为避免重复触发增加防御性逻辑 |

fix(plugin-workflow): fix duplicate triggering

---

packages/core/evaluators/package.json

To fix expression not works as expected in formula.js.
In v4.2.0 of formula.js:
```
WORKDAY('2025-01-10T12:37:55.192Z', 1); // works
WORKDAY('2025-01-10T12:37:55.192Z', -1); // throws error
```
In v4.4.9 it works.
| 🇺🇸 English | Upgrade version of library formula.js to 4.4.9 |
| 🇨🇳 Chinese | 升级 formula.js 库的版本至 4.4.9 |

chore(evaluators): upgrade formulajs version to 4.4.9

---

packages/plugins/@nocobase/plugin-users/src/client/PasswordField.tsx
packages/plugins/@nocobase/plugin-users/src/client/schemas/users.ts

| 🇺🇸 English |  Disable browser autofill when setting passwords for users in user management         |
| 🇨🇳 Chinese | 在用户管理中给用户设置密码的时候关闭浏览器自动填充          |

fix(users): disable browser autofill when setting passwords for users in user management

---

packages/core/client/src/schema-component/common/withPopupWrapper/index.tsx

| 🇺🇸 English |  Fix missing current popup variable in the field enable link modal         |
| 🇨🇳 Chinese |   修复 字段启用连接的弹窗中缺少当前弹窗变量        |

fix: missing current popup variable in the field enable link modal

---

packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx

| 🇺🇸 English |   Fix number field format in readPretty mode affecting edit mode        |
| 🇨🇳 Chinese |   整数字段在阅读模式下设置的格式也会影响编辑模式        |

fix: number field format in readPretty mode affecting edit mode

---

packages/core/client/src/block-provider/hooks/index.ts

| 🇺🇸 English |   Fix incorrect loading of modal association  fields in table block        |
| 🇨🇳 Chinese |     修复表格区块加载时误加载弹窗区块中的关系字段      |

fix: incorrect loading of modal association  fields in table block

---

packages/plugins/@nocobase/plugin-data-visualization/src/server/query-parser/query-parser.ts

| 🇺🇸 English | Remove the `LIMIT` clause when using aggregate functions without setting dimensions in chart queries         |
| 🇨🇳 Chinese |  在图表查询中使用聚合函数且没有设置维度的时候去除 `LIMIT` 语句         |

fix(data-vi): remove the `LIMIT` clause when using aggregate functions without dimensions

---

packages/core/resourcer/src/resourcer.ts
packages/plugins/@nocobase/plugin-action-custom-request/src/server/__tests__/actions.test.ts

Allow empty object as values in action.
| 🇺🇸 English | Allow empty object as values in action |
| 🇨🇳 Chinese | 支持 API 请求中传入空对象作为 values 的值 |

refactor(resourcer): allow empty object as values

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts

Add validate API for triggers to validate configurations.
* feat: add validateConfig to trigger
* refactor: validateConfig
* fix: validate config
| 🇺🇸 English | Add validate API for triggers to validate configurations |
| 🇨🇳 Chinese | 为触发器基类增加验证配置的 API |

feat: add validateConfig to trigger (#6040)

---

packages/core/client/src/data-source/data-block/DataBlockProvider.tsx
packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx

| 🇺🇸 English |        Fix the issue where association field default values are not refreshed after switching pages   |
| 🇨🇳 Chinese |      修复切换页面后，不刷新关系字段默认值的问题     |

fix: refresh association field data after page switching

---

packages/plugins/@nocobase/plugin-collection-tree/src/server/__tests__/issues.test.ts
packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts

| 🇺🇸 English |  Disallow setting a node of tree collection as its own parent         |
| 🇨🇳 Chinese | 禁止将树表节点自身设置为其父节点          |

fix(tree): should not set a tree collection node as its own parent

---

packages/core/client/src/schema-component/antd/association-field/Nester.tsx

| 🇺🇸 English |       Fix the issue where association fields are not displaying data after adding them in sub-details    |
| 🇨🇳 Chinese |     修复在子详情中添加关系字段后，不显示关系字段数据的问题      |

fix: refresh entire block after adding field

---

packages/core/client/src/block-provider/hooks/index.ts

| 🇺🇸 English |       When the linkage rule's conditions involve association fields that are not displayed, the button's linkage rule becomes ineffective    |
| 🇨🇳 Chinese |     当联动规则的条件中使用了没有显示出来的关系字段时，按钮的联动规则无效      |

fix: button linkage rule is not taking effect

---

packages/plugins/@nocobase/plugin-collection-sql/src/server/__tests__/select-query.test.ts
packages/plugins/@nocobase/plugin-collection-sql/src/server/sql-collection/query-generator.ts

| 🇺🇸 English |  Fix the issue where filtering SQL Collection throws an error when `DB_TABLE_PREFIX` is set        |
| 🇨🇳 Chinese |  修复设置了 `DB_TABLE_PREFIX` 时过滤 SQL Collection 报错的问题         |

fix(sql-collection): filtering SQL Collection throws an error when `DB_TABLE_PREFIX` is set

---

packages/core/client/src/schema-component/antd/association-field/InternalPopoverNester.tsx

| 🇺🇸 English | Incorrect translation for title of `Sub-form(Popover)` |
| 🇨🇳 Chinese | `子表单(弹窗)`标题翻译不正确 |

fix: popover subform incorrect translated

---

packages/plugins/@nocobase/plugin-workflow-notification/src/server/NotificationInstruction.ts

Fixed an issue where notifications failed to send when user input contained Handlebars-like syntax.
| 🇺🇸 English |     Ensured notifications are sent correctly when user input contains Handlebars-like syntax.    |
| 🇨🇳 Chinese |   确保当用户输入包含 Handlebars 语法时，通知能够正确发送。       |

fix(notification): notifications failed to send when user input contained Handlebars-like syntax

---

packages/plugins/@nocobase/plugin-mobile/src/client/desktop-mode/DesktopMode.tsx

| 🇺🇸 English |       Hide mobile config page header when no config permission    |
| 🇨🇳 Chinese |     当没有配置权限时，隐藏移动端配置页 header      |

chore: hide the header when no permissions are configured

---

packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx

| 🇺🇸 English |       The 'Allow Multiple Selection' configuration option for association fields is not displayed in Filter Forms    |
| 🇨🇳 Chinese |     筛选表单中的关系字段不显示“允许多选”配置项      |

fix: should show 'Allow multiple selection' in filter form

---

packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/defineMyInAppChannels.ts

The channel list API's subqueries for retrieving message timestamps and titles currently lack user filtering conditions. This security issue could potentially expose message information from other users to the current user.
This PR fixes two security vulnerabilities in the channel list query:
1. Added user filtering to the latest message timestamp subquery:
2. Added user filtering to the latest message title subquery:
| 🇺🇸 English | Fix: Add user filter to message timestamp and title subqueries in channel list API to ensure data isolation. |
| 🇨🇳 Chinese | 修复：在渠道列表 API 的消息时间戳和标题子查询中添加用户过滤条件，确保数据隔离。 |

fix: add user filter to message timestamp and title subqueries

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
packages/core/client/src/schema-component/antd/association-field/__tests__/AssociationFieldModeProvider.test.tsx
packages/core/client/src/schema-component/antd/association-field/index.ts

| 🇺🇸 English |   missing drag setting in relation data quick-create operation modal      |
| 🇨🇳 Chinese |    关系数据快捷创建操作的弹窗中组件缺少拖动设置项       |

fix: missing drag setting in quick-create operation modal

---

packages/core/client/src/modules/fields/component/Picker/__e2e__/schemaSettings.test.ts
packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts

| 🇺🇸 English |     In the edit form, the displayed association field value does not change when the associated field updates      |
| 🇨🇳 Chinese |      编辑表单中，显示的关系字段值不会随着关联字段变化而变化     |

fix: edit form association collection field value not change

---

packages/core/client/src/schema-initializer/utils.ts

| 🇺🇸 English | Missing unique key for association fields submenu in UI |
| 🇨🇳 Chinese | 界面上关联字段菜单缺少唯一性 key 属性 |

fix: missing unique keys of association fields

---

packages/plugins/@nocobase/plugin-workflow-loop/src/server/LoopInstruction.ts
packages/plugins/@nocobase/plugin-workflow-loop/src/server/__tests__/instruction.test.ts
packages/plugins/@nocobase/plugin-workflow-test/src/server/instructions.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Processor.test.ts

Fix loop exit earlier when node inside pending.
| 🇺🇸 English | Fix loop exit earlier when node inside pending |
| 🇨🇳 Chinese | 修复循环内部有等待节点时提前退出的问题 |

fix(plugin-workflow-loop): fix pending nodes in loop but resolved

---

packages/plugins/@nocobase/plugin-workflow/src/client/AddNodeContext.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx

Support to extend group of instruction in workflow.
```js
export default class YourPluginClient extends Plugin {
load() {
const pluginWorkflow = this.app.pm.get(PluginWorkflowClient);
pluginWorkflow.registerInstructionGroup('ai', { label: `{{t("AI", { ns: "${NAMESPACE}" })}}` });
}
}
```
| 🇺🇸 English | Support to extend group of instruction in workflow |
| 🇨🇳 Chinese | 支持扩展工作流节点分组 |
| 🇺🇸 English | [Extends Node Group](https://docs.nocobase.com/handbook/workflow/development/api#registerinstructiongroup) |
| 🇨🇳 Chinese | [扩展节点分组](https://docs-cn.nocobase.com/handbook/workflow/development/api#registerinstructiongroup) |

feat(plugin-workflow): add api to register group of instruction

---

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
packages/core/client/src/schema-component/antd/variable/VariableSelect.tsx

Show `<Variable.TextArea />` component correctly in disabled mode.
| 🇺🇸 English | Show `<Variable.TextArea />` component correctly in disabled mode |
| 🇨🇳 Chinese | 在禁用状态下正确展示 `<Variable.TextArea />` 组件 |

fix(client): fix variable component disabled height

---

packages/plugins/@nocobase/plugin-auth/src/server/actions/auth.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts

Support to trigger workflow when change password
| 🇺🇸 English | Support to trigger workflow when change password |
| 🇨🇳 Chinese | 支持修改密码时触发用户表的工作流 |

fix(plugin-auth): support to trigger workflow when change password

---

packages/core/client/src/schema-component/antd/variable/TextAreaWithGlobalScope.tsx
packages/plugins/@nocobase/plugin-notification-email/src/client/ConfigForm.tsx

Fix input html tag character error in mail channel config form.
| 🇺🇸 English |       Fixed html tag character in the mail channel config form input field.    |
| 🇨🇳 Chinese |    修复邮件通道配置表单中输入标签的字符编码错误。       |

fix(notification-mail): html tag character in the mail channel config form input field

---

packages/core/server/src/application.ts
packages/core/server/src/gateway/index.ts

Adjust max number of event listeners to avoid warnings.
https://nodejs.org/api/events.html#emittersetmaxlistenersn
We are using a lot of events on the instance of app and db. Trying to increase the numbers. We could set them to infinity (0) if required.
| 🇺🇸 English | Adjust max number of event listeners to avoid warnings |
| 🇨🇳 Chinese | 调整事件监听函数最大数量以避免警告 |

chore(server): adjust max listeners number

---

packages/core/auth/src/base/auth.ts

Skip user auth check when token is api key.
| 🇺🇸 English |     Skip user auth check when token is api key      |
| 🇨🇳 Chinese |    当令牌是 API 密钥时跳过用户身份验证检查。       |

fix: auth check failed before api token expired

---

packages/plugins/@nocobase/plugin-field-sequence/src/client/sequence.tsx

Fix sequence field not disabled when on read-only mode.
| 🇺🇸 English | Fix sequence field not disabled when on read-only mode |
| 🇨🇳 Chinese | 修复自动编号字段在只读模式下未禁用 |

fix(plugin-field-sequence): fix read only mode

---

packages/plugins/@nocobase/plugin-acl/src/server/__tests__/list-action.test.ts
packages/plugins/@nocobase/plugin-acl/src/server/middlewares/with-acl-meta.ts

| 🇺🇸 English | Incorrect data records when using many to many fields as data scope in collection permissions          |
| 🇨🇳 Chinese | 配置数据表权限，使用多对多字段作为数据范围筛选条件，响应的数据记录不正确          |

fix(acl): incorrect data records when using m2m fields in collection permission data scope

---

packages/core/devtools/umiConfig.js

… available
Ensure X-Forwarded-For header is set only if req.ip is not undefined.
| 🇺🇸 English |    Ensure X-Forwarded-For header is set only if req.ip is not undefined.       |
| 🇨🇳 Chinese |     确保仅在 req.ip 不为 undefined 时，设置 X-Forwarded-For 头部。      |

fix(devtools): ensure X-Forwarded-For header is set only if req.ip is not undefined

---

packages/plugins/@nocobase/plugin-users/src/client/UsersManagement.tsx

| 🇺🇸 English |      An error UI briefly flashes when the user permission management table loads for the first time     |
| 🇨🇳 Chinese |     用户权限管理表格在首次加载页面时，有一个报错的 UI 一闪而过      |

fix(users): add loading state for users management tab

---

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx

| 🇺🇸 English |     subform components not aligning with main form when label is hidden       |
| 🇨🇳 Chinese |      子表单隐藏字段标题时字段组件与主表单中的组件未对齐     |

fix: subform components not aligning with main form when label is hidden

---

packages/core/evaluators/src/utils/formulajs.ts
packages/core/evaluators/src/utils/mathjs.ts
packages/plugins/@nocobase/plugin-workflow-aggregate/package.json
packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/AggregateInstruction.tsx
packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/__e2e__/DataOfCollection.test.ts
packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/AggregateInstruction.ts
packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/__tests__/instruction.test.ts
packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
packages/plugins/@nocobase/plugin-workflow-test/src/server/collections/posts.ts

Add round process for aggregated number based on double type.
| 🇺🇸 English | Add round process for aggregated number based on double type |
| 🇨🇳 Chinese | 对聚合后的数字进行小数四舍五入的处理 |

fix(plugin-workflow-aggregate): add precision process after query

---

packages/core/database/src/__tests__/relation-repository/relation-repository.test.ts
packages/core/database/src/relation-repository/relation-repository.ts

| 🇺🇸 English |  Fix error when retrieving relation collection records if the source key in relation fields is a numeric string        |
| 🇨🇳 Chinese |  修复当关系字段的源表标识字段值为数字型字符串时，获取关系数据记录报错的问题        |

fix(db): the string sourceKeyValue in relation repository is being converted to a number

---

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
packages/plugins/@nocobase/plugin-public-forms/src/client/schemas/editActionSchema.ts
packages/plugins/@nocobase/plugin-public-forms/src/client/schemas/publicForms.tsx

| 🇺🇸 English |  attachment field storage setting dropdown not displaying options         |
| 🇨🇳 Chinese |   附件字段存储空间设置下拉不显示选项        |

fix: attachment field storage setting dropdown not displaying options

---

packages/plugins/@nocobase/plugin-action-import/src/client/useImportAction.ts

| 🇺🇸 English |        import button should not include Pro import logic     |
| 🇨🇳 Chinese |     导入按钮插件中不应包含pro 导入按钮的逻辑    |

fix: import button should not include Pro import logic 

---

packages/core/client/src/modules/blocks/data-blocks/table/tableColumnSettings.tsx

| 🇺🇸 English |      missing sortable setting for inherited collection fields      |
| 🇨🇳 Chinese |      继承父表的字段在表格中缺少排序设置项    |

fix: missing sortable setting for inherited collection fields

---

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts

Allow skip to trigger collection workflow in database event.
```diff
const post = await PostRepo.create({
values: { title: 'post1' },
context: {
+     skipWorkflow: true,
}
});
```
| 🇺🇸 English | Allow skip to trigger collection workflow in database event |
| 🇨🇳 Chinese | 支持在数据表事件中不触发工作流 |

refactor(plugin-workflow): add option to skip triggering in collection event

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/configure/schemas/configure.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/query-parser/query-parser.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/types.ts

Close #6282 
| 🇺🇸 English | Support NULLS sorting in chart queries          |
| 🇨🇳 Chinese |  支持在图表查询中设置 NULLS 排序         |

feat(data-vi): support nulls sorting in chart queries

---

packages/plugins/@nocobase/plugin-acl/src/client/permissions/MenuPermissions.tsx

| 🇺🇸 English |       In the permission management table, the tab page name is empty    |
| 🇨🇳 Chinese |     权限管理表格中，tab 页的名称为空      |

fix: handle undefined menu titles in MenuPermissions component

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/__tests__/trigger.test.ts

Support to use end node to determine status.
| 🇺🇸 English | Support to use end node to determine status |
| 🇨🇳 Chinese | 支持通过结束节点决定操作的结果状态 |

refactor(plugin-workflow-action-trigger): support to use end node to determine status

---

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/InboxContent.tsx

Differentiate the in-app message list background color from the message cards to enhance visual hierarchy and readability.
| 🇺🇸 English |     Differentiate the in-app message list background color from the message cards to enhance visual hierarchy and readability.      |
| 🇨🇳 Chinese |     在站内信列表中，将背景颜色与消息卡片的颜色区分开，以提升视觉层次感和可读性。 |

fix(in-app message): differentiate the in-app message list background color from the message cards

---

packages/core/client/src/application/globalOperators.js

…ction
| 🇺🇸 English |       When using the '$anyOf' operator, the linkage rule is invalid    |
| 🇨🇳 Chinese |      使用“$anyOf”操作符时，联动规则无效     |

fix(globalOperators): handle null and empty array cases in  function

---

packages/core/client/src/locale/it-IT.json
packages/core/client/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-block-template/src/client/components/BlockTemplatePage.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/components/SaveAsTemplateSetting.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/hooks/useIsPageBlock.ts
packages/plugins/@nocobase/plugin-block-template/src/client/utils/setting.ts
packages/plugins/@nocobase/plugin-block-template/src/locale/en-US.json
packages/plugins/@nocobase/plugin-block-template/src/locale/zh-CN.json

| 🇺🇸 English | Save as template incorrect behavior in mobile client |
| 🇨🇳 Chinese | 移动端页面区块另存为模板不正确 |

fix: mobile saveas template not correctly

---

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx

| 🇺🇸 English |     date field range selection excludes the max date      |
| 🇨🇳 Chinese |      表单日期字段日期范围，最大日期可选范围少一天      |

fix: date field range selection excludes the max date

---

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageConfigForm.tsx
packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/en-US.json
packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/zh-CN.json
packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/parseUserSelectionConf.ts
packages/plugins/@nocobase/plugin-notification-manager/src/server/utils/compile.ts

Avoid wrong receivers configuration query all users.
| 🇺🇸 English | Avoid wrong receivers configuration query all users |
| 🇨🇳 Chinese | 避免错误的接收人配置导致查询出全部用户 |

fix: avoid wrong receivers configuration query all users

---

packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/migrations/20250312100512-change-table-name.test.ts
packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250312100512-change-table-name.ts

Change version limit of migration to `<1.7.0`.
| 🇺🇸 English | Change version limit of migration to `<1.7.0` |
| 🇨🇳 Chinese | 调整迁移脚本版本范围限制为 `<1.7.0` |
| 🇺🇸 English |  |
| 🇨🇳 Chinese |  |

fix(plugin-workflow-manual): fix migration version

---

packages/core/server/src/middlewares/parse-variables.ts
packages/plugins/@nocobase/plugin-acl/src/server/__tests__/actions.test.ts
packages/plugins/@nocobase/plugin-acl/src/server/actions/role-check.ts
packages/plugins/@nocobase/plugin-acl/src/server/index.ts
packages/plugins/@nocobase/plugin-acl/src/server/server.ts
packages/plugins/@nocobase/plugin-action-custom-request/src/server/actions/send.ts
packages/plugins/@nocobase/plugin-client/src/server/__tests__/desktopRoutes-union-role.test.ts
packages/plugins/@nocobase/plugin-client/src/server/server.ts
packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-source.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/external-data-source.test.ts
packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts
packages/plugins/@nocobase/plugin-mobile/src/server/__tests__/union-role-mobileRoutes.test.ts
packages/plugins/@nocobase/plugin-mobile/src/server/plugin.ts

Incorrect adjustment of the role - permission calculation logic might lead to over - or under - restricting access in other, untested role - combination scenarios. 
| 🇺🇸 English | Replace all instances of ctx.state.currentRole (single role) with ctx.state.currentRoles (supports multiple roles). |
| 🇨🇳 Chinese |  将所有使用 ctx.state.currentRole（单角色）的地方替换为 ctx.state.currentRoles（支持多角色）。 |

fix: replace all instances of ctx.state.currentRole with ctx.state.currentRoles

---

packages/core/acl/src/__tests__/acl-role.test.ts
packages/core/acl/src/utils/acl-role.ts

Fixed the issue where relationship fields are not displayed under the role union.
| 🇺🇸 English | Fixed the issue where relationship fields are not displayed under the role union.          |
| 🇨🇳 Chinese |      修复角色并集下关系字段不显示     |

fix: the relationship fields are not displayed under the role union

---

packages/plugins/@nocobase/plugin-workflow/src/client/settings/BindWorkflowConfig.tsx

Remove bind workflow settings button from data picker.
| 🇺🇸 English | Remove bind workflow settings button from data picker |
| 🇨🇳 Chinese | 在数据选择器中移除绑定工作流的配置按钮 |

fix(plugin-workflow): remove bind workflow settings button from data picker

---

packages/core/evaluators/src/utils/__tests__/formulajs.test.ts
packages/core/evaluators/src/utils/formulajs.ts
packages/core/evaluators/src/utils/mathjs.ts

Revert round decimal places to 9, to avoid double number precision issues.
| 🇺🇸 English | Revert round decimal places to 9 |
| 🇨🇳 Chinese | 将表达式计算保留小数调整回 9 位 |

fix(evaluator): fix round decimal places

---

packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx

| 🇺🇸 English |   add chi ld button not displaying icon-only mode        |
| 🇨🇳 Chinese |    添加子记录按钮设置只显示图标不生效      |

fix: add child button not displaying icon-only mode

---

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx
packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx
packages/core/client/src/schema-component/antd/table-v2/__tests__/Table.settings.test.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/components/SaveAsTemplateSetting.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/index.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/initializers/TemplateBlockInitializer.tsx

| 🇺🇸 English | Save as template action will be failed if containing association field |
| 🇨🇳 Chinese | 存在关联字段的区块另存为模板报错 |

fix: save as template not working if fields containing nest properties

---

packages/plugins/@nocobase/plugin-block-template/src/client/initializers/TemplateBlockInitializer.tsx

| 🇺🇸 English | linkage rules of the form block have not been synced from template correctly |
| 🇨🇳 Chinese | 表单联动规则未正确从模板同步 |

fix: template linkapge rules not synced for form template

---

packages/plugins/@nocobase/plugin-block-template/src/client/index.tsx

| 🇺🇸 English | duplicate save as template menu in the details block |
| 🇨🇳 Chinese | 详情区块存在重复的另存为模板菜单 |

fix: duplicate saveas template menu for details block

---

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts
packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/__tests__/trigger.test.ts

Multiple records in bulk action should trigger multiple times.
| 🇺🇸 English | Multiple records in bulk action should trigger multiple times |
| 🇨🇳 Chinese | 多行记录的批量操作需要触发多次 |

fix(plugin-workflow-action-trigger): trigger on multiple records

---

packages/core/client/src/schema-component/antd/upload/Upload.tsx

Only support plain text file to preview. Avoid CSV file to be downloaded when open preview.
| 🇺🇸 English | Only support plain text file to preview |
| 🇨🇳 Chinese | 仅支持纯文本文件预览 |

fix(client): only support plain text file to preview

---

packages/core/client/src/collection-manager/interfaces/input.ts
packages/core/client/src/locale/zh-CN.json
packages/core/database/src/__tests__/fields/string-field.test.ts
packages/core/database/src/fields/string-field.ts

Add trim option for string field.
| 🇺🇸 English | Add trim option for string field |
| 🇨🇳 Chinese | 为单行文本增加自动去除首尾空白字符的选项 |

feat(database): add trim option for string field

---

packages/core/database/src/fields/datetime-no-tz-field.ts
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts

Avoid "datetimeNoTz" field changes when value not changed in updating record.
Sequelize is using `_.isEqual` to compare old value and new value. While the implementation in legacy `datetimeNoTz` field always set string value to record, this will cause changed (to Date value), which is not expected.
| 🇺🇸 English | Avoid "datetimeNoTz" field changes when value not changed in updating record |
| 🇨🇳 Chinese | 避免“日期时间（无时区）”字段在值未变动的更新时触发值改变 |

fix(database): fix datetimeNoTz field

---

packages/core/client/src/application/schema-initializer/components/SchemaInitializerItem.tsx

Fix `disabled` property not works when `SchemaInitializerItem` has items.
| 🇺🇸 English | Fix `disabled` property not works when `SchemaInitializerItem` has `items` |
| 🇨🇳 Chinese | 修复 `SchemaInitializerItem` 配置了 `items` 时 `disabled` 属性无效的问题 |

fix(client): support disabled props for SchemaInitializerItem when has items

---

packages/core/client/src/collection-manager/interfaces/textarea.ts
packages/core/database/src/__tests__/fields/text-field.test.ts
packages/core/database/src/fields/text-field.ts

Add trim option for text field.
| 🇺🇸 English | Add trim option for text field |
| 🇨🇳 Chinese | 为多行文本类型字段增加去除首尾空白字符的选项 |

feat(database): add trim option for text field

---

packages/plugins/@nocobase/plugin-file-manager/src/server/collections/storages.ts

Add trim option for text fields of storages collection.
| 🇺🇸 English | Add trim option for text fields of storages collection |
| 🇨🇳 Chinese | 为存储引擎表的文本字段增加去除首尾空白字符的选项 |

refactor(file-manager): add trim option for text fields

---

packages/core/client/src/schema-component/antd/input/Input.tsx
packages/core/client/src/schema-component/antd/input/demos/new-demos/input.tsx
packages/core/client/src/schema-component/antd/variable/TextArea.tsx

Add `trim` API for `Input` and `Variable.TextArea`.
By default:
* `trim` for `Input` is `false`
* `trim` for `Variable.TextArea` is `true`
| 🇺🇸 English | Add `trim` API for `Input` and `Variable.TextArea` |
| 🇨🇳 Chinese | 为 `Input` 和 `Variable.TextArea` 组件增加 `trim` API |

refactor(client): add trim API for Input and Variable.TextArea

---

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
packages/core/sdk/src/APIClient.ts

| 🇺🇸 English |      The relationship fields in the filter form report an error after the page is refreshed because x-data-source is not carried     |
| 🇨🇳 Chinese |       筛选表单中的关系字段在刷新页面后，由于没有携带 x-data-source 而报错    |

fix: add headers to API request in AssociationFieldProvider

---

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx
packages/plugins/@nocobase/plugin-block-template/src/client/components/BlockTemplatePage.tsx

| 🇺🇸 English |  blank area between the block template configuration page title and the menu |
| 🇨🇳 Chinese | 区块模板配置页面标题与菜单存在空白区域 |

fix: block template configure page style

---

packages/plugins/@nocobase/plugin-action-export/src/client/useExportAction.tsx

| 🇺🇸 English |   missing filter params when exporting data after changing pagination        |
| 🇨🇳 Chinese |     筛选数据后切换分页再导出时筛选参数丢失     |

fix(export-action): missing filter params when exporting data after changing pagination

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/plugins/@nocobase/plugin-workflow-delay/src/client/DelayInstruction.tsx

Add default type fallback API for `Variable.Input`
```diff
<Variable.Input
parseOptions={{
+     defaultTypeOnNull: 'number'
}}
/>
```
| 🇺🇸 English | Add default type fallback API for `Variable.Input` |
| 🇨🇳 Chinese | 为 `Variable.Input` 组件增加默认退避类型的 API |

refactor(client): add default type fallback api for `Variable.Input`

---

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx

| 🇺🇸 English |   subtable description overlapping with add new button        |
| 🇨🇳 Chinese |     子表格中描述信息与操作按钮遮挡      |

fix: subtable description overlapping with add new button

---

packages/core/client/src/data-source/collection-field/CollectionField.tsx
packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts

| 🇺🇸 English |       In the form block, the default value of the field configuration will first be displayed as the original variable string and then disappear    |
| 🇨🇳 Chinese |     表单区块中，字段配置的默认值会先显示为原始变量字符串然后再消失      |

fix(defaultValue): avoid directly displaying variable strings

---

packages/core/client/src/modules/blocks/filter-blocks/FilterCollectionField.tsx

| 🇺🇸 English |      "allow multiple" option not working for relation field      |
| 🇨🇳 Chinese |    筛选表单中关系字段的“允许多选”设置项不生效       |

fix(filter-form): "allow multiple" option not working for relation field

---

packages/core/client/src/block-provider/hooks/index.ts

| 🇺🇸 English |       In the filter form, when the filter button is clicked, if there are fields that have not passed validation, the filtering is still triggered    |
| 🇨🇳 Chinese |     筛选表单中，当点击筛选按钮时，如果有字段未校验通过，依然会触发筛选的问题      |

fix(FilterForm): do not trigger filtering when validation fails

---

packages/core/client/src/route-switch/antd/admin-layout/__tests__/findFirstPageRoute.test.tsx
packages/core/client/src/route-switch/antd/admin-layout/index.tsx

| 🇺🇸 English |       Switching to the group menu should not jump to a page that has already been hidden in menu    |
| 🇨🇳 Chinese |     切换到分组菜单时，不应该跳转到已经在菜单中被隐藏的页面      |

fix: should not automatically redirect to hidden pages

---

packages/core/build/package.json
packages/core/build/src/buildPlugin.ts

After upgrade rspack version and build configuration, the bundle size hasn't changed
| 🇺🇸 English | build output is incorrect when plugin depends on some AMD libraries |
| 🇨🇳 Chinese | 插件依赖 AMD 库时构建产物不正确 |

fix: build output is not correct if plugin using some old amd library

---

packages/core/client/src/schema-component/antd/input/Input.tsx

Add native Password component to HoC Input.
| 🇺🇸 English | Add native Password component to HoC Input |
| 🇨🇳 Chinese | 补全原生的 Password 组件到封装过的输入组件 |

fix(client): fix input component

---

packages/core/client/src/schema-component/hooks/useFieldModeOptions.tsx

| 🇺🇸 English | custom association field not displaying field component  settings      |
| 🇨🇳 Chinese |   自定义的关系字段没有显示关系字段组件 |

fix: association field detection to be based on type

---

packages/core/client/src/schema-initializer/utils.ts

Fix error thrown when mouse hover on referenced template block in approval node configuration.
| 🇺🇸 English | Fix error thrown when mouse hover on referenced template block in approval node configuration |
| 🇨🇳 Chinese | 修复审批节点配置中引用模板区块的添加按钮报错问题 |

fix(client): add fault tolerant when no x-component in schema

---

packages/core/client/src/schema-component/antd/linkageFilter/useValues.ts
packages/core/client/src/schema-settings/LinkageRules/index.tsx
packages/core/client/src/schema-settings/SchemaSettings.tsx

| 🇺🇸 English |    variable conversion in sub-table/sub-form linkage rule conditions       |
| 🇨🇳 Chinese |    子表格、子表单中左侧变量转换历史数据异常，应为「当前对象  」     |

fix(linkage-rule): variable conversion in sub-table/sub-form linkage rule conditions

---

packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx
packages/core/client/src/schema-settings/LinkageRules/useValues.ts

| 🇺🇸 English |   missing action option constraints when reopening linkage rules        |
| 🇨🇳 Chinese |   重新打开联动规则时缺少操作选项约束        |

fix: missing action option constraints when reopening linkage rules

---

packages/core/build/src/tarPlugin.ts

Fix error thrown in tar command.
```log
yarn build packages/pro-plugins/@nocobase/plugin-pubsub-adapter-redis --only-tar                                                                                                                                                      
yarn run v1.22.22                                                                                                                                                                                                                                              
$ nocobase build packages/pro-plugins/@nocobase/plugin-pubsub-adapter-redis --only-tar                                                                                                                                                                         
$ tsup …
```

fix(build): tar cli

---

packages/plugins/@nocobase/plugin-block-template/src/client/components/BlockTemplateMenusProvider.tsx

| 🇺🇸 English | block templates can't be used in mysql envrionment |
| 🇨🇳 Chinese | mysql 环境下无法使用区块模板 |

fix: block templates not shown for mysql env

---

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/components/MobileDatePicker.tsx

Improve rendering performance by reducing the selectable range. Users can customize the selectable range through the "Date range limit" option：
| 🇺🇸 English |       Optimize the opening speed of the mobile date picker popup    |
| 🇨🇳 Chinese |     优化移动端日期选择弹窗的打开速度      |

fix: update min and max date limits in MobileDateTimePicker

---

packages/core/client/src/modules/actions/associate/AssociateActionProvider.tsx

…on collection table
| 🇺🇸 English |    missing filter for already associated data when adding association data       |
| 🇨🇳 Chinese |      添加关联表格时未过滤已关联的数据
|

fix: missing filter for already associated data when adding association data

---

packages/core/client/src/schema-component/antd/action/Action.tsx

…ord' variable
| 🇺🇸 English |  tree table 'Add Child' button linkage rule missing 'current record'         |
| 🇨🇳 Chinese |       树表格中添加子记录按钮的联动规则缺失「当前记录」变量    |

fix:  tree table 'Add Child' button linkage rule missing 'current record'

---

packages/plugins/@nocobase/plugin-gantt/src/client/components/calendar/calendar.tsx
packages/plugins/@nocobase/plugin-gantt/src/client/components/calendar/style.tsx
packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/gantt.tsx

| 🇺🇸 English |     gantt chart block overlapping months in calendar header for month view      |
| 🇨🇳 Chinese |    甘特图区块设置月份视图时，日历头部月份重叠       |

style(gantt): gantt chart block overlapping months in calendar header for month view

---

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchAction.tsx
packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx

| 🇺🇸 English |   action panel icon missing when icon-only is enabled        |
| 🇨🇳 Chinese |    操作面板 icon-only 配置下图标未显示     |

fix: action panel icon missing when icon-only is enabled

---

packages/core/client/src/modules/blocks/data-blocks/grid-card/__e2e__/schemaInitializer.test.ts
packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/actions/linkage.test.ts
packages/core/client/src/route-switch/antd/admin-layout/menuItemSettings.tsx
packages/core/client/src/schema-component/antd/page/Page.tsx

| 🇺🇸 English |       Prohibit moving menus before or after page tabs   |
| 🇨🇳 Chinese |     禁止将菜单移动到页面 tab 的前面和后面      |

fix: filter out tabs from route items in toItems function

---

packages/plugins/@nocobase/plugin-file-manager/package.json
packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/server.test.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts
packages/plugins/@nocobase/plugin-file-manager/src/server/storages/local.ts

Add a `getFileStream` API to support efficient file streaming in the file manager.
- Implemented `getFileStream` API.
- Allows streaming files without loading them fully into memory.
- Handles missing files and permission errors.
N/A
| 🇺🇸 English | Feature: Add `getFileStream` API for file streaming support. |
| 🇨🇳 Chinese | 新增：添加 `getFileStream` API 支持文件流式处理。 |
| 🇺🇸 English |  |
| 🇨🇳 Chinese |  |

feat(file-manager): add getFileStream api

---

packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx

| 🇺🇸 English |      In the filter form, switching the field operator and then refreshing the page causes an error     |
| 🇨🇳 Chinese |     筛选表单中，切换字段操作符后，刷新页面会报错      |

fix: refreshing the page after switching operators causes an error

---

packages/core/client/src/schema-component/antd/action/Action.Link.tsx
packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx

| 🇺🇸 English |     alignment issue of the add child record button in the tree table      |
| 🇨🇳 Chinese |     树表中添加子记录按钮未与其他按钮对齐    |

fix: alignment issue of the add child record button in the tree table

---

packages/core/client/src/block-provider/hooks/index.ts
packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.Item.tsx

| 🇺🇸 English |       In the collapse block, clicking the clear button in the relationship field search box should not delete the data range    |
| 🇨🇳 Chinese |     折叠面板区块中，当点击关系字段搜索框的清空按钮后，不应该删除数据范围      |

fix(Collapse): issue with data scope being cleared

---

packages/core/client/src/schema-settings/LinkageRules/index.tsx
packages/core/client/src/schema-settings/VariableInput/hooks/useFormVariable.ts

…variable
| 🇺🇸 English |     field linkage rules in filter form block missing 'current form'  variable      |
| 🇨🇳 Chinese |      筛选表单区块的字段联动规则缺少 "当前表单" 变量     |

fix: field linkage rules in filter form block missing 'current form'  variable

---

packages/plugins/@nocobase/plugin-action-custom-request/src/client/hooks/useCustomizeRequestActionProps.ts

| 🇺🇸 English |  custom request response set to variable not displaying correctly         |
| 🇨🇳 Chinese |   自定义请求成功后返回信息设置为变量未正确显示        |

fix(custom-request): custom request response set to variable not displaying correctly

---

packages/core/client/src/modules/fields/component/SubTable/subTablePopoverComponentFieldSettings.tsx
packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
packages/core/client/src/schema-component/antd/form-item/hooks/useLinkageRulesForSubTableOrSubForm.ts

| 🇺🇸 English | 子表格中子表单（弹窗）联动规则缺少字段属性设置      |
| 🇨🇳 Chinese |   missing field property settings in field linkage rules for subform (popup) in subtable        |

fix: missing field property settings in field linkage rules for subform (popup) in subtable

---

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchLinkActionSchemaInitializerItem.tsx

| 🇺🇸 English |    duplicate linkage rules in the operation panel's link action         |
| 🇨🇳 Chinese |   操作面板link操作出现两个联动规则        |

fix:  duplicate linkage rules in the operation panel's link action

---

packages/core/client/src/schema-initializer/utils.ts

| 🇺🇸 English |       Fix the issue where one-to-many field sub-fields cannot be selected as filtering options in filter forms    |
| 🇨🇳 Chinese |     修复无法在筛选表单中选择一对多字段的子字段作为筛选项的问题      |

fix: exclude 'attachmentURL' from associated form item filter

---

packages/core/client/src/modules/fields/component/SubTable/subTablePopoverComponentFieldSettings.tsx
packages/core/client/src/schema-component/antd/form-item/hooks/useLinkageRulesForSubTableOrSubForm.ts

…btable
| 🇺🇸 English |   issue with configuring linkage rules in subform (popup) within subtable         |
| 🇨🇳 Chinese |    子表格中子表单（弹窗）无法配置联动规则的     |

fix: issue with configuring linkage rules in subform (popup) within subtable

---

packages/core/client/src/schema-component/antd/variable/Input.tsx
packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx

| 🇺🇸 English | when variable selection requires async loading, the last selected menu is lost. |
| 🇨🇳 Chinese | 变量选择时，若需要异步加载，则会丢失最后选中的菜单 |

fix: incorrect variable selection when first click to load data

---

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx

| 🇺🇸 English |    subtable pagination bar style issue in read-only mode       |
| 🇨🇳 Chinese |     阅读模式下子表格分页栏被遮住      |

fix: subtable pagination bar style issue in read-only mode

---

packages/core/database/src/__tests__/eager-loading/eager-loading-tree.test.ts
packages/core/database/src/dialects/mariadb-dialect.ts

Fix belongs-to association not loaded in appends when foreign key is bigInt under MariaDB.
https://github.com/sequelize/sequelize/issues/12390
| 🇺🇸 English | Fix belongs-to association not loaded in appends when foreign key is bigInt under MariaDB |
| 🇨🇳 Chinese | 修复多对一关系字段在 MariaDB 下外键为大整数配置了 appends 时无法加载的问题 |

fix(database): eager load belongsTo got null on bigint foreign key

---

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
packages/core/client/src/schema-component/antd/action/Action.tsx

…y confirmation
| 🇺🇸 English |     variable parsing incompatibility with {{title}} data in secondary confirm      |
| 🇨🇳 Chinese |      二次确认变量解析不兼容{{title}}数据     |

fix: variable parsing incompatibility with {{title}} data in secondary confirm

---

packages/plugins/@nocobase/plugin-action-duplicate/src/client/DuplicateAction.tsx

| 🇺🇸 English |   modal closes on first input click when editing duplicated data        |
| 🇨🇳 Chinese |  复制数据后编辑时，首次点击字段输入会关闭弹窗的问题         |

fix(duplicate-action): modal closes on first input click when editing duplicated data

---

packages/core/client/src/collection-manager/interfaces/password.ts
packages/core/client/src/schema-component/antd/linkageFilter/LinkageFilterItem.tsx

| 🇺🇸 English |      operator missing when switching in linkage rules     |
| 🇨🇳 Chinese |    联动规则中切换操作符时操作符缺失       |

fix: missing operator in linkage rule

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/block/ChartBlockProvider.tsx

| 🇺🇸 English | Chart blocks do not display when added to popups triggered from block-level actions          |
| 🇨🇳 Chinese |  在区块级别操作中打开弹窗，添加图表不显示         |

fix(data-vi): chart blocks do not display when added to popups triggered from block-level actions

---

packages/core/client/src/modules/fields/component/FileManager/fileManagerComponentFieldSettings.tsx
packages/core/client/src/modules/fields/component/FileManager/previewComponentFieldSettings.tsx
packages/core/client/src/modules/fields/component/FileManager/uploadAttachmentComponentFieldSettings.tsx
packages/core/client/src/schema-component/antd/upload/Upload.tsx

| 🇺🇸 English |  add more built-in size settings for read status image         |
| 🇨🇳 Chinese |    增加阅读状态图片的内置尺寸选项       |

refactor: add more built-in sizes for read status image

---

packages/core/client/src/schema-settings/SchemaSettingsDataScope.tsx

| 🇺🇸 English |   missing current form variables in data scope of data selector table        |
| 🇨🇳 Chinese |    表单中数据选择器表格的数据范围应支持当前表单变量       |

fix: missing current form variables in data scope of data selector table

---

packages/core/client/src/application/RouterManager.tsx
packages/plugins/@nocobase/plugin-block-workbench/src/client/components/qrcode-scanner/useScanner.ts

Read the route basename from the scanner to adapt for the desktop environment.
| 🇺🇸 English |     Read the route basename from the scanner to adapt for the desktop environment.      |
| 🇨🇳 Chinese |   读取扫码器中的路由 basename，以适配桌面端。        |

fix(scanner): read the route basename from the scanner to adapt for the desktop environment

---

packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx

| 🇺🇸 English |      cascade component in modal not loading association data initially      |
| 🇨🇳 Chinese |      关系字段使用级联组件时，在弹窗首次打开未显示数据     |

fix:  cascade component in modal not loading association data initially

---

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx

在 Select 组件的 `onChange` 回调中，原使用 `value?.length !== 0 ? value : null` 来判断输入值是否为空。
这种写法适用于数组类型，但若传入的是一个包含 `length: 0` 属性的对象，则会被错误地识别为“空值”，导致数据被转换为 `null` 并丢失值。
- 修改了 `onChange` 中对空值的判断逻辑
- 前提条件：关联的对象中有一个名为length的数字类型的字段
- 修改前
将含有length=0的对象判断为控制，值丢失
- 修改后 
能正确读取值
| 🇺🇸 English |    Fix issue where objects with `length: 0` are incorrectly converted to null in the Select component       |
| 🇨🇳 Chinese |  修复 Select 组件中对具有 `length: 0` 的对象被错误转为 null 的问题 |
| 🇨🇳 Chinese |     |

fix: handle non-array values in select onChange

---

packages/core/client/src/application/globalOperators.js

…kage rules
| 🇺🇸 English |   incorrect empty value check for toMany association field in linkage rule        |
| 🇨🇳 Chinese |   联动规则中对多关系字段的为空判断不正确        |

fix: fix: incorrect empty value check for toMany association field in linkage rule

---

packages/core/client/src/schema-settings/LinkageRules/LinkageRuleAction.tsx

| 🇺🇸 English |   missing current object variable in linkage rule inside subtable         |
| 🇨🇳 Chinese |    子表格中联动规则缺少当前对象变量       |

fix: missing current object variable in linkage rule inside subtable

---

packages/plugins/@nocobase/plugin-collection-tree/src/server/__tests__/path.test.ts
packages/plugins/@nocobase/plugin-collection-tree/src/server/commands/sync-path.ts
packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts

Previously, path updates used `$startsWith` on path strings, which could mistakenly include nodes with similar prefixes (e.g. `/1/21` matched when updating `/1/2`). This caused unintended path changes. Now uses precise matching: `$or` with both exact path and strict prefix.
Also provide a command for re-syncing path collection.
| 🇺🇸 English | Avoid incorrect updates to similar path prefixes during path updates          |
| 🇨🇳 Chinese |  更新路径表的时候避免由于匹配到相似前缀，导致错误更新         |

fix(tree-collection): avoid incorrect updates to similar path prefixes during path updates

---

packages/core/client/src/schema-component/antd/error-fallback/ErrorFallback.tsx

Fix the issue with the copy button in the error pop-up copying out as [object Object].
| 🇺🇸 English |     Fix the issue with the copy button in the error pop-up copying out as [object Object].      |
| 🇨🇳 Chinese |      修复错误弹窗里的复制按钮复制出来是[object Object]的问题     |

fix: the copy button in the error pop-up copying out as [object Object]

---

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx

| 🇺🇸 English |   paginate association field dropdown data with page size of 200        |
| 🇨🇳 Chinese |    关系字段下拉请求数据按 200 条分页       |

fix: paginate association field dropdown data with page size of 200

---

packages/core/client/src/variables/VariablesProvider.tsx

…ead of using form value
| 🇺🇸 English |     subtable linkage variable fetches association data on clear instead of using form value      |
| 🇨🇳 Chinese |    修复编辑表单中子表格联动规则在清空关系字段后触发请求，未使用表单实时值计算值     |

fix: subtable linkage variable fetches association data on clear instead of using form value

---

packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts
packages/core/client/src/variables/VariablesProvider.tsx

…variable with empty value
| 🇺🇸 English | association field in subtable triggering request when iteration variable with empty value           |
| 🇨🇳 Chinese |    修复子表格中使用当前对象关系字段值作为变量值时，当关系字段值为空会发起请求的问题       |

fix: association field in subtable triggering request when iteration variable with empty value 

---

packages/core/client/src/schema-component/antd/association-field/components/CreateRecordAction.tsx
packages/plugins/@nocobase/plugin-action-duplicate/src/client/DuplicateAction.tsx

| 🇺🇸 English |     issue where select association field popup closes on first input when adding new data      |
| 🇨🇳 Chinese |     修复下拉关系字段组件新增数据时，首次打开弹窗输入内容会自动关闭弹窗的问题      |

fix：issue where select association field popup closes on first input when adding new data

---

packages/core/client/src/schema-component/antd/input/ReadPretty.tsx

| 🇺🇸 English |      Fix the issue where single-line text field values are displayed as an array in esay-reading mode     |
| 🇨🇳 Chinese |     修复单行文本字段阅读模式下，值会显示成一个数组的问题      |

fix: handle array values in ReadPretty.Input component

---

packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/utils.tsx

Use `filterByTk` instead of `filter` under selected mode.
| 🇺🇸 English | Use `filterByTk` instead of `filter` under selected mode |
| 🇨🇳 Chinese | 在选择模式下使用 `filterByTk` 代替 `filter` 作为筛选参数 |

fix(plugin-action-bulk-edit): use filterByTk instead of filter under selected mode

---

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx

… unsaved changes warning
| 🇺🇸 English |   switching page in subtable of detail block within modal triggers unsaved changes warning   |
| 🇨🇳 Chinese |     修复弹窗详情区块子表格翻页触发未保存提示的问题      |

fix: switching page in subtable of detail block within modal triggers unsaved changes warning

---

packages/core/client/src/schema-component/antd/block-item/BlockItemCard.tsx

…modal button
| 🇺🇸 English |     markdown block linkage rules not working when triggered by popup action       |
| 🇨🇳 Chinese |    修复弹窗按钮中的 Markdown 区块联动规则不生效的问题
|

fix: markdown block linkage rules not working when triggered by popup action

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/index.tsx

| 🇺🇸 English | Checkbox group fields in charts should display labels instead of raw values          |
| 🇨🇳 Chinese | 复选框字段在图表中应该显示标签值而不是原始值          |

fix(data-vi): checkbox group fields in charts should display labels instead of raw values

---

packages/core/client/src/modules/blocks/filter-blocks/FilterCollectionField.tsx

| 🇺🇸 English |    select field options not working in filter form linkage rules       |
| 🇨🇳 Chinese |    修复筛选表单中联动规则设置下拉选项字段的 options 不生效问题       |

fix: select field options not working in filter form linkage rules

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/TriggerCollectionRecordSelect.tsx

Fix error thrown in manual execute action when trigger not configured correctly.
| 🇺🇸 English | Fix error thrown in manual execute action when trigger not configured correctly |
| 🇨🇳 Chinese | 修复触发器未正确配置时手动执行的报错 |

fix(pluginw-workflow): fix error thrown in manual execute action

---

packages/core/client/src/schema-component/antd/action/Action.tsx

…p form
| 🇺🇸 English |    auto-closing issue when configuring fields in the secondary popup form        |
| 🇨🇳 Chinese |     修复二级弹窗配置表单字段时自动关闭弹窗的问题      |

fix: auto-closing issue when configuring fields in the secondary popup form

---

packages/plugins/@nocobase/plugin-data-visualization/src/client/settings/chartFilterItem.tsx

| 🇺🇸 English |    incorrect display of between date field in chart filter       |
| 🇨🇳 Chinese |     修复图表区块中筛选表单的日期字段设置为“介于”时组件未正确显示的问题  |

fix(chart-filter): incorrect display of between date field in chart filter

---

packages/core/database/src/__tests__/operator/eq.test.ts
packages/core/database/src/operators/eq.ts

| 🇺🇸 English |  make eq operator for string fields compatible with number type  |
| 🇨🇳 Chinese |  string 类型字段的 eq 操作符兼容 number 类型  |

fix: make eq operator for string fields compatible with number type

---

packages/core/client/src/collection-manager/Configuration/EditFieldAction.tsx

… not checked
| 🇺🇸 English |        After creating the reverse relation field, the option "Create reverse relation field in the target data table" in the association field settings was not checked.   |
| 🇨🇳 Chinese |     创建反向关系字段后，编辑关系字段设置项“在目标数据表里创建反向关系字段”未勾选      |

fix(client): reverse field missing in target table if "create reverse" unchecked

---

packages/core/client/src/schema-initializer/utils.ts

| 🇺🇸 English |   incorrect Markdown (Vditor) rendering in subtable        |
| 🇨🇳 Chinese |    修复子表格中 Markdown（Vditor）字段组件渲染不正确的问题       |

fix: incorrect Markdown (Vditor) rendering in subtable

---

packages/core/client/src/block-provider/BlockSchemaComponentProvider.tsx
packages/core/client/src/modules/blocks/data-blocks/grid-card/__tests__/createGridCardBlockSchema.test.ts
packages/core/client/src/modules/blocks/data-blocks/grid-card/createGridCardBlockUISchema.ts
packages/core/client/src/modules/blocks/data-blocks/grid-card/hooks/useGridCardActionBarProps.ts
packages/core/client/src/schema-component/antd/action/ActionBar.tsx

Need to recreate the Grid card block for this to take effect.
| 🇺🇸 English |       Auto-hide grid card block action bar when empty    |
| 🇨🇳 Chinese |     网格卡片区块操作栏为空时自动隐藏      |

feat:  auto-hide grid card block action bar when empty 

---

packages/core/client/src/schema-component/antd/input/ReadPretty.tsx

| 🇺🇸 English |       Table column text alignment function is not working    |
| 🇨🇳 Chinese |     表格列的文本对齐功能无效      |

fix(ReadPretty): apply conditional flex styling based on ellipsis prop

---

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx

…able
| 🇺🇸 English |     association field default value overrides existing data in sub-table      |
| 🇨🇳 Chinese |   修复 编辑表单中子表格的关系字段设置的默认值覆盖已有数据的问题        |

fix: association field default value overrides existing data in sub-table

---

packages/core/client/src/collection-manager/interfaces/dateOnly.ts
packages/core/client/src/schema-component/antd/date-picker/util.ts
packages/core/database/src/operators/date.ts
packages/core/utils/src/date.ts
packages/core/utils/src/parse-filter.ts

…ds using Exact day variable
| 🇺🇸 English |   filtering issue on DateOnly or Datetime (without time zone) using Exact day variable   |
| 🇨🇳 Chinese |    修复使用 Exact day 变量过滤 DateOnly 或 Datetime (without time zone) 字段时筛选错误的问题       |

fix: filtering error on DateOnly or Datetime (without time zone) using Exact day variable

---

packages/core/client/src/modules/blocks/data-blocks/form/hooks/useDataFormItemProps.ts

| 🇺🇸 English |     background color style issue  in subtable on detail block       |
| 🇨🇳 Chinese |       修复详情区块中子表格设置背景颜色时样式重复的问题    |

fix: background color style issue  in subtable on detail block

---

packages/core/client/src/schema-component/antd/form-v2/Templates.tsx

| 🇺🇸 English |      Fix the error issue with filter forms in the Duplicate button popup     |
| 🇨🇳 Chinese |     修复复制按钮弹窗中，筛选表单报错的问题      |

fix: prevent template assignment in filter form block

---

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx

| 🇺🇸 English |  set default week start day to 'monday' in calendar block       |
| 🇨🇳 Chinese |    日历区块周起始日默认为周一       |

fix(calendar): set default week start day to 'monday' when value 

---

packages/core/client/src/schema-component/antd/page/PagePopups.tsx

| 🇺🇸 English |       Fix the issue where clicking buttons cannot open popups    |
| 🇨🇳 Chinese |     修复点击按钮无法打开弹窗的问题      |

fix(PagePopups): clean up popup layer state on unmount

---

packages/core/cli/src/util.js

Before installing the plugin, the environment verification ignores the mac address verification
安装插件前环境校验忽略mac地址校验

fix: cli ignore mac address verification

---

packages/core/client/src/document-title/index.tsx
packages/core/client/src/schema-component/antd/page/Page.tsx

| 🇺🇸 English |       Browser tab title is not synchronized when switching between submenus    |
| 🇨🇳 Chinese |     子菜单切换时浏览器标签标题未同步更新      |

fix(DocumentTitleProvider): add setTimeout to update document title

---

packages/core/auth/src/base/jwt-service.ts

| 🇺🇸 English |  Fix the issue where an empty `secret` in sub-application configuration prevents sign-in         |
| 🇨🇳 Chinese | 修复子应用配置中 `secret` 为空，无法登录的问题          |

fix(auth): use the `APP_KEY` environment variable as a fallback for the app secret key

---

packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/utils.tsx
packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx

| 🇺🇸 English |      Unable to perform bulk edit and bulk update in data selector     |
| 🇨🇳 Chinese |     数据选择器中无法进行批量编辑和批量更新      |

fix: add useTableSelectorContext to bulk edit and update action props

---

packages/core/client/src/schema-component/antd/page/pagePopupUtils.tsx
packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowManualProvider.tsx

| 🇺🇸 English |      storePopupContext supports saving default context     |
| 🇨🇳 Chinese |     storePopupContext 支持保存默认的上下文      |

fix: enhance popup context storage to use default values when missing

---

packages/core/client/src/schema-component/antd/linkageFilter/LinkageFilterItem.tsx

| 🇺🇸 English |  missing current object variable in sub-table linkage rules         |
| 🇨🇳 Chinese |    修复 子表单联动规则中缺失当前对象变量的问题       |

fix: missing current object variable in sub-table linkage rules

---

packages/core/utils/src/parse-date.ts

| 🇺🇸 English |    incorrect timezone handling for parseDate       |
| 🇨🇳 Chinese |    修复 parseDate 解析时间变量时区处理错误的问题       |

fix: incorrect timezone handling for parseDate

---

packages/core/client/src/modules/blocks/filter-blocks/FilterCollectionField.tsx

| 🇺🇸 English |       When using variables to set field default values in filter forms, if the variable value is empty, the input box will display the original variable string    |
| 🇨🇳 Chinese |     当在筛选表单中使用变量设置字段默认值，且变量值为空时，输入框中会显示变量的原始字符串      |

fix(filter): prevent variable string display issue

---

packages/plugins/@nocobase/plugin-file-previewer-office/src/client/index.tsx

Allow `.docx`, `.xlsx` and `.pptx` file with only URL to be previewed.
| 🇺🇸 English | Support `.docx`, `.xlsx` and `.pptx` file with only URL to be previewed |
| 🇨🇳 Chinese | 支持 URL 中包含 `.docx`, `.xlsx` 和 `.pptx` 的文件预览 |

fix(plugin-file-previewer-office): fix type matching

---

packages/plugins/@nocobase/plugin-workflow/src/client/components/WorkflowTitle.tsx

Show normal title when disabled.
| 🇺🇸 English | Show normal title when disabled |
| 🇨🇳 Chinese | 工作流禁用后也展示正常的标题 |

fix(plugin-workflow): show normal title when disabled

---

packages/plugins/@nocobase/plugin-workflow-parallel/src/server/ParallelInstruction.ts
packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts

Fix parallel node suspend after resume under MySQL.
`await job.save()` may cause BigInt issue in MySQL.
| 🇺🇸 English | Fix parallel node suspend after resume under MySQL |
| 🇨🇳 Chinese | 修复 MySQL 下并行分支节点在恢复执行后假死的问题 |

fix(plugin-workflow-parallel): fix suspend

---

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts

Avoid error thrown caused by publishing to event queue when stopping.
Should not use event queue when app stopping.
| 🇺🇸 English | Avoid error thrown caused by publishing to event queue when stopping |
| 🇨🇳 Chinese | 避免应用停止时调用队列报错 |

fix(plugin-workflow): avoid error thrown when stopping

---

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx

| 🇺🇸 English |   calendar event item tooltip showing [object Object]        |
| 🇨🇳 Chinese |    修复了日历事件悬停提示框未显示事件标题字段内容，显示为 “[object Object]” 的问题      |

fix: calendar event item tooltip showing [object Object]

---

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx

Support displaying icons identified by strings in the Select component when in read-only mode.
| 🇺🇸 English | Support displaying icons identified by strings in the Select component when in read-only mode |
| 🇨🇳 Chinese | 支持 Select 组件在阅读态时可以展示字符串标识的图标 |

refactor(client): support read-pretty select to use string icon

---

packages/plugins/@nocobase/plugin-block-template/src/client/utils/template.ts
packages/plugins/@nocobase/plugin-block-template/src/server/utils/template.ts

| 🇺🇸 English | Resolved an issue where mail blocks were not visible when placed inside an inherited template block |
| 🇨🇳 Chinese | 修复了邮件区块在继承模版中不可见的问题 |

fix: invisible mail block if inside inherited block template

---

packages/core/client/src/schema-component/antd/upload/shared.ts

To show file icon based on extname correctly.
File URL with search parameters not show correct icon.
https://forum.nocobase.com/t/url/6821
| 🇺🇸 English | Fix the issue where the icon was displayed incorrectly when the URL in the attachment URL field contained query parameters |
| 🇨🇳 Chinese | 修复附件 URL 字段的 URL 中包含查询参数时图标展示不正确的问题 |

fix(client): fix file icon

---

packages/plugins/@nocobase/plugin-file-manager/src/client/FileManagerProvider.tsx

Fix the error when editing the `storage` field in the file collection.
| 🇺🇸 English | Fix the error when editing the `storage` field in the file collection. |
| 🇨🇳 Chinese | 修复文件表的 storage 字段编辑时的报错 |

fix(plugin-file-manager): fix error when show storages collection as target

---

packages/core/client/src/application/globalOperators.js

| 🇺🇸 English |    incorrect 'not empty' check for numeric fields in linkage rule       |
| 🇨🇳 Chinese |    联动规则数值字段「不为空」判断错误        |

fix: incorrect 'not empty' check for numeric fields in linkage rule

---

packages/plugins/@nocobase/plugin-action-import/src/server/actions/import-xlsx.ts
packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts

Support setting of row data default values ​​when importing table data
| 🇺🇸 English |     Support setting of row data default values ​​when importing table data      |
| 🇨🇳 Chinese |    导入表格数据时支持设置行数据默认值       |

fix: import xlsx with defaut values

---

packages/plugins/@nocobase/plugin-workflow/.env.example
packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/nodes.test.ts
packages/plugins/@nocobase/plugin-workflow/src/server/actions/nodes.ts

Support to limit the maximum number of nodes in a workflow through environment variables.
| 🇺🇸 English | Support to limit the maximum number of nodes in a workflow through environment variables |
| 🇨🇳 Chinese | 支持通过环境变量限制一个工作流中的最大节点数 |

feat(plugin-workflow): add node limit env
