packages/core/server/src/middlewares/validate-filter-params.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/role-resource.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/validate-filter-params.test.ts, packages/plugins/@nocobase/plugin-auth/src/server/__tests__/actions.test.ts
=> chore: empty filter check

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx, packages/core/client/src/schema-component/antd/date-picker/__tests__/date-picker.test.tsx
=> fix: test error

.vscode/launch.json, packages/core/cli/src/commands/dev.js
Fix command and add shortcut.
| 🇺🇸 English | fix command and add shortcut |
| 🇨🇳 Chinese | 修复开发命令并添加参数缩写 |
=> chore(command): fix command and add shortcut

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Fix transaction across data sources which cause collection event error.
1. Add a sync collection event on external datasource.
2. Trigger the event.
* Expected: triggered.
* Actually: not triggered, with error.
| 🇺🇸 English | Fix transaction across data sources which cause collection event error |
| 🇨🇳 Chinese | 修复由于事务引起的外部数据源数据表同步事件触发错误 |
=> fix(plugin-workflow): fix transaction across data sources

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/OnField.tsx
Fix date type missed in date field based schedule configuration.
| 🇺🇸 English | Fix date type missed in date field based schedule configuration |
| 🇨🇳 Chinese | 修复定时任务时间字段配置中缺少的日期类型 |
=> fix(plugin-workflow): fix date type for schedule field

packages/core/client/src/schema-initializer/utils.ts
| 🇺🇸 English |    Fix display issue for inherited fields in form configuration       |
| 🇨🇳 Chinese |    修复表单配置字段继承字段的显示问题       |
=> fix(client): display issue for inherited fields in form configuration

packages/core/client/src/schema-initializer/utils.ts
| 🇺🇸 English |  Fix  issue with external data source fields not display in table block        |
| 🇨🇳 Chinese |    修复表格区块中外部数据源字段列表没有显示       |
=> fix: issue with external data source fields not display in table block

packages/core/client/src/modules/blocks/data-blocks/details-multi/__e2e__/schemaInitializer.test.ts, packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaInitializer.test.ts, packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/subTable.test.ts, packages/core/client/src/modules/variable/__e2e__/currentObject.test.ts, packages/core/client/src/modules/variable/__e2e__/parentObject.test.ts, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/manyToOne/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/singleLineText/schemaSettings.test.ts
=> fix: sub-table e2e test

packages/plugins/@nocobase/plugin-action-export/src/client/useExportAction.tsx
=> fix: export by association

packages/core/client/src/api-client/APIClient.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/setCurrentRole.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts
| 🇺🇸 English |  Refresh the page when the user's role is incorrect  |
| 🇨🇳 Chinese |  用户角色不对时刷新页面 |
=> fix(acl): refresh the page when the user's role is incorrect

packages/core/acl/src/acl.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/list-action.test.ts
| 🇺🇸 English |    Fix the problem of using fields to query the relationship in the ACL       |
| 🇨🇳 Chinese |     修复 ACL 中使用 fields 查询关系的问题      |
=> fix: acl with association in fields params

packages/plugins/@nocobase/plugin-action-import/src/client/useImportAction.ts, packages/plugins/@nocobase/plugin-action-import/src/server/actions/import-xlsx.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
=> fix: import by associations

packages/plugins/@nocobase/plugin-calendar/src/client/__tests__/createCalendarBlockSchema.test.ts, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calender.Settings.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/createCalendarBlockUISchema.ts, packages/plugins/@nocobase/plugin-calendar/src/locale/zh-CN.json
| 🇺🇸 English |     Calendar plugin add event opening mode      |
| 🇨🇳 Chinese |    日历插件添加事项打开模式     |
=>  plugin-calendar add event open method

.gitignore, packages/core/client/src/schema-component/hooks/useDesignable.tsx, packages/core/sdk/src/APIClient.ts
Provide auxiliary support for template printing functionality.
| 🇺🇸 English |     Provide auxiliary support for template printing functionality.      |
| 🇨🇳 Chinese |   为模版打印功能提供辅助支持        |
=> feat(template-print-support): provide auxiliary support for template printing functionality

packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx
=> fix: markdown variables

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx, packages/core/client/src/schema-settings/__e2e__/SchemaToolbar.test.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-action-custom-request/src/client/initializer/CustomRequestInitializer.tsx
| 🇺🇸 English |        Fix the issue where the 'Custom Request' button is not immediately visible after being added   |
| 🇨🇳 Chinese |      修复添加“自定义请求”按钮后，不会立即显示的问题     |
=> fix(custom-request): fix refresh issue

packages/core/server/src/application.ts
| 🇺🇸 English |   Set the default available actions for the ACL  |
| 🇨🇳 Chinese |  为 ACL 设置默认的可用操作         |
=> fix(acl): set default available actions

packages/core/client/src/block-provider/FormBlockProvider.tsx
| 🇺🇸 English |     Fix data template issue in filter form configured in association field record picker     |
| 🇨🇳 Chinese |    修复 关系字段 record picker 中配置的筛选表单出现数据模板缺陷       |
=> fix: data template issue in filter form

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/block-provider/TemplateBlockProvider.tsx, packages/core/client/src/modules/fields/component/DatePicker/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/menu/__e2e__/schemaSettings1.test.ts
| 🇺🇸 English |       Fix the issue where association fields in reference templates sometimes do not display data    |
| 🇨🇳 Chinese |     修复在引用模板中的关系字段，有时会不显示数据的问题      |
=> fix(template): fix the issue of association field data loss

packages/core/client/src/application/CustomRouterContextProvider.tsx
| 🇺🇸 English |       Fix the issue where refreshing the page in the data source management page redirects to the homepage    |
| 🇨🇳 Chinese |     修复在数据源管理页面刷新页面后，会跳转到首页的问题      |
=> fix: fix page navigation issues

packages/core/client/src/pm/PluginManager.tsx, packages/core/client/src/pm/PluginSetting.tsx
| 🇺🇸 English |       Fix the issue where the browser tab title doesn't update after switching pages    |
| 🇨🇳 Chinese |      修复切换页面后，浏览器标签名称未更新的问题     |
=> fix(documentTitle): fix the issue of browser tab title not refreshing

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx
| 🇺🇸 English |   Fix mobile adaptation of date component on sub-page        |
| 🇨🇳 Chinese |    修复 移动端子页面日期组件未适配为移动端组件       |
=> fix: mobile adaptation of date component on sub-page

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx
=> fix: mobile client test

packages/core/client/src/schema-component/antd/upload/Upload.tsx
Remove debug code.
| 🇺🇸 English | Remove debug code |
| 🇨🇳 Chinese | 移除前端组件中的调试代码 |
=> chore(client): remove console.log

packages/core/sdk/src/APIClient.ts, packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/Edit.tsx
| 🇺🇸 English |  Remove the default locale   |
| 🇨🇳 Chinese | 移除默认 locale  |
=> fix: remove the default locale

packages/core/database/src/__tests__/interfaces/datetime-interface.test.ts, packages/core/database/src/__tests__/value-parsers/date.test.ts, packages/core/database/src/interfaces/datetime-interface.ts, packages/core/database/src/interfaces/datetime-no-tz-interface.ts
=> chore: datetime parser

packages/core/client/src/block-provider/hooks/useParsedFilter.ts, packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/lazyLoadVariables.test.ts, packages/core/client/src/modules/fields/__e2e__/component/AssociationSelect/dataScope.test.ts, packages/core/client/src/modules/fields/__e2e__/component/AssociationSelect/templatesOfBug.ts, packages/core/client/src/schema-settings/hooks/useParseDataScopeFilter.ts
| 🇺🇸 English |       Fix the issue where nested association field variables in data scope have empty values    |
| 🇨🇳 Chinese |      修复数据范围中，选择嵌套的关系字段变量，变量值为空的问题     |
=> fix(dataScope): fix issue with nested association field variables

packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/query.ts
| 🇺🇸 English | Allows to use foreign keys in query configuration of charts          |
| 🇨🇳 Chinese | 支持在图表的查询配置中使用外键          |
=> fix(data-vi): allows to use foreign keys in query configuration of charts

packages/core/acl/src/acl.ts, packages/core/server/src/middlewares/data-template.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/get-action.test.ts
| 🇺🇸 English |    Fixed issues related to replication records after configuring permissions        |
| 🇨🇳 Chinese |    修复配置权限之后复制记录相关问题       |
=> fix: template with appends

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
| 🇺🇸 English |       Fix the issue where extra 'N/A' options sometimes appear in association field dropdowns    |
| 🇨🇳 Chinese |     修复关系字段的下拉选项中，有时会出现多余的 “N/A” 选项的问题      |
=> fix(RemoteSelect): fix 'N/A' issue

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Fix loading workflow in manually executing.
Error thrown when preparing processor in resume phase.
| 🇺🇸 English | Fix error thrown when async node resuming in manually executing workflow |
| 🇨🇳 Chinese | 修复手动执行未启用工作流在异步节点报错的问题 |
=> fix(plugin-workflow): fix loading workflow in manually executing

packages/core/server/src/audit-manager/index.ts, packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts
| 🇺🇸 English |     Optimize the logic of getting metadata of audit actions.    |
| 🇨🇳 Chinese |     优化获取审计操作的 metadata 的逻辑      |
=> refactor(audit-manager): optimize the logic of getting metadata

packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/chart.ts
| 🇺🇸 English |  Fix the initial height of chart block         |
| 🇨🇳 Chinese |  修复图表区块的初始高度         |
=> fix(data-vi): height issue

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
…izontal
| 🇺🇸 English |    Fix issue with group styles in form blocks when layout is set to horizontal       |
| 🇨🇳 Chinese |     修复：表单区块分组在水平布局下样式异常      |
=> fix: issue with group styles in form blocks when layout is set to horizontal

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx
=> fix: collection select client test

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx
…heme
配置页跟随全局主题，公开表单实际页面不随主题切换改变
| 🇺🇸 English |       Fix issue where global theme switch affects public form preview page theme    |
| 🇨🇳 Chinese |     修复全局切换主题导致公开表单预览页主题被影响的问题
|
=> fix: issue where global theme switch affects public form preview page theme

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx, packages/core/client/src/collection-manager/templates/view.tsx, packages/core/client/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/ConfigurationTable.tsx
| 🇺🇸 English |   Fix PG view creation issue, resolve error when selecting views across schemas        |
| 🇨🇳 Chinese |  修复 PG 视图创建错误，解决跨 schema 选择问题         |
=> fix:pg view creation issue, resolve error when selecting views across schemas

packages/plugins/@nocobase/plugin-user-data-sync/src/client/UserDataSyncSource.tsx, packages/plugins/@nocobase/plugin-user-data-sync/src/client/schemas/user-data-sync-sources.ts
| 🇺🇸 English | Fix display issues of sync and tasks buttons.          |
| 🇨🇳 Chinese | 修复同步和任务按钮的显示问题。          |
=> fix(user-data-sync): display issues of sync and tasks buttons

packages/core/database/src/interfaces/datetime-interface.ts, packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts
=> fix: datetime parser of YYYYMMDD format

packages/core/database/src/__tests__/relation-repository/belongs-to-many-repository.test.ts, packages/core/database/src/__tests__/relation-repository/belongs-to-repository.test.ts, packages/core/database/src/__tests__/relation-repository/has-many-repository.test.ts, packages/core/database/src/__tests__/relation-repository/has-one-repository.test.ts, packages/core/database/src/relation-repository/belongs-to-array-repository.ts, packages/core/database/src/relation-repository/belongs-to-many-repository.ts, packages/core/database/src/relation-repository/belongs-to-repository.ts, packages/core/database/src/relation-repository/hasmany-repository.ts, packages/core/database/src/relation-repository/multiple-relation-repository.ts, packages/core/database/src/relation-repository/relation-repository.ts, packages/core/database/src/relation-repository/single-relation-repository.ts, packages/core/database/src/relation-repository/types.ts, packages/core/database/src/repository.ts, packages/core/database/src/utils/filter-utils.ts
…gsToManyRepository
| 🇺🇸 English |       add firstOrCreate & updateOrCreate  to relation repository  |
| 🇨🇳 Chinese |     关系 repository 支持 firstOrCreate & updateOrCreate      |
=> feat(database): add firstOrCreate and updateOrCreate methods to Relation repository

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |      Fix horizontal scrollbar issue in table within plugin      |
| 🇨🇳 Chinese |      修复 插件中的表格出现横向滚动条     |
=> fix: horizontal scrollbar issue in table within plugin

packages/core/client/src/modules/blocks/data-blocks/form/__tests__/fieldSettingsFormItem.test.tsx, packages/core/client/src/modules/fields/component/CascadeSelect/cascadeSelectComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/DatePicker/datePickerComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/Tag/tagComponentFieldSettings.tsx
| 🇺🇸 English |      Make more components support the 'Ellipsis overflow content' configuration item     |
| 🇨🇳 Chinese |     使更多的组件支持“省略超出长度的内容” 配置项     |
=> feat: add ellipsis configuration support for more components

packages/plugins/@nocobase/plugin-backup-restore/src/server/resourcers/backup-files.ts
=> fix: download api vulnerability

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx
Fix variable input in node test modal.
| 🇺🇸 English | Fix variable input in node test modal |
| 🇨🇳 Chinese | 修复工作流节点测试对话框中的变量输入框无法输入的问题 |
=> fix(plugin-workflow): fix variable input in node test

packages/plugins/@nocobase/plugin-collection-sql/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-collection-sql/src/server/resources/sql.ts
| 🇺🇸 English | Fix the issue where fields disappear after updating an SQL Collection.          |
| 🇨🇳 Chinese | 修复 SQL 数据表更新后字段消失的问题。          |
=> fix: update sql collection

packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/http-api/belongs-to.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/hooks/afterCreateForForeignKeyField.ts
| 🇺🇸 English |     Fixed foreign key loading issues      |
| 🇨🇳 Chinese |    修复外键加载问题       |
=> fix: load foreign key after create

packages/core/client/src/user/EditProfile.tsx, packages/core/client/src/user/LanguageSettings.tsx, packages/plugins/@nocobase/plugin-auth/src/locale/en-US.json, packages/plugins/@nocobase/plugin-auth/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-auth/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-auth/src/server/actions/auth.ts, packages/plugins/@nocobase/plugin-theme-editor/src/client/hooks/useUpdateThemeSettings.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-theme-editor/src/server/actions/update-user-theme.ts, packages/plugins/@nocobase/plugin-theme-editor/src/server/plugin.ts, packages/plugins/@nocobase/plugin-users/src/locale/en-US.json, packages/plugins/@nocobase/plugin-users/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-users/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts
| 🇺🇸 English | Optimize API validation for user profile editing and password updates          |
| 🇨🇳 Chinese | 优化用户资料编辑和密码修改的 API 校验逻辑          |
=> fix(users): optimize API validation for user profile editing and password updates

packages/plugins/@nocobase/plugin-collection-sql/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-collection-sql/src/server/plugin.ts, packages/plugins/@nocobase/plugin-collection-sql/src/server/resources/sql.ts, packages/plugins/@nocobase/plugin-collection-sql/src/server/utils.ts
| 🇺🇸 English | Prohibit the use of dangerous keywords and functions in SQL.          |
| 🇨🇳 Chinese | 禁止在 SQL 中使用危险关键字和函数。           |
=> fix(sql-collection): block dangerous keywords

packages/plugins/@nocobase/plugin-data-visualization/src/client/configure/schemas/configure.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRendererProvider.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/locale/en-US.json, packages/plugins/@nocobase/plugin-data-visualization/src/locale/ja-JP.json, packages/plugins/@nocobase/plugin-data-visualization/src/locale/ko-KR.json, packages/plugins/@nocobase/plugin-data-visualization/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-data-visualization/src/server/query-parser/query-parser.ts, packages/plugins/@nocobase/plugin-data-visualization/src/server/types.ts
For the purpose of data analysis, I need the corresponding interface parameters for support. 
Added the offset parameter to facilitate the construction of paginated requests.
| 🇺🇸 English |  Improvement(data-visualization): add offset param to charts-query |
| 🇨🇳 Chinese |   优化(数据可视化): 图表查询增加 offset 参数（需要构造分页） |
=> feat(data-visualization): add offset param to charts-query

packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/AggregateInstruction.ts, packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/__tests__/instruction.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Fix incorrect aggregation result caused by transaction.
| 🇺🇸 English | Fix incorrect aggregation result caused by transaction |
| 🇨🇳 Chinese | 修复由于事务造成的统计节点结果错误问题 |
=> fix(plugin-workflow): fix transactions between data sources

packages/core/client/src/schema-settings/LinkageRules/LinkageRuleAction.tsx
| 🇺🇸 English |      Fix property field search in linkage rules not matching correct data     |
| 🇨🇳 Chinese |      修复 联动规则中属性字段搜索无法匹配正确数据     |
=> fix: property field search in linkage rules not matching correct data

packages/core/server/src/plugin-manager/plugin-manager.ts
| 🇺🇸 English |  Collections were not automatically created when enabling the plugin  |
| 🇨🇳 Chinese |  激活插件时未自动建表 |
=> fix: collections were not automatically created when enabling the plugin

packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowManualProvider.tsx, packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowTodo.tsx, packages/plugins/@nocobase/plugin-workflow-manual/src/client/index.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-manual/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/actions.ts, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/output.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/subflow.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
Add a fixed global entry for all type of workflow todos.
| 🇺🇸 English | Add a fixed global entry for all type of workflow todos |
| 🇨🇳 Chinese | 为所有类型的工作流待办添加固定的全局入口 |
=> feat(plugin-workflow): add workflow task panel in toolbar

packages/core/client/src/schema-settings/LinkageRules/LinkageRuleAction.tsx, packages/core/database/src/fields/unix-timestamp-field.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/models/field.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/models/data-sources-field-model.ts, packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/defineMyInAppChannels.ts
| 🇺🇸 English |      Fix UnixTimestamp field precision conversion issue     |
| 🇨🇳 Chinese |    修复时间戳字段精度转换问题       |
=> fix: unix timestamp accuracy

packages/plugins/@nocobase/plugin-verification/src/client/ProviderOptions.tsx
| 🇺🇸 English |        Fix empty form fields when opening the edit drawer in the Verification settings page   |
| 🇨🇳 Chinese |      修复在验证码配置页面，打开编辑弹窗，弹窗中的表单不显示值的问题     |
=> fix: update ProviderOptions.tsx

packages/core/client/src/schema-component/antd/upload/Upload.tsx
Remove `console.log` in component.
| 🇺🇸 English | remove useless debug log |
| 🇨🇳 Chinese | 移除不必要的调试日志 |
=> fix(client): remove console.log

packages/core/client/src/block-provider/TableBlockProvider.tsx
| 🇺🇸 English |       Fix the table block error caused by data containing fields named 'children'    |
| 🇨🇳 Chinese |     修复因数据包含 children 命名的字段，而导致表格区块报错的问题      |
=> fix: fix children field error

packages/presets/nocobase/package.json
| 🇺🇸 English |       Enable theme plugin by default    |
| 🇨🇳 Chinese |     默认启动主题插件
=> chore: change default theme to compact mode

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
…r deleting
| 🇺🇸 English |   Fix issue with field assignment in subtable when re-select data after deleting data        |
| 🇨🇳 Chinese |    修复 子表格中通过多对一字段赋值时，删除行记录后再次选择数据未成功赋值的问题       |
=> fix: issue with field assignment in subtable when re-select data after deleting data

packages/core/test/src/server/mock-server.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/server/__tests__/mock-server.test.ts
=> test: sub app agent

packages/core/database/src/relation-repository/relation-repository.ts, packages/core/database/src/relation-repository/types.ts, packages/core/database/src/repository.ts
…ose context
| 🇺🇸 English |  the firstOrCreate and updateOrCreate methods of the repository lose context |
| 🇨🇳 Chinese |  repository 的 firstOrCreate 和 updateOrCreate 方法缺失 context |
=> fix: the firstOrCreate and updateOrCreate methods of the repository lose context

packages/core/client/src/schema-settings/SchemaSettingsDefaultValue.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useContextAssociationFields.tsx
| 🇺🇸 English |  Supports using "Table selected records" variable in m2m array fields         |
| 🇨🇳 Chinese |  支持多对多（数组）字段使用“表格中选中的记录”变量        |
=> feat(m2m-array): supports using "Table selected records" variable in m2m array fields

packages/core/client/src/application/schema-initializer/components/SchemaInitializerItemSearchFields.tsx
| 🇺🇸 English |    Fix  issue  when adding a one-to-one relationship field in the form       |
| 🇨🇳 Chinese |     修复表单中添加对一关系字段时控制台报错      |
=> fix:  issue  when adding a one-to-one relationship field in the form

packages/core/database/src/__tests__/repository.test.ts, packages/core/database/src/repository.ts
| 🇺🇸 English |   Fixed an issue in destory action where filterByTk with filter parameter could not delete data     |
| 🇨🇳 Chinese |     修复 filterByTk 带 filter 参数无法删除数据的问题      |
=> fix: destory with filterByTk

packages/core/client/src/pm/PluginManager.tsx
| 🇺🇸 English | Add a filter keyword "Security" for plugin manager          |
| 🇨🇳 Chinese |  给插件管理器增加“安全性”筛选关键字         |
=> chore: add a filter keyword "Security" for plugin manager

packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |    Fix alignment issue when action column buttons are hidden       |
| 🇨🇳 Chinese |     修复 表格操作列按钮隐藏时没有左对齐      |
=> fix: alignment issue when action column buttons are hidden

packages/core/client/src/collection-manager/Configuration/DeleteCollectionAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/hooks.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
…tion  management
| 🇺🇸 English |    Fix issue with batch deletion of system and general fields in collection manager       |
| 🇨🇳 Chinese |    修复 数据表管理 无法同时删除系统字段和普通字段       |
=> fix: issue with batch deletion of system and general fields in collection manager

packages/plugins/@nocobase/plugin-mobile/src/client/constants.ts, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/styles.ts
| 🇺🇸 English |       Fix the issue of bottom buttons being obscured on mobile devices    |
| 🇨🇳 Chinese |     修复移动端底部按钮被遮挡的问题      |
=> fix(mobile): fix SafeArea not working issue

packages/core/client/src/collection-manager/Configuration/components/index.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/index.tsx
=> refactor: target key

packages/core/client/src/schema-component/antd/list/List.Decorator.tsx
Fix list component style.
| 🇺🇸 English | Fix list component style |
| 🇨🇳 Chinese | 修复列表组件样式 |
=> fix(client): remove useless style

packages/core/client/src/schema-component/antd/table-v2/Table.Column.ActionBar.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Decorator.tsx
| 🇺🇸 English |     Fix style of setting button in compact theme      |
| 🇨🇳 Chinese |      修复紧凑模式下配置按钮错位问题     |
=> fix: style of setting button in compact theme

packages/core/client/src/api-client/APIClient.ts, packages/core/client/src/api-client/__tests__/APIClient.test.tsx, scripts/release/changelogAndRelease.js
| 🇺🇸 English |  Fixed the issue where headers included in client requests were being overwritten         |
| 🇨🇳 Chinese | 修复客户端请求中携带的 headers 被覆盖的问题           |
=> fix(client): fix the issue where headers included in client requests were being overwritten

packages/core/client/src/modules/actions/submit/updateSubmitActionSettings.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/BulkEditAction.Settings.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/BulkEditSubmitActionInitializer.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/index.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/utils.tsx
…inkage rule
| 🇺🇸 English |      Refactor bulk edit form submit button: remove field assignment and linkage rule     |
| 🇨🇳 Chinese |      批量编辑中提交按钮移除字段赋值和联动规则配置项     |
=> refactor: bulk edit form submit button: remove field assignment and linkage rule

packages/plugins/@nocobase/plugin-multi-app-manager/src/server/server.ts
=> chore: throw error when enable multi-app-manager in sub app

packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/common/dnd-context/index.tsx
| 🇺🇸 English |        Fix the issue where table rows cannot be dragged and sorted   |
| 🇨🇳 Chinese |     修复表格行无法拖拽排序的问题      |
=> fix(Table): fix the issue where table rows cannot be dragged

packages/plugins/@nocobase/plugin-map/src/client/components/ReadPretty.tsx
| 🇺🇸 English |    Fix map field in detail block should  render as map block       |
| 🇨🇳 Chinese |    详情区块中的地图字段，应显示地图       |
=> fix(map):  map field in detail block should  render as map block

packages/core/client/src/schema-component/antd/action/Action.style.ts, packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |   Fix misalignment issue when action column buttons are hidden        |
| 🇨🇳 Chinese |    修复 操作列按钮隐藏时没有左对齐的问题       |
=> fix: misalignment issue when action column buttons are hidden

packages/core/client/src/application/Application.tsx, packages/core/client/src/application/__tests__/Application.test.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/desktop-mode/Header.tsx
| 🇺🇸 English |  Add app.getFullUrl() method  |
| 🇨🇳 Chinese |  添加 app.getFullUrl() 方法  |
=> feat: add app.getFullUrl() method

packages/core/client/src/user/CurrentUserProvider.tsx
| 🇺🇸 English |  Continue rendering the page after the authentication check request is completed         |
| 🇨🇳 Chinese |  认证检查请求完成后才继续渲染页面        |
=> fix(client): continue rendering the page after the authentication check is completed

packages/core/database/src/interfaces/to-many-interface.ts, packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts
| 🇺🇸 English |    fix import with belongs to many associations that use different target key       |
| 🇨🇳 Chinese |   修复无法导入使用不同 target key 的多对多关联的问题      |
=> fix: import with associations

packages/core/client/src/modules/actions/__e2e__/link/basic.test.ts, packages/core/client/src/modules/variable/__e2e__/basic.test.ts, packages/core/client/src/schema-component/antd/select/Select.tsx, packages/core/client/src/schema-component/antd/select/__tests__/select.test.tsx, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/manyToMany/schemaSettings1.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/manyToMany/schemaSettings2.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/mutipleSelect/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/client/__e2e__/fields/oneToMany/schemaSettings2.test.ts
| 🇺🇸 English |      support maxTagCount: 'responsive' in multi-select dropdown component     |
| 🇨🇳 Chinese |    下拉多选组件支持 maxTagCount: 'responsive'       |
=> refactor: support maxTagCount:'responsive' in multi-select component

packages/core/client/src/locale/zh-CN.json, packages/core/evaluators/src/client/engines/formulajs.ts, packages/core/evaluators/src/client/engines/mathjs.ts, packages/plugins/@nocobase/plugin-workflow/src/client/components/renderEngineReference.tsx
Change reference links of evaluators to doc site.
| 🇺🇸 English | Change reference links of evaluators to doc site |
| 🇨🇳 Chinese | 将运算引擎的说明文档链接修改为指向文档站 |
=> fix(evaluators): change reference links to doc site

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings2.test.ts, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useFormVariable.ts, packages/core/client/src/schema-settings/__e2e__/linkageRules.test.ts, packages/core/client/src/schema-settings/__e2e__/template.ts
| 🇺🇸 English |       Fix the issue where style rules are not taking effect in sub-details    |
| 🇨🇳 Chinese |     修复子详情中使用“样式规则”不生效的问题      |
=> fix(linkageRules): fix invalid issue of form linkage rules (#5876)

packages/core/database/src/collection.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/models/field.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/resourcers/collections.ts
=> fix: fields sort

packages/core/client/src/schema-settings/LinkageRules/action-hooks.ts
… value)
| 🇺🇸 English |   Support linkage rules in the details block to hide(reserved value)        |
| 🇨🇳 Chinese |     详情区块联动规则支持隐藏并保留值      |
=> refactor: support linkage rules in the details block to hide(reserved value)

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx
=> chore(public-form): get link by app.getHref

packages/core/app/client/.umirc.ts, packages/core/client/src/schema-component/antd/upload/placeholder.ts
| 🇺🇸 English |  Resolve missing public path in icon file paths  |
| 🇨🇳 Chinese |  修复 icon 文件路径未加 public path 的问题  |
=> fix: resolve missing public path in icon file paths

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/ScheduleModes.tsx
Fix value type for DatePicker component.
| 🇺🇸 English | Fix value type for DatePicker component |
| 🇨🇳 Chinese | 修复传入 DatePicker 组件的值参数类型 |
=> fix(plugin-workflow): fix schedule picker value

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/schedule/mode-date-field.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts
Fix date field based schedule event not triggers after app started.
| 🇺🇸 English | Fix date field based schedule event not triggers after app started |
| 🇨🇳 Chinese | 修复基于数据表字段的定时任务在启动后不执行的问题 |
=> fix(plugin-workflow): fix schedule trigger conditions and logs

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |       Fix the issue where fixed actions column are not working properly in tables    |
| 🇨🇳 Chinese |     修复在表格中固定操作列不生效的问题      |
=> fix(table): fix fixed column not working issue

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
| 🇺🇸 English |  Fix style issue in sub-table in detail block         |
| 🇨🇳 Chinese |     去掉详情区块中子表格右侧空隙      |
=> fix: style issue in sub-table in detail block

packages/core/client/src/schema-component/core/SchemaComponent.tsx
| 🇺🇸 English |       Fix the issue where field assignments for form buttons in workflow manual nodes are invalid    |
| 🇨🇳 Chinese |      修复工作流人工节点的表单按钮的字段赋值无效的问题     |
=> fix: avoid invalid refresh method provided

packages/core/client/src/pm/PluginSetting.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.ActionBar.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Decorator.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/hooks/useDesigner.ts
| 🇺🇸 English |    Fix table header cell style issue in ant-table       |
| 🇨🇳 Chinese |     修复 表格样式问题，调整表头单元格样式      |
=> fix: table header cell style issue in ant-table

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx
=> fix: public form style issue

packages/core/client/src/schema-component/antd/table-v2/Table.Column.Decorator.tsx
=> fix: client e2e test

packages/core/database/src/fields/sort-field.ts
| 🇺🇸 English |  fix an issue when init sort field with primary key          |
| 🇨🇳 Chinese |     修复排序字段从主键初始化问题      |
=> fix: init sort field by primary key

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
| 🇺🇸 English |     datePicker component input read only      |
| 🇨🇳 Chinese |      日期选择器组件输入框只读     |
=> feat: datePicker component input read only

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo1.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo2.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo3.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo7.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo8.tsx
=> fix: datePicker client test

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo1.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo2.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo3.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo7.tsx, packages/core/client/src/schema-component/antd/date-picker/demos/demo8.tsx, packages/core/client/src/schema-component/antd/date-picker/util.ts
=> chore: set inputReadOnly for DatePicker based on device type

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/RepeatField.tsx
Fix repeat field component in schedule configuration.
| 🇺🇸 English | Fix repeat field component in schedule configuration |
| 🇨🇳 Chinese | 修复定时任务重复配置字段组件的问题 |
=> fix(plugin-workflow): fix repeat field component

packages/core/client/src/pm/PluginCard.tsx, packages/core/server/src/plugin-manager/plugin-manager.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts, packages/presets/nocobase/src/server/index.ts
| 🇺🇸 English |  Improve the extensibility of file-storage  |
| 🇨🇳 Chinese |  改进文件存储扩展 |
=> feat: improve the extensibility of file-storage

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-create/schemaSettings.test.ts, packages/core/client/src/schema-component/antd/association-field/ReadPretty.tsx
| 🇺🇸 English |      Fix the issue where default values for association fields are not taking effect in Easy-reading mode     |
| 🇨🇳 Chinese |     修复 Easy-reading 模式的关系字段默认值不生效的问题      |
=> fix(defaultValue): fix the issue where the default value of easy reading mode is not taking effect

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts
=> feat: add validateConfig to trigger

packages/core/client/src/collection-manager/templates/sql.tsx
| 🇺🇸 English |  Allows to add descriptions for SQL collections         |
| 🇨🇳 Chinese | 支持给 SQL 数据表添加描述          |
=> feat(sql-collection): allows to add description

packages/core/server/src/gateway/index.ts, packages/core/server/src/gateway/ws-server.ts, packages/plugins/@nocobase/plugin-async-task-manager/src/server/plugin.ts, packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
=> chore: ws api

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/server/ActionTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowCanvas.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/ScheduleModes.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts
Change API name to reasonable ones.
| 🇺🇸 English | Change API name to reasonable ones |
| 🇨🇳 Chinese | 将部分 API 调整为更合理的名称 |
=> refactor(plugin-workflow): refactor validate context api

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calender.Settings.tsx
=> fix: calendar default view locale

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Fix dispatch not process in preparing phase.
| 🇺🇸 English | Fix dispatch not process in preparing phase |
| 🇨🇳 Chinese | 修复在准备阶段的调度未能执行的问题 |
=> fix(plugin-workflow): fix dispatch not process in preparing phase

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/locale/en-US.json, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
=> feat: add stack limit to workflow

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/modules/blocks/data-blocks/details-single/hooks/useDetailsDecoratorProps.ts, packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
| 🇺🇸 English |        Fix the issue where block data is empty in the popup window on the embedded page   |
| 🇨🇳 Chinese |      修复在嵌入页面中，弹窗中的区块数据为空的问题     |
=> fix: fix the issue of empty data when opening popup in embedded page

packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/AggregateInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-delay/src/client/DelayInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/DynamicCalculation.tsx, packages/plugins/@nocobase/plugin-workflow-loop/src/client/LoopInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-mailer/src/client/MailerInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/index.tsx, packages/plugins/@nocobase/plugin-workflow-notification/src/client/NotificationInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-parallel/src/client/ParallelInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-sql/src/client/SQLInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts, packages/plugins/@nocobase/plugin-workflow/src/client/AddNodeContext.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/Branch.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/create.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/destroy.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/end.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/update.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx
Make workflow canvas to contain more content.
| 🇺🇸 English | adjust style of workflow canvas, to make content compacted |
| 🇨🇳 Chinese | 调整工作流画布样式，使内容更紧凑 |
=> refactor(plugin-workflow): adjust canvas style

packages/core/client/src/user/CurrentUserProvider.tsx, packages/core/sdk/src/APIClient.ts, packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts
Fix the issue where accessing the registration page and public form page while not logged in redirects to the login page.
| 🇺🇸 English |  Fix the issue where accessing the registration page and public form page while not logged in redirects to the login page.     |
| 🇨🇳 Chinese |     修复当未登录时访问注册页和公开表单页会重定向至登录页的问题。   |
- [] Test cases are updated/provided or not needed
- [] Doc is updated/provided or not needed
- [] Component demo is updated/provided or not needed
=> fix(auth): fix redirecting unauthenticated users from registration/public forms to the login page

packages/plugins/@nocobase/plugin-verification/src/client/schemas/providers.ts
Provider id should not be editable.
| 🇺🇸 English | Fix provider ID could be edit |
| 🇨🇳 Chinese | 修复提供商 ID 可以被修改的问题 |
=> fix(plugin-verification): provider id should not be editable

packages/plugins/@nocobase/plugin-environment-variables/package.json, packages/plugins/@nocobase/plugin-environment-variables/src/client/components/EnvironmentTabs.tsx, packages/plugins/@nocobase/plugin-environment-variables/src/client/index.tsx, packages/plugins/@nocobase/plugin-environment-variables/src/client/utils.ts, packages/plugins/@nocobase/plugin-environment-variables/src/locale/zh-CN.json
=> feat: variables and secrets

docker/nocobase/docker-entrypoint.sh, packages/core/cli/src/commands/start.js, packages/core/cli/src/util.js, packages/core/server/src/gateway/index.ts
=> fix: permission denied for sock files

packages/plugins/@nocobase/plugin-workflow-loop/src/client/LoopInstruction.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
Fix styles.
| 🇺🇸 English | Fix styles |
| 🇨🇳 Chinese | 修复工作流画布的样式问题 |
=> fix(plugin-workflow): fix styles

packages/plugins/@nocobase/plugin-auth/src/server/collections/issued-tokens.ts, packages/plugins/@nocobase/plugin-auth/src/server/collections/token-poilcy-config.ts
Update migration rules for issued tokens and token policy config.
| 🇺🇸 English |     Update migration rules for issued tokens and token policy config.|
| 🇨🇳 Chinese |  更新 Token 签发表和 token 策略表的迁移规则。         |
=> fix(plugin-auth): update migration rules for issued tokens and token policy config

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
| 🇺🇸 English |  The default value of the assocation field has not been updated  |
| 🇨🇳 Chinese | 关系字段设置的默认值没有更新 |
=> fix: association field default value

.gitignore, packages/core/sdk/src/APIClient.ts
Provide auxiliary support for template printing functionality.
| 🇺🇸 English |     Provide auxiliary support for template printing functionality.      |
| 🇨🇳 Chinese |   为模版打印功能提供辅助支持        |
=> chore(template-print-support): provide auxiliary support for template printing functionality

packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx
| 🇺🇸 English |    Remove drag-and-drop  button in  association  field quick  add new  action      |
| 🇨🇳 Chinese |    关系数据的快捷 添加数据（弹窗）按钮，移除拖拽功能       |
=> fix: drag issue in quick popup add  action  for association field

packages/plugins/@nocobase/plugin-workflow-test/src/server/index.ts
To fix mock datasource test cases depend on ACL.
| 🇺🇸 English | To fix mock datasource test cases depend on ACL |
| 🇨🇳 Chinese | 修复依赖权限控制的多数据源测试用例 |
=> fix(plugin-workflow-test): fix acl for mock data source

packages/core/client/src/schema-component/antd/variable/TextArea.tsx, packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx
=> fix: merge bug

packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
Fix request node pending in loop.
Involved by #6022.
| 🇺🇸 English | Fix request node pending in loop |
| 🇨🇳 Chinese | 修复请求节点在循环调用中状态为等待的问题 |
=> fix(plugin-workflow-request): fix flow bug

packages/core/client/src/data-source/data-block/DataBlockRequestProvider.tsx
| 🇺🇸 English |       Fix the issue where 'data loading mode' becomes invalid after switching pages    |
| 🇨🇳 Chinese |      修复切换页面后“数据加载方式”失效的问题     |
=> fix: loading mode

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |      Fix an issue with displaying N/A for association fields in Table     |
| 🇨🇳 Chinese |     修复表格中关系字段显示 N/A 的问题      |
=> fix(Table): fix incorrect rowKey

packages/core/database/src/__tests__/repository/update.test.ts, packages/core/database/src/repository.ts
| 🇺🇸 English |     Fix update collection that without primary keys      |
| 🇨🇳 Chinese |    修复更新无主键表的问题      |
=> fix: update table value without primary keys

packages/core/client/src/schema-component/antd/association-field/components/CreateRecordAction.tsx
| 🇺🇸 English |  The content is not displayed in the quick add popup   |
| 🇨🇳 Chinese |  快捷新增的弹窗里不显示内容  |
=> fix: the content is not displayed in the quick add popup

packages/core/client/src/block-provider/BlockProvider.tsx
| 🇺🇸 English |       Fix the issue where association field blocks do not request data    |
| 🇨🇳 Chinese |     修复关系字段区块不请求数据的问题      |
=> fix: fix the issue where oho field block does not request data

packages/core/server/src/aes-encryptor.tsx, packages/core/server/src/application.ts, packages/core/server/src/index.ts, packages/plugins/@nocobase/plugin-environment-variables/src/server/plugin.ts
| 🇺🇸 English | move AesEncryptor to the core |
| 🇨🇳 Chinese | 将 AesEncryptor 移至内核 |
=> chore: move AesEncryptor to the core

packages/core/database/src/belongs-to-array/belongs-to-array-repository.ts, packages/core/database/src/filter-parser.ts, packages/core/database/src/index.ts, packages/core/database/src/relation-repository/single-relation-repository.ts, packages/core/database/src/repository.ts, packages/core/database/src/update-associations.ts, packages/core/database/src/utils.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/issues.test.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/m2m-array-bigint-api.test.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/belongs-to-array-field.ts
| 🇺🇸 English | Fix the issue where updating many to many (array) fields in a subform is not working          |
| 🇨🇳 Chinese |  修复在子表单中更新多对多（数组）字段无效的问题         |
=> fix(m2m-array): updating many to many (array) fields in a subform is not working

packages/core/database/src/__tests__/fields/uuid-field.test.ts, packages/core/database/src/operators/string.ts
| 🇺🇸 English |    fix filter by uuid field       |
| 🇨🇳 Chinese |    修复无法按 UUID 筛选的问题      |
=> fix: query uuid field

packages/plugins/@nocobase/plugin-field-china-region/src/server/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts
| 🇺🇸 English |    fix acl permission with chinaRegion       |
| 🇨🇳 Chinese |      修复行政区划关联的权限问题      |
=> chore: append acl strategy resource

packages/core/client/src/schema-component/hooks/useCompile.ts
| 🇺🇸 English |        The data source management page is reporting an error   |
| 🇨🇳 Chinese |      数据源管理页面报错     |
=> fix(useCompile): avoid error

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/modules/fields/__e2e__/ellipsis.test.ts, packages/core/client/src/schema-component/antd/grid/Grid.tsx
| 🇺🇸 English |        Layout anomaly after deleting blocks or fields   |
| 🇨🇳 Chinese |      删除区块或者字段后，布局异常     |
=> fix: should refresh page when deleting block

packages/core/actions/src/actions/move.ts
Fix move action to trigger workflow.
| 🇺🇸 English | Fix "move" action to trigger workflow |
| 🇨🇳 Chinese | 修复“移动”操作以触发工作流 |
=> fix(actions): fix move action to trigger workflow

packages/plugins/@nocobase/plugin-field-sort/src/server/action.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
Add test case for "move" action to trigger workflow.
| 🇺🇸 English | Add test case for "move" action to trigger workflow |
| 🇨🇳 Chinese | 为“移动”操作可触发工作流增加测试用例 |
=> fix(plugin-field-sort): fix move action to trigger workflow

packages/core/client/src/schema-component/antd/action/utils.ts
| 🇺🇸 English |       The linkage rules of the button are not functioning properly due to an issue with the sequence    |
| 🇨🇳 Chinese |      按钮的联动规则因顺序问题导致的不能正常工作     |
=> fix: linkage rules of action

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
| 🇺🇸 English |       Unable to submit when selecting data    |
| 🇨🇳 Chinese |     选择数据后无法提交      |
=> fix: unable to submit when selecting data

packages/plugins/@nocobase/plugin-notification-email/package.json, packages/plugins/@nocobase/plugin-notification-in-app-message/package.json, packages/plugins/@nocobase/plugin-notification-manager/package.json
Add homepage links to notification plugins in package.json。
| 🇺🇸 English |     Add homepage links to notification plugins in package.json.      |
| 🇨🇳 Chinese |      在 package.json 中为通知插件添加主页链接。     |
=> chore: add homepage links to notification plugins in package.json

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx
| 🇺🇸 English | Unable to add fields in the `Sub-form(Popover)` of public forms |
| 🇨🇳 Chinese | 无法在公开表单的`子表单(弹窗)`中新增字段 |
=> fix: popup subform not working in public forms

packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/form.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/actions.ts
Fix form values not parsed in terminal button submitting.
| 🇺🇸 English | Fix form values not parsed in terminal button submitting |
| 🇨🇳 Chinese | 修复人工节点使用终止按钮提交表单数据未被解析的问题 |
=> fix(plugin-workflow-manual): fix result values in failed status

packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/style.tsx
| 🇺🇸 English |      gantt block style improve     |
| 🇨🇳 Chinese |    甘特图没有出现滚动条       |
=> fix: gantt block style improve

packages/core/client/src/data-source/collection/AssociationProvider.tsx
| 🇺🇸 English |       The popup opened by clicking the belongsToArray field is fetching incorrect data    |
| 🇨🇳 Chinese |     点击 belongsToArray 字段打开的弹窗，获取的数据错误      |
=> fix: belongsToArray

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Add loading to duplicate action.
| 🇺🇸 English | Add loading to duplicate action |
| 🇨🇳 Chinese | 为复制工作流操作增加加载中提示 |
=> fix(plugin-workflow): add loading to duplicate action

packages/core/client/src/modules/menu/PageMenuItem.tsx, packages/core/client/src/modules/menu/__e2e__/dragAndDrop.test.ts, packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/test/src/e2e/e2eUtils.ts, packages/plugins/@nocobase/plugin-client/src/client/routesTableSchema.tsx, packages/plugins/@nocobase/plugin-client/src/server/migrations/2024122912211-transform-menu-schema-to-routes.ts, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/types/MobileTabBar.Page/initializer.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/header/tabs/MobilePageTabs.tsx
| 🇺🇸 English |      Remove default page tab title     |
| 🇨🇳 Chinese |     去除页面默认 tab 标题      |
=> fix: remove default tab title

packages/core/utils/plugin-symlink.js
| 🇺🇸 English |  optimize the storage/plugins reading logic  |
| 🇨🇳 Chinese |  优化 storage/plugins 读取逻辑  |
=> fix: optimize the storage/plugins reading logic

packages/core/client/src/modules/menu/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts
| 🇺🇸 English |       Field remains hidden after being hidden by linkage rules    |
| 🇨🇳 Chinese |     用联动规则将字段隐藏后，字段不再显示      |
=> fix: linkage rules issue

packages/core/client/src/modules/fields/component/Input/inputComponentSettings.tsx
Fix error thrown in create node field settings.
| 🇺🇸 English | Fix error thrown in create node field settings |
| 🇨🇳 Chinese | 修复新增数据节点的字段配置报错 |
=> fix(client): fix use block context

packages/core/client/src/schema-component/antd/page/Page.tsx, packages/core/client/src/schema-component/antd/page/__tests__/page.test.tsx
| 🇺🇸 English |       Page title defaults to using the route's title    |
| 🇨🇳 Chinese |     页面标题默认使用路由的标题      |
=> fix(page): improve document title handling and remove unused request

packages/plugins/@nocobase/plugin-notification-in-app-message/src/server/__tests__/server.test.ts
add test for retrieving latest message title and timestamp in in-app channels
| 🇺🇸 English |    Add test for retrieving latest message title and timestamp in in-app channels.       |
| 🇨🇳 Chinese |     增加在站内信渠道中获取最新消息标题和最新接收时间的测试用例。      |
=> chore(notification-manager): add test case

packages/core/client/src/data-source/data-block/DataBlockRequestProvider.tsx
| 🇺🇸 English |       Block does not refresh after page navigation    |
| 🇨🇳 Chinese |     切换页面后，区块不刷新      |
=> fix: handle undefined dataLoadingMode in BlockRequestContextProvider

packages/core/client/src/schema-component/antd/input-number/ReadPretty.tsx, packages/core/client/src/schema-settings/SchemaSettingsNumberFormat.tsx
| 🇺🇸 English |     issue with high precision number formatting not applying       |
| 🇨🇳 Chinese |    数值格式化精度设置未生效       |
=> fix: issue with high precision number formatting not applying

packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
| 🇺🇸 English | WebSocket authentication issue          |
| 🇨🇳 Chinese | WebSocket 认证问题          |
=> fix(auth): ws auth issue

packages/plugins/@nocobase/plugin-field-sort/src/server/__tests__/sort.test.ts, packages/plugins/@nocobase/plugin-field-sort/src/server/plugin.ts
Fix sort field type not registered in external data source.
| 🇺🇸 English | Fix sort field type not registered in external data source |
| 🇨🇳 Chinese | 修复排序字段类型在外部数据源未注册的问题 |
=> fix(plugin-field-sort): fix field registering for external data source

packages/core/client/src/schema-component/antd/page/Page.tsx
| 🇺🇸 English |      When switching page tabs, include query parameters in the URL     |
| 🇨🇳 Chinese |     切换页面标签页时，URL 中带上查询参数      |
=> fix(navigation): add search parameters to tab navigation

packages/core/auth/src/base/auth.ts, packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts, packages/plugins/@nocobase/plugin-auth/src/constants.ts, packages/plugins/@nocobase/plugin-auth/src/server/__tests__/token-controller.test.ts, packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/observables/message.ts, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/observables/sse.ts
Enhance token concurrent update and auth error logic.
| 🇺🇸 English |   Enhance token concurrent update and auth error handling logic.     |
| 🇨🇳 Chinese |    提升 token 并发更新和认证错误处理逻辑。       |
=> fix(auth): enhance token concurrent update and auth error handling logic

packages/plugins/@nocobase/plugin-mobile/src/client/mobile-providers/context/MobileRoutes.tsx
| 🇺🇸 English |       Mobile menu data is incomplete in permission configuration table    |
| 🇨🇳 Chinese |     权限配置表格中，移动端菜单数据展示不全      |
=> fix(permissions): disable pagination for resource fetching

packages/core/client/src/schema-component/antd/block-item/BlockItemCard.tsx, packages/core/client/src/schema-component/antd/card-item/CardItem.tsx, packages/core/client/src/schema-settings/SchemaSettingsBlockHeightItem.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx
| 🇺🇸 English |  adjust block height settings, set the minimum value to 100         |
| 🇨🇳 Chinese |    调整区块高度设置项，最小值设置为 100       |
=> refactor: adjust block height settings, set the minimum value to 100

packages/core/client/src/application/Application.tsx
=> refactor: remove registerOperators

packages/core/client/src/schema-settings/SchemaSettingsBlockHeightItem.tsx
| 🇺🇸 English |         The minimum block height limit is 40  |
| 🇨🇳 Chinese |      区块高度最小值限制为40    |
=> refactor: block height setting

packages/core/client/src/schema-component/common/withPopupWrapper/index.tsx
| 🇺🇸 English | Can't open field link popup in embed page |
| 🇨🇳 Chinese | 嵌入页面无法打开字段链接的弹窗 |
=> fix: can't open field link in embed page

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterForm.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterProvider.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/hooks/filter.ts
| 🇺🇸 English | Filterting error occurs when the data source name contains a hyphen `-`          |
| 🇨🇳 Chinese | 数据源标识包含 `-` 时，筛选报错的问题          |
=> fix(data-vi): filterting error occurs when the data source name contains a hyphen `-`

packages/core/client/src/application/CustomRouterContextProvider.tsx, packages/core/client/src/schema-component/antd/action/context.tsx
| 🇺🇸 English |       When closing the sub-page, multiple block data requests are triggered    |
| 🇨🇳 Chinese |     关闭子页面时，会触发多次区块数据请求      |
=> fix: block refresh issue

packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/index.tsx, packages/plugins/@nocobase/plugin-field-markdown-vditor/src/server/plugin.ts
| 🇺🇸 English |  Vditor CDN use local resources  |
| 🇨🇳 Chinese |  Vditor CDN 使用本地资源 |
=> fix: vditor cdn use local resources

packages/core/client/src/modules/actions/associate/AssociateActionProvider.tsx
| 🇺🇸 English |   association block associate action popup issue on mobile        |
| 🇨🇳 Chinese |      关系区块中的关联按钮弹窗在移动端的显示异常     |
=> fix: association block associate action popup issue on mobile

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
| 🇺🇸 English |   font color setting not working         |
| 🇨🇳 Chinese |    设置字体颜色不生效       |
=> fix(calendar):font color setting not working color

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
=> fix: datePicker missing picker

packages/core/client/src/schema-component/antd/date-picker/util.ts
=> fix: issue with inferPickerType 

packages/plugins/@nocobase/plugin-workflow-parallel/src/client/ParallelInstruction.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/DrawerDescription.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Fix style details in workflow canvas.
* Node type text overflow
* Parallel branch button icon alignment
* Node card padding
| 🇺🇸 English | Fix style details in workflow canvas |
| 🇨🇳 Chinese | 修复工作流画布的样式细节 |
=> fix(plugin-workflow): fix style details

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/__tests__/upload.test.tsx
Fix files missed after uploaded.
| 🇺🇸 English | Fix files missed after uploaded |
| 🇨🇳 Chinese | 修复上传多个文件后文件丢失的问题 |
=> fix(client): fix uploaded files missing

packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Hide node id from node card in workflow canvas.
| 🇺🇸 English | Hide node id from node card in workflow canvas |
| 🇨🇳 Chinese | 在工作流画布的节点上隐藏节点 ID |
=> refactor(plugin-workflow): hide node id from canvas

packages/plugins/@nocobase/plugin-file-manager/package.json
Upgrade AWS SDK version to fix minio upload bug.
| 🇺🇸 English | Upgrade AWS SDK version to fix MinIO upload bug |
| 🇨🇳 Chinese | 升级 AWS SDK 版本以修复 MinIO 上传问题 |
=> fix(plugin-file-manager): fix aws sdk version

packages/plugins/@nocobase/plugin-action-print/src/client/__e2e__/schemaInitailizer.test.ts, packages/plugins/@nocobase/plugin-calendar/src/client/index.tsx
=> fix: print action e2e test

packages/plugins/@nocobase/plugin-block-template/src/client/components/BlockTemplateMenusProvider.tsx
| 🇺🇸 English | Require login when accessing public form |
| 🇨🇳 Chinese | 访问公开表单会重定向到登录界面 |
=> fix: public form redirects to login

packages/core/client/src/user/CurrentUserProvider.tsx
| 🇺🇸 English |     Skip auth error for CurrentUserProvider.      |
| 🇨🇳 Chinese |   跳过 CurrentUserProvider 中的认证错误。       |
=> fix(user): skip auth error for CurrentUserProvider

packages/plugins/@nocobase/plugin-block-template/src/server/plugin.ts, packages/presets/nocobase/package.json
=> fix: request error for uischemas

packages/plugins/@nocobase/plugin-block-template/package.json, packages/plugins/@nocobase/plugin-block-template/src/server/plugin.ts, packages/presets/nocobase/package.json
=> fix: incorrect version of plugin block template

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/collections/attachments.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/migrations/20250224112112-increase-url-length.ts
Increase URL length to 1024.
| 🇺🇸 English | Increase URL length to 1024 |
| 🇨🇳 Chinese | URL 字段长度增加为 1024 |
=> fix(plugin-file-manager): increase url length

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/FileModel.ts
add backend code to generate file preview url
add backend code to generate file preview url, the preview image is displayed based on the preview field, if it does not exist, it is dynamically spliced ​​based on url and thumbnailRule; if it exists, the preview field is used directly
| 🇺🇸 English |      add backend code to generate file preview url     |
| 🇨🇳 Chinese |     后端添加生成preview地址代码      |
=> feat: add backend code to generate file preview url for next

packages/core/client/src/locale/zh-CN.json, packages/core/client/src/schema-component/antd/block-item/BlockItemCard.tsx, packages/core/client/src/schema-settings/SchemaSettingsBlockTitleItem.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/SchemaSettingsBlockTitleItem.tsx
=> refactor: edit block title & description

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/user/CurrentUserProvider.tsx, packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts
Remove unnecessary NavigateIfNotSignIn wrapper from AdminProvider.
| 🇺🇸 English |     Remove unnecessary NavigateIfNotSignIn wrapper from AdminProvider.      |
| 🇨🇳 Chinese |      移除 AdminProvider 不必要的 NavigateIfNotSignIn  组件。    |
=> refactor: remove unnecessary NavigateIfNotSignIn wrapper from AdminProvider

packages/core/auth/src/auth.ts, packages/core/auth/src/base/auth.ts, packages/core/client/src/api-client/hooks/useRequest.ts, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
| 🇺🇸 English |  Skip auth check in the public form  |
| 🇨🇳 Chinese |  公开表单里跳过 Auth 检查 |
=> fix: skip auth check in the public form

packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx
| 🇺🇸 English |       Unable to move the page into a group    |
| 🇨🇳 Chinese |      无法将页面移动到分组中     |
=> fix: move to inner

packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts
Fix `path` column type of file collection.
| 🇺🇸 English | Fix `path` column type of file collection |
| 🇨🇳 Chinese | 修复文件表 `path` 列的类型 |
=> fix(plugin-file-manager): fix file template column type

packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
Fix E2E test cases based on new features.
| 🇺🇸 English | Fix E2E test cases based on new features |
| 🇨🇳 Chinese | 修复新功能相关的 E2E 测试用例 |
=> fix(plugin-workflow): e2e test

packages/core/client/src/schema-component/antd/record-picker/util.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
…r block
| 🇺🇸 English |     add 'collectionField' parameter to TitleRenderer in calendar      |
| 🇨🇳 Chinese |      日历区块标题字段 TitleRenderer 增加入参数 collectionField      |
=> refactor: add 'collectionField' parameter to TitleRenderer in calendar

packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/migrations/20250226105145-custom-request-action.ts
=> add: custom requests action migration

packages/plugins/@nocobase/plugin-ui-schema-storage/src/server/migrations/20250226105145-custom-request-action.ts
=> add: custom request action migration

packages/core/database/src/inherited-collection.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/migrations/20250225225034-increase-url-length.ts
Fix migration for inherited collection.
| 🇺🇸 English | Fix migration for inherited collection |
| 🇨🇳 Chinese | 修复继承表的迁移问题 |
=> fix(plugin-file-manager): fix migration for inherited collection

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx
| 🇺🇸 English |       After clicking the left menu, the sub-page is abnormally closed    |
| 🇨🇳 Chinese |      点击左侧菜单后，子页面被异常关闭     |
=> fix(action-modal): improve modal visibility handling

packages/plugins/@nocobase/plugin-block-template/src/client/schemas/blockTemplates.ts
=> fix: dialog button position not correct in block template

packages/plugins/@nocobase/plugin-block-workbench/src/client/SchemaSettingsBlockTitleItem.tsx
| 🇺🇸 English |   issue with action panel block description        |
| 🇨🇳 Chinese |     操作面板区块描述未回显      |
=> fix: issue with action panel block description

packages/core/client/src/schema-initializer/items/DataBlockInitializer.tsx
=> fix: dataBlockInitializer

packages/core/client/src/schema-component/antd/menu/Menu.tsx
| 🇺🇸 English |      Incorrect position after dragging the menu     |
| 🇨🇳 Chinese |     拖动菜单之后，位置不对      |
=> fix(menu): drag issue

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx
| 🇺🇸 English |      Setting the height of the action panel is invalid     |
| 🇨🇳 Chinese |     设置操作面板的高度无效      |
=> fix(workbench-block): improve block height and layout responsiveness

packages/core/client/src/schema-component/antd/block-item/BlockItemCard.tsx
| 🇺🇸 English |   optimize block description style        |
| 🇨🇳 Chinese |    区块描述样式优化       |
=> style: optimize block description style

packages/plugins/@nocobase/plugin-map/src/client/fields/schema.ts, packages/plugins/@nocobase/plugin-map/src/client/index.tsx
| 🇺🇸 English |    Configuration settings for map field are missing/not visible       |
| 🇨🇳 Chinese |     地图字段不显示配置项      |
=> fix(Map): prevent undefined values in Map.Designer

packages/core/app/client/.umirc.ts, packages/core/client/src/application/Application.tsx
| 🇺🇸 English |       Pages with custom favicon briefly flash the NocoBase favicon during loading    |
| 🇨🇳 Chinese |     已经自定义 favicon 的页面，在页面加载时会闪一下 NocoBase 的 favicon      |
=> feat(favicon): add dynamic favicon update functionality

packages/plugins/@nocobase/plugin-workflow/src/client/ExecutionCanvas.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/ExecutionPage.tsx
Lazy load job result for better performance.
| 🇺🇸 English | Lazy load job result for better performance |
| 🇨🇳 Chinese | 后置节点结果加载以提升执行记录画布性能 |
=> refactor(plugin-workflow): lazy load job result for better performance

packages/core/auth/src/auth.ts, packages/core/auth/src/base/auth.ts, packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
Fix accidentally logged out due to WebSocket authorization.
| 🇺🇸 English |     Avoid renewing the token during WebSocket authorization.   |
| 🇨🇳 Chinese |       在 WebSocket 授权过程中避免刷新令牌。    |
=> fix(auth): accidentally logged out due to WebSocket authorization.

packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Fix acl for getting job.
| 🇺🇸 English | Fix acl for getting job |
| 🇨🇳 Chinese | 修复加载节点结果的权限问题 |
=> fix(plugin-workflow): fix acl for getting job

packages/plugins/@nocobase/plugin-action-import/src/client/ImportActionInitializer.tsx, packages/plugins/@nocobase/plugin-action-import/src/client/useImportAction.ts
=> refactor: import action

packages/core/client/src/schema-component/antd/upload/__tests__/upload.test.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/templates/file.ts
Fix error thrown when creating file collection
Error notified like: "this._length.toLowerCase is not a function"
```log
TypeError: this._length.toLowerCase is not a function                                                                                                                        
at TEXT.toSql (/app/nocobase/node_modules/sequelize/src/data-types.js:125:26)                                                       
at TEXT.toString (/app/nocobase/node_modules/sequelize/src/data-types.js:17:17)                                                     
at MySQLQueryGenerator.attributeToSQL (/app/nocobase/node_modules/sequelize/src/dialects/mysql/query-generator.js:371:44)           
at MySQLQueryGenerator.attributesToSQL (/app/nocobase/node_modules/sequelize/src/dialects/mysql/query-gener …
```
=> fix(plugin-file-manager): fix error thrown when creating file collection

packages/plugins/@nocobase/plugin-ai/src/server/llm-providers/deepseek.ts, packages/plugins/@nocobase/plugin-ai/src/server/llm-providers/openai.ts, packages/plugins/@nocobase/plugin-ai/src/server/llm-providers/provider.ts
| 🇺🇸 English | Issue where the default `baseURL` for LLM provider is `undefined`          |
| 🇨🇳 Chinese | LLM 服务默认 `baseURL` 为空的问题           |
=> fix(ai): issue where the default `baseURL` for LLM provider is `undefined`

packages/plugins/@nocobase/plugin-action-export/src/client/useExportAction.tsx
| 🇺🇸 English |      missing sort parameter in export button     |
| 🇨🇳 Chinese |    导出按钮没有传 sort 参数        |
=> fix: missing sort parameter in export button

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
| 🇺🇸 English |    incorrect formatting of time field in filter form       |
| 🇨🇳 Chinese |    时间字段在筛选表单中格式化异常       |
=> fix: incorrect formatting of time field in filter form

packages/plugins/@nocobase/plugin-action-import/src/client/ImportActionInitializer.tsx
=> fix: import action x-toolbar

packages/plugins/@nocobase/plugin-users/package.json, packages/plugins/@nocobase/plugin-users/src/client/UsersManagement.tsx, packages/plugins/@nocobase/plugin-users/src/server/__tests__/system-settings.test.ts, packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts
| 🇺🇸 English |  "No permissions" error when updating system settings in user management         |
| 🇨🇳 Chinese | 在用户管理里更新系统设置时出现 "No permissions" 报错          |
=> fix(users): no permissions error when updating system settings in user management

packages/plugins/@nocobase/plugin-users/src/client/EditProfile.tsx, packages/plugins/@nocobase/plugin-users/src/server/server.ts
| 🇺🇸 English | "No permissions" error when users without user management permissions view their own profile          |
| 🇨🇳 Chinese | 没有用户管理权限的用户访问自己的个人资料时提示无权限          |
=> fix(users): "No permissions" error when users without user management permissions view their profile

packages/plugins/@nocobase/plugin-client/src/client/index.ts, packages/plugins/@nocobase/plugin-client/src/client/routesTableSchema.tsx
| 🇺🇸 English |      Adding tab pages in route management table does not take effect     |
| 🇨🇳 Chinese |     在路由管理表格中添加 tab 页面不生效      |
=> fix: correct parentSchemaUid reference in routesTableSchema

packages/plugins/@nocobase/plugin-client/src/client/routesTableSchema.tsx
| 🇺🇸 English |      After adding a page to the route table, the page appears blank     |
| 🇨🇳 Chinese |     在路由表中添加一个页面后，页面显示空白      |
=> fix: properly handle hidden field in tab routing

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/menu/index.ts, packages/plugins/@nocobase/plugin-client/src/client/routesTableSchema.tsx
| 🇺🇸 English |      Menu title custom translation is invalid     |
| 🇨🇳 Chinese |      菜单标题的自定义翻译无效     |
=> fix: integrate menu translation for route titles in admin layout

packages/plugins/@nocobase/plugin-theme-editor/src/client/hooks/useUpdateThemeSettings.tsx
| 🇺🇸 English |   theme switching fails after multiple consecutive switches        |
| 🇨🇳 Chinese |    主题连续切换多次后切换失败的问题       |
=> fix: theme switching fails after multiple consecutive switches

packages/core/auth/src/__tests__/base-auth.test.ts, packages/core/auth/src/__tests__/middleware.test.ts, packages/core/auth/src/base/auth.ts, packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts, packages/plugins/@nocobase/plugin-auth/src/locale/en-US.json, packages/plugins/@nocobase/plugin-auth/src/locale/zh-CN.json
`
Handle non-existent user with 401 error and update locale messages.
| 🇺🇸 English |    Handle non-existent user with 401 error and update locale messages       |
| 🇨🇳 Chinese |      用户不存在时返回 401 错误并更新本地化信息。      |
=> fix(auth): handle non-existent user with 401 error and update locale messages

packages/core/utils/src/date.ts
| 🇺🇸 English |    mobile date picker format       |
| 🇨🇳 Chinese |     修复移动端日期组件报错      |
=> fix: mobile date picker format

packages/core/utils/src/date.ts
| 🇺🇸 English |    date picker format error in mobile       |
| 🇨🇳 Chinese |     移动端日期组件格式化报错      |
=> fix: date picker format error in mobile

packages/core/server/src/plugin-manager/options/resource.ts
| 🇺🇸 English | Incorrect browser cache after running `yarn start` command |
| 🇨🇳 Chinese | `yarn start` 启动服务器后前端缓存未刷新 |
=> fix: yarn start cache issue

packages/core/client/src/modules/blocks/data-blocks/table/tableColumnSettings.tsx
| 🇺🇸 English |     collectionField undefined in sortable      |
=> fix: collectionField undefined in sortable

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/AddFieldAction.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/EditFieldAction.tsx
| 🇺🇸 English |   error when editing fields in external data source        |
| 🇨🇳 Chinese |    外部数据源点击字段编辑报错       |
=> fix: error when editing fields in external data source

packages/core/client/src/schema-component/antd/form-drawer/index.tsx, packages/core/client/src/schema-component/antd/index.ts, packages/plugins/@nocobase/plugin-environment-variables/src/client/components/EnvironmentTabs.tsx
| 🇺🇸 English |    FormDrawer theme context issue       |
| 🇨🇳 Chinese |       FormDrawer 缺失主题上下文    |
=> fix: formDrawer theme context issue

packages/core/client/src/pm/index.tsx, packages/core/client/src/schema-initializer/components/DeprecatedTemplateTitle.tsx, packages/plugins/@nocobase/plugin-block-template/src/client/hooks/useIsPageBlock.ts
| 🇺🇸 English | Save as template option has not been shown in page data block |
| 🇨🇳 Chinese | 页面数据区块另存为模板菜单不显示 |
=> fix: save as template not shown

packages/plugins/@nocobase/plugin-client/src/server/server.ts, packages/plugins/@nocobase/plugin-mobile/src/server/plugin.ts
=> fix: use repository.firstOrCreate

packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250227220712-add-pending-tasks.ts
Avoid conflict on unique key.
| 🇺🇸 English | Avoid conflict on unique key |
| 🇨🇳 Chinese | 避免唯一键冲突 |
=> fix(plugin-workflow-manual): fix task migration

packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts
User has no roles should redirect error message page.
| 🇺🇸 English |   User has no roles should redirect error message page.      |
| 🇨🇳 Chinese |   无角色用户需重定向至错误信息页。      |
=> fix(auth): user has no roles should redirect error message page

packages/core/client/src/route-switch/antd/admin-layout/index.tsx
| 🇺🇸 English |      Deep-level menus are not displaying icon     |
| 🇨🇳 Chinese |     深层级的菜单没有显示图标      |
=> fix: menu icon display issue

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx
Fix API 401 when not logged in.
| 🇺🇸 English | Fix API 401 when not logged in |
| 🇨🇳 Chinese | 修复未登录时 API 请求 401 |
=> fix(lugin-workflow-tasks): only use the provider in admin layout

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/index.tsx
| 🇺🇸 English |    optimize public form styles      |
| 🇨🇳 Chinese |  公开表单样式优化         |
=> fix:  public form style improve

packages/core/client/src/modules/blocks/BlockSchemaToolbar.tsx, packages/core/client/src/pm/PluginManagerLink.tsx, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/action/Action.Page.style.ts, packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/list/List.tsx, packages/core/client/src/schema-component/antd/page/Page.tsx, packages/core/client/src/schema-component/antd/page/PopupSettingsProvider.tsx, packages/core/client/src/schema-component/antd/tabs/Tabs.tsx, packages/core/client/src/schema-component/core/DesignableSwitch.tsx, packages/core/client/src/schema-component/hooks/useDesignable.tsx, packages/core/client/src/schema-templates/BlockTemplate.tsx, packages/core/utils/src/__tests__/transformMultiColumnToSingleColumn.test.ts, packages/core/utils/src/client.ts, packages/core/utils/src/transformMultiColumnToSingleColumn.ts, packages/plugins/@nocobase/plugin-action-import/src/client/ImportAction.tsx, packages/plugins/@nocobase/plugin-action-import/src/client/ImportActionInitializer.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/MobileComponentsProvider.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.style.ts, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/FilterAction.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/index.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/MobilePage.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/components/MobileDatePicker.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/components/MobilePicker.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx
| 🇺🇸 English |       Desktop page adaptation for mobile devices    |
| 🇨🇳 Chinese |      桌面端页面自适应移动端样式     |
=> feat: adapt styles for mobile devices

packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/migrations/20250225175712-change-table-name.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/migrations/20250312100512-change-table-name.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250225175712-change-table-name.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250312100512-change-table-name.ts
Fix migration which missed table prefix and schema logic.
| 🇺🇸 English | Fix migration which missed table prefix and schema logic |
| 🇨🇳 Chinese | 修复遗漏表前缀和 schema 的迁移脚本 |
=> fix(plugin-workflow-manual): fix migration

packages/plugins/@nocobase/plugin-api-keys/src/client/Configuration/index.tsx
| 🇺🇸 English |   API keys plugin role list removal union        |
| 🇨🇳 Chinese | API keys 插件角色列表移除 union |
=> fix: API keys plugin role list removal union

packages/core/client/src/user/CurrentUserProvider.tsx, packages/plugins/@nocobase/plugin-acl/src/client/RoleModeSelect.tsx
=> fix: roleMode

packages/core/client/src/route-switch/antd/admin-layout/index.tsx
| 🇺🇸 English |      The logo style is inconsistent with the previous one     |
| 🇨🇳 Chinese |     Logo 的样式与之前的不一致      |
=> fix(logo): logo style

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterItemInitializers.tsx
| 🇺🇸 English | Removed fields appear when adding custom filter fields          |
| 🇨🇳 Chinese | 添加自定义筛选字段时会出现已移除字段          |
=> fix(data-vi): removed fields appear when adding custom filter fields

packages/plugins/@nocobase/plugin-action-custom-request/src/server/__tests__/actions.test.ts
=> fix(custom request): custom request server test

packages/core/client/src/data-source/collection-field/CollectionField.tsx
=> fix: collection field test

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/user/CurrentUserProvider.tsx, packages/plugins/@nocobase/plugin-acl/src/client/RoleModeSelect.tsx, packages/plugins/@nocobase/plugin-acl/src/client/SwitchRole.tsx, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/union-role.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/actions/role-check.ts, packages/plugins/@nocobase/plugin-acl/src/server/actions/union-role.ts, packages/plugins/@nocobase/plugin-acl/src/server/server.ts
Fixed switching roles does not take effect.
| 🇺🇸 English |     Fixed switching roles does not take effect.      |
| 🇨🇳 Chinese |     修复角色不生效      |
=> fix: switching roles does not take effect

packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/index.ts, packages/core/client/src/schema-component/antd/upload/shared.ts, packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/Edit.tsx
Fix special character in image URL caused not showing.
| 🇺🇸 English | Fix special character in image URL caused not showing |
| 🇨🇳 Chinese | 修复图片中特殊字符导致不显示的问题 |
=> fix(plugin-file-manager): fix image url

packages/core/client/src/application/RouterManager.tsx, packages/core/client/src/application/__tests__/RouterManager.test.tsx, packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts, packages/plugins/@nocobase/plugin-public-forms/src/client/index.tsx
Add skipAuthCheck to router.add to prevent redirecting to login on public pages.
| 🇺🇸 English |       Add skipAuthCheck to router.add to prevent redirecting to login on public pages.    |
| 🇨🇳 Chinese |      在 router.add 中添加 skipAuthCheck，防止在访问公共页面时重定向到登录页。     |
=> chore(router): add skipAuthCheck option to router.add to prevent redirecting to login on public pages

packages/core/client/src/schema-component/antd/input/ReadPretty.tsx, packages/core/client/src/schema-component/antd/upload/shared.ts
=> fix: encode

packages/plugins/@nocobase/plugin-file-manager/src/server/storages/s3.ts
| 🇺🇸 English |   Unable to delete files stored in S3. |
| 🇨🇳 Chinese |  无法删除 s3 文件存储的文件  |
=> fix: unable to delete files stored in S3

packages/core/client/src/modules/fields/component/CascadeSelect/cascadeSelectComponentFieldSettings.tsx, packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
| 🇺🇸 English |      Cascade Selection Component Add Data Scope Setting     |
| 🇨🇳 Chinese |     级联选择组件添加数据范围设置     |
=> feat: cascade selection component add dataScope setting

packages/core/utils/src/crypto.ts, packages/core/utils/src/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/s3.ts
Move `md5` to utils.
| 🇺🇸 English | Move `md5` to utils |
| 🇨🇳 Chinese | 将 `md5` 方法移到通用包 |
=> refactor(utils): move md5 to utils

packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/AggregateInstruction.ts, packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/__tests__/instruction.test.ts
Fix round on null result.
| 🇺🇸 English | Fix round on null result |
| 🇨🇳 Chinese | 修复对聚合结果为 null 时取整报错 |
=> fix(plugin-workflow-aggregate): fix round on null result

packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/migrations/20250312100513-change-table-name.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250312100513-change-table-name.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250313133421-remove-m2m-fields.ts
Fix migration error when id column is not exists.
| 🇺🇸 English | Fix migration error when id column is not exists |
| 🇨🇳 Chinese | 修复 id 列不存在时迁移脚本报错 |
=> fix: migration error

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/tasks.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflowTasks.ts, packages/plugins/@nocobase/plugin-workflow/src/server/collections/workflowTasks.ts
Don't count tasks when workflow deleted.
| 🇺🇸 English | Don't count tasks when workflow deleted |
| 🇨🇳 Chinese | 不统计已删除的工作流的待办 |
=> fix(plugin-workflow): fix tasks count

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/MainDataSourceManager/Configuration/CollectionFields.tsx
=> fix(collection-manager): configureActions undefined

packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowManualProvider.tsx
Fix workflow title field in filter.
| 🇺🇸 English | Fix workflow title field in filter |
| 🇨🇳 Chinese | 修复区块的筛选组件中工作流标题项 |
=> fix(plugin-workflow-manaul): fix workflow title field in filter

packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx
| 🇨🇳 Chinese | 调整 启用序号列 位置          |
=> refactor: optimize  enabling the index column

packages/core/client/src/css-variable/CSSVariableProvider.tsx, packages/core/client/src/plugin-manager/PinnedPluginListProvider.tsx
| 🇺🇸 English |      The color of the icons in the upper right corner of the page does not change with the theme    |
| 🇨🇳 Chinese |     页面右上角图标的颜色不会随主题变化      |
=> feat: add colorTextHeaderMenu variable for header menu styling

packages/core/client/src/schema-component/antd/rich-text/RichText.tsx
| 🇺🇸 English |    rich text field not clearing data on submission       |
| 🇨🇳 Chinese |     富文本字段清空后提交时数据未删除      |
=> fix: rich text field not clearing data on submission

packages/core/client/src/schema-component/antd/form-drawer/index.tsx, packages/plugins/@nocobase/plugin-environment-variables/src/client/components/EnvironmentTabs.tsx
| 🇺🇸 English | Buttons have not been shown in create new variables drawer |
| 🇨🇳 Chinese | 变量与密钥弹窗界面按钮不显示 |
=> fix: buttons have not shown when creating new variables

packages/core/client/src/schema-settings/LinkageRules/LinkageRuleAction.tsx
| 🇺🇸 English |    missing fields in the linkage rule configuration       |
| 🇨🇳 Chinese |    联动规则中字段列表没有显示全部可选字段       |
=> fix: missing fields in the linkage rule configuration

packages/core/database/src/collection.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/index.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/view/view-collection.test.ts
Unable to create a MySQL view. 
| 🇺🇸 English |  Unable to create a MySQL view.         |
| 🇨🇳 Chinese |  无法创建 MySQL 视图         |
=> fix: unable to create a MySQL view

packages/core/database/src/relation-repository/belongs-to-many-repository.ts, packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/AggregateInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-aggregate/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/AggregateInstruction.ts, packages/plugins/@nocobase/plugin-workflow-aggregate/src/server/__tests__/instruction.test.ts
Support to configure precision for aggregation result.
| 🇺🇸 English | Support to configure precision for aggregation result |
| 🇨🇳 Chinese | 支持为聚合结果配置精度选项 |
=> feat(plugin-workflow-aggregate): add precision option

packages/core/client/src/collection-manager/interfaces/textarea.ts
| 🇺🇸 English |     support long text fields as title fields for association field      |
| 🇨🇳 Chinese |     支持长文本字段作为关系字段的标题字段      |
=> feat: support long text fields as title fields for association field

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflowTasks.ts
Fix legacy tasks count after workflow deleted.
| 🇺🇸 English | Fix legacy tasks count after workflow deleted |
| 🇨🇳 Chinese | 修复历史遗留任务数量工作流删除后统计错误 |
=> fix(plugin-workflow): fix legacy tasks count after workflow deleted

packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/utils.ts
=> fix: encode url

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/user/CurrentUserProvider.tsx, packages/plugins/@nocobase/plugin-environment-variables/src/client/EnvironmentVariablesAndSecretsProvider.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx
=> perf: useIsLoggedIn

packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/__e2e__/DataOfCollection.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/createRecordForm1.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/createRecordForm2.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/createRecordForm3.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/createRecordForm4.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/createRecordForm5.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/customFormBlocks.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/customFormBlocks1.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/customFormBlocks2.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/customFormBlocks3.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/datablocks.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/datablocks1.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/datablocks2.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/updateRecordForm.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/updateRecordForm1.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/updateRecordForm2.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/client/__e2e__/updateRecordForm3.test.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
=> fix: workflow e2e

packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts
| 🇺🇸 English |      linkage rule field default hidden with retained value not working     |
| 🇨🇳 Chinese |    联动规则字段默认设置为 隐藏保留值 不生效       |
=> fix: linkage rule field default hidden with retained value not working

packages/plugins/@nocobase/plugin-client/src/client/routesTableSchema.tsx, packages/plugins/@nocobase/plugin-client/src/client/utils.tsx
| 🇺🇸 English |       The path in the route management table is different from the actual path    |
| 🇨🇳 Chinese |      路由管理表格中的路径与实际路径不一样     |
=> fix: remove deprecated menuSchemaUid usage and simplify path generation

packages/core/client/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-client/src/client/ClearCache.tsx
| 🇺🇸 English |       add secondary confirmation prompt for Clear Cache    |
| 🇨🇳 Chinese |     增加 Clear Cache 操作的二次确认提示      |
=> refactor: add secondary confirmation prompt for Clear Cache

packages/plugins/@nocobase/plugin-notification-email/src/client/ConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-email/src/locale/zh-CN.json
Add secure config description.
| 🇺🇸 English |    Add secure field config description.       |
| 🇨🇳 Chinese |   增加安全字段配置描述。        |
=> chore(notification-mail): add secure config description

packages/plugins/@nocobase/plugin-map/package.json, packages/plugins/@nocobase/plugin-map/src/client/components/Configuration.tsx, packages/plugins/@nocobase/plugin-map/src/locale/zh-CN.json
| 🇺🇸 English |  secret key fields not triggering validation in map management         |
| 🇨🇳 Chinese |   地图管理中密钥必填校验失败        |
=> fix: secret key fields not triggering validation in map management

packages/plugins/@nocobase/plugin-workflow-mailer/src/client/MailerInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-mailer/src/locale/en-US.json, packages/plugins/@nocobase/plugin-workflow-mailer/src/locale/zh-CN.json
Add secure config description.
| 🇺🇸 English |    Add secure field config description.       |
| 🇨🇳 Chinese |   增加安全字段配置描述。        |
=> feat(mailer): add description for secure setting and update translations

packages/plugins/@nocobase/plugin-block-workbench/src/client/components/qrcode-scanner/useScanner.ts, packages/plugins/@nocobase/plugin-mobile/src/client/demos/DesktopMode-basic.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageList.tsx
Update navigation logic to remove base path from URLs in QR code scanner and in-app-message list.
| 🇺🇸 English |    Update navigation logic to remove base path from URLs in QR code scanner and in-app-message list.       |
| 🇨🇳 Chinese |    更新导航逻辑，以从二维码扫描器和应用内消息列表中的URL中移除基础路径。       |
=> fix: update navigation logic to remove base path from URLs in QR code scanner and in-app-message list

packages/plugins/@nocobase/plugin-file-manager/src/server/actions/attachments.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/tx-cos.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/utils.ts
| 🇺🇸 English |  Unable to access files stored in COS  |
| 🇨🇳 Chinese |  COS 存储的文件无法访问 |
=> fix: unable to access files stored in COS

packages/core/client/src/schema-component/common/utils/uitls.tsx
| 🇨🇳 Chinese |     iframe html 中自定义注入的变量不应该在控制台中报错      |
=> refactor: getRenderContent

packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/s3.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/utils.ts
=> fix: getFileKey

packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
| 🇺🇸 English |  X-Authenticator missing  |
| 🇨🇳 Chinese |  X-Authenticator 缺失 |
=> fix: authenticator missing

packages/core/server/src/application.ts
| 🇺🇸 English | The upgrade command may cause workflow errors |
| 🇨🇳 Chinese | Upgrade 命令可能造成工作流报错 |
=> fix: ensure old instances are cleaned up during application reinitialization

packages/plugins/@nocobase/plugin-auth/src/client/settings/Authenticator.tsx, packages/plugins/@nocobase/plugin-auth/src/client/settings/schemas/authenticators.ts
| 🇺🇸 English | Trim authenticator options          |
| 🇨🇳 Chinese | 移除认证器配置项前后的空格、换行符          |
=> fix(auth): trim authenticator options

packages/core/database/src/mock-database.ts, packages/core/logger/src/logger.ts, packages/core/logger/src/system-logger.ts, packages/core/server/src/run-plugin-static-imports.ts, packages/plugins/@nocobase/plugin-async-task-manager/src/server/index.ts, packages/plugins/@nocobase/plugin-async-task-manager/src/server/static-import.ts
=> fix: runPluginStaticImports

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
…eation
| 🇺🇸 English |      set public form page title to the configured title upon creation      |
| 🇨🇳 Chinese |     公开表单页面标题，显示为创建时设置的标题      |
=> refactor:   set public form page title to the configured title upon creation

packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
| 🇺🇸 English | Migration issue for plugin-collection-tree          |
| 🇨🇳 Chinese | 树表插件的迁移脚本问题          |
=> fix(collection-tree): migration issue

packages/core/client/src/schema-component/antd/page/index.en-US.md, packages/core/client/src/schema-component/antd/page/index.md
| 🇺🇸 English | `yarn doc` command error |
| 🇨🇳 Chinese | `yarn doc` 命令报错 |
=> fix: yarn doc error

packages/plugins/@nocobase/plugin-action-custom-request/src/client/hooks/useCustomizeRequestActionProps.ts
| 🇺🇸 English |  Unable to download UTF-8 encoded files         |
| 🇨🇳 Chinese | 无法下载utf8编码的文件          |
=> fix(custom-request): unable to download utf-8 encoded files

packages/core/client/src/modules/menu/LinkMenuItem.tsx, packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts
| 🇺🇸 English |       Unable to use 'Current User' variable when adding a link page    |
| 🇨🇳 Chinese |     添加链接页面时，无法使用“当前用户”变量      |
=> fix(Link): cannot use 'current user' variable

packages/core/client/src/schema-component/antd/action/Action.Link.tsx, packages/core/client/src/schema-component/common/sortable-item/SortableItem.tsx, packages/plugins/@nocobase/plugin-action-import/src/client/ImportAction.tsx
| 🇺🇸 English |   table row button drag-and-drop issue        |
| 🇨🇳 Chinese |     表格行按钮拖拽排序缺陷    |
=> fix: table row button drag-and-drop issue

packages/core/client/src/block-provider/hooks/index.ts, packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx
| 🇺🇸 English |       字段赋值对字段进行“空值”赋值无效    |
| 🇨🇳 Chinese |      field assignment with null value is ineffective      |
=> fix: field assignment with null value is ineffective

packages/core/client/src/schema-component/antd/action/Action.Link.tsx, packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
| 🇺🇸 English |   optimize button style for no-permission state        |
| 🇨🇳 Chinese |    调整无权限时Button按钮样式       |
=> style:  optimize button style for no-permission state

packages/core/client/src/api-client/APIClient.ts, packages/core/client/src/application/Application.tsx, packages/core/client/src/nocobase-buildin-plugin/index.tsx
| 🇺🇸 English | Optimize 502 error message |
| 🇨🇳 Chinese | 优化 502 错误提示 |
=> feat: optimize 502 error message

packages/plugins/@nocobase/plugin-auth/src/client/basic/SignUpForm.tsx
Close #6539 
| 🇺🇸 English | Localization issue for fields of sign up page          |
| 🇨🇳 Chinese | 注册页面字段的本地化问题          |
=> fix(l10n): localization for fields of sign up page

packages/plugins/@nocobase/plugin-field-sequence/src/client/index.tsx
| 🇺🇸 English |  support setting sequence as the title field for calendar block         |
| 🇨🇳 Chinese |    支持使用 sequence 作为日历区块的标题字段       |
=> feat: support setting sequence as the title field for calendar block

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx
| 🇺🇸 English |    issue with date field display in data scope filtering       |
| 🇨🇳 Chinese |     数据范围中筛选日期字段显示异常      |
=> fix: issue with date field display in data scope filtering

packages/plugins/@nocobase/plugin-environment-variables/src/client/components/EnvironmentPage.tsx, packages/plugins/@nocobase/plugin-environment-variables/src/client/components/EnvironmentTabs.tsx
| 🇺🇸 English |     missing icon filter button, filter count not displaying, and data not refreshing after filtering when switching pages      |
| 🇨🇳 Chinese |   变量密钥筛选按钮缺少 icon、筛选后不显示筛选个数、筛选后切换页面变量密钥数据不刷新        |
=> fix(environment-variables): missing icon filter button, filter count not displaying, and data not refreshing after filtering when switching pages

packages/core/client/src/route-switch/antd/admin-layout/index.tsx
| 🇺🇸 English |       Older versions of browsers will display a blank page    |
| 🇨🇳 Chinese |     旧版本的浏览器，页面会显示空白      |
=> fix(layout): adjust height calculation for mobile support using dvh unit

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx, packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
| 🇺🇸 English |     issue with public form page title displaying 'Loading...'       |
| 🇨🇳 Chinese |     公开表单页面标题不应该显示 Loading...      |
=> fix: issue with public form page title displaying 'Loading...'

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/MobileComponentsProvider.tsx
| 🇺🇸 English |       Adjust the font size displayed on the phone to 14px    |
| 🇨🇳 Chinese |     调整在手机上显示的字体大小为 14px      |
=> fix: adjust the font size displayed on the phone to 14px

packages/plugins/@nocobase/plugin-acl/src/server/__tests__/union-role.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts, packages/plugins/@nocobase/plugin-client/src/server/__tests__/desktopRoutes-union-role.test.ts, packages/plugins/@nocobase/plugin-mobile/src/server/__tests__/union-role-mobileRoutes.test.ts
Incorrect current role assignment during login
| 🇺🇸 English |     Incorrect current role assignment during login      |
| 🇨🇳 Chinese |      设置当前登录角色不正确     |
=> fix: incorrect current role assignment during login

packages/plugins/@nocobase/plugin-async-task-manager/src/client/components/AsyncTasks.tsx
| 🇺🇸 English |    error in migration task popup during async export        |
| 🇨🇳 Chinese |    异步导出迁移任务时弹窗报错       |
=> fix: error in migration task popup during async export

packages/plugins/@nocobase/plugin-async-task-manager/src/client/components/AsyncTasks.tsx
| 🇺🇸 English |     error when downloading async migration file      |
| 🇨🇳 Chinese |    下载异步导出的迁移文件报错       |
=> fix: error when downloading async migration file

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx
| 🇺🇸 English |       missing data on boundary dates in weekly calendar view    |
| 🇨🇳 Chinese |      日历区块以周为视图时，边界日期不显示数据     |
=> fix:  missing data on boundary dates in weekly calendar view

packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
…n deleting and re-selecting
| 🇺🇸 English |     cascade  issue: 'The value of xxx cannot be in array format' when deleting and re-selecting       |
| 🇨🇳 Chinese |     级联组件删除后重新选择时出现 'The value of xxx cannot be in array format'       |
=> fix: cascade  issue: 'The value of xxx cannot be in array format' when deleting and re-selecting

packages/plugins/@nocobase/plugin-map/src/client/components/Configuration.tsx
…ce input
| 🇺🇸 English |   map management validation should not pass with space input      |
| 🇨🇳 Chinese |     地图管理必填校验不应通过空格输入      |
=> fix: map management validation should not pass with space input

packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |     submit and refresh buttons not displaying icon-only mode correctly       |
| 🇨🇳 Chinese |     提交、刷新按钮设置 仅显示图标不起作用      |
=> fix: submit and refresh buttons not displaying icon-only mode correctly

packages/plugins/@nocobase/plugin-auth/src/client/AuthProvider.tsx
| 🇺🇸 English |  token assignment in `AuthProvider`         |
| 🇨🇳 Chinese |  `AuthProvider` 中的 token 赋值         |
=> fix(auth): token assignment in `AuthProvider`

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx
Fix sync option display incorrectly.
| 🇺🇸 English | Fix sync option display incorrectly |
| 🇨🇳 Chinese | 修复同步选项展示问题 |
=> fix(plugin-workflow): fix sync option display incorrectly

packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/RepeatField.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/StaticScheduleTrigger.ts
Improve code.
| 🇺🇸 English | Improve code |
| 🇨🇳 Chinese | 优化代码 |
=> refactor(plugin-workflow): improve code of schedule trigger

packages/core/database/src/belongs-to-array/belongs-to-array-repository.ts, packages/core/database/src/eager-loading/eager-loading-tree.ts, packages/core/database/src/query-interface/mysql-query-interface.ts, packages/core/database/src/query-interface/postgres-query-interface.ts, packages/core/database/src/query-interface/query-interface.ts, packages/core/database/src/query-interface/sqlite-query-interface.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/issues.test.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/m2m-array-bigint-api.test.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/m2m-array-string-api.test.ts
| 🇺🇸 English | Issue of filtering by fields in an association collection with a many to many (array) field          |
| 🇨🇳 Chinese | 主表筛选带有多对多（数组）字段的关联表中的字段报错的问题          |
=> fix(m2m-array): error of filtering by fields in an association collection with a m2m array field

packages/core/client/src/route-switch/antd/admin-layout/index.tsx
| 🇺🇸 English |       Determine whether to display the mobile layout based on device type rather than page width    |
| 🇨🇳 Chinese |     根据设备类型而非页面宽度来判断是否显示移动端布局      |
=> fix: update mobile layout handling and clean up unused context

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> fix: oneToMa ny e2e test

packages/plugins/@nocobase/plugin-public-forms/src/server/plugin.ts
| 🇺🇸 English |  View permissions include list and get  |
| 🇨🇳 Chinese |  查看权限包括 list 和 get |
=> fix: view permissions include list and get

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx
| 🇺🇸 English |       Determine whether to display the mobile components based on device type rather than page width    |
| 🇨🇳 Chinese |     根据设备类型而非页面宽度来判断是否显示移动端组件      |
=> fix(public-form): determine whether it is a mobile terminal based on the device type

packages/core/client/src/data-source/collection-field/CollectionField.tsx
| 🇺🇸 English |      x-disabled property not taking effect on form fields      |
| 🇨🇳 Chinese |      表单字段设置不可编辑不起作用     |
=> fix: x-disabled property not taking effect on form fields

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx
| 🇺🇸 English |       optimize title styling on the public form configuration page    |
| 🇨🇳 Chinese |    公开表单配置页面标题样式优化       |
=> style: optimize title styling on the public form configuration page

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
| 🇺🇸 English |       style issue of tooltip-icon in form fields    |
| 🇨🇳 Chinese |       表单字段中 tooltip-icon 的样式问题    |
=> fix: style issue of tooltip-icon in form fields

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/plugins/@nocobase/plugin-gantt/src/client/GanttBlockProvider.tsx
| 🇺🇸 English |   data issue with Gantt block in tree collection         |
| 🇨🇳 Chinese |  树表使用甘特图区块时数据显示异常         |
=> fix: issue with Gantt block in tree collection

packages/core/client/src/application/components/defaultComponents.tsx, packages/core/client/src/nocobase-buildin-plugin/index.tsx, packages/plugins/@nocobase/plugin-error-handler/src/server/error-handler.ts
* feat: compatible with historical button access control settings
* fix:  bug
Support custom title in AppError component.
| 🇺🇸 English |      Support custom title in AppError component.     |
| 🇨🇳 Chinese |   在 AppError 组件中支持自定义标题。        |
=> feat(client): support custom title in AppError component

packages/plugins/@nocobase/plugin-workflow-delay/src/server/DelayInstruction.ts, packages/plugins/@nocobase/plugin-workflow/package.json, packages/plugins/@nocobase/plugin-workflow/src/server/Dispatcher.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Optimize save job logic.
Change job saving timing from after each node to before exiting of execution.
| 🇺🇸 English | Optimize save job logic |
| 🇨🇳 Chinese | 优化执行记录写入逻辑 |
=> refactor(plugin-workflow): optimize save job logic

packages/core/client/src/schema-component/antd/filter/FilterItem.tsx
Support to search field in Filter component.
| 🇺🇸 English | Support to search field in Filter component |
| 🇨🇳 Chinese | 支持筛选组件中对字段进行搜索 |
=> fix(client): support to search field

packages/plugins/@nocobase/plugin-block-template/src/client/utils/template.ts, packages/plugins/@nocobase/plugin-block-template/src/server/utils/template.ts
| 🇺🇸 English | Modify and delete same fields from template and block, after creating a block from template, can cause rendering errors |
| 🇨🇳 Chinese | 模板创建区块后，模板和区块修改删除同一个字段可能会造成渲染错误 |
=> fix: null x-component has not been cleaned correctly

packages/core/utils/src/dayjs.ts
Add duration extension for dayjs.
| 🇺🇸 English | Add duration extension for dayjs |
| 🇨🇳 Chinese | 为 dayjs 包增加时长扩展 |
=> chore(utils): add extends for dayjs

packages/plugins/@nocobase/plugin-users/src/server/actions/users.ts
| 🇺🇸 English | Issue with parsing the user profile form schema          |
| 🇨🇳 Chinese | 用户个人资料表单 schema 的解析问题          |
=> fix(users): issue with parsing the user profile form schema

packages/plugins/@nocobase/plugin-workflow-delay/src/client/DelayInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-delay/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-delay/src/server/DelayInstruction.ts, packages/plugins/@nocobase/plugin-workflow-delay/src/server/__tests__/instruction.test.ts, packages/plugins/@nocobase/plugin-workflow-delay/src/server/__tests__/migrations/20250403223032-add-duration-unit.test.ts, packages/plugins/@nocobase/plugin-workflow-delay/src/server/migrations/20250403223032-add-duration-unit.ts
Support to use variable for duration.
| 🇺🇸 English | Support to use variable for duration |
| 🇨🇳 Chinese | 支持延迟时间使用变量 |
=> refactor(plugin-workflow-delay): support to use variable for duration

packages/plugins/@nocobase/plugin-block-template/src/client/components/SaveAsTemplateSetting.tsx
| 🇺🇸 English | when the referenced template used by the page block has been deleted, saving as a template fails |
| 🇨🇳 Chinese | 当页面区块使用的引用模板已经被删除，保存为模板不成功 |
=> fix save as error with ref template

packages/core/client/src/modules/blocks/data-blocks/list/__e2e__/schemaInitializer.test.ts, packages/core/client/src/schema-component/antd/action/Action.Modal.tsx
| 🇺🇸 English |    dashed underline caused by horizontal form layout in modal       |
| 🇨🇳 Chinese |     弹窗表单在 horizontal 布局下初始宽度计算错误，导致出现提示和 下划虚线    |
=> fix: dashed underline caused by horizontal form layout in modal

packages/core/client/src/locale/de-DE.json, packages/core/client/src/locale/en-US.json, packages/core/client/src/locale/es-ES.json, packages/core/client/src/locale/fr-FR.json, packages/core/client/src/locale/it-IT.json, packages/core/client/src/locale/ja-JP.json, packages/core/client/src/locale/ko-KR.json, packages/core/client/src/locale/pt-BR.json, packages/core/client/src/locale/ru-RU.json, packages/core/client/src/locale/tr-TR.json, packages/core/client/src/locale/uk-UA.json, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/locale/zh-TW.json, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/ShowTipWhenNoPages.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/mobile-action-page/MobileActionPage.style.ts, packages/plugins/@nocobase/plugin-mobile/src/client/mobile-layout/mobile-tab-bar/styles.ts, packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/content/initializer.tsx
优化未配置页面时的提示：
| 🇺🇸 English |       Optimize prompts for unconfigured pages    |
| 🇨🇳 Chinese |     优化未配置页面时的提示      |
=> refactor: optimize prompt information

packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx
| 🇺🇸 English |  workflow node edit drawer title display [object Object]         |
| 🇨🇳 Chinese |  工作流节点编辑抽屉标题显示为 [object Object]         |
=> fix: workflow node edit drawer title display [object Object]

packages/core/client/src/schema-component/antd/variable/Input.tsx, packages/core/client/src/schema-component/antd/variable/TextArea.tsx
| 🇺🇸 English | incorrect variable input style |
| 🇨🇳 Chinese | 变量输入框样式不正确 |
=> fix: incorrect variable input style

packages/core/client/src/schema-component/antd/upload/Upload.tsx
| 🇺🇸 English |       Fix the issue of preview images being obscured    |
| 🇨🇳 Chinese |     修复预览图片被遮挡的问题      |
=> fix: add global style for LightBox to prevent image overlay issues

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
| 🇺🇸 English |      Horizontal 布局下表单标题因冒号导致的截断      |
| 🇨🇳 Chinese |   label cutoff issue in horizontal layout with colon        |
=> fix: label cutoff issue in horizontal layout with colon

packages/core/cli/src/util.js
=> fix: error: ENOTEMPTY: directory not empty

packages/core/client/src/filter-provider/FilterProvider.tsx, packages/core/client/src/filter-provider/highlightBlock.ts, packages/core/client/src/locale/de-DE.json, packages/core/client/src/locale/en-US.json, packages/core/client/src/locale/es-ES.json, packages/core/client/src/locale/fr-FR.json, packages/core/client/src/locale/it-IT.json, packages/core/client/src/locale/ja-JP.json, packages/core/client/src/locale/ko-KR.json, packages/core/client/src/locale/nl-NL.json, packages/core/client/src/locale/pt-BR.json, packages/core/client/src/locale/ru-RU.json, packages/core/client/src/locale/tr-TR.json, packages/core/client/src/locale/uk-UA.json, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/locale/zh-TW.json, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/page/AllDataBlocksProvider.tsx, packages/core/client/src/schema-component/antd/page/Page.tsx, packages/core/client/src/schema-component/antd/page/index.ts, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/SchemaSettingsConnectDataBlocks.tsx, packages/plugins/@nocobase/plugin-action-bulk-update/src/client/BulkUpdateAction.Settings.tsx, packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx, packages/plugins/@nocobase/plugin-block-template/src/client/components/BlockTemplatePage.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/mobile/Mobile.tsx
| 🇺🇸 English |      Support refreshing data in other data blocks after updating data in a block    |
| 🇨🇳 Chinese |     支持在更新区块数据后刷新其它区块的数据      |
=> feat: support automatic data block refresh

packages/core/client/src/schema-component/antd/collection-select/__tests__/collection-select.test.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
| 🇺🇸 English |  style issue in variable input when setting default value         |
| 🇨🇳 Chinese |   表单字段设置默认值，变量输入框样式显示异常        |
=> fix: style issue in variable input when setting default value

packages/core/client/src/schema-initializer/utils.ts
| 🇺🇸 English |  inherited fields shown in current collection  field assignment list       |
| 🇨🇳 Chinese |     字段赋值本表字段列表中显示了继承表字段，应只显示本表字段      |
=> fix: inherited fields shown in current collection  field assignment list  

packages/plugins/@nocobase/plugin-block-iframe/src/client/Iframe.tsx
| 🇺🇸 English |    vertical scrollbar appears when iframe block is set to full height        |
| 🇨🇳 Chinese |     iframe 区块设置全高时页面出现滚动条      |
=> fix(iframe): vertical scrollbar appears when iframe block is set to full height

packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts
Fix error thrown when serializing role model to cache.
| 🇺🇸 English | Fix error thrown when serializing role model to cache |
| 🇨🇳 Chinese | 修复角色数据模型缓存序列化时的报错问题 |
=> fix(plugin-acl): fix role in cache

packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowTodo.tsx, packages/plugins/@nocobase/plugin-workflow-manual/src/common/constants.ts
Fix manual task status constant.
| 🇺🇸 English | Fix manual task status constant |
| 🇨🇳 Chinese | 修复人工节点任务状态常量 |
=> fix(plugin-workflow-manual): fix task status

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
| 🇺🇸 English |  field descriptions display issue in workflow         |
| 🇨🇳 Chinese |    工作流中字段描述显示[object Object]     |
=> fix(client): field descriptions display issue in workflow

packages/core/client/src/locale/zh-CN.json
Fix locale for upload component.
| 🇺🇸 English | Fix locale for upload component |
| 🇨🇳 Chinese | 修复上传组件语言问题 |
=> fix(client): fix upload component locale

packages/core/client/src/schema-settings/LinkageRules/index.tsx
| 🇺🇸 English |  linkage rules compatibility with legacy data         |
| 🇨🇳 Chinese |   联动规则兼容历史数据的问题        |
=> fix: linkage rules compatibility with legacy data

packages/core/database/src/interfaces/time-interface.ts
| 🇺🇸 English |     Fixed ci build error      |
| 🇨🇳 Chinese |     修复 CI 编译错误      |
=> fix: ci build

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/action/types.ts
Add delay API for scenarios which open without delay.
| 🇺🇸 English | Add delay API for scenarios which open without delay |
| 🇨🇳 Chinese | 为弹窗组件增加 delay API |
=> refactor(client): add delay API for scenarios without delay

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
Fix error thrown in create / update node of workflow.
| 🇺🇸 English | Fix error thrown in create / update node of workflow |
| 🇨🇳 Chinese | 修复新增和更新节点字段赋值的报错 |
=> fix(client): fix error thrown when no block context

packages/plugins/@nocobase/plugin-action-custom-request/src/server/actions/send.ts
| 🇺🇸 English |  Ensure custom request data must be JSON  |
| 🇨🇳 Chinese |  自定义请求的 data 参数必须为 JSON |
=> fix: ensure custom request data must be JSON

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/mobile/MobileTabBarMessageItem.tsx
On mobile devices, when switching tabs or unmounting the message component, the SSE (Server-Sent Events) connection was not closed properly. This could lead to multiple persistent connections being maintained simultaneously, causing unnecessary resource consumption and potential issues with real-time messaging.
- Disconnect SSE connection when the message component is unmounted on mobile.
- Also disconnect SSE when the user switches tabs.
- Prevents multiple long-lived SSE connections from being kept alive at the same time.
- Manually tested on major mobile browsers to ensure expected behavior.
N/A – No UI changes.
| 🇺🇸 English | fix: disconnect SSE on mobile when message component unmounts or tab is switched to avoid excessive …
=> fix(in-app-message): disconnect SSE on mobile when message component unmounts or tab is switched

packages/core/client/src/acl/ACLProvider.tsx
| 🇺🇸 English |    export button shown without export permission       |
| 🇨🇳 Chinese |    未设置导出权限时仍显示导出按钮       |
=> fix(acl):  export button shown without export permission

packages/core/client/src/schema-component/antd/action/hooks/useGetAfterSuccessVariablesOptions.ts
=> fix: after success link

packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
Add date types to variable types set.
| 🇺🇸 English | Add date types to variable types set |
| 🇨🇳 Chinese | 为变量的类型集合增加日期相关类型 |
=> refactor(plugin-workflow): adjust date type of variable

packages/plugins/@nocobase/plugin-file-manager/src/server/index.ts
Expose utils API.
| 🇺🇸 English | Expose utils API |
| 🇨🇳 Chinese | 暴露公共包 API |
=> refactor(plugin-file-manager): expose utils api

packages/plugins/@nocobase/plugin-workflow/src/client/components/TriggerCollectionRecordSelect.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/index.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/index.ts
Fix error thrown when execute schedule event in subflow.
| 🇺🇸 English | Fix error thrown when execute schedule event in subflow |
| 🇨🇳 Chinese | 修复子流程执行定时任务报错的问题 |
=> fix(plugin-workflow): fix schedule in subflow

packages/core/client/src/global-theme/type.ts, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/meta/category.ts, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/token-panel-pro/TokenContent.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/token-panel-pro/token-meta.json
| 🇺🇸 English |  Allow setting sidebar width in theme config  |
| 🇨🇳 Chinese |  主题支持设置侧边栏宽度  |
=> feat: allow setting sidebar width in theme config

packages/core/client/src/modules/blocks/data-blocks/table/tableBlockSettings.tsx, packages/core/client/src/schema-settings/LinkageRules/useValues.ts
| 🇺🇸 English |  incorrect value display for "Enable index column"         |
| 🇨🇳 Chinese |   启用序号列设置后回显错误        |
=> fix: incorrect value display for "Enable index column"

packages/core/client/src/application/globalOperators.js, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/utils/src/date.ts, packages/plugins/@nocobase/plugin-action-duplicate/src/client/__e2e__/schemaSettings.test.ts
| 🇺🇸 English |   date time field condition not working in linkage rules        |
| 🇨🇳 Chinese |    联动规则中时间字段作为判断条件无效       |
=> fix: date time field condition not working in linkage rules

packages/core/client/src/schema-component/common/utils/uitls.tsx
| 🇺🇸 English |     issue with time field as condition in linkage rules       |
| 🇨🇳 Chinese |    联动规则中时间字段值作为条件判断错误     |
=> fix: issue with time field as condition in linkage rules

packages/core/client/src/schema-settings/SchemaSettings.tsx
| 🇺🇸 English |       The issue of the collapse button in the left menu being obscured by the workflow pop-up window    |
| 🇨🇳 Chinese |     左侧菜单的收起按钮会被绑定工作流弹窗遮挡的问题      |
=> fix(SchemaSettingsActionModalItem): fix zIndex

packages/core/server/src/commands/create-migration.ts
| 🇺🇸 English |  appVersion incorrectly generated by create-migration  |
| 🇨🇳 Chinese |  create-migration 命令生成的 appVersion 不准确 |
=> fix: appVersion incorrectly generated by create-migration

packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx, packages/plugins/@nocobase/plugin-mock-collections/src/server/collection-templates/index.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2eCollectionModel.ts
| 🇨🇳 Chinese |   调整formula 语法参考链接        |
=> refactor: formula syntax references link

packages/core/client/src/schema-component/antd/linkageFilter/useValues.ts
| 🇺🇸 English |   display issue with linkage rules in multi-level association data        |
| 🇨🇳 Chinese |   多层级关系数据中联动规则未正确显示        |
=> fix: display issue with linkage rules in multi-level association data

packages/core/client/src/acl/Configuration/schemas/scopes.ts, packages/plugins/@nocobase/plugin-acl/src/client/schemas/scopes.ts, packages/plugins/@nocobase/plugin-ai/src/client/schemas/llms.ts, packages/plugins/@nocobase/plugin-block-template/src/client/schemas/editActionSchema.ts, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/channel/schemas/index.ts, packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/log/schemas/index.ts, packages/plugins/@nocobase/plugin-public-forms/src/client/schemas/editActionSchema.ts, packages/plugins/@nocobase/plugin-verification/src/client/schemas/verificators.ts
| 🇺🇸 English |    remove icon from row buttons in plugin       |
| 🇨🇳 Chinese |   移除插件中行按钮的图标        |
=> refactor: remove icon from row buttons in plugin

packages/core/client/src/locale/zh-CN.json, packages/core/client/src/schema-component/antd/upload/Upload.tsx
Adjust upload message.
| 🇺🇸 English | Adjust upload message |
| 🇨🇳 Chinese | 调整上传文件的提示信息 |
=> fix(client): adjust upload message

packages/core/client/src/acl/ACLProvider.tsx
| 🇺🇸 English |    adjust view collection action permission control       |
| 🇨🇳 Chinese |     视图表操作权限优化 ,配置状态无权限时设置透明度 ，使用状态下不显示按钮    |
=> refactor: adjust view collection action permission control

packages/core/client/src/variables/utils/getAction.tsx
| 🇺🇸 English | Incorrect data retrieved for many-to-many array fields from related tables in forms          |
| 🇨🇳 Chinese | 在表单中获取关联表中的多对多数组字段数据不正确          |
=> fix(m2m-array): incorrect data retrieved for m2m array fields from association in forms

packages/core/database/src/view-collection.ts, packages/plugins/@nocobase/plugin-action-import/src/client/index.ts, packages/plugins/@nocobase/plugin-collection-sql/src/server/sql-collection/sql-collection.ts
| 🇺🇸 English |   add  unavailableActions to sql collection and view collection       |
| 🇨🇳 Chinese |      补充sql collection和view collection 的unavailableActions     |
=> refactor: unavailableActions to sql collection and view collection

packages/core/cli/templates/create-app-package.json, packages/core/create-nocobase-app/src/generator.js, packages/core/create-nocobase-app/templates/app/package.json
| 🇺🇸 English |  Temporarily fix mariadb issue by downgrading to 2.5.6  |
| 🇨🇳 Chinese |  回退 mariadb 版本至 2.5.6，解决兼容性问题  |
=> chore: temporarily fix mariadb issue by downgrading to 2.5.6

packages/core/client/src/schema-component/antd/linkageFilter/useValues.ts, packages/core/client/src/schema-settings/VariableInput/__tests__/hooks/useURLSearchParamsVariable.test.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useURLSearchParamsVariable.ts
| 🇺🇸 English |    url query parameter operator issue       |
| 🇨🇳 Chinese |    URL 查询参数作为左侧变量操作符 异常      |
=> fix: url query parameter operator issue

packages/core/client/src/common/AppNotFound.tsx, packages/core/client/src/common/index.ts, packages/core/client/src/nocobase-buildin-plugin/index.tsx, packages/core/client/src/pm/PluginManager.tsx, packages/core/client/src/pm/PluginSetting.tsx, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/page/Page.tsx, packages/core/client/src/schema-component/antd/page/PagePopups.tsx
| 🇺🇸 English |      All 404 pages are displayed using the same component     |
| 🇨🇳 Chinese |     所有 404 页面使用同一个组件显示      |
=> refactor: unify 404 page components

packages/core/client/src/modules/blocks/data-blocks/table/TableBlockInitializer.tsx, packages/core/client/src/modules/blocks/data-blocks/table/__tests__/createTableBLockSchema.test.ts, packages/core/client/src/modules/blocks/data-blocks/table/createTableBlockUISchema.ts, packages/core/client/src/modules/blocks/data-blocks/table/hooks/useTableBlockDecoratorProps.ts, packages/core/client/src/schema-initializer/items/RecordAssociationBlockInitializer.tsx
| 🇺🇸 English |       Table block displays duplicate data when filtering    |
| 🇨🇳 Chinese |     表格区块在筛选时重复显示数据      |
=> refactor: remove rowKey from table block schema creation

packages/core/client/src/schema-component/antd/filter/FilterItem.tsx, packages/core/utils/src/__tests__/common.test.ts, packages/core/utils/src/common.ts
1. Sort and categorize the field list
2. Increase the height of the field list scroll area
| 🇺🇸 English |       Increase the height of the filter button field list and sort/categorize the fields    |
| 🇨🇳 Chinese |     增加筛选按钮字段列表的高度，和对字段进行排序分类      |
=> chore(Filter): improve user experience

.github/workflows/manual-npm-publish-license-kit.yml, packages/core/client/src/block-provider/hooks/index.ts
| 🇺🇸 English |    association field not submitting data when displaying field from related collection       |
| 🇨🇳 Chinese |       关系字段，在显示关系表下的字段数据时不提交数据    |
=> fix:  association field not submitting data when displaying field from related collection

packages/core/client/src/block-provider/hooks/index.ts
Reverts nocobase/nocobase#6789
=> Revert "fix:  association field not submitting data when displaying field from related collection"

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
…same row
| 🇺🇸 English |     optimize subtable add button style and align paginator on the  same row      |
| 🇨🇳 Chinese | 优化子表格添加按钮样式，并将分页器与按钮排列在同一行          |
=> style: optimize subtable add button style and align paginator on the  same row

packages/plugins/@nocobase/plugin-auth/src/client/settings/schemas/authenticators.ts
| 🇺🇸 English | Disallow changing authenticator name          |
| 🇨🇳 Chinese |  不允许修改认证器标识         |
=> fix(auth): disallow changing authenticator name

packages/core/client/src/schema-component/antd/variable/Input.tsx
Pass other props to Variable.Input component.
| 🇺🇸 English |      Pass other props to Variable.Input component.     |
| 🇨🇳 Chinese |     将其他属性传递给组件 Variable.Input。       |
=> fix(client): add other props to Variable.Input

packages/core/client/src/block-provider/FormBlockProvider.tsx
…field
| 🇺🇸 English |      multiple error messages displayed when validation rule is violated in form fields      |
| 🇨🇳 Chinese |     表单字段验证规则违反时错误信息多次显示      |
=> fix(form）:  multiple error messages displayed when validation rule is violated in form fields

packages/core/database/src/__tests__/fields/string-field.test.ts, packages/core/database/src/__tests__/fields/text-field.test.ts, packages/core/database/src/fields/string-field.ts, packages/core/database/src/fields/text-field.ts
Fix test cases.
| 🇺🇸 English | Fix test cases |
| 🇨🇳 Chinese | 修复测试用例 |
=> fix(database): fix test cases

packages/plugins/@nocobase/plugin-verification/src/server/migrations/20250111192640-providers2verificators.ts
| 🇺🇸 English | Fix issues of migration script          |
| 🇨🇳 Chinese | 修复升级脚本的问题         |
=> fix(verification): migration script

packages/core/client/src/schema-component/antd/rich-text/RichText.tsx
RichText component support modules and formats props
| 🇺🇸 English |    RichText component support modules and formats props       |
| 🇨🇳 Chinese |     RichText组件支持modules和formats参数       |
=> fix: RichText component support modules and formats props

packages/core/client/src/block-provider/hooks/index.ts
| 🇺🇸 English |    multiple association field failed to submit when showing fields from association collection       |
| 🇨🇳 Chinese |     表单中多个关系字段展示关系表字段时会导致关系字段不提交      |
=> fix: multiple association field failed to submit when showing fields from association collection

packages/core/database/src/interfaces/input-interface.ts, packages/core/database/src/interfaces/utils.ts
| 🇺🇸 English |      Import failed due to text field values.     |
| 🇨🇳 Chinese |    导入文本字段是数字值时失败       |
=> fix: import fialed due to text field values

packages/core/client/src/schema-settings/LinkageRules/LinkageRuleAction.tsx, packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx
| 🇺🇸 English |      linkage rule value component style improve      |
| 🇨🇳 Chinese |      改进联动规则表达式赋值组件样式     |
=> style: linkage rule value component style improve

packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts, packages/plugins/@nocobase/plugin-async-task-manager/src/server/task-type.ts
| 🇺🇸 English |       Add the log of the import plugin    |
| 🇨🇳 Chinese |      添加导入插件日志     |
=> feat: add the log of the import plugin

packages/plugins/@nocobase/plugin-block-workbench/src/client/WorkbenchBlock.tsx
Before fix:
After fix:
| 🇺🇸 English |      The color of the Action panel is incorrect in dark mode     |
| 🇨🇳 Chinese |     操作面板在暗黑模式下颜色不对      |
=> fix(Action-panel): fix theme style issues

packages/core/client/src/schema-settings/LinkageRules/bindLinkageRulesToFiled.ts
| 🇺🇸 English |       The hidden fields are still displayed    |
| 🇨🇳 Chinese |      被隐藏的字段，依然会显示出来     |
=> fix(linkageRules): hidden fields are still displayed

packages/plugins/@nocobase/plugin-workflow-test/src/server/index.ts
Fix failed test cases due to required preset plugin.
| 🇺🇸 English | Fix failed test cases due to required preset plugin |
| 🇨🇳 Chinese | 修复由于缺少必要插件造成失败的测试用例 |
=> fix(plugin-workflow-test): add required preset plugin

packages/core/database/src/repository.ts, packages/plugins/@nocobase/plugin-action-export/src/server/__tests__/export-to-xlsx.test.ts, packages/plugins/@nocobase/plugin-action-export/src/server/services/base-exporter.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts
| 🇺🇸 English |     Fixed   exporting empty values in nested associations and attachment url  |
| 🇨🇳 Chinese |  导出多级关联关系和附件 URL 时的空值问题。|
=> fix: exporting empty values in nested associations and attachment url

packages/core/client/src/modules/blocks/data-blocks/form/__e2e__/form-edit/schemaInitializer.test.ts, packages/core/client/src/modules/blocks/data-blocks/list/__e2e__/schemaInitializer.test.ts
=> refactor: e2e test page reload

packages/plugins/@nocobase/plugin-data-visualization/src/server/__tests__/issues.test.ts, packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts
| 🇺🇸 English |  Fix error when filtering nested m2m fields         |
| 🇨🇳 Chinese |  修复筛选嵌套多对多字段报错         |
=> fix(data-vi): error when filtering nested m2m fields

packages/core/build/src/buildPlugin.ts
fix the client runtime error in plugin-workflow-javascript: process undefine error
| 🇺🇸 English |      fix the client runtime error in plugin-workflow-javascript, process undefine error    |
| 🇨🇳 Chinese |      修复plugin-workflow-javascript前端运行，process undefine 错误     |
=> fix: process undefined error

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx
Fix navigating back not works when directly open popup link in tasks center.
| 🇺🇸 English | Fix navigating back not works when directly open popup link in tasks center |
| 🇨🇳 Chinese | 修复直接打开待办中心弹窗链接后无法后退关闭的问题 |
=> fix(plugin-workflow): fix popup navigate back in task center

packages/core/client/src/schema-component/antd/cascader/Cascader.tsx, packages/plugins/@nocobase/plugin-action-export/src/client/useShared.ts, packages/plugins/@nocobase/plugin-action-import/src/client/useShared.ts
| 🇺🇸 English |    improve performance when deleting fields in import/export field settings       |
| 🇨🇳 Chinese |    导入导出字段配置中删除字段严重卡顿       |
=> fix(export/import): improve performance when deleting fields in import/export field settings

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/action/utils.ts
| 🇺🇸 English |   button linkage issue  in detail block        |
| 🇨🇳 Chinese |    详情区块联动规则按钮缺陷      |
=> fix: button linkage in detail block

packages/core/client/src/index.ts, packages/plugins/@nocobase/plugin-field-attachment-url/src/client/settings/index.ts
…d status
| 🇺🇸 English |  add more built-in sizes to the attachment URL field for read status         |
| 🇨🇳 Chinese |    attachment URL 字段支持更多阅读状态的内置尺寸       |
=> refactor(attachment URL): add more built-in sizes to the attachment URL field for read status

packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts
Fix types.
| 🇺🇸 English | Fix types |
| 🇨🇳 Chinese | 修复类型 |
=> fix(plugin-file-manager): fix types

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/workflows.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/repositories/WorkflowRepository.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/CollectionTrigger.ts
Fix stack limit works incorrectly for collection event.
| 🇺🇸 English | Fix stack limit works incorrectly for collection event |
| 🇨🇳 Chinese | 修复循环触发限制更新后数据表事件触发不正确 |
=> fix(plugin-workflow): fix collection event when stack limit

packages/core/client/src/acl/ACLProvider.tsx
| 🇺🇸 English |    snippets undefined       |
=> fix: snippets undefined

packages/plugins/@nocobase/plugin-workflow-manual/src/client/WorkflowTodo.tsx
Fix render error when show unprocessed item.
| 🇺🇸 English | Fix render error when show unprocessed item |
| 🇨🇳 Chinese | 修复展示未处理待办时的渲染错误 |
=> fix(plugin-workflow-manual): fix render error when show unprocessed item

packages/plugins/@nocobase/plugin-ai/src/client/schemas/llms.ts, packages/plugins/@nocobase/plugin-verification/src/client/schemas/verificators.ts
| 🇺🇸 English |  Content is not displayed when switching between LLM service config and validation config pages         |
| 🇨🇳 Chinese | 修复 LLM 服务配置页面和验证配置页面切换不显示内容的问题          |
=> fix: schema names

packages/plugins/@nocobase/plugin-file-manager/src/server/utils.ts
=> fix: invalid url

packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/migrations/20250426134102-tasks-stats.test.ts, yarn.lock
Fix test case due to plugin removed from built-in list.
| 🇺🇸 English | Fix test case due to plugin removed from built-in list |
| 🇨🇳 Chinese | 修复由于插件移出默认开启列表导致的测试用例问题 |
=> fix(plugin-workflow-manual): fix test case

packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/server.test.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/storages/index.ts
Fix preview URL on non-image files.
| 🇺🇸 English | Fix preview URL on non-image files |
| 🇨🇳 Chinese | 修复非图片文件的预览地址 |
=> fix(plugin-file-manager): fix preview url

packages/core/client/src/schema-component/antd/action/Action.tsx
| 🇺🇸 English |  disable linkage rule not working for action button         |
| 🇨🇳 Chinese |  操作按钮禁用联动规则未生效         |
=> fix: disable linkage rule not working for action button

.github/workflows/build-docker.yml, docker/nocobase/Dockerfile-cn, docker/nocobase/docker-entrypoint.sh
| 🇺🇸 English | Build the full docker image |
| 🇨🇳 Chinese |  构建 Full 版本 Docker 镜像         |
=> chore: build the full docker image

packages/plugins/@nocobase/plugin-file-manager/src/server/__tests__/server.test.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts
Fix preview match rule.
Involved by #6889.
| 🇺🇸 English | Fix preview match rule |
| 🇨🇳 Chinese | 修复文件预览 URL 的生成匹配规则 |
=> fix(plugin-file-manager): fix preview match rule

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
…iation field
| 🇺🇸 English |    rendering error caused by invalid style format when adding association field        |
| 🇨🇳 Chinese |     添加关联字段时因 style 字段格式导致的渲染报错      |
=> fix: rendering error caused by invalid style format when adding association field

packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
=> chore: optimize get user roles in register audit log login

packages/plugins/@nocobase/plugin-notification-email/src/server/mail-server.ts, packages/plugins/@nocobase/plugin-workflow-mailer/src/server/MailerInstruction.ts
This fix ensures robust email delivery by handling undefined 'to' fields gracefully and improving recipient validation to prevent send failures.
| 🇺🇸 English |    Handle undefined 'to' field and improve email recipient processing.       |
| 🇨🇳 Chinese |   处理未定义的 'to' 字段并优化邮件收件人处理。        |
=> fix: handle undefined 'to' field and improve email recipient processing

packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/style.ts
| 🇺🇸 English |   markdown (Vditor) field not adapting to theme        |
| 🇨🇳 Chinese |    Markdown（Vditor）字段未适配主题       |
=> fix: markdown (Vditor) field not adapting to theme

.github/workflows/deploy-client-docs.yml, .github/workflows/e2e.yml, .github/workflows/manual-e2e.yml, .github/workflows/nocobase-test-windows.yml
Upgrade Node version to 20 for CI.
| 🇺🇸 English | Upgrade Node version to 20 for CI |
| 🇨🇳 Chinese | CI 环境升级 Node 版本至 20 |
=> chore(ci): upgrade node version to 20

packages/core/client/src/schema-component/common/date-filter-dynamic-component/DateFilterDynamicComponent.tsx
| 🇺🇸 English |   adjust date filter option content display        |
| 🇨🇳 Chinese |    调整日期字段筛选器的选项       |
=> refactor: adjust date filter option content display

packages/core/client/src/application/globalOperators.js
| 🇺🇸 English |     noneOf condition check failed in linkage rules      |
| 🇨🇳 Chinese |     联动规则条件不包含任意一个判断逻辑错误      |
=> fix: noneOf condition check failed in linkage rules

packages/core/client/src/schema-component/antd/grid/Grid.tsx
Fix issue where hidden form controls captured tab key, significantly improving form operation efficiency
| 🇺🇸 English |     Fix issue where hidden form controls captured tab key, significantly improving form operation efficiency      |
| 🇨🇳 Chinese |      解决表单隐藏控件也捕获了tab键的问题，极大提高了表单操作效率     |
=> [Fix] Prevent hidden form controls from capturing tab key for improved form operation efficiency

packages/core/client/src/schema-component/antd/grid/Grid.tsx
| 🇺🇸 English |  Block resize by dragging not working |
| 🇨🇳 Chinese |  区块拖拽调整宽度失效  |
=> fix: block resize by dragging not working

packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/index.tsx
| 🇺🇸 English |      Hide theme switch option and fix popup style     |
| 🇨🇳 Chinese |     隐藏主题切换选项，和修复弹窗样式      |
=> fix(mobile): hide theme switch option and fix popup style

packages/core/auth/src/base/token-control-service.ts, packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts
| 🇺🇸 English | Performance issue caused by expired token cleanup          |
| 🇨🇳 Chinese | 因清理过期token导致的性能问题          |
=> fix: performance issue caused by expired token cleanup

packages/core/client/src/block-provider/DetailsBlockProvider.tsx, packages/core/client/src/modules/popup/__e2e__/router.test.ts, packages/core/client/src/modules/popup/__e2e__/schemaInitializer1.test.ts, packages/core/client/src/modules/popup/__e2e__/subPage.test.ts, packages/core/client/src/schema-component/antd/grid/Grid.tsx, packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/__e2e__/refresh.test.ts, packages/plugins/@nocobase/plugin-gantt/src/client/__e2e__/drag.test.ts, packages/plugins/@nocobase/plugin-gantt/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-mobile/src/client/__e2e__/pageHeader.test.ts
| 🇺🇸 English |       Fields and actions only take effect after refreshing the page    |
| 🇨🇳 Chinese |     添加字段和按钮后需要刷新页面才生效      |
=> fix: resolve UI refresh issue

packages/plugins/@nocobase/plugin-public-forms/src/client/components/AdminPublicFormPage.tsx
Support to use url parameter as variable.
| 🇺🇸 English | Support to use url parameter as variable |
| 🇨🇳 Chinese | 支持使用 URL 参数作为变量 |
=> fix(plugin-public-forms): support to use url parameter as variable

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
before fixed
after fixed
| 🇺🇸 English |  missing field title in assignedField component          |
| 🇨🇳 Chinese |  修复字段赋值组件中字段标题未显示的问题         |
=> fix: missing field title in assignedField component

packages/core/client/src/data-source/data-block/DataBlockRequestProvider.tsx
| 🇺🇸 English |       The content displayed incorrectly on pages opened through popup links    |
| 🇨🇳 Chinese |     通过弹窗链接打开的页面，内容显示的不对      |
=> feat: add support for default parameters in useRequest hook

packages/plugins/@nocobase/plugin-workflow-test/src/server/index.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts
Fix workflow stats not auto created.
| 🇺🇸 English | Fix workflow stats not auto created |
| 🇨🇳 Chinese | 修复工作流统计数据未自动生成的问题 |
=> fix(plugin-workflow): auto create stats for workflows

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/hooks/useWorkflowFilterActionProps.ts, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Support to filter more fields of workflow.
| 🇺🇸 English | Support to filter more fields of workflow |
| 🇨🇳 Chinese | 支持使用更多字段筛选工作流 |
=> fix(plugin-workflow): fix filter fields

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
| 🇺🇸 English |   missing field title when setting a variable in the assignment component       |
| 🇨🇳 Chinese |    修复字段赋值组件赋值变量时未显示字段标题       |
=> fix: missing field title when setting a variable in the assignment component

packages/core/client/src/application/globalOperators.js
| 🇺🇸 English |     field style linkage rules not working       |
| 🇨🇳 Chinese |     修复字段样式联动规则设置不生效的问题      |
=> fix: field style linkage rules not working

packages/plugins/@nocobase/plugin-localization/src/server/source-manager.ts
| 🇺🇸 English |  Resolve error caused by empty texts         |
| 🇨🇳 Chinese | 修复词条为空导致的报错          |
=> fix(localization): resolve error caused by empty texts

packages/core/client/src/route-switch/antd/admin-layout/menuItemSettings.tsx
| 🇺🇸 English |      Prohibit moving a group menu into itself     |
| 🇨🇳 Chinese |     禁止将一个分组菜单移动到自己内部      |
=> fix: improve MoveToMenuItem logic and formatting

packages/core/client/src/collection-manager/templates/view.tsx
| 🇺🇸 English |      Resolved an issue where block failed to read view data from external data sources.     |
| 🇨🇳 Chinese |     修复了区块读取外部数据源视图数据时报错的问题。      |
=> fix: resolve external data source view reading error in block

packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calender.Settings.tsx, packages/plugins/@nocobase/plugin-calendar/src/client/schema-initializer/CalendarBlockProvider.tsx, packages/plugins/@nocobase/plugin-calendar/src/locale/zh-CN.json
| 🇺🇸 English |     support setting week start day in calendar block       |
| 🇨🇳 Chinese |     支持设置日历区块的周起始日（周日或周一）      |
=> refactor: support setting week start day in calendar block

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/DateFieldScheduleTrigger.ts
Fix `toJSON()` caused error in schedule trigger.
| 🇺🇸 English | Fix `toJSON()` caused error in schedule trigger |
| 🇨🇳 Chinese | 修复定时任务由于 `toJSON()` 导致的错误 |
=> fix(plugin-workflow): fix toJSON caused error in schedule trigger

packages/plugins/@nocobase/plugin-auth/src/server/plugin.ts
=> fix(auth): issue #7034

packages/plugins/@nocobase/plugin-acl/src/server/middlewares/with-acl-meta.ts, packages/plugins/@nocobase/plugin-acl/src/server/server.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/belongs-to-array-field.test.ts
Reverts nocobase/nocobase#7028
=> Revert "fix: resolve permission error for many-to-many(many) fields in data t…"

packages/core/client/src/hooks/useParsedValue.ts, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/page/Page.tsx
| 🇺🇸 English |       After clearing the badge value, the UI is not updated    |
| 🇨🇳 Chinese |     清空徽标值后，界面没有更新      |
=> fix: after clearing the badge value, the UI is not updated 

packages/core/server/src/commands/db-sync.ts
…sage')
| 🇺🇸 English |  Cannot read properties of undefined (reading 'setMaaintainingMessage') |
| 🇨🇳 Chinese | Cannot read properties of undefined (reading 'setMaaintainingMessage') |
=> fix: cannot read properties of undefined (reading 'setMaaintainingMessage')

packages/plugins/@nocobase/plugin-data-source-manager/src/server/__tests__/migrations/20250613230000-clean-datasource-collection-schema.test.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/migrations/20250613230000-clean-datasource-collection-schema.ts
| 🇺🇸 English |       Fix the issue where blocks fail to read data from external data source views.   |
| 🇨🇳 Chinese |       修复区块读取外部数据源视图数据时报错的问题。    |
=> fix: fix the issue where blocks fail to read data from external data source views

packages/plugins/@nocobase/plugin-acl/src/server/model/RoleResourceActionModel.ts, packages/plugins/@nocobase/plugin-acl/src/server/model/RoleResourceModel.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/__tests__/data-source-with-acl.test.ts, packages/plugins/@nocobase/plugin-data-source-manager/src/server/plugin.ts
| 🇺🇸 English |      Scope changes now take effect immediately for all related roles.     |
| 🇨🇳 Chinese |   修改权限的数据范围后，相关角色同步生效        |
=> fix: sync scope changes to all related roles immediately

packages/core/cache/src/__tests__/cache.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/setCurrentRole.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts
| 🇺🇸 English |      Fixed an issue where the app blocked entry when no default role existed     |
| 🇨🇳 Chinese |    修复了在没有默认角色时无法进入应用的问题       |
=> fix: allow app access when no default role exists

packages/plugins/@nocobase/plugin-async-task-manager/src/client/components/AsyncTasks.tsx
| 🇺🇸 English |      Improve performance of task creation during export     |
| 🇨🇳 Chinese |      优化导出创建任务响应慢     |
=> refactor: improve performance of task creation during export

packages/core/client/src/data-source/commonsSettingsItem/fieldComponent.ts
… number
| 🇺🇸 English |   decimal point lost after switching amount component from mask to inputNumer        |
| 🇨🇳 Chinese |    修复金额字段组件从掩码改为数字后小数点丢失的问题       |
=> fix: decimal point lost after switching amount component from mask to inputNumer

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx
…pages
| 🇺🇸 English |  required validation message in subtable persists when switching page         |
| 🇨🇳 Chinese |    修复子表格字段切换页面后必填提示不消失的问题       |
=> fix: required validation message in subtable persists when switching page

packages/plugins/@nocobase/plugin-field-sequence/src/server/__tests__/sequence-field.test.ts, packages/plugins/@nocobase/plugin-field-sequence/src/server/fields/sequence-field.ts
Fix string based bigint sequence calculation.
| 🇺🇸 English | Fix string based bigint sequence calculation |
| 🇨🇳 Chinese | 修复基于字符串的大整数序列计算 |
=> fix(plugin-field-sequence): fix bigint sequence

packages/core/client/src/variables/hooks/useLocalVariables.tsx
…default values
| 🇺🇸 English |     URL query parameter variables not working in public form field default value       |
| 🇨🇳 Chinese |     修复公开表单字段默认值中 URL 查询参数变量无效的问题      |
=> fix:  URL query parameter variables not working in public form field default value

packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx
| 🇺🇸 English |       Public forms: Fix unauthorized access issue on form submission    |
| 🇨🇳 Chinese |     公开表单：修复提交表单时报无权限的问题      |
=> fix(public-form): fix the issue of form token loss

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
Reverts nocobase/nocobase#7012
=> Revert "fix(client): fix assigned field variable scope"

packages/plugins/@nocobase/plugin-file-manager/src/common/collections/attachments.ts
Fix attachments field can not be updated in approval process.
| 🇺🇸 English | Fix attachments field can not be updated in approval process |
| 🇨🇳 Chinese | 修复审批处理中附件字段无法被更新的问题 |
=> fix(plugin-file-manager): fix collection definition

packages/plugins/@nocobase/plugin-workflow-action-trigger/src/client/ActionTrigger.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/create.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/collection.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/schedule/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
Adjust API of `getCollectionFieldOptions`.
| 🇺🇸 English | Adjust API of `getCollectionFieldOptions` |
| 🇨🇳 Chinese | 调整 `getCollectionFieldOptions` 方法的 API |
=> refactor(plugin-workflow): refactor variable api

packages/core/client/src/schema-component/antd/select/Select.tsx
| 🇺🇸 English |      Error when clicking filter button     |
| 🇨🇳 Chinese |     点击筛选按钮报错      |
=> fix: handle single value selection in multiple mode

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx, packages/plugins/@nocobase/plugin-workflow/src/common/collections/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/actions/workflows.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/migrations/20250619213102-add-missed-stats.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20250619213102-add-missed-stats.ts
Fix stats cascade deleted by non-current workflow version.
| 🇺🇸 English | Fix stats cascade deleted by non-current workflow version |
| 🇨🇳 Chinese | 修复统计数据被不是主版本的工作流级联删除的问题 |
=> fix(plugin-workflow): fix stats cascade deleted

packages/plugins/@nocobase/plugin-public-forms/src/client/components/components/MobileDatePicker.tsx
| 🇺🇸 English |      Optimize the performance of date components in public forms     |
| 🇨🇳 Chinese |     优化公开表单中日期组件的性能      |
=> fix(MobileDatePicker): reorder imports and update date range limits

.github/workflows/e2e.yml, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx
Fix params of loading record in tasks.
| 🇺🇸 English | Fix params of loading record in tasks |
| 🇨🇳 Chinese | 修复待办中心加载记录的参数 |
=> fix(plugin-workflow): fix params of loading record in tasks

packages/core/client/src/modules/blocks/data-blocks/form/createFormBlockSettings.tsx
Fault tolerance for settings based on 'x-acl-action'.
| 🇺🇸 English | Fault tolerance for settings based on 'x-acl-action' |
| 🇨🇳 Chinese | 对基于 'x-acl-action' 的表单配置项容错 |
=> fix(client): fault tolerance for settings based on x-acl-action

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowPane.tsx
Fix error thrown by cycling import.
| 🇺🇸 English | Fix error thrown by cycling import |
| 🇨🇳 Chinese | 修复循环引用导致的报错 |
=> fix(plugin-workflow): fix cycling import

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
| 🇺🇸 English |     Setting field displayName in connected view had no effect     |
| 🇨🇳 Chinese |     在连接视图中设置字段显示名称（displayName）未生效的问题      |
=> fix: setting field displayName in connected view does not take effect

.env.example, packages/core/database/src/__tests__/helpers.test.ts, packages/core/database/src/helpers.ts, packages/core/server/src/application.ts
Support to add pool options from env.
| 🇺🇸 English | Support to add pool options from env |
| 🇨🇳 Chinese | 支持从环境变量配置连接池的选项 |
=> refactor(database): add pool options from env

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/executions.tsx
Improve execution list load performance by excepting json field.
| 🇺🇸 English | Improve executions list load performance by excepting JSON field |
| 🇨🇳 Chinese | 排除 JSON 字段加载以改进执行计划列表加载性能 |
=> fix(plugin-workflow): except json field for load performance

packages/core/cli/src/commands/pkg.js
fix undefined error in download plug-in exception capture
| 🇺🇸 English |     undefined error in download plugins      |
| 🇨🇳 Chinese |     下载插件异常时 undefined 报错      |
=> fix: undefined error in download plug-in exception capture

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/antd/table.ts
| 🇺🇸 English | Table pagination issue          |
| 🇨🇳 Chinese | 表格分页器问题          |
=> fix(data-vi): table pagination issue

packages/core/client/src/schema-component/antd/appends-tree-select/AppendsTreeSelect.tsx, packages/plugins/@nocobase/plugin-workflow-manual/src/client/index.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/common/constants.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/migrations/20250426134102-tasks-stats.ts, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowTasks.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/NotificationFieldset.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/UsersSelect.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/index.ts, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/en-US.json, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
Move common components to base plugin.
| 🇺🇸 English | Move common components to base plugin |
| 🇨🇳 Chinese | 将公用组件移动到基础插件 |
=> refactor(plugin-workflow): add common components

.github/workflows/e2e.yml
Fix e2e.yml.
| 🇺🇸 English | Fix e2e.yml |
| 🇨🇳 Chinese | 修复 e2e CI 文件 |
=> chore(ci): fix e2e.yml

packages/core/client/package.json
| 🇺🇸 English |      add html5-qrcode dependency      |
| 🇨🇳 Chinese |      client 包 添加 html5-qrcode 依赖     |
=> refactor:  add html5-qrcode dependency

packages/core/client/src/flag-provider/FlagProvider.tsx, packages/core/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/antd/upload/Upload.tsx
| 🇺🇸 English |       Fix the issue where setting table column width is ineffective    |
| 🇨🇳 Chinese |     修复设置表格列宽度无效的问题      |
=> fix: update EllipsisWithTooltip to use field schema for dynamic width

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/cluster.test.ts
Skip event queue test case with SQLite due to transaction in race condition.
| 🇺🇸 English | Skip event queue test case with SQLite due to transaction in race condition |
| 🇨🇳 Chinese | 由于 SQLite 事务竞态问题，跳过事件队列的测试用例 |
| 🇺🇸 English |   |
=> test(plugin-workflow): skip event queue test case with sqlite

packages/core/acl/src/acl.ts
| 🇺🇸 English |       Fix error when deleting a role under role union mode that includes the root role.   |
| 🇨🇳 Chinese |      修复在使用包含 root 角色的并集模式下删除角色时报错的问题。  |
=> fix: error when deleting roles involved in role union with root

packages/core/client/src/schema-component/antd/fieldset/Fieldset.tsx, packages/core/client/src/schema-component/antd/fieldset/index.ts, packages/core/client/src/schema-component/antd/index.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/client/settings/schemas/applications.ts
Fix auth options in unexpected position.
| 🇺🇸 English | Fix auth options in unexpected position |
| 🇨🇳 Chinese | 修复认证选项出现在意外的位置 |
=> fix(plugin-multi-app-manager): fix auth options

packages/core/client/src/flag-provider/FlagProvider.tsx, packages/core/client/src/schema-component/antd/linkageFilter/LinkageFilterItem.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useBaseVariable.tsx, packages/plugins/@nocobase/plugin-file-manager/src/client/interfaces/attachment.ts
…ildren function
| 🇺🇸 English |      issue where attachment fields could not be selected as variables in linkage rule   |
| 🇨🇳 Chinese |    修复联动规则左侧变量无法选中附件字段的问题      |
=> fix: issue where attachment fields could not be selected as variables in linkage rule

packages/plugins/@nocobase/plugin-workflow-cc/README.md
Update content of README.
| 🇺🇸 English | Update content of README |
| 🇨🇳 Chinese | 更新 README 内容 |
=> chore(plugin-workflow-cc): update README

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Use logging instead of throwing error when execution should not run due to status.
| 🇺🇸 English | Use logging instead of throwing error when execution should not run due to status |
| 🇨🇳 Chinese | 在执行计划由于状态不可执行时用日志替代抛错 |
=> fix(plugin-workflow): avoid processor error

packages/core/client/src/schema-settings/VariableInput/hooks/useBaseVariable.tsx
| 🇺🇸 English |   display issue for association fields in linkage rules        |
| 🇨🇳 Chinese |  修复联动规则中关系字段显示异常的问题         |
=> fix: display issue for association fields in linkage rules

packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/read-db-tables.test.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/hooks/beforeDestoryField.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/repositories/collection-repository.ts, packages/plugins/@nocobase/plugin-data-source-main/src/server/server.ts
| 🇺🇸 English |  Support displaying plugin-defined tables in the main data source.         |
| 🇨🇳 Chinese |    支持主数据源显示插件定义的表。       |
=> feat: support displaying plugin-defined tables in main data source

packages/plugins/@nocobase/plugin-workflow-test/src/server/triggers.ts
Add missed API implementation for mock trigger types.
| 🇺🇸 English | Add missed API implementation for mock trigger types |
| 🇨🇳 Chinese | 为模拟触发器类型增加遗漏的 API 实现 |
=> test(plugin-workflow): add missed api implementation

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/logicCalculate.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/logicCalculate.ts
Make comparison compatible for date values.
| 🇺🇸 English | Make comparison compatible for date values |
| 🇨🇳 Chinese | 改进比较逻辑以兼容日期值 |
=> fix(plugin-workflow): make comparison compatible for date values

packages/core/database/src/cursor-builder.ts
| 🇺🇸 English |     Fixed failure when exporting large datasets from PostgreSQL      |
| 🇨🇳 Chinese |      修复 PostgreSQL 大数据量导出 XLSX 时的报错     |
=> fix: resolve xlsx export failure for large PostgreSQL datasets

packages/plugins/@nocobase/plugin-data-source-manager/src/server/resourcers/data-sources-collections.ts
| 🇺🇸 English |    Fixed preserve external datasource attributes in collection configuration       |
| 🇨🇳 Chinese |      修复修改外部数据源导致属性重置   |
=> fix: preserve external datasource attributes in collection configuration

packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx
| 🇺🇸 English |     Data selector title field setting is invalid      |
| 🇨🇳 Chinese |     数据选择器设置标题字段无效      |
=> feat: add default options handling for InternalPicker component

packages/core/cli/src/commands/pkg.js
add node_modules plugin judgment, if plugin in node_modules, not download
=> fix: add node_modules plugin judgment

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
| 🇺🇸 English |    Fix issue where Markdown fields were not rendered correctly in the detail view.       |
| 🇨🇳 Chinese |     修复 Markdown 字段在详情视图中未正确渲染为 Markdown 的问题。      |
=> fix: render markdown correctly in detail view

packages/plugins/@nocobase/plugin-workflow-parallel/src/client/ParallelInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-parallel/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-parallel/src/server/ParallelInstruction.ts, packages/plugins/@nocobase/plugin-workflow-parallel/src/server/__tests__/instruction.test.ts
Add "All settled" mode for parallel node.
| 🇺🇸 English | Add "All settled" mode for parallel node |
| 🇨🇳 Chinese | 为并行分支节点增加“全部执行”的模式 |
=> feat(plugin-workflow-parallel): add all-settled mode

packages/core/server/src/__tests__/application.test.ts, packages/core/server/src/helper.ts
| 🇺🇸 English |    Support configuring request body size limit via environment variable       |
| 🇨🇳 Chinese |      支持通过环境变量配置请求体大小限制     |
=> feat: support configuring body size limit via environment variable

packages/plugins/@nocobase/plugin-ai/src/server/workflow/nodes/llm/index.ts, packages/plugins/@nocobase/plugin-workflow-delay/src/server/DelayInstruction.ts, packages/plugins/@nocobase/plugin-workflow-mailer/src/server/MailerInstruction.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/ManualInstruction.ts, packages/plugins/@nocobase/plugin-workflow-notification/src/server/NotificationInstruction.ts, packages/plugins/@nocobase/plugin-workflow-parallel/src/server/ParallelInstruction.ts, packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts, packages/plugins/@nocobase/plugin-workflow-test/src/server/instructions.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/ConditionInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/EndInstruction.ts
Remove `await` for invoking `saveJob`.
| 🇺🇸 English | Remove `await` for invoking `saveJob` |
| 🇨🇳 Chinese | 移除调用 `saveJob` 的 `await` |
=> refactor(plugin-workflow): remove async saveJob

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
…ssociation field
| 🇺🇸 English |    fuzzy search not working in select association field when using formula as title field       |
| 🇨🇳 Chinese |   修复下拉关系字段使用 formula 作为标题时未按模糊匹配查询的问题        |
=> fix: fuzzy search not working in select association field when using formula as title field

packages/plugins/@nocobase/plugin-workflow-delay/src/server/DelayInstruction.ts, packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Fix BigInt ID issue in MySQL when save job.
| 🇺🇸 English | Fix BigInt ID issue in MySQL when save job |
| 🇨🇳 Chinese | 修复 MySQL 下保存执行记录时大整型 ID 字段的问题 |
=> fix(plugin-workflow): fix bigint id issue when save job

packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/common.ts, packages/plugins/@nocobase/plugin-file-manager/src/locale/zh-CN.json
Adjust description for configuration.
| 🇺🇸 English | Adjust description for configuration |
| 🇨🇳 Chinese | 调整配置项描述 |
=> fix(plugin-file-manager): adjust description

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
| 🇺🇸 English |       Fix issue where tree table cannot be expanded    |
| 🇨🇳 Chinese |     修复树表格无法展开的问题      |
=> fix(table): fix issue where tree table cannot be expanded

packages/plugins/@nocobase/plugin-workflow-loop/src/server/LoopInstruction.ts, packages/plugins/@nocobase/plugin-workflow-request/src/server/RequestInstruction.ts
Fix racing condition bug.
| 🇺🇸 English | Fix racing condition bug |
| 🇨🇳 Chinese | 修复竞态问题 |
=> fix(plugin-workflow-request): fix racing condition bug

packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/DynamicExpression.tsx
Fix legacy API caused error.
| 🇺🇸 English | Fix legacy API caused error |
| 🇨🇳 Chinese | 修复旧 API 导致的错误 |
=> fix(plugin-workflow-dynamic-calculation): change api

packages/presets/nocobase/package.json
Add new plugin to preset.
| 🇺🇸 English | Add new plugin to preset |
| 🇨🇳 Chinese | 将新插件加入到预置集合 |
=> fix(preset): add new plugin

packages/plugins/@nocobase/plugin-collection-tree/src/server/__tests__/sync-path.test.ts, packages/plugins/@nocobase/plugin-collection-tree/src/server/commands/sync-path.ts
修复collection-tree插件中树形路径同步逻辑的问题。原有的递归逻辑在处理父节点路径时存在缺陷，可能导致路径构建不正确。
| 🇺🇸 English | Fix the path synchronization logic of tree collections |
| 🇨🇳 Chinese | 修复树表路径同步逻辑 |
=> fix(collection-tree): improve tree path sync logic

packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts
| 🇺🇸 English |       Fix the issue where variable raw strings are submitted with the form    |
| 🇨🇳 Chinese |     修复变量原始字符串会随表单提交的问题      |
=> fix(useParseDefaultValue): set initial value to undefined

packages/core/client/src/collection-manager/Configuration/DeleteCollectionAction.tsx
| 🇺🇸 English |    Fix bulk delete collections error       |
| 🇨🇳 Chinese |    修复批量删除数据表时的错误       |
=> fix: bulk delete collections error

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
| 🇺🇸 English |       Fix the issue where multi-column form layout doesn't convert to single-column layout on mobile devices    |
| 🇨🇳 Chinese |      修复表单的多列布局在移动端没有变成单列布局的问题     |
=> fix(Form): add mobile layout support for schema transformation

packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/triggers/collection.test.ts
Fix unstable test case.
| 🇺🇸 English | Fix unstable test case |
| 🇨🇳 Chinese | 修复不稳定的测试用例 |
=> fix(plugin-workflow): fix unstable test case

packages/core/client/src/variables/__tests__/useVariables.test.tsx
=> fix: date variable client test

packages/core/server/src/audit-manager/index.ts
| 🇺🇸 English | Some requests lack `ctx.action`, causing errors in the audit log middleware          |
| 🇨🇳 Chinese |  部分请求没有 `ctx.action`, 导致审计日志中间件报错         |
=> fix(audit-logger): some requests lack `ctx.action`, causing errors in the audit log middleware

packages/plugins/@nocobase/plugin-locale-tester/src/server/plugin.ts
| 🇺🇸 English | Improve translation debugging tool |
| 🇨🇳 Chinese |  改进翻译调试工具  |
=> fix: locale tester

packages/plugins/@nocobase/plugin-field-formula/src/client/interfaces/formula.tsx
Fix the issue where formula input could not pass validation due to variable type.
| 🇺🇸 English | Fix the issue where formula input could not pass validation due to variable type |
| 🇨🇳 Chinese | 修复公式输入由于变量类型导致无法通过验证的问题 |
=> fix(plugin-field-formula): remove validation rule for expression

packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/ContentConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/components/MessageConfigForm.tsx, packages/plugins/@nocobase/plugin-notification-in-app-message/src/locale/zh-CN.json
Fix translations.
| 🇺🇸 English | Fix translations |
| 🇨🇳 Chinese | 修复多语言翻译 |
=> fix(plugin-notification-in-app-message): fix locale

packages/plugins/@nocobase/plugin-file-manager/src/client/schemas/storageTypes/common.ts, packages/plugins/@nocobase/plugin-file-manager/src/locale/zh-CN.json
Remove the hint for the file upload size limit.
| 🇺🇸 English | Remove the hint for the file upload size limit |
| 🇨🇳 Chinese | 移除文件上传大小的上限提示 |
=> fix(plugin-file-manager): fix locale

packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.tsx
| 🇺🇸 English |       Fix the issue where the form submission data in the mobile approval dialog is incorrect    |
| 🇨🇳 Chinese |     修复移动端审批弹窗中的表单提交的数据不正确的问题      |
=> fix(ActionDrawer): add basePath to SchemaComponent

packages/plugins/@nocobase/plugin-action-import/src/server/__tests__/xlsx-importer.test.ts, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
在使用 `XLSX.utils.sheet_to_json` 读取 Excel 时，遇到整行空数据的情况，返回结果中会包含 `[]` 空行
参考官方文档：https://docs.sheetjs.com/docs/api/utilities/array#array-output  
| 🇺🇸 English |  Fixed an issue where blank rows from Excel were included |
| 🇨🇳 Chinese | 修复 Excel 读取时包含空行的问题|
=> fix(action-import): skip blank rows

packages/plugins/@nocobase/plugin-mobile/src/client/pages/dynamic-page/components/MobileDatePicker.tsx
| 🇺🇸 English |    incorrect display format of date field on mobile        |
| 🇨🇳 Chinese |  修复移动端日期字段显示为错误格式的问题         |
=> fix: incorrect display format of date field on mobile

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/@nocobase/plugin-mobile/src/client/adaptor-of-desktop/ActionDrawer.tsx
| 🇺🇸 English |      Fix the "Maximum call stack size exceeded" error in the MobileLayoutProvider component     |
| 🇨🇳 Chinese |     修复 MobileLayoutProvider 组件报 “Maximum call stack size exceeded” 的错误      |
=> fix(route): remove setIsMobileLayout from Context.Consumer

packages/core/database/src/index.ts, packages/core/database/src/utils/filter-include.ts, packages/plugins/@nocobase/plugin-acl/src/server/middlewares/with-acl-meta.ts
| 🇺🇸 English |      Optimized ACL Meta query performance     |
| 🇨🇳 Chinese |    优化 ACL Meta 查询性能       |
=> perf(acl): optimize ACL Meta query performance

packages/core/client/src/schema-component/antd/quick-edit/QuickEdit.tsx
| 🇺🇸 English |    required validation not working for attachment fields in subtable        |
| 🇨🇳 Chinese |     子表格中附件字段必填校验不生效的问题      |
=> fix:  required validation not working for attachment fields in subtable

packages/core/client/src/schema-component/hooks/useBlockSize.ts
| 🇺🇸 English |       Fix an issue where, in certain scenarios, editing a record in the mobile record picker popup causes an error    |
| 🇨🇳 Chinese |     修复在某些场景下，移动端数据选择器弹窗编辑记录时出错的问题      |
=> fix(hooks): handle optional chaining for parent schema

packages/plugins/@nocobase/plugin-workflow/src/common/collections/executions.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Plugin.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20250826154821-execution-dispatched.ts, packages/plugins/@nocobase/plugin-workflow/src/server/types/Execution.ts
Optimize the query performance for retrieving queueing execution by using separate fields and indexes.
| 🇺🇸 English | Optimize the query performance for retrieving queueing execution by using separate fields and indexes |
| 🇨🇳 Chinese | 使用独立的字段和索引优化获取队列中工作流的查询性能 |
=> refactor(plugin-workflow): refactor queueing status for performance

packages/core/database/src/eager-loading/eager-loading-tree.ts, packages/core/database/src/repository.ts, packages/core/database/src/utils.ts, packages/plugins/@nocobase/plugin-field-m2m-array/src/server/__tests__/issues.test.ts
| 🇺🇸 English |  Fixed an issue where filtering by many-to-many (array) fields in related collections caused errors |
| 🇨🇳 Chinese |  修复了在主表筛选关联表中的多对多（数组）字段时报错的问题       |
=> fix(m2m-array): error when filtering by m2m array fields in the related collection

packages/plugins/@nocobase/plugin-action-import/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-action-import/src/server/services/xlsx-importer.ts
| 🇺🇸 English |      Fix incorrect row number displayed when duplicate data is imported     |
| 🇨🇳 Chinese |    修复导入xlsx重复数据时报错行数显示错误       |
=> fix: incorrect row number in duplicate data import xlsx error

packages/plugins/@nocobase/plugin-action-duplicate/src/client/DuplicateAction.tsx
=> fix: duplicateAction build error

packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
| 🇺🇸 English | Remove database events related to the collection after deleting a tree collection          |
| 🇨🇳 Chinese |   在删除树表之后移除和该表有关的数据库事件        |
=> fix(collection-tree): remove event listeners after destroying tree collections

packages/plugins/@nocobase/plugin-public-forms/src/client/components/PublicFormPage.tsx
| 🇺🇸 English |  public form field default value not applied when using variables         |
| 🇨🇳 Chinese |   修复 公开表单字段配置变量作为默认值时未生效的问题        |
=> fix: public form field default value not applied when using variables

packages/plugins/@nocobase/plugin-workflow-notification/src/client/NotificationInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-notification/src/server/NotificationInstruction.ts
Support to test the node of notification.
| 🇺🇸 English | Support to test the node of notification |
| 🇨🇳 Chinese | 支持通知节点测试执行 |
=> feat(plugin-workflow-notification): make notification node testable

packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Optimize the workflow preparation process to support using preloaded node data.
| 🇺🇸 English | Optimize the workflow preparation process to support using preloaded node data |
| 🇨🇳 Chinese | 优化工作流准备执行过程，支持使用已加载的节点数据 |
=> refactor(plugin-workflow): refactor prepare method

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx
Remove the ellipsis popover from file list.
| 🇺🇸 English | Remove the ellipsis popover from file list |
| 🇨🇳 Chinese | 移除文件列表上多余的省略预览浮层 |
=> fix(client): remove ellipsis for files

packages/core/client/src/schema-component/antd/rich-text/RichText.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/components/MobileDatePicker.tsx, packages/plugins/@nocobase/plugin-public-forms/src/client/components/components/MobilePicker.tsx
…ic forms
| 🇺🇸 English |   readonly select/multiselect/date/richtext still editable on public form        |
| 🇨🇳 Chinese |  修复公开表单 select/多选/日期/富文本在只读时仍可编辑的问题         |
=> fix: readonly select/multiselect/date/richtext still editable on public form

packages/core/auth/src/__tests__/base-auth.test.ts, packages/core/auth/src/base/auth.ts, packages/core/client/src/collection-manager/interfaces/input.ts, packages/plugins/@nocobase/plugin-auth/src/client/basic/SignInForm.tsx
| 🇺🇸 English | Support using `.` in usernames          |
| 🇨🇳 Chinese |  支持在用户名中使用 `.`         |
=> chore(users): support using `.` in usernames

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Fix the issue where incorrect subscription logic on background task queue in the workflow caused execution message incorrectly handled.
| 🇺🇸 English | Fix the issue where incorrect subscription logic on background task queue in the workflow caused execution message incorrectly handled |
| 🇨🇳 Chinese | 修复工作流后台任务队列订阅逻辑不正确导致执行消息处理异常的问题 |
=> fix(plugin-workflow): fix background job subscribing

packages/core/client/docs/zh-CN/examples/flow-definition/ui-mode/footer.tsx, packages/core/client/docs/zh-CN/examples/flow-definition/ui-mode/index.md, packages/core/client/src/flow/actions/linkageRules.tsx, packages/core/client/src/flow/actions/openView.tsx, packages/core/client/src/flow/components/DynamicFlowsIcon.tsx, packages/core/flow-engine/src/__tests__/flowSettings.open.test.tsx, packages/core/flow-engine/src/flowSettings.ts, packages/core/flow-engine/src/views/PageComponent.tsx, packages/core/flow-engine/src/views/usePage.tsx
=> feat: optimize embed  mode

packages/plugins/@nocobase/plugin-multi-app-manager/src/client/settings/schemas/applications.tsx
Check whether multiple applications are enabled before migrating old data
| 🇺🇸 English |     Check whether multiple applications are enabled before migrating old data      |
| 🇨🇳 Chinese |     迁移老数据前检查多应用是否启用      |
=> fix: Check whether multiple applications are enabled before migrating old data

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Fix the issue of duplicated executing due to improper queue handling.
| 🇺🇸 English | Fix the issue of duplicated executing due to improper queue handling |
| 🇨🇳 Chinese | 修复由于队列处理不当导致的工作流重复执行问题 |
=> fix(plugin-workflow): fix duplicated executing

packages/core/server/src/gateway/index.ts
Add graceful shutdown lifecycle handling for the application.
| 🇺🇸 English | Add graceful shutdown lifecycle handling for the application |
| 🇨🇳 Chinese | 为应用增加优雅停机的生命周期处理 |
=> feat(server): add gracefully exit

packages/plugins/@nocobase/plugin-workflow/src/client/components/TriggerWorkflowSelect.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/flows/triggerWorkflows.tsx
Fix the issue where adding a workflow in the bound workflow button configuration caused the application to freeze after clicking.
| 🇺🇸 English | Fix the issue where adding a workflow in the bound workflow button configuration caused the application to freeze after clicking |
| 🇨🇳 Chinese | 修复配置绑定工作流按钮中添加工作流点击后卡死的问题 |
=> fix(plugin-workflow): fix configuration of bind button
