README.md, package.json, packages/actions/src/actions/common.ts, packages/app/src/components/pages/AdminLoader/Actions/index.tsx, packages/app/src/components/pages/AdminLoader/Page/index.tsx, packages/app/src/components/pages/AdminLoader/View/Kanban/index.tsx, packages/app/src/components/views/Field/index.tsx, packages/resourcer/src/action.ts, packages/resourcer/src/index.ts
1. 修改部分文档措辞。
2. 修复开发启动命令。
3. 调整常量位置。
4. 修复一些由于 `key` 缺失造成的 warning。
=> fix: minor problems

packages/client/src/components/admin-layout/More.tsx, packages/client/src/components/route-schema-renderer/index.tsx, packages/client/src/locale/en_US.ts, packages/client/src/locale/zh_CN.ts, packages/plugin-system-settings/src/collections/system_settings.ts, packages/plugin-ui-router/src/ui-schema/signin.ts
=> feat: allow sign up

packages/client/src/schema-component/antd/checkbox/Checkbox.tsx, packages/client/src/schema-component/antd/checkbox/demos/demo1.tsx, packages/client/src/schema-component/antd/checkbox/demos/demo2.tsx, packages/client/src/schema-component/antd/checkbox/index.ts
=> optimize: rename checkbox component file

packages/client/src/schema-component/antd/date-picker/DatePicker.tsx, packages/client/src/schema-component/antd/date-picker/ReadPretty.tsx, packages/client/src/schema-component/antd/date-picker/demos/demo1.tsx, packages/client/src/schema-component/antd/date-picker/demos/demo2.tsx, packages/client/src/schema-component/antd/date-picker/index.md, packages/client/src/schema-component/antd/date-picker/index.ts, packages/client/src/schema-component/antd/date-picker/util.ts, packages/client/src/schema-component/antd/index.ts
add DatePicker into schema components
=> feat: add DatePicker into schema components

packages/client/src/schema-component/antd/index.ts, packages/client/src/schema-component/antd/tree-select/ReadPretty.tsx, packages/client/src/schema-component/antd/tree-select/TreeSelect.tsx, packages/client/src/schema-component/antd/tree-select/demos/demo1.tsx, packages/client/src/schema-component/antd/tree-select/index.md, packages/client/src/schema-component/antd/tree-select/index.ts
feat: add TreeSelect component into schema components
=> feat: add TreeSelect component into schema components

packages/client/src/schema-component/antd/AntdSchemaComponentProvider.tsx, packages/client/src/schema-component/antd/filter/Filter.tsx, packages/client/src/schema-component/antd/filter/FilterGroup.tsx, packages/client/src/schema-component/antd/filter/FilterItem.tsx, packages/client/src/schema-component/antd/filter/FilterList.tsx, packages/client/src/schema-component/antd/filter/demos/demo1.tsx, packages/client/src/schema-component/antd/filter/index.md, packages/client/src/schema-component/antd/filter/index.ts, packages/client/src/schema-component/antd/filter/style.less, packages/client/src/schema-component/antd/index.ts, packages/client/src/schema-component/index.tsx
add Filter component into schema componens
=> add Filter component into schema componens

packages/client/src/schemas/filter/index.tsx
=> fix: filter issue

packages/client/src/collection-manager/action-hooks.ts, packages/client/src/schema-component/antd/action/Action.Modal.tsx, packages/client/src/schema-component/antd/grid/Grid.tsx, packages/client/src/schema-component/antd/kanban/utils.ts, packages/client/src/schema-initializer/Initializers/Items/FilterActionInitializer.tsx, packages/plugin-ui-schema-storage/src/__tests__/fixtures/data.ts
=> Fix some bug

packages/client/src/schema-component/antd/markdown/Markdown.Void.tsx, packages/client/src/schema-component/antd/markdown/Markdown.tsx, packages/client/src/schema-component/antd/markdown/util.ts, packages/client/src/schema-initializer/Initializers/utils.ts, packages/client/src/schema-initializer/SchemaInitializer.tsx
=> markdown add "format" props

packages/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx, packages/client/src/schema-component/antd/input/ReadPretty.tsx, packages/client/src/schema-component/antd/input/demos/demo2.tsx, packages/client/src/schema-component/antd/input/shared.ts
textarea read pretty can support break line
=> fix: textarea read pretty can support break line

packages/client/src/schema-component/antd/upload/style.less
=> fix: modify antd style of default

packages/client/src/slate/RichText.tsx, packages/client/src/slate/index.less
=> modify slate rich style

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
long text will line feed in FormItem
=> fix: long text will line feed in FormItem

packages/core/client/src/schema-component/antd/index.less, packages/core/client/src/schema-component/antd/kanban-v2/Kanban.tsx, packages/core/client/src/schema-component/antd/kanban-v2/index.less
=> Fix: modify form item lable style

packages/core/client/src/collection-manager/interfaces/attachment.ts, packages/core/client/src/schema-component/antd/kanban-v2/Kanban.Card.Designer.tsx, packages/core/client/src/schema-component/antd/menu/Menu.Designer.tsx, packages/core/client/src/schema-component/antd/menu/Menu.tsx, packages/core/client/src/schema-initializer/utils.ts
fix menu link url style problem.
=> Fix:menu url style

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/workflow/WorkflowLink.tsx, packages/core/client/src/workflow/calculators.tsx, packages/core/client/src/workflow/nodes/condition.tsx, packages/core/client/src/workflow/nodes/index.tsx, packages/core/client/src/workflow/nodes/parallel.tsx, packages/core/client/src/workflow/nodes/query.tsx, packages/core/client/src/workflow/nodes/update.tsx, packages/core/client/src/workflow/schemas/collection.ts, packages/core/client/src/workflow/schemas/workflows.ts, packages/core/client/src/workflow/style.tsx, packages/core/client/src/workflow/triggers/collection.tsx, packages/core/client/src/workflow/triggers/index.tsx, packages/plugins/workflow/src/__tests__/execution.test.ts, packages/plugins/workflow/src/__tests__/instructions/calculation.test.ts, packages/plugins/workflow/src/__tests__/instructions/condition.test.ts, packages/plugins/workflow/src/__tests__/instructions/create.test.ts, packages/plugins/workflow/src/__tests__/instructions/destroy.test.ts, packages/plugins/workflow/src/__tests__/instructions/query.test.ts, packages/plugins/workflow/src/__tests__/instructions/update.test.ts, packages/plugins/workflow/src/triggers/collection.ts, packages/plugins/workflow/src/triggers/index.ts
* fix i18n contents
* change model event to collection event
```sql
update workflows set type='collection';
```
=> Fix(plugin workflow)

packages/core/client/src/workflow/WorkflowCanvas.tsx, packages/core/client/src/workflow/schemas/collection.ts, packages/core/client/src/workflow/triggers/collection.tsx, packages/core/client/src/workflow/triggers/index.tsx, packages/plugins/workflow/src/__tests__/instructions/condition.test.ts
* fix(plugin-workflow): fix component reaction
* test(plugin-workflow): try to fix ci random failing
=> Fix(plugin-workflow)

packages/core/client/src/schema-component/antd/filter/FilterItem.tsx
modify filter close icon color
=> fix: modify filter close icon color

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx, packages/core/client/src/schema-component/antd/action/hooks.ts
=> Feat: Unsaved changes tip

packages/core/client/src/workflow/nodes/index.tsx, packages/core/client/src/workflow/triggers/index.tsx, packages/plugins/workflow/src/__tests__/instructions/update.test.ts, packages/plugins/workflow/src/collections/flow_nodes.ts, packages/plugins/workflow/src/instructions/create.ts, packages/plugins/workflow/src/instructions/query.ts, packages/plugins/workflow/src/instructions/update.ts
=> Fix(plugin workflow): fix cannot get job result properties

packages/core/client/src/workflow/nodes/index.tsx
=> fix(plugin-workflow): fix node type title in drawers

packages/plugins/workflow/src/__tests__/execution.test.ts, packages/plugins/workflow/src/collections/workflows.ts, packages/plugins/workflow/src/models/Workflow.ts
Upgrade SQL to be run with:
~~~sql
ALTER TABLE workflows ALTER executed SET DEFAULT null;
ALTER TABLE workflows ALTER COLUMN executed TYPE INTEGER
USING CASE
WHEN false THEN 0 ELSE 1
END;
ALTER TABLE workflows ALTER executed SET DEFAULT 0;
~~~
=> refactor(plugin-workflow): change column type of executed from boolean to integer

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
=> feat: add button type color

docs/en-US/development/http-api/index.md, docs/en-US/development/http-api/rest-api.md, docs/en-US/getting-started/upgrading.md, docs/en-US/release-notes.md, docs/zh-CN/release-notes.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
=> docs(various): Improve readability

packages/core/client/src/antd-config-provider/index.tsx, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/filter/FilterItem.tsx, packages/core/client/src/workflow/calculators.tsx, packages/core/client/src/workflow/nodes/index.tsx, packages/core/client/src/workflow/schemas/collection.ts, packages/core/client/src/workflow/triggers/index.tsx, packages/core/client/src/workflow/triggers/schedule/DateFieldsSelect.tsx, packages/core/client/src/workflow/triggers/schedule/ScheduleConfig.tsx, packages/core/client/src/workflow/triggers/schedule/index.tsx, packages/core/client/src/workflow/triggers/schedule/locale/Cron.zh-CN.ts
Due to: `dropdownMatchSelectWidth` property in https://ant.design/components/select-cn/#API
=> fix(client): set `dropdownMatchSelectWidth` to false globally

packages/plugins/export/src/client/ExportActionInitializer.tsx
fix export plugin default exportable fields
=> fix: fix export plugin default exportable fields

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-initializer/buttons/FormActionInitializers.tsx, packages/core/client/src/schema-initializer/buttons/ReadPrettyFormActionInitializers.tsx
action loading, refresh context, form submit and validate
=> fix: action loading, refresh context, form submit and validate

packages/core/client/src/collection-manager/CollectionField.tsx, packages/core/client/src/collection-manager/interfaces/attachment.ts, packages/core/client/src/collection-manager/interfaces/m2m.tsx, packages/core/client/src/collection-manager/interfaces/m2o.tsx, packages/core/client/src/collection-manager/interfaces/o2m.tsx, packages/core/client/src/collection-manager/interfaces/o2o.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx, packages/core/client/src/schema-component/antd/kanban/Kanban.Card.Designer.tsx, packages/core/client/src/schema-component/antd/kanban/demos/demo1.tsx, packages/core/client/src/schema-component/antd/kanban/index.md, packages/core/client/src/schema-component/antd/record-picker/ReadPrettyRecordPicker.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx, packages/core/client/src/schema-initializer/utils.ts
the association fields of table text is overflow
=> fix: the association fields of table text is overflow

packages/core/client/src/schema-component/antd/select/shared.ts
Due to https://github.com/alibaba/formily/issues/3235.
=> fix(client): change toArr to _.castArray in select component

packages/plugins/export/src/server/__tests__/utils/utils.test.ts, packages/plugins/export/src/server/actions/export-xlsx.ts, packages/plugins/export/src/server/renders/renders.ts, packages/plugins/export/src/server/utils/columns2Appends.ts, packages/plugins/export/src/server/utils/index.ts
=> fix: export association table data

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
temporary solution to APP crash
=> fix(client): comment out useless code

packages/core/client/src/schema-component/antd/menu/Menu.tsx
=> fix: incorrectly :active background

packages/core/client/src/schema-component/antd/grid/Grid.tsx, packages/core/client/src/schema-component/common/dnd-context/index.tsx
releated issue: #383
fix second bug
=> fix: dragging an element to the left, right, or bottom would cause the element to disappear

packages/core/client/src/collection-manager/CollectionField.tsx, packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
=> fix: field loss enum

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> refactor: replace react-drag-listview with @dnd-kit/sortable

packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx, packages/core/client/src/schema-component/antd/input-number/ReadPretty.tsx, packages/core/client/src/schema-component/antd/input-number/__tests__/toFixedByStep.test.ts, packages/core/utils/src/client.ts, packages/core/utils/src/index.ts, packages/core/utils/src/number.ts, packages/core/utils/src/server.ts, packages/plugins/export/src/server/renders/renders.ts
=> fix: fix accuracy of percent

packages/core/client/src/application/Application.tsx, packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx, packages/core/client/src/schema-component/antd/date-picker/ReadPretty.tsx, packages/core/client/src/schema-component/antd/date-picker/__tests__/util.test.ts, packages/core/client/src/schema-component/antd/date-picker/util.ts, packages/core/utils/package.json, packages/core/utils/src/client.ts, packages/core/utils/src/date.ts, packages/core/utils/src/index.ts, packages/core/utils/src/server.ts, packages/plugins/export/src/server/renders/renders.ts
=> fix: fix date format

packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: required field delete submit error (#688)

packages/core/client/src/block-provider/TableFieldProvider.tsx, packages/core/client/src/collection-manager/ResourceActionProvider.tsx, packages/plugins/export/src/client/useExportAction.ts, packages/plugins/export/src/server/actions/export-xlsx.ts
=> fix: sync table sort to export

packages/core/client/src/collection-manager/interfaces/checkbox.ts, packages/core/client/src/collection-manager/interfaces/email.ts, packages/core/client/src/collection-manager/interfaces/input.ts, packages/core/client/src/collection-manager/interfaces/integer.ts, packages/core/client/src/collection-manager/interfaces/number.ts, packages/core/client/src/collection-manager/interfaces/password.ts, packages/core/client/src/collection-manager/interfaces/percent.ts, packages/core/client/src/collection-manager/interfaces/phone.ts, packages/core/client/src/collection-manager/interfaces/properties/index.ts, packages/core/client/src/collection-manager/interfaces/radioGroup.ts, packages/core/client/src/collection-manager/interfaces/select.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/database/src/__tests__/magic-attribute-model.test.ts, packages/core/database/src/collection.ts, packages/core/database/src/fields/field.ts, packages/core/database/src/magic-attribute-model.ts, packages/core/database/src/transaction-decorator.ts, packages/plugins/acl/src/__tests__/prepare.ts, packages/plugins/collection-manager/package.json, packages/plugins/collection-manager/src/__tests__/action.test.ts, packages/plugins/collection-manager/src/__tests__/field-options/indexes.test.ts, packages/plugins/collection-manager/src/__tests__/http-api/collections.test.ts, packages/plugins/collection-manager/src/__tests__/index.ts, packages/plugins/collection-manager/src/__tests__/through.test.ts, packages/plugins/collection-manager/src/models/field.ts, packages/plugins/collection-manager/src/server.ts, packages/plugins/error-handler/src/error-handler.ts, packages/plugins/ui-schema-storage/src/__tests__/server-hook-impl.test.ts, packages/plugins/ui-schema-storage/src/__tests__/server-hook.test.ts
* Base field types could be set to unique in UI.
* input
* email
* phone
* password
* integer
* number
* percent
* Unique constraint will be synced to DB.
* Field with duplicated values could not be set to unique.
* I18n error message for meeting any unique constraint.
* One test case in SQLite throws error but pass:
~~~
PASS  packages/plugins/collection-manager/src/__tests__/resources/collections.test.ts
collections
✓ remove collection (147ms)
✓ remove collection (223ms)
✓ remove collection (274ms)
console.error node_modules/jest-mock/build/index.js:866
Error: 
at Database.<anonymous> (.../node_modules/sequelize/lib/dialects/sqlite/query.js:227:27)
at .../node_modules/sequelize/lib/dialects/sqlite/query.js:225:50
at new Promise (<anonymous>)
at Query.run …
=> feat(plugin-cm): add unique option for base fields

packages/plugins/export/src/client/useExportAction.ts
=> fix: fix uiSchema undefined

packages/plugins/verification/src/actions/verifications.ts, packages/plugins/verification/src/locale/zh-CN.ts, packages/plugins/verification/src/providers/sms-aliyun.ts
=> fix(plugin-verification): change provider rate limit error to 429

packages/core/client/src/block-provider/TableBlockProvider.tsx
=> fix: sort parameter is missing

yarn.lock
=> chore: fix incorrect deps

packages/core/client/src/schema-component/antd/calendar/Calendar.tsx, packages/core/client/src/schema-component/antd/calendar/Title.tsx, packages/core/client/src/schema-component/antd/calendar/components/Header.tsx, packages/core/client/src/schema-component/antd/calendar/style.less, packages/core/client/src/schema-component/antd/calendar/types.d.ts, packages/core/client/src/schema-component/antd/calendar/utils.ts
=> feat: support show lunar day in week and day

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/schema-component/antd/table-v2/TableSelectorDesigner.tsx
fix record-picker's data range config lose  bug
=> fix(client/table-selector-provider): make data range config effective

packages/plugins/collection-manager/src/__tests__/migrations/20221104151410-update-collections-hidden.test.ts
=> test(collection-manager): 20221104151410-update-collections-hidden test correct

packages/plugins/import/src/client/useImportAction.ts
change import timeout as 10 min
=> fix: change import timeout as 10 min

.github/workflows/aliyun-container-registry.yml, docker/nocobase/nocobase.conf
=> fix: change nginx timeout as 10min

packages/plugins/workflow/src/client/calculators.tsx, packages/plugins/workflow/src/client/components/EjsTextArea.tsx
=> fix(workflow/request-var): fix request node var editor

packages/core/client/src/schema-component/antd/record-picker/ReadPrettyRecordPicker.tsx, packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
=> fix(snapshot-field): relational data without linking

packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts
=> fix: filter removeNullConditions

packages/core/client/src/block-provider/SharedFilterProvider.tsx, packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.Item.tsx, packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts
=> refactor: filter

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix(FixedBlock): using both association filters and FixedBlock does not show the complete table

.env.example, packages/core/cli/bin/index.js, packages/core/database/src/database.ts, packages/plugins/import/src/server/actions/importXlsx.ts
node.js 17+, add openssl-legacy-provider
=> fix: node.js 17+, add openssl-legacy-provider

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
Reverts nocobase/nocobase#1415
=> revert: "fix(table): make td overflow behavior right (#1392)"

README.zh-CN.md
Fix a Chinese translation issue.
=> docs: fix typo

packages/core/database/src/__tests__/fields/sort-field.test.ts, packages/core/database/src/fields/sort-field.ts, packages/plugins/collection-manager/src/__tests__/fields/belongsToMany.test.ts, packages/plugins/collection-manager/src/hooks/afterCreateForForeignKeyField.ts, packages/presets/nocobase/src/index.ts
fallback sort field init to createdAt field when primary key not exists
=> feat: fallback sort field init to createdAt field

packages/core/client/src/collection-manager/CollectionManagerProvider.tsx, packages/core/client/src/schema-component/antd/page/FixedBlock.tsx, packages/core/client/src/schema-initializer/SchemaInitializer.tsx, packages/core/client/src/schema-initializer/buttons/TableActionColumnInitializers.tsx, packages/core/client/src/schema-initializer/index.ts, packages/core/client/src/schema-initializer/utils.ts, packages/plugins/audit-logs/src/client/AuditLogsBlockInitializer.tsx, packages/plugins/audit-logs/src/client/AuditLogsBlockProvider.tsx, packages/plugins/audit-logs/src/client/AuditLogsProvider.tsx, packages/plugins/audit-logs/src/client/collections.tsx, packages/plugins/audit-logs/src/client/components/AuditLogsField.tsx, packages/plugins/audit-logs/src/client/components/AuditLogsValue.tsx, packages/plugins/audit-logs/src/client/components/AuditLogsViewActionInitializer.tsx, packages/plugins/audit-logs/src/client/deplicated/AuditLogs.tsx, packages/plugins/audit-logs/src/client/deplicated/AuditLogsDesigner.tsx, packages/plugins/audit-logs/src/client/initializers/AuditLogsTableActionColumnInitializer.tsx, packages/plugins/audit-logs/src/client/initializers/AuditLogsTableActionColumnInitializers.tsx, packages/plugins/audit-logs/src/client/initializers/AuditLogsTableActionInitializers.tsx, packages/plugins/audit-logs/src/client/initializers/AuditLogsTableColumnInitializers.tsx, packages/plugins/audit-logs/src/client/locale/en-US.ts, packages/plugins/audit-logs/src/client/locale/index.ts, packages/plugins/audit-logs/src/client/locale/ja-JP.ts, packages/plugins/audit-logs/src/client/locale/ru-RU.ts, packages/plugins/audit-logs/src/client/locale/tr-TR.ts, packages/plugins/audit-logs/src/client/locale/zh-CN.ts
=> refactor: audit log

packages/core/client/src/block-provider/FormBlockProvider.tsx
=> fix(record-picker):  supports adding sub-collection records

packages/app/client/.umirc.ts, packages/core/client/.umirc.ts, packages/core/client/package.json, packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx, packages/core/client/src/schema-component/antd/markdown/Markdown.tsx, packages/core/client/src/schema-component/antd/markdown/highlight-theme/default.less, packages/core/client/src/schema-component/antd/markdown/highlight-theme/table.less, packages/core/client/src/schema-component/antd/markdown/markdown-it-plugins/mermaidPlugin.ts, packages/core/client/src/schema-component/antd/markdown/md.ts, packages/core/client/src/schema-component/antd/markdown/util.ts, yarn.lock
=> feat(markdown): support Mermaid and better style

packages/plugins/audit-logs/src/client/components/AuditLogsField.tsx, packages/plugins/audit-logs/src/client/components/AuditLogsValue.tsx, packages/plugins/audit-logs/src/client/components/AuditLogsViewActionInitializer.tsx
=> fix(audit-logs): Add ellipsis feature to table columns 

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix: linkage rule config closing rules require reopening the form to take effect

packages/core/client/src/schema-initializer/SchemaInitializerProvider.tsx, packages/plugins/audit-logs/src/client/AuditLogsBlockProvider.tsx, packages/plugins/audit-logs/src/client/AuditLogsProvider.tsx, packages/plugins/file-manager/src/client/index.tsx, packages/plugins/map/src/client/block/index.tsx, packages/plugins/snapshot-field/src/client/index.tsx
=> fix: fix the 'Add menu item' button disappears

packages/core/client/src/collection-manager/interfaces/linkTo.ts, packages/core/client/src/collection-manager/interfaces/m2m.tsx, packages/core/client/src/collection-manager/interfaces/m2o.tsx, packages/core/client/src/collection-manager/interfaces/o2m.tsx, packages/core/client/src/collection-manager/interfaces/o2o.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/preview/Preview.tsx, packages/core/client/src/schema-component/antd/record-picker/InputRecordPicker.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/core/client/src/schema-component/antd/upload/shared.ts, packages/plugins/file-manager/src/client/hooks/useUploadFiles.ts, packages/plugins/file-manager/src/client/initializers/UploadActionInitializer.tsx, packages/plugins/file-manager/src/client/templates/file.ts
=> feat: optimize file collection

jest.config.js, jest.setup.ts, jest.setupAfterEnv.ts
Should not load `.env` file when running test.
=> test: should load the .env.test

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix: cannot display data when remove last page and the page only just one item

packages/core/client/src/collection-manager/Configuration/AddCollectionAction.tsx, packages/core/client/src/collection-manager/Configuration/AddFieldAction.tsx, packages/core/client/src/collection-manager/Configuration/SyncFieldsAction.tsx
=> fix: button loading does not disappear when the  operation submit failed

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/schema-component/antd/record-picker/InputRecordPicker.tsx
=> fix(record-picker): fix the table paging problem

.github/workflows/nocobase-test-full.yml, .github/workflows/nocobase-test-lite.yml
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> chore(ci): add timeout config for jobs

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/filter-provider/__tests__/transformToFilter.ts, packages/core/client/src/filter-provider/utils.ts, packages/core/client/src/schema-component/antd/association-select/useServiceOptions.ts, packages/core/client/src/schema-component/antd/record-picker/InputRecordPicker.tsx, packages/core/client/src/schema-initializer/utils.ts, packages/core/database/src/__tests__/filter.test.ts, packages/core/utils/src/__tests__/getValuesByPath.test.ts, packages/core/utils/src/client.ts, packages/core/utils/src/getValuesByPath.ts, packages/core/utils/src/parse-filter.ts
=> fix(FilterFormBlock): fix association field can not to filter

packages/core/client/src/pm/index.tsx
line 160: Plugin staring --> Plugin starting
=> fix: correcting misspelled word

packages/core/client/src/schema-component/antd/filter/useValues.ts
数据范围 、联动规则、工作流节点中的条件部分，改变and or逻辑会清空条件框的内容
期望：改变顶层 or and，不应该清空条件组里的内容
=> fix: filter-condition-update-incorrectly(switch "and"、"or")

packages/core/client/src/collection-manager/CollectionManagerProvider.tsx, packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/Configuration/CollectionFieldsTableArray.tsx, packages/core/client/src/collection-manager/Configuration/ConfigurationTable.tsx, packages/core/client/src/collection-manager/Configuration/ConfigurationTabs.tsx, packages/core/client/src/collection-manager/Configuration/EditCollectionAction.tsx, packages/core/client/src/collection-manager/Configuration/EditFieldAction.tsx, packages/core/client/src/collection-manager/Configuration/OverridingCollectionField.tsx, packages/core/client/src/collection-manager/Configuration/schemas/collectionFields.ts, packages/core/client/src/collection-manager/Configuration/schemas/collections.ts, packages/core/client/src/collection-manager/action-hooks.ts, packages/core/client/src/collection-manager/hooks/useCollectionManager.ts, packages/core/client/src/collection-manager/types.ts, packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/pt_BR.ts, packages/core/client/src/locale/ru_RU.ts, packages/core/client/src/locale/tr_TR.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/table/Table.Array.tsx, packages/core/client/src/schema-settings/DataTemplates/FormDataTemplates.tsx, packages/plugins/client/src/locale/en-US.json, packages/plugins/client/src/locale/pt-BR.json, packages/plugins/client/src/locale/zh-CN.json
=> feat(collection-manager): support for setting the title field

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/interfaces/linkTo.ts, packages/core/client/src/collection-manager/interfaces/m2m.tsx, packages/core/client/src/collection-manager/interfaces/m2o.tsx, packages/core/client/src/collection-manager/interfaces/o2m.tsx, packages/core/client/src/collection-manager/interfaces/o2o.tsx, packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/core/client/src/schema-settings/DataTemplates/FormDataTemplates.tsx
=> fix: improve the display of the title field

packages/app/client/.umirc.ts, packages/core/client/package.json, packages/core/client/src/application/Application.tsx, packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/pt_BR.ts, packages/core/client/src/locale/ru_RU.ts, packages/core/client/src/locale/tr_TR.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/error-fallback/ErrorFallback.tsx, packages/core/client/src/schema-component/antd/error-fallback/index.ts, packages/core/client/src/schema-component/antd/page/Page.tsx, yarn.lock
=> chore: optimize the white screen problem

packages/core/client/src/api-client/hooks/useRequest.ts, packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/pt_BR.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/association-filter/AssociationFilter.FilterBlockInitializer.tsx, packages/plugins/client/src/locale/en-US.json, packages/plugins/client/src/locale/pt-BR.json, packages/plugins/client/src/locale/zh-CN.json, packages/plugins/graph-collection-manager/src/client/locale/en-US.ts, packages/plugins/graph-collection-manager/src/client/locale/pt-BR.ts, packages/plugins/graph-collection-manager/src/client/locale/zh-CN.ts
* 修复bug: 筛选区块，折叠面板中数据范围和排序规则下拉无内容
* "Optional fields" 变更 为 "Choices fields"
* 优化 useRequest 逻辑，移除条件判断内的 hook
=> fix(filter-block): fix association fields not being filtered

packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> fix(AssociationSelect): fix x-read-pretty not working

packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/schema-settings/LinkageRules/FilterDynamicComponent.tsx, packages/core/client/src/schema-settings/LinkageRules/Variables.tsx
=> fix(linkage-rule): condition variable field is allow select  To many association fields

packages/core/client/src/collection-manager/CollectionField.tsx, packages/core/client/src/collection-manager/CollectionFieldProvider.tsx, packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/pt_BR.ts, packages/core/client/src/locale/ru_RU.ts, packages/core/client/src/locale/tr_TR.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-initializer/buttons/TableActionColumnInitializers.tsx, packages/core/client/src/schema-initializer/components/BulkEditField.tsx, packages/core/client/src/schema-initializer/components/DeletedField.tsx, packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
1. 修复当字段删除时，批量更新、编辑、操作-update record 导致页面报错的问题
2. 修改 locale 字段的 key 值语法错误
=> fix: action error when field deleted

packages/core/client/src/schema-initializer/buttons/TableColumnInitializers.tsx
=> fix: inherit fields filter foreign key fields

packages/core/client/src/collection-manager/templates/expression.tsx, packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx, packages/plugins/workflow/src/client/schemas/collection.ts
> **Note**
Add searchable for `CollectionSelect`.
When there are too many collections, need to type title to filter the dropdown list.
- Backend (后端)
None.
None.
None.
=> feat(client): allow search by title in collection select

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/core/client/src/schema-initializer/buttons/TableColumnInitializers.tsx
=> fix:association select no options when clearing filter

packages/core/client/src/block-provider/BlockProvider.tsx
> **Note**
详情关系数据字段展示/隐藏时数据没有刷新，导致看不到数据
=> fix: data is not updated when appends are changed

packages/core/client/src/schema-component/antd/association-field/Nester.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> feat(association-field): default one data for to-many association

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE/bug_fix.md, .github/PULL_REQUEST_TEMPLATE/feature.md
> **Note**
Clean PR templates format.
PR templates are not so clean in format.
=> chore(github-template): clean comments and format

packages/plugins/workflow/src/client/components/NodeDescription.tsx, packages/plugins/workflow/src/client/index.tsx, packages/plugins/workflow/src/client/locale/zh-CN.ts, packages/plugins/workflow/src/client/nodes/aggregate.tsx, packages/plugins/workflow/src/client/nodes/calculation.tsx, packages/plugins/workflow/src/client/nodes/condition.tsx, packages/plugins/workflow/src/client/nodes/create.tsx, packages/plugins/workflow/src/client/nodes/delay.tsx, packages/plugins/workflow/src/client/nodes/destroy.tsx, packages/plugins/workflow/src/client/nodes/index.tsx, packages/plugins/workflow/src/client/nodes/loop.tsx, packages/plugins/workflow/src/client/nodes/manual/index.tsx, packages/plugins/workflow/src/client/nodes/parallel.tsx, packages/plugins/workflow/src/client/nodes/query.tsx, packages/plugins/workflow/src/client/nodes/request.tsx, packages/plugins/workflow/src/client/nodes/update.tsx, packages/plugins/workflow/src/client/schemas/collection.ts
Add a description block for editing node.
To explain the usage for each type of nodes.
- Languages
- Backend (后端)
None.
=> feat(plugin-workflow): add node description to drawer when edit node

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.Designer.tsx, packages/core/client/src/schema-component/antd/grid-card/GridCard.Designer.tsx, packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx, packages/core/client/src/schema-component/antd/table-v2/TableSelectorDesigner.tsx, packages/core/client/src/schema-component/antd/table/Table.Void.Designer.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: field required  when setting sorting rules

packages/plugins/workflow/src/client/schemas/collection.ts
=> fix(plugin-workflow): fix language

packages/core/client/src/acl/Configuration/RoleConfigure.tsx, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/user/CurrentUser.tsx, packages/plugins/client/src/server.ts
增加一个按钮允许手动清除缓存
用于临时解决多节点缓存不同步问题
=> feat(system): add clear cache button

packages/core/client/src/block-provider/hooks/index.ts
=> fix: updateAssociationValues

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-items/GeneralSchemaItems.tsx
=> fix: hiding the title of a subform will hide all embedded titles

packages/core/client/src/schema-initializer/buttons/FormActionInitializers.tsx
=> fix: disable popup button in add-modal

packages/core/client/src/collection-manager/Configuration/ConfigurationTabs.tsx
=> fix(ConfigurationTabs): avoid error

packages/core/client/src/pm/PluginManagerLink.tsx, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx, packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/filter/FilterAction.tsx, packages/core/client/src/schema-component/antd/icon-picker/IconPicker.tsx, packages/core/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx, packages/core/client/src/schema-component/common/sortable-item/SortableItem.tsx, packages/core/client/src/schema-settings/DataTemplates/components/AsDefaultTemplate.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/settings-form/SettingsForm.tsx, packages/core/client/src/user/CurrentUser.tsx, packages/plugins/import/src/client/ImportModal.tsx, packages/plugins/multi-app-manager/src/client/index.tsx
Clean some client warnings.
Warnings are disturbing development console.
- `visible`/`onVisibleChange` to `open`/`onOpenChange` in some dropdown components.
- `overlap` to `menu` in some dropdown components.
- Backend (后端)
* Plugin manager dropdown links
* Multi-app dropdown links
None.
None.
=> fix(client): fix some warnings

packages/plugins/multi-app-manager/src/client/locale/zh-CN.ts, packages/plugins/multi-app-manager/src/client/settings/schemas/applications.ts, packages/plugins/multi-app-manager/src/server/__tests__/multiple-apps.test.ts, packages/plugins/multi-app-manager/src/server/server.ts, yarn.lock
1. 子应用支持配置是否自动启动，配置为是时随主应用启动时初始化。
2. 子应用独立部署时，应用启动时自动初始化。
目前子应用为冷启动，第一次访问时才初始化，生产环境耗时过长。
子应用管理配置，增加 `Auto start` 配置项。
- Backend (后端)
在子应用管理插件 `mulit-app-manager` 中监听 `app.afterStart` hook，主应用启动后自动初始化并注册需要自动启动的子应用。
1. 非独立部署，测试配置为“自动启动”的子应用有没有随主应用自动初始化并加载到内存。
2. 子应用独立部署，测试启动时子应用是否已经初始化完成。
=> feat(multi-app-manager): support auto start

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/core/client/src/schema-component/antd/select/Select.tsx
> **Note**
关系字段使用select组件时，请求数据中显示loading,请求结束显示数据
数据请求中时显示无数据 ，容易造成用户困惑，数据量大时更明显
- Backend (后端)
=> refactor: association select display loading when data is loading

packages/core/client/src/collection-manager/action-hooks.ts, packages/core/client/src/schema-component/common/utils/logic.js, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/schema-settings/LinkageRules/FilterDynamicComponent.tsx
> **Note**
联动规则条件支持对多的关系字段进行条件判断
如表格中的行按钮需要根据某个对多关系字段的值进行条件判断显示/隐藏
conditionAnalyse 方法调整，根据对多关系字段做区分逻辑
1.对多关系字段的条件判断和表格中filter中对多关系字段的使用类似，可以参考
2.对多关系字段目前支持的程度：int类型字段，string类型字段，单选/多选字段，其他字段要后续进一步支持
3.目前不支持关系的关系字段做条件判断
4.目前不支持关系的日期字段做条件判断
=> refactor(linkage rule): linkage rules condition  support toMany association fields

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-items/GeneralSchemaItems.tsx
> **Note**
修复网格卡片，列表显示/隐藏标题只在当前的区块生效
=> fix(grid-card, list): display title only work on current block

packages/core/client/src/schema-component/antd/select/Select.tsx
=> fix(select):select value should display empty when the value is null

packages/core/client/src/schema-component/antd/select/Select.tsx
=> fix: select toValue

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/core/client/src/schema-component/antd/select/Select.tsx
=> fix: select with color tag value

packages/core/client/src/schema-component/antd/association-field/Editable.tsx
=> fix(association-field): form.get & set valuesIn field.path

packages/plugins/formula-field/src/client/components/Formula/Result.tsx, packages/plugins/formula-field/src/client/components/Formula/index.tsx
#1987
Condition of invoking `onFormValuesChange` effect not correct.
Check if field component is inside a real self related and editable form first.
=> fix(plugin-formula): fix result component caused page crash

packages/plugins/mobile-client/src/server/plugin.ts, packages/plugins/mobile-client/src/server/routes.ts
=> fix: re-insert repeat routes

packages/core/client/src/schema-component/antd/grid-card/GridCard.tsx
=> fix(GridCard): column count not work

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx, packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
如果是表单模板数据，使用子表单和子表格组件时，过滤掉关系 ID
表单数据模板时，如果关系使用子表单组件，模板数据为复制
测试表单数据模板，数据复制、引用等情况
Close T-343
=> feat: filter out IDs in sub-forms

packages/core/server/src/middlewares/data-template.ts
=> fix(data-template): filter out foreign keys

packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts
> **Note**
数据模板中，子字段和父字段勾选时不用联动
- Backend (后端)
=> refactor(data-template):  child and parent field are not linked

packages/core/client/src/block-provider/hooks/index.ts
联动区块字段删除（collection中删除了字段）后，界面报错
=> fix: error reported after deleting the associationFilter  block filter field

packages/core/client/src/auth/SigninPage.tsx, packages/core/client/src/filter-provider/FilterProvider.tsx, packages/core/client/src/schema-component/antd/tabs/Tabs.tsx, packages/core/client/src/schema-component/antd/tabs/context.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/plugins/mobile-client/src/client/configuration/App.tsx, packages/plugins/mobile-client/src/client/core/bridge/index.ts, packages/plugins/mobile-client/src/client/core/bridge/injects.ts, packages/plugins/mobile-client/src/client/core/schema/common/index.ts, packages/plugins/mobile-client/src/client/core/schema/common/page.ts, packages/plugins/mobile-client/src/client/core/schema/components/container/Container.Designer.tsx, packages/plugins/mobile-client/src/client/core/schema/components/container/Container.tsx, packages/plugins/mobile-client/src/client/core/schema/components/header/Header.tsx, packages/plugins/mobile-client/src/client/core/schema/components/menu/Menu.tsx, packages/plugins/mobile-client/src/client/core/schema/components/page/Page.Designer.tsx, packages/plugins/mobile-client/src/client/core/schema/components/page/Page.tsx, packages/plugins/mobile-client/src/client/core/schema/components/tab-bar/TabBar.tsx, packages/plugins/mobile-client/src/client/locale/index.ts, packages/plugins/mobile-client/src/client/locale/zh-CN.ts, packages/plugins/mobile-client/src/client/router/InterfaceRouter.tsx, packages/plugins/mobile-client/src/client/router/RouteSwitchProvider.tsx, packages/plugins/mobile-client/src/server/plugin.ts, packages/plugins/mobile-client/src/server/routes.ts
> **Note**
删除最后一个tab导致页面崩溃
Close T-366
Close T-430
Close T-438
Close T-435
Close T-444
=> fix(mobile-client): some mobile-client bugs

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx, packages/core/client/src/schema-component/antd/association-field/Nester.tsx
> **Note**
连接数据区块功能导致 Form 十分卡顿。
https://height.app/4VWp6D2JPv/T-467
- 测一下数据关联区块的页面，是否仍有卡顿的问题。
=> fix: form performance

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/zh_CN.ts
> **Note**
多语言补充
- Backend (后端)
=> refactor(client): duplicate action locale

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> fix: avoid error

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix(tableV2): rowSelection undefined

packages/core/client/src/locale/zh_CN.ts
=> fix(client): fix locale

packages/core/client/src/schema-component/antd/input/Json.tsx
=> fix(client): remove incorrect onchange in json component

.dumirc.ts, docs/config.ts, docs/en-US/api/cli.md, package.json, yarn.lock
> **Note**
Link T-584
- Backend (后端)
=> chore: upgrade dumi-theme-nocobase

packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/client/src/migrations/20230620203213-admin-ui-schema-uid.ts, packages/plugins/client/src/server.ts, packages/plugins/mobile-client/src/client/router/Application.tsx, packages/plugins/mobile-client/src/server/migrations/20230620203215-mobile-ui-schema-uid.ts, packages/plugins/mobile-client/src/server/plugin.ts
=> refactor: migrate adminSchemaUid & mobileSchemaUid to system settings

packages/core/client/src/acl/Configuration/MenuItemsProvider.tsx, packages/core/client/src/hooks/index.ts, packages/core/client/src/hooks/useAdminSchemaUid.ts, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/plugins/mobile-client/src/client/router/Application.tsx
=> fix: add useAdminSchemaUid

packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
=> fix: incomplete display of current record fields list for assigned field 

packages/core/client/src/schema-initializer/buttons/TableColumnInitializers.tsx
… association fields
> **Note**
详情区块里，子表格的配置配置支持「显示关联表的字段」
- Backend (后端)
=> fix(sub-table): allows configuration of "Display association fields"

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
=> fix: select options

packages/core/cli/package.json, packages/core/cli/templates/plugin/src/client/index.tsx, packages/core/create-nocobase-app/package.json, yarn.lock
=> fix: create plugin cli error

packages/core/client/src/schema-initializer/utils.ts
=> fix(sub-table): inherited fields cannot be edited in a subtable

scripts/setupVitest.ts
=> chore: fix typo

packages/core/client/src/schema-component/antd/grid-card/GridCard.Item.tsx, packages/core/client/src/schema-component/antd/list/List.Decorator.tsx, packages/core/client/src/schema-component/antd/list/List.Item.tsx, packages/core/client/src/schema-component/antd/list/List.tsx
=> style:list and gridCard block style improve

packages/core/client/src/block-provider/GanttBlockProvider.tsx, packages/core/client/src/block-provider/TableBlockProvider.tsx, packages/core/client/src/schema-component/antd/gantt/components/gantt/gantt.tsx, packages/core/client/src/schema-component/antd/gantt/components/grid/grid-body.tsx, packages/core/client/src/schema-component/antd/gantt/components/task-item/bar/bar-small.tsx, packages/core/client/src/schema-component/antd/gantt/components/task-item/task-item.tsx, packages/core/client/src/schema-component/antd/gantt/helpers/bar-helper.ts, packages/core/client/src/schema-component/antd/gantt/helpers/other-helper.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/antd/table-v2/utils.ts
树形甘特图显示不对，默认应该展开所有，
开始时间和结束时间没有值不应初始化为1970年
=> fix: tree gantt block does not display correctly

packages/core/client/src/schema-settings/SchemaSettings.tsx
1. 点击此处添加一个 `Update record` 按钮
2. 点击 `字段赋值`
应该弹出弹窗
没有弹窗
#2109
#2109 的修改导致弹窗的代码没有被渲染。
让弹窗代码渲染。
close T-677
=> fix: fix dialog does not appear

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
=> refactor: request data when the drop-down list is opened

packages/plugins/client/src/migrations/20230620203216-admin-ui-schema-uid.ts, packages/plugins/mobile-client/src/server/migrations/20230620203218-mobile-ui-schema-uid.ts
=> fix: migration up error

packages/core/client/src/pm/index.tsx, packages/plugins/mobile-client/src/client/core/schema/components/header/Header.tsx
=> refactor: should use useDocumentTitle to change document title

packages/core/client/src/api-client/APIClient.ts
解决请求报错时 notification 太多的问题
- Backend (后端)
Before
After
=> feat: error cache

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
=> refactor: optimization of tree table stuck performance

docs/config.ts
=> fix: doc translation

packages/core/client/src/schema-component/antd/select/ReadPretty.tsx, packages/core/client/src/schema-component/antd/select/Select.tsx, packages/core/client/src/user/CurrentUserProvider.tsx, packages/core/client/src/user/SwitchRole.tsx, packages/plugins/acl/src/collections/roles.ts, packages/plugins/api-keys/src/client/Configuration/index.tsx, packages/plugins/api-keys/src/client/Configuration/roles.ts, packages/plugins/api-keys/src/collections/api-keys.ts
Because `roles:list` may be cannot access
Close T-789
=> fix(plugin-api-keys): use currentRoles instead of get roles from roles:list

packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx
=> test: add data-testid

packages/core/client/src/schema-component/antd/filter/FilterItems.tsx
=> fix: error opening when data scope is null

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
=> fix: cannot open the template when the data template filter is a custom function

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx, packages/core/client/src/schema-settings/EnableChildCollections/DynamicComponent.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useIterationVariable.ts
> **Note**
启用子表时支持 当前对象和当前表单变量设置（和数据范围的变量设置类似）
当前表单是「表单里的字段」
当前对象是「子表单里的字段」
- Backend (后端)
=> refactor: enable child collection support current object

packages/core/client/src/collection-manager/Configuration/OverridingCollectionField.tsx
=> fix: error reported when rewriting the collection field

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-initializer/components/DuplicateAction.tsx
=> refactor: duplicate   support  inherited collection

packages/core/client/src/schema-settings/EnableChildCollections/DynamicComponent.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useIterationVariable.ts
=> fix: current object variable can not be selected

packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts
=> fix: error reported when open data scope

packages/core/client/src/collection-manager/CollectionFieldProvider.tsx
=> fix: association field display has been delete in sub-form

packages/core/client/src/schema-initializer/SchemaInitializer.tsx, packages/core/client/src/schema-initializer/style.ts
=> fix: should limit submenu height

packages/core/client/src/schema-initializer/SchemaInitializer.tsx, packages/core/client/src/schema-initializer/style.ts, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: should only show one scroll bar in drop-down menu

packages/core/client/src/schema-component/antd/menu/Menu.tsx
=> fix: avoid crashing when delete group menu

packages/core/client/src/schema-initializer/components/DuplicateAction.tsx
=> fix: no template data requested during depulicating

packages/core/client/src/schema-component/antd/date-picker/util.ts
=> fix: avoid crashes when emptying DatePicker's value

packages/plugins/workflow/src/server/Plugin.ts
Avoid workflow not resume.
None.
All pending node should resume normally.
Sometimes, node not resume, like manual and request.
#2235.
Link T-503.
Events cache cleaned too early to queue another resume event.
Adjust phase of cleaning the events cache.
=> fix(plugin-workflow): fix dispatch bug

packages/plugins/workflow/src/client/nodes/manual/WorkflowTodo.tsx, packages/plugins/workflow/src/client/nodes/manual/WorkflowTodoBlockInitializer.tsx
=> fix: option field display value in workflow todo list

packages/plugins/workflow/src/client/ExecutionCanvas.tsx, packages/plugins/workflow/src/client/WorkflowCanvas.tsx
Fix and design warning on breadcrumb component.
=> chore(plugin-workflow): fix breadcrumb warning

packages/core/client/src/collection-manager/action-hooks.ts
=> fix: loading did not disappear after submission failure

packages/core/client/src/collection-manager/Configuration/ViewInheritedField.tsx
=> fix:  view  inherited collection field reported error

packages/core/client/src/schema-component/common/utils/logic.js
> **Note**
联动规则支持时间字段对比
- Backend (后端)
=> refactor: linkage rules support datetime

packages/core/client/src/collection-manager/CollectionManagerProvider.tsx
=> fix: collection select no options

packages/core/client/src/schema-component/antd/page/style.ts
=> fix: fix style of page tab

packages/core/client/src/schema-component/common/utils/uitls.tsx
=> fix: linkage failed with current date variable

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx, packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx, packages/core/client/src/schema-component/antd/association-field/util.ts
=> fix: the drop-down multiple selection fields are not displayed as title fields when inherited collection

packages/plugins/workflow/package.json, packages/plugins/workflow/src/client/locale/zh-CN.ts, packages/plugins/workflow/src/client/nodes/index.tsx, packages/plugins/workflow/src/client/nodes/sql.tsx, packages/plugins/workflow/src/server/__tests__/instructions/sql.test.ts, packages/plugins/workflow/src/server/instructions/index.ts, packages/plugins/workflow/src/server/instructions/sql.ts
Add SQL node in extension plugin.
Allow to execute an SQL in database.
Add a new node type.
1. Test SQL executes correctly.
2. Test SQL with workflow variables.
None.
=> feat(plugin-workflow): add sql node

packages/core/client/src/user/CurrentUser.tsx, packages/core/client/src/user/CurrentUserSettingsMenuProvider.tsx, packages/plugins/theme-editor/src/client/hooks/useUpdateThemeSettings.tsx, packages/plugins/theme-editor/src/client/index.tsx
=> fix: fix sorting of user menu

packages/plugins/theme-editor/src/client/components/InitializeTheme.tsx, packages/plugins/theme-editor/src/client/components/ThemeCard.tsx, packages/plugins/theme-editor/src/client/components/ThemeList.tsx, packages/plugins/theme-editor/src/client/hooks/useThemeSettings.tsx, packages/plugins/theme-editor/src/client/locale/zh-CN.ts, packages/plugins/theme-editor/src/server/builtinThemes.ts, packages/plugins/theme-editor/src/server/plugin.ts
- 初次启用主题插件时，应该包含 antd 默认主题 、暗黑、紧凑、紧凑暗黑 4 个内置主题
- 将 antd 默认主题 作为默认主题并在页面右上角的菜单中选中
- 当主题被设置为默认主题时，不能被删除，其余的主题可以删除
- 默认主题必须是用户能选择的
- 默认主题不能为空，也就是说当仅有一个主题时，该主题必须是默认主题
- 所有主题都可以被编辑
#2228 
1. 判断主题插件是否是第一次开启（如果 `系统设置` 和 `用户设置` 中都没有设置 `themeId` 则可以断定是初次启用）
2. 如果是第一次启用，则会调用接口去更新 `系统设置` 和 `用户设置` 的 `themeId`
- Backend (后端)
1. 在服务端插件的 `install` 阶段，初始化内置主题数据
1. 在插件管理器页面开启 `主题编辑器` 插件，然后调换到系统设置的 `主题编辑器` 页面，查看是否正常
2. 在插件管理器页面关闭 `主题插件` 然后再开启，之后再跳转到系统设置的 `主题编辑器` 页面，查看是否有重复添加的主题
3. 默认主题不允许被删除
4. 默认主题不允许不可选
5. 必须指定一个默认主题，且只能有一个
无
测试地址：https://pr-2284.test.nocobase.com
=> feat: add built-in themes

packages/core/client/src/schema-component/antd/table-v2/components/ColumnFieldProvider.tsx
=> fix:  modal  not displayed when clicking on the association field in table

packages/core/client/src/schema-component/antd/table-v2/components/ColumnFieldProvider.tsx
=> fix: table column field failed to be activated

packages/core/client/src/schema-component/antd/table-v2/components/ColumnFieldProvider.tsx
=> fix: table column field undefined fix

packages/core/client/src/schema-component/antd/table-v2/components/ColumnFieldProvider.tsx
=> refactor: table column field provider optimize

package.json, yarn.lock
close T-889
在提交 `commit` 的时候，自动运行 `eslint` 和 `prettier` ，并自动修复错误。
=> chore: auto fix eslint errors when pre-commit

packages/core/client/src/schema-component/common/dnd-context/index.tsx, packages/plugins/data-visualization/src/client/block/ChartConfigure.tsx, packages/plugins/data-visualization/src/client/renderer/ChartRenderer.tsx, packages/plugins/data-visualization/src/server/actions/query.ts, yarn.lock
新建图表区块 - 新建图表 - 复制当前图表或新建一张图表 - 拖拽排列 - 刷新页面
图表布局生效
刷新后图表布局失效
插入新图表时, schema没有带上wrap schema
```
insertAdjacent('afterEnd', gridRowColWrap(createRendererSchema(schema?.['x-decorator-props'])), {
wrap: gridRowColWrap,
})
```
```
insertAdjacent('afterEnd', gridRowColWrap(createRendererSchema(schema?.['x-decorator-props'])))
```
Close T-787
=> fix(bi): issue of dnd

packages/plugins/auth/src/server/token-blacklist.ts
=> fix: should use `filter` instead of `where`

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: collectionField undefined

packages/core/client/src/schema-component/core/FormProvider.tsx, packages/plugins/data-visualization/src/client/block/ChartConfigure.tsx, yarn.lock
在图表的`Filter`中使用公式字段
https://github.com/nocobase/nocobase/discussions/2094#discussioncomment-6384199
`Form`组件清空了组件上下文，导致找不到`Formula`组件
`Form` -> `FormProvider`
Close T-888
=> fix(bi): lose input when using formula field in filter

packages/plugins/data-visualization/src/client/block/schemas/configure.ts, packages/plugins/data-visualization/src/client/renderer/library/G2PlotLibrary.tsx, packages/plugins/data-visualization/src/server/actions/query.ts, yarn.lock
选择关系日期字段作为维度，并使用日期格式化
返回格式化后的数据
返回了格式化字符串
后端接口没有正确获取关系字段类型。
=> fix(bi): issue of formatting relation field & reference link of line chart

packages/core/client/src/schema-component/antd/association-field/Nester.tsx
=> fix(sub-form):  multi-level sub-form record provider data matching failed

packages/plugins/auth/src/swagger/index.ts, packages/plugins/oidc/src/swagger/index.ts, packages/plugins/saml/src/swagger/index.ts, yarn.lock
补充auth, saml-auth, oidc-auth相关api文件
=> docs: add auth swagger files

packages/plugins/localization-management/src/server/plugin.ts, yarn.lock
Switch user role to "Admin" and try to edit the translation in the localization management plugin.
Translations can be edited if "Admin" role has accessible permission of localization management plugin.
"No permission" popped up while trying to submit translation editing form.
https://github.com/nocobase/nocobase/issues/2344
Missing permission snippet `localizationTranslations:*`
Add permission snippet `localizationTranslations:*`
Close T-1247
=> fix(locale): acl bug of localization management

packages/plugins/workflow/src/client/components/Duration.tsx, packages/plugins/workflow/src/client/components/FieldsSelect.tsx, packages/plugins/workflow/src/client/nodes/aggregate.tsx, packages/plugins/workflow/src/client/nodes/condition.tsx, packages/plugins/workflow/src/client/nodes/index.tsx, packages/plugins/workflow/src/client/nodes/manual/AssigneesSelect.tsx, packages/plugins/workflow/src/client/nodes/request.tsx, packages/plugins/workflow/src/client/schemas/collection.ts, packages/plugins/workflow/src/client/style.tsx, packages/plugins/workflow/src/client/triggers/collection.tsx, packages/plugins/workflow/src/client/triggers/index.tsx
Classname `full-width` in component not works.
Adjust `full-width` to opposite `auto-width`.
=> refactor(plugin-workflow): adjust full-width to auto-width

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix: inherited association field failed to get detail data

packages/plugins/theme-editor/src/client/hooks/useThemeSettings.tsx, packages/plugins/theme-editor/src/client/utils/changeAlgorithmFromStringToFunction.tsx, packages/plugins/theme-editor/src/server/plugin.ts
=> chore(theme-editor): only dev env can throw errors

packages/plugins/graph-collection-manager/src/client/GraphDrawPage.tsx, packages/plugins/graph-collection-manager/src/client/components/Entity.tsx
=> fix:(graph-collection-manager) graph collection current appInfo error

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx
=> fix(default-value): should not show 'N/A' when a normal value is selected.

packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx
…ion field details in sub-table
> **Note**
- Backend (后端)
=> refactor(sub-table): modal will automatically close when config fields to association  detail field in sub-table

packages/core/client/src/global-theme/AntdAppProvider.tsx
=> fix(plugin-mobile): the layout is incorrect

.vscode/launch.json
Change debug server command to `yarn dev --server`.
Plugin and app refactored, and debug server entry missed.
- Backend (后端)
None.
None.
None.
=> chore: change debug server to yarn dev

packages/core/client/src/schema-component/antd/variable/Input.tsx
=> fix(variable): currentObject  variables unable to load association field fields

packages/core/client/src/pm/Card.tsx, packages/core/client/src/schema-component/antd/markdown/Markdown.Void.tsx, packages/core/client/src/schema-component/antd/markdown/Markdown.tsx, packages/core/client/src/schema-component/antd/markdown/style.ts, packages/core/database/src/database.ts
=> fix(markdowm): markdown style hook error reporting

packages/core/client/src/schema-settings/LinkageRules/components/LinkageHeader.tsx
=> fix(linkageRule): the copied new rule affects the replicated rule data

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
> **Note**
remoteSelect 支持简单值作为value并自动请求数据
- Backend (后端)
=> refactor: remoteSelect support non object value

packages/core/client/src/api-client/hooks/useRequest.ts
=> fix(useRequest): resource undefined

packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx
…e sub table
> **Note**
- Backend (后端)
=> fix: no field configuration items for association field details in sub-table

packages/core/client/src/schema-component/common/utils/uitls.tsx
=> fix: customized create  action  supports tree data for table selection data

packages/core/client/src/schema-component/common/utils/uitls.tsx
=> fix: contextData undefined

packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
=> fix(sub-table): params report undefined in data scope config

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-component/antd/table-v2/utils.ts
=> refactor: should not trigger event of row when clicking in drawer

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/action/Action.tsx, packages/plugins/workflow/src/client/WorkflowProvider.tsx, packages/plugins/workflow/src/client/schemas/workflows.ts, packages/plugins/workflow/src/locale/zh-CN.ts, packages/plugins/workflow/src/server/actions/workflows.ts
Add modal to edit title when duplicating workflow.
Hardcode for new title as "- copy" is not so good when duplicating.
- Add a modal to fill new title.
- Backend (后端)
* Review workflow duplicating flow.
None.
=> feat(plugin-workflow): add modal to edit title when duplicating workflow

packages/plugins/workflow/src/client/schemas/executions.tsx, packages/plugins/workflow/src/locale/zh-CN.ts, packages/plugins/workflow/src/server/__tests__/actions/executions.test.ts, packages/plugins/workflow/src/server/__tests__/index.ts, packages/plugins/workflow/src/server/actions/executions.ts, packages/plugins/workflow/src/server/actions/index.ts
Add clear button for clearing executions
Too many executions in history not useful.
- Clear button in execution list.
- Backend (后端)
- Destroy action.
Via cases.
None.
=> feat(plugin-workflow): add clear button for clearing executions

packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
… table
> **Note**
- Backend (后端)
=> refactor: restrict the fields within the configured data scope in sub table

packages/core/client/src/schema-settings/DataTemplates/hooks/useCollectionState.ts, packages/core/client/src/schema-settings/DataTemplates/utils.tsx
=> fix: useSyncFromForm support multi-level relationships

packages/plugins/map/src/client/components/AMap/Map.tsx, packages/plugins/map/src/client/components/GoogleMaps/Map.tsx
=> refactor: map field clear button pop-up blocked in sub-form(popover)

packages/plugins/workflow/src/client/WorkflowCanvas.tsx, packages/plugins/workflow/src/client/style.tsx
Adjust workflow revisions dropdown alignment styles.
=> fix(plugin-workflow): adjust styles

packages/core/client/src/schema-component/antd/action/Action.Drawer.tsx, packages/core/client/src/schema-component/antd/grid-card/GridCard.Item.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/plugins/mobile-client/src/client/configuration/App.tsx, packages/plugins/mobile-client/src/client/devices/index.tsx, packages/plugins/mobile-client/src/client/router/Application.tsx, packages/plugins/mobile-client/src/client/router/InterfaceRouter.tsx, packages/plugins/mobile-client/src/client/router/OpenInNewTab.tsx, packages/plugins/mobile-client/src/locale/zh-CN.ts, packages/plugins/theme-editor/src/client/index.tsx
> **Note**
1. 修复布局错误
2. 修复子应用展示的移动端地址不正确
3. 增加 Open in new tab 的按钮
查看布局是否有影响
=> fix(mobile-client): style broken and display correct mobile url in sub app

packages/core/client/src/schema-initializer/items/RecordFormBlockInitializer.tsx, packages/core/client/src/schema-initializer/items/RecordReadPrettyFormBlockInitializer.tsx, packages/core/client/src/schema-templates/SchemaTemplateManagerProvider.tsx
> **Note**
父表只能用本表的模板
子表可以用本表以及父表的模板
- Backend (后端)
=> refactor(schema-template): Inherit collection using blockTemplate

packages/core/client/src/collection-manager/action-hooks.ts, packages/plugins/workflow/src/client/WorkflowProvider.tsx, packages/plugins/workflow/src/client/components/ExecutionStatusSelect.tsx, packages/plugins/workflow/src/client/constants.tsx, packages/plugins/workflow/src/client/schemas/workflows.ts, packages/plugins/workflow/src/client/style.tsx, packages/plugins/workflow/src/locale/zh-CN.ts, packages/plugins/workflow/src/server/Plugin.ts, packages/plugins/workflow/src/server/Processor.ts, packages/plugins/workflow/src/server/__tests__/Plugin.test.ts, packages/plugins/workflow/src/server/actions/workflows.ts, packages/plugins/workflow/src/server/collections/workflows.ts, packages/plugins/workflow/src/server/migrations/20230809113132-workflow-options.ts
Allow to configure auto delete execution in history.
Massive executions in history and are useless in most scenarios. Manually delete them will be bothering.
- Add workflow options configurations.
- Backend (后端)
- Add destroy logic on configured.
Via cases.
None.
=> feat(plugin-workflow): allow to configure auto delete execution in history

packages/plugins/workflow/src/client/schemas/workflows.ts, packages/plugins/workflow/src/locale/zh-CN.ts
Adjust description of "Use transaction".
=> fix(plugin-workflow): fix locale

packages/plugins/workflow/src/client/schemas/workflows.ts, packages/plugins/workflow/src/locale/zh-CN.ts
Add enablement editing back to workflow form.
=> fix(plugin-workflow): add enablement editing back to workflow form

packages/plugins/file-manager/src/server/actions/attachments.ts
=> refactor:  attachment title supports utf-8 encoding

packages/core/client/src/schema-settings/SchemaSettings.tsx
=> style(schemaSettings): schemaSettings dropdown style improve

packages/core/client/src/collection-manager/Configuration/AddCollectionAction.tsx
=> refactor(collection-manager): recordPicker => associationField

packages/core/client/src/schema-initializer/utils.ts
…th each other
> **Note**
- Backend (后端)
=> fix(findSchema): table operation action  and detail operation action  interact with each other

packages/plugins/map/src/client/components/AMap/Block.tsx, packages/plugins/map/src/client/components/GoogleMaps/Block.tsx
=> fix(plugin-map): should filter empty data, Close T-1380

packages/core/client/src/schema-initializer/items/CreateActionInitializer.tsx
=> refactor:  default icon should be expected when add new action initialization

packages/core/client/src/schema-component/antd/input/EllipsisWithTooltip.tsx
=> style: ellipsisWithTooltip style improve

packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
=> refactor: remoteSelect fieldName value

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/hooks/useCollectionManager.ts, packages/core/client/src/schema-component/antd/association-select/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-settings/DataTemplates/components/Designer.tsx
move `isTitleField` into `useCollectionManager`
=> fix: hook error in `isTitleField`

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx
=> fix:  prompt on the last row of the subtable row is obscured

packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix:  error in tree table dragging and sorting

packages/core/client/src/schema-component/antd/quick-edit/QuickEdit.tsx
=> fix: large field in sub-table do not display value

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
…llection
> **Note**
- Backend (后端)
=> fix: source collections not updated during synchronization in view collection

packages/core/sdk/src/APIClient.ts
> **Note**
window is not defined in nuxt
nocobase/sdk
无
无
无
=> fix(sdk): window is not defined in nuxt (#2479)

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx, packages/core/client/src/collection-manager/templates/components/PreviewTable.tsx, packages/core/client/src/collection-manager/templates/view.tsx
=> fix(view-collection): source field mismatch during view collection configuration switching

packages/core/client/src/schema-component/antd/association-field/InternalTag.tsx
=> fix(tag): the color value of the association field tag field is incorrect

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
- `sequence` 字段不应该支持设置默认值
close T-1490
=> chore: remove Default value option for sequence field

packages/core/app/client/.umirc.ts, packages/core/app/client/src/pages/index.tsx, packages/core/client/src/application/Application.tsx, packages/core/client/src/application/PluginManager.ts, packages/core/client/src/application/utils/remotePlugins.ts, packages/core/devtools/umiConfig.js
> **Note**
DEV 环境下，未启用的插件不应该加载。
- 插件加载相关
=> fix: dev load plugin

packages/core/client/src/collection-manager/templates/view.tsx
=> fix: view collection  reported error when editing

packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> refactor: m2m data filtering through collection data for association field default value

packages/plugins/workflow/src/client/CanvasContent.tsx, packages/plugins/workflow/src/client/style.tsx
Adjust terminal style on workflow canvas.
Terminal card style not so good.
- Terminal styles of workflow canvas
- Backend (后端)
None.
None.
=> style(plugin-workflow): adjust terminal style on workflow canvas

packages/plugins/workflow/src/client/WorkflowCanvas.tsx, packages/plugins/workflow/src/client/WorkflowProvider.tsx, packages/plugins/workflow/src/client/components/ExecutionStatusColumn.tsx, packages/plugins/workflow/src/client/schemas/executions.tsx, packages/plugins/workflow/src/server/Processor.ts, packages/plugins/workflow/src/server/collections/executions.ts, packages/plugins/workflow/src/server/instructions/condition.ts, packages/plugins/workflow/src/server/instructions/delay.ts, packages/plugins/workflow/src/server/instructions/manual/index.ts, packages/plugins/workflow/src/server/instructions/parallel.ts, packages/plugins/workflow/src/server/instructions/request.ts
Add node in executions list when failed.
Make it a little easy to show why an execution fails.
- Add node tag to executions list.
- Backend (后端)
- Add `lastJob` field to executions table.
None.
Failed node in branch may not be shown as last job, most will be main branch nodes.
=> feat(plugin-workflow): add node in executions list when failed

packages/plugins/theme-editor/src/server/plugin.ts
=> fix(theme-editor): fix enable invalid

packages/plugins/workflow/src/client/WorkflowProvider.tsx, packages/plugins/workflow/src/client/schemas/workflows.ts
Add filter button for workflows list.
When there are too many workflows, hard to find some one, filter is needed.
- Workflow list schema.
- Backend (后端)
Use the filter.
None.
=> feat(plugin-workflow): add filter button for workflows list

packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
…ttings
> **Note**
- Backend (后端)
=> refactor:  association fields in  table should not have data scope setting

packages/presets/nocobase/src/server/index.ts, packages/presets/nocobase/src/server/migrations/20230829160015-set-audit-local.ts, yarn.lock
将`audit-logs`插件修改为本地插件，非内置。
Close T-1671
=> chore: set audit-logs as local plugin

packages/core/client/src/collection-manager/Configuration/AddFieldAction.tsx, packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/Configuration/CollectionFieldsTableArray.tsx, packages/core/client/src/collection-manager/Configuration/EditFieldAction.tsx, packages/core/client/src/collection-manager/Configuration/OverridingCollectionField.tsx, packages/core/client/src/collection-manager/Configuration/ViewInheritedField.tsx, packages/core/client/src/collection-manager/Configuration/schemas/collectionFields.ts, packages/core/client/src/collection-manager/Configuration/schemas/collections.ts, packages/core/client/src/collection-manager/templates/calendar.tsx, packages/core/client/src/collection-manager/templates/expression.tsx, packages/core/client/src/collection-manager/templates/general.tsx, packages/core/client/src/collection-manager/templates/properties/index.ts, packages/core/client/src/collection-manager/templates/tree.tsx, packages/core/client/src/collection-manager/templates/view.tsx, packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts, packages/core/client/src/schema-component/antd/input/Input.tsx, packages/plugins/collection-manager/src/server/__tests__/collections.repository.test.ts, packages/plugins/collection-manager/src/server/collections/collections.ts, packages/plugins/collection-manager/src/server/collections/fields.ts, packages/plugins/file-manager/src/client/templates/file.ts
=> refactor(collection-manager): collection &&fields support description  config

packages/plugins/workflow/src/swagger/index.ts
Add more detail about swagger docs.
Parameters and responses not so clear.
- Docs
None.
=> docs(plugin-workflow): fix swagger docs

packages/core/client/src/schema-component/antd/input-number/InputNumber.tsx
=> fix(input-number): number field report error when clearing data

packages/plugins/api-keys/src/client/Configuration/schema.tsx, packages/plugins/api-keys/src/locale/zh-CN.ts
=> feat(api-keys): add tooltip for roles

packages/core/client/src/acl/Configuration/FilterDynamicComponent.tsx
=> fix(FilterDynamicComponent): avoid crashing

packages/plugins/file-manager/src/server/migrations/20230831160742-fix-attachment-field.ts, packages/plugins/file-manager/src/server/server.ts
Legacy attachment with storage settings will not work (#2577). Need to add migration.
=> fix(plugin-fm): add migration to fix attachment ui schema

packages/core/client/src/block-provider/TableBlockProvider.tsx, packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx, packages/core/client/src/schema-component/antd/table-v2/TableSelectorDesigner.tsx
=> refactor: restrict the use of tree table in data selectors

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix: association block report error for toOne association field

packages/plugins/auth/src/client/settings/schemas/authenticators.ts, yarn.lock
=> fix(auth): add authenticator uid limitation

packages/core/client/src/schema-component/antd/table-v2/TableBlockDesigner.tsx
=> fix: resource undefined in work todo list

packages/plugins/collection-manager/src/server/server.ts, packages/plugins/multi-app-manager/src/server/server.ts, packages/plugins/theme-editor/src/server/plugin.ts, yarn.lock
1. 创建一个角色，取消全局的查看、新增、编辑、删除，但是有所有插件的操作权限
2. 编辑主题、添加数据表分类、访问多应用管理页面
2中操作正常
2中操作报错`No permissions`
Close T-1800, T-1791, T-1793, T-1794
插件acl snippet未注册相关接口
将相关接口注册到插件acl snippet
=> fix: issue of plugin snippet

packages/core/client/src/global-theme/defaultTheme.ts, packages/plugins/theme-editor/src/client/index.tsx
=> chore(antd): reduce animation duration

packages/plugins/workflow/src/client/components/CollectionFieldset.tsx, packages/plugins/workflow/src/client/nodes/calculation.tsx
Allow some node to select variable from midway path.
Sometimes need to select whole trigger data as an object.
- Calculation node, create node and update node.
- Backend (后端)
Sometimes variable will be used with mistake.
=> feat(plugin-workflow): support variable in midway path

packages/core/client/src/block-provider/hooks/index.ts
=> fix: create action reported error when config save mode filterKeys

packages/plugins/mobile-client/src/client/core/schema/components/container/Container.Designer.tsx
close: #2533
###Height Tasks
Close T-1604
=> fix(mobile-client-plugin): avoid primary field error

packages/core/client/src/collection-manager/Configuration/ConfigurationTabs.tsx
=> style: collection category style improve

packages/core/server/src/__tests__/command.test.ts, packages/core/server/src/application.ts
=> fix(cli): reset command options

packages/core/client/src/schema-component/antd/filter/Filter.Action.Designer.tsx, packages/core/client/src/schema-component/antd/filter/useFilterActionProps.ts, packages/core/client/src/schema-settings/LinkageRules/Variables.tsx
=> fix(collection-manager): filterable undefined

packages/core/client/src/collection-manager/interfaces/number.ts
=> refactor: view collection float type field support number and percent

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx
=> fix(collection-fields): interface  group undefined

packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowProvider.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/WorkflowTodo.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/forms/custom.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
Allow plugin to register new trigger types.
Trigger types is static array, should be changed to dynamic generated when needed.
- `getTriggersOptions()`
- Backend (后端)
None.
=> refactor(plugin-workflow): adjust code

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx
=> fix: file association field failed to set file manager as field component in table 

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/schema-component/antd/association-field/InternalNester.tsx, packages/plugins/@nocobase/plugin-import/src/client/ImportActionInitializer.tsx, packages/plugins/@nocobase/plugin-import/src/client/ImportPluginProvider.tsx
=> fix(acl): association field acl check error

packages/core/client/src/acl/Configuration/RoleConfigure.tsx, packages/plugins/@nocobase/plugin-import/src/client/ImportPluginProvider.tsx
=> style:form-item style improve

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/acl/Configuration/RoleConfigure.tsx, packages/plugins/@nocobase/plugin-import/src/client/ImportActionInitializer.tsx
=> refactor(acl):  acl collection field provider

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> refactor(acl): association block acl authority improve

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix(client): deep level association field adding error

packages/core/client/src/filter-provider/utils.ts, packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx
=> fix: fix operator called $dateBetween of date field

packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx
Add client exports members.
For testing plugins.
- exports
- Backend (后端)
None.
None.
None.
=> refactor(plugin-workflow): add client exports

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/association-field/Editable.tsx
…t effective
> **Note**
- Backend (后端)
=> fix:  saving method of association field creation button is not effect

packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx, packages/core/client/src/schema-component/antd/filter/useValues.ts
=> fix: tableoid options value of association field in filter is incorrect

packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
=> fix(client): form-data-template failed to clear option

packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx
=> fix(client): inherited collections failed to select

packages/core/client/src/block-provider/hooks/index.ts
=> refactor(client): useAssociationNames support tree collection

packages/core/client/src/schema-component/antd/action/Action.tsx
=> fix(client): action linkage rule not effect in tree collection

packages/core/client/src/block-provider/hooks/index.ts
=> fix: association block should not close drawer after deleting data

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx
=> fix: fileManager did not close drawer after selecting files

packages/core/client/src/collection-manager/interfaces/json.tsx
=> refactor: view collection support jsonb

packages/core/client/src/schema-initializer/utils.ts
…d as title field
> **Note**
- Backend (后端)
=> refactor: file association field default to using preview field as title field

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix(association-field): sub-table cannot move

packages/plugins/@nocobase/plugin-oidc/src/client/OIDCButton.tsx, packages/plugins/@nocobase/plugin-oidc/src/server/__tests__/oidc.test.ts, packages/plugins/@nocobase/plugin-oidc/src/server/actions/redirect.ts, packages/plugins/@nocobase/plugin-oidc/src/server/oidc-auth.ts, packages/plugins/@nocobase/plugin-saml/src/client/SAMLButton.tsx, packages/plugins/@nocobase/plugin-saml/src/server/__tests__/saml.test.ts, packages/plugins/@nocobase/plugin-saml/src/server/actions/redirect.ts, packages/plugins/@nocobase/plugin-saml/src/server/saml-auth.ts, yarn.lock
Switch the OIDC and SAML popup login methods to page redirection.
The compatibility of popup is not optimal and may not be suitable in certain environments, like in WebView.
Close T-2024
https://github.com/nocobase/nocobase/discussions/2050
=> refactor(auth): OIDC, SAML auth switch popup to redirectction

packages/core/client/src/schema-component/antd/list/List.Decorator.tsx
=> style: list block style improve

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx, packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/components/Entity.tsx, packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/style.tsx
=> fix(graph-collection-manager):graph collection cannot open edit modal

packages/core/client/src/schema-component/antd/association-field/SubTable.tsx, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useSpecialCase.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/variables/constants.ts
=> fix(subtable): should not have a value by default and fix key of table

packages/core/client/src/schema-settings/LinkageRules/ValueDynamicComponent.tsx
=> fix(variable): should not disable options in expression

packages/core/utils/src/__tests__/getValuesByPath.test.ts, packages/core/utils/src/getValuesByPath.ts, tsconfig.json, vitest.config.ts
=> fix(variable): should not return undefined when parsing 0

packages/core/client/src/__tests__/e2e/bugs/T-2165.test.ts, packages/core/client/src/schema-component/antd/variable/TextArea.tsx
=> fix(expression): should reset lastIndex of regular

packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
=> refactor(duplicate action):duplicate fields error when change duplicate mode & support unselect all 

packages/core/client/src/schema-component/antd/percent/Percent.tsx, packages/core/client/src/schema-component/antd/percent/__tests__/percent.test.tsx
=> fix(percent): percent failed to input 0

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/form.ts, packages/plugins/@nocobase/plugin-workflow/src/server/utils.ts
Form trigger throw error.
1. Create a form workflow.
2. Add some appends fields.
3. Trigger the workflow.
Process correctly.
Throw errors.
#2749
Not check type for `toJSON` input.
Add type checking.
=> fix(plugin-workflow): fix toJSON type check

packages/core/client/src/__tests__/e2e/bugs/T-2165.test.ts, packages/core/client/src/__tests__/e2e/faker.test.ts, packages/core/test/src/client/e2eUtils.ts, playwright.config.ts, scripts/runE2e.setup.ts, scripts/utils.ts
=> refactor(e2e):  support batch creation of collections

packages/core/client/src/schema-component/antd/variable/TextArea.tsx
Reverts nocobase/nocobase#2770
=> Revert "fix(client): fix rerendering cause range bug"

packages/core/client/src/schema-component/antd/percent/Percent.tsx
=> fix(percent): percent value should divide by 100

packages/core/client/src/schema-component/antd/percent/Percent.tsx
=> fix: percent value invalid

packages/core/test/src/client/__tests__/__snapshots__/omitSomeFields.test.ts.snap, packages/core/test/src/client/__tests__/omitSomeFields.test.ts, packages/core/test/src/client/e2eUtils.ts
=> chore(e2e): delete collectionName key

packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-settings/hooks/useParseDataScopeFilter.ts
=> fix: data scope linkage in association field

packages/core/client/src/__tests__/e2e/bugs/T-2176.test.ts, packages/core/client/src/schema-initializer/SchemaInitializer.tsx
=> fix: should not show loading when children is enpty in menu

packages/core/client/src/__tests__/e2e/bugs/T-2186.test.ts, packages/core/client/src/schema-component/antd/filter/DynamicComponent.tsx
=> fix: the input box displayed should correspond to the field type

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx
=> fix: option should clear when data scope change

packages/plugins/@nocobase/plugin-import/src/client/ImportPluginProvider.tsx
=> style: import action modal formlayout

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/variables/VariablesProvider.tsx
=> fix: data scope report error with invalid variables

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: assign field modal automatically close

packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/form-v2/utils.tsx
=> fix: cascadeSelect report error in m2m association field

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> fix: multiple select should assigned null value after clearing

packages/plugins/@nocobase/plugin-workflow/src/client/CanvasContent.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/WorkflowLink.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/__tests__/e2e/createFormEvent.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__tests__/e2e/editFormEvent.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__tests__/e2e/triggerCollectionEvent.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.ts
Adjust UI details of workflow.
UI confused sometime.
- Backend (后端)
None.
None.
None.
=> refactor(plugin-workflow): adjust ui and client api

packages/core/client/src/__tests__/e2e/bugs/T-2165.test.ts, packages/core/client/src/__tests__/e2e/bugs/T-2200.test.ts, packages/core/client/src/schema-settings/GeneralSchemaDesigner.tsx
=> fix: fix auto-close dialog

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
Move "Add new" button to right in workflow list.
To follow ant design action order.
- Backend (后端)
None.
None.
None.
=> fix(plugin-workflow): fix action order in workflow list

packages/core/client/src/collection-manager/interfaces/m2m.tsx, packages/core/client/src/collection-manager/interfaces/m2o.tsx, packages/core/client/src/collection-manager/interfaces/o2m.tsx, packages/core/client/src/collection-manager/interfaces/o2o.tsx, packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
…ection field config
> **Note**
- Backend (后端)
=> fix: association field in assign field should set title field as collection field configured

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-initializer/components/assigned-field/AssignedField.tsx
=> revert:association field log

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/action/utils.ts, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> fix: revert linkage rules

packages/core/client/src/schema-initializer/index.ts
Export `createReadPrettyFormBlockSchema` method from client.
To reuse detail block initial schema.
- Add client export member.
- Backend (后端)
None.
None.
None.
=> refactor(client): add exports

packages/core/client/src/schema-component/antd/variable/Input.tsx, packages/core/client/src/schema-component/antd/variable/JSONInput.tsx, packages/core/client/src/schema-component/antd/variable/RawTextArea.tsx, packages/core/client/src/schema-component/antd/variable/TextArea.tsx, packages/core/client/src/schema-component/antd/variable/VariableSelect.tsx, packages/core/client/src/schema-component/antd/variable/XButton.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
The screenshot after the changes
https://github.com/nocobase/nocobase/assets/29533304/9c1fdffe-da71-4ed8-9f23-f0a02862259c
=> feat(custom-request): improve x button of variable

packages/core/client/src/schema-settings/hooks/useIsAllowToSetDefaultValue.tsx
=> fix: field in detail block should not allow config default value

packages/core/client/src/schema-component/hooks/useFieldModeOptions.tsx
=> fix(useFieldModeOptions): m2o association field should not allow sub-table as field component

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-settings/hooks/useIsAllowToSetDefaultValue.tsx
=> fix: after successful submission failed to config redirectTo

packages/core/logger/src/create-logger.ts, packages/plugins/@nocobase/plugin-custom-request/package.json, packages/plugins/@nocobase/plugin-custom-request/src/client/hooks/useCustomizeRequestActionProps.ts, packages/plugins/@nocobase/plugin-custom-request/src/server/__tests__/__snapshots__/actions.test.ts.snap, packages/plugins/@nocobase/plugin-custom-request/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-custom-request/src/server/actions/send.ts, packages/plugins/@nocobase/plugin-custom-request/src/server/plugin.ts
=> fix(plugin-custom-request): variables not work in form block

packages/core/client/src/block-provider/hooks/index.ts
=> fix: record picker did not refresh list after adding data

packages/core/client/src/schema-component/antd/action/utils.ts
=> fix: action linkage not work in detail block

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> fix:  rendering error in association select creation mode

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/schema-component/antd/action/hooks.ts, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-initializer/items/CreateActionInitializer.tsx
…ited collection block
> **Note**
- Backend (后端)
=> fix: non UI configured states should only display correspond inherited collection block

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/request.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.ts
=> fix(plugin-workflow): fix lang

packages/core/client/src/schema-component/antd/variable/Input.tsx, packages/core/client/src/schema-component/antd/variable/JSONInput.tsx, packages/core/client/src/schema-component/antd/variable/RawTextArea.tsx, packages/core/client/src/schema-component/antd/variable/TextArea.tsx, packages/plugins/@nocobase/plugin-custom-request/src/client/hooks/useCustomizeRequestActionProps.ts
=> fix(plugin-custom-request): improve x button style and afterSuccess not work when manualClose is enable

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> refactor(association-select): association select file clear linkage

packages/core/client/src/schema-component/antd/association-field/Nester.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix(variable): fix currentObject

packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadAssociationFieldOfForm.ts
=> fix: disappearing of sub-form data

packages/core/client/src/block-provider/hooks/useParsedFilter.ts, packages/core/client/src/schema-component/antd/association-field/Nester.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-settings/hooks/useParseDataScopeFilter.ts, packages/core/client/src/variables/hooks/useLocalVariables.tsx
=> fix(variable): compat old variable names

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx
=> fix: fileManager selector should be single choice when not allow multiple

packages/plugins/@nocobase/plugin-workflow/src/client/AddButton.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/sql.tsx
Add `isAvailable()` check for adding node.
If extended node type need to only be used in specific workflow, need that check.
- `isAvailable()` API for instruction.
- Backend (后端)
None.
None.
None.
=> refactor(plugin-workflow): add `isAvailable` check for adding node

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx
=> fix: linkage rule memory overflow

packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix: foreignKey undefined in useServiceOptions

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/block-provider/hooks/index.ts
=> fix: useRecord for parent record

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix: linkage rules cause abnormal field display

packages/core/client/src/schema-component/antd/page/FixedBlock.tsx, packages/core/client/src/schema-component/antd/page/hooks/useIsBlockInPage.ts
=> fix: disappearing of fixed-block option

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix: association block was not associated after adding data

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx, packages/core/client/src/schema-component/antd/association-field/FileManager.tsx, packages/core/client/src/schema-component/antd/input/Json.tsx, packages/core/client/src/schema-component/antd/upload/Upload.tsx, packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Map.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/Map.tsx
=> refactor: reset form values after create action

packages/plugins/@nocobase/plugin-workflow/src/client/Branch.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/CanvasContent.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/loop.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/parallel.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Adjust branch styles in workflow canvas.
* Export style objects.
* Unify branch styles.
- Styles
- Backend (后端)
None.
None.
None.
=> refactor(plugin-workflow): adjust branch styles

.github/workflows/nocobase-test-e2e.yml, packages/plugins/@nocobase/plugin-theme-editor/src/client/__tests__/e2e/demo.test.ts
=> chore(e2e): based postgres in CI to run e2e

packages/core/test/src/client/e2eUtils.ts
=> feat(e2e): add test.pgOnly

packages/plugins/@nocobase/plugin-workflow/package.json, packages/plugins/@nocobase/plugin-workflow/src/client/Branch.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/WorkflowTodo.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Add end property to branch.
To express branch will be ended after all nodes processed.
- Branch component.
- Backend (后端)
None.
None.
=> refactor(plugin-workflow): add end property to branch

packages/plugins/@nocobase/plugin-workflow/src/client/AddButton.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Adjust end sign style.
Decrease end sign height.
- Style
- Backend (后端)
None.
None.
None.
=> fix(plugin-workflow): ajdust style

packages/core/client/src/locale/en_US.ts, packages/core/client/src/locale/es_ES.ts, packages/core/client/src/locale/fr_FR.ts, packages/core/client/src/locale/ja_JP.ts, packages/core/client/src/locale/pt_BR.ts, packages/core/client/src/locale/ru_RU.ts, packages/core/client/src/locale/tr_TR.ts, packages/core/client/src/locale/uk_UA.ts, packages/core/client/src/locale/zh_CN.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useParentRecordVariable.ts
=> refactor(variable): rename

packages/core/client/src/schema-component/antd/variable/RawTextArea.tsx, packages/plugins/@nocobase/plugin-custom-request/src/server/__tests__/__snapshots__/actions.test.ts.snap, packages/plugins/@nocobase/plugin-custom-request/src/server/__tests__/actions.test.ts, packages/plugins/@nocobase/plugin-custom-request/src/server/actions/send.ts
=> fix(custom-request): parsed not working when the value of the variable is of type o2m.

packages/core/client/src/block-provider/CalendarBlockProvider.tsx, packages/core/client/src/schema-component/antd/calendar/Calendar.tsx
确保每月正确显示数据。
这个 PR 修复当前月第一天当周的数据显示不全的问题
=> fix(calendar): render data of next month is incorrect

packages/core/client/src/schema-component/antd/input/Input.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/CanvasContent.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/style.tsx
Add slider bar to zoom workflow canvas.
When there are plenty of nodes, hard to display all in one screen.
- Workflow canvas and styles
- Backend (后端)
None.
None.
=> feat(plugin-workflow): add zoomer for workflow canvas

packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx
=> fix: target collection pointed to by tableOid is incorrect

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx
=> fix(graph-collection-manager): create collection reporting error 

packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/calculation.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/loop.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/query.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/request.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/sql.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/collection.ts, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/schedule.ts
New node could not be select in downstream variables, unless refresh page.
1. Create a calculation node (1).
2. Open node configuration then close.
3. Create another calculation node (2) above (1).
4. Open node (1) configuration try to select variable from node (2).
Could select variable from node (2).
Cannot.
None.
Hooks.
Fix hooks.
=> fix(plugin-workflow): fix variables and form changed

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/schema-initializer/buttons/GridCardActionInitializers.tsx, packages/core/client/src/schema-initializer/buttons/ListActionInitializers.tsx, packages/plugins/@nocobase/plugin-import/src/client/ImportInitializerProvider.tsx
=> fix: import action should not visible when view collection not editable

packages/core/client/src/schema-component/antd/percent/Percent.tsx
=> fix: percent field component should support decimal point

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/expand-action/Expand.Action.tsx, packages/core/client/src/schema-initializer/items/ExpandActionInitializer.tsx
=> fix: add child action should omit children data

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> fix: button of details is not refresh when updating record

packages/core/client/src/schema-component/antd/association-field/AssociationSelect.tsx
=> fix:  association select should not clear value after setting data scope

packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx
=> fix(formula-field): formula field failed to real-time evaluating and support sub-form

packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts
=> chore: optimize error message

packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/user/LanguageSettings.tsx, packages/plugins/@nocobase/plugin-theme-editor/src/client/hooks/useThemeSettings.tsx
close T-2489
优化其它下拉选择器，包括：
1. 主题
2. 语言
=> fix: select item can not be selected in connecting data blocks

packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts
=> chore: add aria label for workflow table

packages/plugins/@nocobase/plugin-workflow/src/client/AddButton.tsx
Create node with dynamic default values.
=> refactor(plugin-workflow): allow to use function for values when creating node

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx, packages/core/client/src/schema-items/GeneralSchemaItems.tsx
=> fix: detail block has no data

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/request.tsx
Body of request node disappeared.
1. Add a request node.
Showing body input JSON.
Disappeared.
None.
Missed migrated component injection.
Add missed component.
=> fix(plugin-workflow): add missed component

packages/core/client/src/schema-component/antd/menu/Menu.tsx
=> fix: menu failed to design while menu title is empty string

packages/core/client/src/pm/PluginManagerLink.tsx, packages/core/client/src/schema-component/core/DesignableSwitch.tsx, packages/core/client/src/user/CurrentUser.tsx
=> fix(theme): text color of page header right side

packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts
=> fix: should lazy load association data in subform

.github/pull_request_template.md
Improve default pull request template.
=> Chore: update default pull request template

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/variables/VariablesProvider.tsx
=> fix: relational data should be loaded correctly on first render

packages/core/client/src/schema-component/antd/association-field/FileManager.tsx, packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadAssociationFieldOfForm.ts, packages/core/client/src/variables/VariablesProvider.tsx
=> fix: should load association data in subform

packages/core/client/src/schema-component/antd/upload/shared.ts
=> fix: attachment field in m2m association field reporting error when setting required

.env.e2e.example, packages/core/test/src/client/e2eUtils.ts, playwright.config.ts, scripts/auth.setup.ts, scripts/codegen.setup.ts, scripts/nocobase.setup.ts, scripts/runE2e.setup.ts, scripts/utils.ts
=> test: optimize command

packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadAssociationFieldOfForm.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts, packages/core/client/src/schema-component/antd/form-item/utils.ts, packages/core/client/src/variables/VariablesProvider.tsx, packages/core/client/src/variables/__tests__/utils/transformVariableValue.test.ts, packages/core/client/src/variables/utils/transformVariableValue.ts, packages/core/utils/src/common.ts
=> fix: fix display association fields with subform

packages/core/client/src/schema-initializer/utils.ts
=> refactor: findSchema should exclude AssociationField.Viewer schema

packages/core/client/src/block-provider/BlockProvider.tsx
=> fix: association block  filter params

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-initializer/components/DuplicateAction.tsx
=> chore: hide linkage rule option in some buttons

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-initializer/components/DuplicateAction.tsx
=> Revert "chore: hide linkage rule option in some buttons (#3046)"

.env.e2e.example, .github/workflows/nocobase-test-e2e.yml, package.json, packages/core/cli/bin/index.js, packages/core/cli/src/commands/e2e.js, packages/core/cli/src/commands/index.js, packages/core/server/src/gateway/index.ts, playwright.config.ts
```bash
yarn e2e test
yarn e2e test --ui
yarn e2e test --url=http://localhost:20000
yarn e2e codegen
yarn e2e start-app
```
=> feat: e2e commands

packages/core/client/src/schema-component/antd/collection-select/CollectionSelect.tsx
… data scope config
- Backend (后端)
=> fix:  tableoid should pointed to target collection 

packages/core/client/src/__tests__/e2e/bugs/T-2174.test.ts, packages/core/client/src/__tests__/e2e/checkTableRow.test.ts, packages/core/client/src/__tests__/e2e/field.test.ts, packages/core/client/src/__tests__/e2e/mock.test.ts, packages/core/test/src/client/e2eUtils.ts, playwright.config.ts
=> feat(e2e): add mockCollections

packages/core/client/src/schema-component/antd/calendar/Calendar.tsx
=> fix(calendar): cannot switch week in week mode

packages/core/server/src/application.ts, packages/core/server/src/locale/locale.ts, packages/core/server/src/middlewares/i18n.ts, packages/plugins/@nocobase/plugin-client/src/server/server.ts, packages/plugins/@nocobase/plugin-localization-management/src/server/actions/localization.ts
=> fix: add i18n resources after server app load

packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx
=> fix(linkage): avoid infinite loop

packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/page/Page.tsx
=> fix(plugin-mobile-client): page content disappears when tab is disabled

packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts
=> fix: subform disappears

packages/core/client/src/block-provider/TableBlockProvider.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx
=> fix: m2o association field should support pattern configure

packages/core/client/src/collection-manager/templates/components/PreviewTable.tsx
=> fix: view collection json field rendering error

packages/plugins/@nocobase/plugin-workflow/src/client/nodes/manual/SchemaConfig.tsx
Show header of manual drawer
Need close button for automation test.
- Manual node drawer style.
- Backend (后端)
None.
None.
=> refactor(plugin-workflow): show header of manual drawer

packages/core/client/src/collection-manager/index.tsx
=> refactor: import interface  getOptions

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix: avoid infinite loop

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> refactor: avoid errors

packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/Processor.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/instructions/request.test.ts, packages/plugins/@nocobase/plugin-workflow/src/server/triggers/schedule.ts
Repeat in cache cycle not follows limit.
Via test case.
Follows limit.
Not follows.
None.
`allExecuted` not updated in cache.
Update `allExecuted` in cache.
=> fix(plugin-workflow): fix schedule trigger

packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx
close T-2617
related #3089 #3091
=> fix(linkageRules): avoid infinite loop

packages/core/client/src/block-provider/BlockProvider.tsx, packages/core/client/src/collection-manager/templates/components/PreviewTable.tsx, packages/plugins/@nocobase/plugin-map/src/client/components/ReadPretty.tsx
=> fix: association data params missing appends

packages/core/client/src/block-provider/hooks/index.ts
Error message is not only for single action name.
#3106.
=> fix(client): adjust error message

packages/core/client/src/schema-component/antd/action/Action.tsx, packages/core/client/src/schema-component/antd/action/utils.ts, packages/core/client/src/schema-component/antd/form-item/FormItem.tsx, packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/schema-component/common/utils/uitls.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx, packages/core/client/src/schema-items/GeneralSchemaItems.tsx, packages/core/client/src/variables/VariablesProvider.tsx
close T-2646
- 使用 reaction 替换 autorun，明确指定依赖项，防止意外触发
- 每次条件变更，需整体从头开始运行联动规则，才能保证联动规则的逻辑正确性
=> fix(linkageRules): fix autorun

packages/plugins/@nocobase/plugin-map/src/client/fields/circle.ts, packages/plugins/@nocobase/plugin-map/src/client/fields/lineString.ts, packages/plugins/@nocobase/plugin-map/src/client/fields/point.ts, packages/plugins/@nocobase/plugin-map/src/client/fields/polygon.ts, packages/plugins/@nocobase/plugin-map/src/client/initialize.tsx
=> refactor: map field support connect as remote table fields

packages/core/client/src/collection-manager/Configuration/AddFieldAction.tsx
=> fix: field options undefined in collection manger

packages/core/client/src/collection-manager/Configuration/AddFieldAction.tsx, packages/core/client/src/schema-templates/BlockTemplate.tsx
=> fix(block template): onTemplateSuccess  is not a function

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/templates/types.ts
=> refactor: collection template support configureActions

packages/core/client/src/collection-manager/Configuration/AddFieldAction.tsx, packages/core/client/src/collection-manager/templates/components/PreviewTable.tsx
=> refactor: view collection support json field

packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
=> fix: association field should support json field as title field

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx, packages/core/client/src/collection-manager/templates/types.ts
=> refactor: collection template support forbidDeletion configure

packages/core/client/src/collection-manager/Configuration/index.tsx
=> fix: uid  validate rule 

packages/core/client/src/nocobase-buildin-plugin/plugins/LocalePlugin.ts, packages/core/client/src/user/LanguageSettings.tsx, packages/plugins/@nocobase/plugin-localization-management/src/server/plugin.ts
1. Enable the localization management plugin
2. Add a collection / field
The title of collection / field would be added as translation texts automatically
It was not updated
Use wrong data format when updating database
Use correct data format
=> fix(lm): texts update hook after collection update

packages/core/client/src/locale/en_US.json, packages/core/client/src/locale/es_ES.json, packages/core/client/src/locale/fr_FR.json, packages/core/client/src/locale/ja_JP.json, packages/core/client/src/locale/ru_RU.json, packages/core/client/src/locale/tr_TR.json, packages/core/client/src/locale/uk_UA.json, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useBaseVariable.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useRoleVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts, packages/core/client/src/schema-settings/hooks/useParseDataScopeFilter.ts, packages/core/client/src/variables/__tests__/useVariables.test.tsx, packages/core/client/src/variables/hooks/useBuiltinVariables.ts, packages/core/server/src/middlewares/parse-variables.ts
添加一个名为 `Current role` 的变量，其值的类型是一个字符串，表示当前系统中用户的角色值。
=> feat(variable): add current role

packages/core/client/src/schema-component/antd/association-field/AssociationFieldProvider.tsx, packages/core/client/src/schema-component/antd/association-field/InternalPopoverNester.tsx
=> fix: sub-form(popover)in sub-table value mutual influence

Dockerfile, docker/nocobase/Dockerfile, docker/nocobase/nocobase.conf
https://github.com/nocobase/nocobase/issues/3130
=> fix: use node:18-bullseye

packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/SchemaConfig.tsx
Added fields disappears in manual node schema configuration panel.
1. Add a manual node.
2. Open UI configuration of the node, and add a data block.
3. Add fields to the block.
4. Close drawer and save the node configuration.
5. Reopen the UI configuration to check the fields in the block.
Fields configured should exist.
Fields configured disappears.
None.
Hooks dependencies.
Fix dependencies.
=> fix(plugin-workflow-manual): fix schema config component

packages/core/client/src/application/Application.tsx, packages/core/client/src/application/PluginManager.ts, packages/core/client/src/application/WebSocketClient.ts, packages/core/client/src/application/components/AppComponent.tsx, packages/core/client/src/application/components/defaultComponents.tsx, packages/core/client/src/auth/SigninPage.tsx, packages/core/client/src/locale/en_US.json, packages/core/client/src/locale/zh-CN.json, packages/core/client/src/nocobase-buildin-plugin/index.tsx, packages/core/client/src/nocobase-buildin-plugin/plugins/LocalePlugin.ts, packages/core/database/src/repository.ts, packages/core/server/src/locale/locale.ts, packages/plugins/@nocobase/plugin-acl/src/locale/en-US.json, packages/plugins/@nocobase/plugin-acl/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/setCurrentRole.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/__tests__/users.test.ts, packages/plugins/@nocobase/plugin-acl/src/server/middlewares/setCurrentRole.ts
1. Sign in with an account that has no roles
Return error message and prompt use another account
Error handling logic has flaws.
=> fix(acl): optimize error handling when logged user has no roles

packages/core/client/src/schema-initializer/buttons/TabPaneInitializers.tsx
=> fix(core):  cannot add a record block in the new tab in the Drawer

packages/core/client/src/application/index.ts, packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx
=> fix(graph-collection-manager): application context missing

packages/core/client/src/filter-provider/utils.ts, packages/core/client/src/schema-component/antd/form-item/SchemaSettingOptions.tsx, packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
=> fix(filter): fix $in operatror

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
Workflows triggered but not processed from some time on.
Can not reproduce.
Should process normally.
Stopped.
None.
Guessing it happens when preparing not succeeded with error thrown.
Add more logs, and add try/catch for preparing.
Keep observing.
=> refactor(plugin-workflow): add logs and try/catch for preparing

packages/plugins/@nocobase/plugin-audit-logs/src/server/hooks/after-create.ts, packages/plugins/@nocobase/plugin-audit-logs/src/server/hooks/after-destroy.ts, packages/plugins/@nocobase/plugin-audit-logs/src/server/hooks/after-update.ts, packages/plugins/@nocobase/plugin-audit-logs/src/server/index.ts
Remove useless function wrap.
None.
- Backend (后端)
- Wrapped function.
Via cases.
None.
None.
=> refactor(plugin-audit-log): remove useless function wrap

packages/core/client/src/schema-component/antd/form-v2/Templates.tsx
…n association select
- Backend (后端)
=> fix: failed to duplicate value in sub-table when setting data scope in association select

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/collection-manager/CollectionField.tsx
=> fix: record picker display incorrect data when field has default value in collection

packages/core/client/src/collection-manager/Configuration/CollectionFields.tsx
=> style: collection manger fields style improve

packages/core/client/src/schema-component/antd/association-field/InternalViewer.tsx
=> fix: associaion block failed to create in internalViewer

.vscode/launch.json, packages/plugins/@nocobase/plugin-workflow-aggregate/package.json, packages/plugins/@nocobase/plugin-workflow-delay/package.json, packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/package.json, packages/plugins/@nocobase/plugin-workflow-form-trigger/package.json, packages/plugins/@nocobase/plugin-workflow-loop/package.json, packages/plugins/@nocobase/plugin-workflow-loop/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-manual/package.json, packages/plugins/@nocobase/plugin-workflow-manual/src/server/__tests__/instruction.test.ts, packages/plugins/@nocobase/plugin-workflow-manual/src/server/actions.ts, packages/plugins/@nocobase/plugin-workflow-parallel/package.json, packages/plugins/@nocobase/plugin-workflow-request/package.json, packages/plugins/@nocobase/plugin-workflow-sql/package.json, packages/plugins/@nocobase/plugin-workflow-test/package.json, packages/plugins/@nocobase/plugin-workflow-test/src/server/index.ts, packages/plugins/@nocobase/plugin-workflow-test/src/server/instructions.ts, packages/plugins/@nocobase/plugin-workflow/package.json, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/condition.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/en-US.json, packages/plugins/@nocobase/plugin-workflow/src/locale/es-ES.json, packages/plugins/@nocobase/plugin-workflow/src/locale/fr-FR.json, packages/plugins/@nocobase/plugin-workflow/src/locale/pt-BR.json, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/CalculationInstruction.ts, packages/plugins/@nocobase/plugin-workflow/src/server/instructions/index.ts
Adjust some api and packages.
Refactor workflow APIs.
- Backend (后端)
Via cases.
None.
None.
=> refactor(plugin-workflow): adjust some api and packages

packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx
=> refactor: record picker submit button display by association type

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
=> fix(view collection): previewFields input exception

.gitignore, packages/core/app/client/public/global.css, packages/core/cli/src/commands/e2e.js, packages/core/cli/src/commands/p-test.js, packages/core/client/src/modules/form-creation/__e2e__/lazyLoadVariables.test.ts, packages/core/client/src/modules/form-creation/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/table/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-component/antd/action/Action.Drawer.style.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/test/src/e2e/defineConfig.ts, packages/core/test/src/e2e/templatesOfPage.ts, packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts, packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/__e2e__/schemaInitailizer.test.ts, packages/plugins/@nocobase/plugin-action-duplicate/src/client/__e2e__/schemaInitailizer.test.ts, packages/plugins/@nocobase/plugin-action-duplicate/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/fields/singleLineText/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-kanban/src/client/__e2e__/schemaSettings.test.ts, yarn.lock
close T-2848
为 #3264 添加测试，并优化代码。
=> fix(defaultValue): fix unparsed default value in edit form's subtable

packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.Settings.tsx
=> fix: record picker should support popupSize setting

packages/core/client/src/schema-component/antd/form-item/FormItem.Settings.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Designer.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: dateformat setting should support  sub-table/table block

packages/plugins/@nocobase/plugin-workflow-request/src/client/RequestInstruction.tsx
Allow to use variable in url.
Link T-2725.
Some parameters or origin part in URL needs variable to be filled.
- Request instruction.
- Backend (后端)
None.
None.
None.
=> feat(plugin-workflow-request): allow to use variable in url

packages/core/client/src/modules/details-multi-data/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-component/antd/form-v2/Form.Settings.tsx
=> fix(client): detail block should support save as block template

packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
Add workflow metric.
Unknown reason caused workflow stops triggering.
- Backend (后端)
- Add counter metric
None.
None.
None.
=> chore(plugin-workflow): add metric example

packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json
Locale is not so precise.
1. Configure "submit to workflow" button.
None.
None.
None.
None.
Adjust it.
=> fix(plugin-workflow): adjust locale

packages/core/devtools/umiConfig.js, packages/plugins/@nocobase/plugin-users/client.d.ts, packages/plugins/@nocobase/plugin-users/client.js, packages/plugins/@nocobase/plugin-users/server.d.ts, packages/plugins/@nocobase/plugin-users/server.js, yarn.lock
=> fix: in the dev environment, all plugins are loaded locally

packages/core/app/client/public/global.css, packages/core/client/src/modules/dialog/__e2e__/templatesOfBug.ts, packages/core/client/src/modules/dialog/__e2e__/zIndex.test.ts, packages/core/client/src/schema-component/antd/action/Action.Drawer.style.ts, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/collection-template/general.test.ts, yarn.lock
close T-2868
相关 PR: #3242 #3278
=> fix: z-index of antd

packages/core/client/src/schema-component/antd/list/List.Decorator.tsx, packages/core/client/src/schema-component/antd/list/List.Item.tsx, packages/core/client/src/schema-component/antd/list/List.style.ts, packages/plugins/@nocobase/plugin-import/src/client/ImportModal.tsx
Adjust `List.Item` style.
* Need to add style to `List.Item`.
* Default padding style not necessary.
- `List.Item`
- Backend (后端)
None.
Any style of `List.Item` usage.
None.
=> refactor(client): adjust list item style and fix warning

packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
=> fix: attachment reporting  error while opening preview modal in table

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
=> fix: view collection should omit rawTitle when sync form database

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
=> refactor: view collection should omit rawTitle when sync form database

packages/plugins/@nocobase/plugin-gantt/src/client/components/gantt/task-gantt-content.tsx
=> refactor(gantt-block): gantt tooltip hover display

packages/plugins/@nocobase/plugin-workflow/src/client/components/DrawerForm.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/triggers/index.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow/src/server/actions/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/server/collections/workflows.ts
Add trigger title for workflow which is different with title.
When setting the title of trigger in workflow canvas, it changes workflow title. Need them to be different.
- Trigger title editing
- Backend (后端)
- Add `triggerTitle` field to `workflows` table.
None.
None.
None.
=> refactor(plugin-workflow): add trigger title for workflow which is different with title

packages/plugins/@nocobase/plugin-workflow-sql/src/client/__e2e__/dataCURD.test.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
=> test: workflow sql node e2e

packages/plugins/@nocobase/plugin-workflow-aggregate/src/client/__e2e__/DataOfCollection.test.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
=> test: Workflow aggregate node e2e

packages/plugins/@nocobase/plugin-workflow-form-trigger/src/client/__e2e__/workflowCRUD.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/ScheduleEventTrigger/workflowCRUD.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/__e2e__/collectionEventTrigger/workflowCRUD.test.ts
=> fix: workflow e2e concurrency errors

packages/core/build/src/buildPlugin.ts
=> fix: build clean

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/components/EditFieldAction.tsx, packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/components/Entity.tsx
=> fix(graph-collection): error updating field

packages/core/client/src/plugin-manager/PinnedPluginListProvider.tsx, packages/core/client/src/route-switch/antd/admin-layout/index.tsx, packages/core/client/src/schema-component/antd/menu/Menu.tsx, packages/plugins/@nocobase/plugin-multi-app-manager/package.json, packages/plugins/@nocobase/plugin-multi-app-manager/src/client/MultiAppManagerProvider.style.ts, packages/plugins/@nocobase/plugin-multi-app-manager/src/client/MultiAppManagerProvider.tsx
=> fix(theme): fix color of header menu

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/plugins/@nocobase/plugin-action-print/src/client/PrintAction.Settings.tsx
=> fix: linkage rule should only support action with record context

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/modules/form-creation/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/form-edit/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/form-filter/__e2e__/schemaSettings.test.ts, packages/core/client/src/schema-component/hooks/useDesigner.ts
=> fix: useDesigner Designer should has default toolbar

packages/plugins/@nocobase/plugin-action-bulk-update/src/client/utils.tsx
=> refactor(bulk-update-action): local improve

packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/utils.ts
=> test: collection selector test

packages/core/client/src/block-provider/TableSelectorProvider.tsx, packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts
=> fix(TableSelectorProvider): parse filter param

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx
=> fix: graph collection auto layout reporting error

packages/plugins/@nocobase/plugin-data-visualization/src/client/filter/FilterActionInitializers.tsx
1. Add a chart block, add a chart
2. Enable filter block
3. add a input form item
4. focus the input and press Enter key
The filter action was triggered.
The page refreshed.
It trigged a empty form action. `<form action=""></form>`
Add `type="submit"` to the filter button.
=> fix(bi): pressing Enter in chart filter form triggering page refresh

packages/core/client/src/block-provider/TableBlockProvider.tsx
=> fix:  table column sort params should support cancel sort

packages/core/cli/src/commands/dev.js, packages/core/cli/src/util.js, packages/core/client/src/application/WebSocketClient.ts, packages/core/devtools/umiConfig.js, packages/core/server/src/__tests__/gateway.test.ts, packages/core/server/src/gateway/index.ts, packages/core/test/src/server/index.ts
支持配置 WS_PATH，默认为 /ws
- Backend (后端)
=> feat: supports the WS_PATH environment variable

packages/plugins/@nocobase/plugin-cas/src/client/SigninPage.tsx, packages/plugins/@nocobase/plugin-cas/src/client/index.tsx, packages/plugins/@nocobase/plugin-cas/src/server/actions/login.ts, packages/plugins/@nocobase/plugin-cas/src/server/actions/service.ts, packages/plugins/@nocobase/plugin-oidc/src/client/OIDCButton.tsx, packages/plugins/@nocobase/plugin-oidc/src/server/actions/getAuthUrl.ts, packages/plugins/@nocobase/plugin-oidc/src/server/actions/redirect.ts, packages/plugins/@nocobase/plugin-saml/src/client/SAMLButton.tsx, packages/plugins/@nocobase/plugin-saml/src/server/actions/getAuthUrl.ts, packages/plugins/@nocobase/plugin-saml/src/server/actions/redirect.ts, packages/plugins/@nocobase/plugin-saml/src/server/saml-auth.ts
Sign in from `/mobile` using any SSO authenticator
Redirecting to `/mobile` after successful sign-in.
Redirecting to `/admin` after successful sign-in.
=> fix(auth): redirect URL after signing in by SSO sucessfully

packages/plugins/@nocobase/plugin-data-visualization/src/client/renderer/ChartRendererProvider.tsx, packages/plugins/@nocobase/plugin-data-visualization/src/client/utils.ts, packages/plugins/@nocobase/plugin-data-visualization/src/server/actions/query.ts
1. Add a chart with a collection where records have numeric fields containing zero values.
2. Apply a filter condition to that field, requiring the value to be non-zero
Records contain zero values would be filtered.
Records contain zero values were returned.
The filter condition is skipped.
Fix filter conditions for a target value of 0.
=> fix(bi): filter conditions of query for a target value of 0

packages/core/client/src/locale/zh-CN.json, packages/core/client/src/schema-component/antd/page/PageTab.Settings.tsx
=> refactor: optimize translation

packages/plugins/@nocobase/plugin-workflow-manual/src/client/instruction/SchemaConfig.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/components/ValueBlock.tsx, packages/plugins/@nocobase/plugin-workflow/src/server/collections/jobs.ts, packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20240115220721-add-node-key-to-job.ts
Value of node result (calculation, aggregate...) not showing in todo blocks.
1. Add a calculation result in manual node UI configuration.
2. Trigger the workflow with manual node.
3. View the task UI configured.
Calculation value showing.
Not showing.
None.
Changed to node key for referencing node result in variables.
Change to node key in `ValueBlock`.
=> fix(plugin-workflow-manual): fix value block in todo block

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/schema-component/antd/association-field/InternalPicker.tsx, packages/core/client/src/schema-component/antd/table-v2/TableSelectorDesigner.tsx, packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts
=> fix: variables as  $nForm and $Iteration is not correct in record picker

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx
=> refactor: parent inherited collection support enable child collection in add new action

packages/core/client/src/schema-component/antd/association-field/InternalSubTable.tsx
=> refactor: permission sholud passed without setting x-acl action in sub-table

packages/core/client/src/acl/ACLProvider.tsx, packages/core/client/src/schema-component/antd/action/Action.tsx
…splayed, but cannot be clicked
- Backend (后端)
=> refactor:  action without permission should be displayed but cannot clicked in configuration mode

packages/core/client/src/modules/form-creation/__e2e__/lazyLoadAssociationFields.test.ts, packages/core/client/src/modules/form-creation/__e2e__/templatesOfBug.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useLazyLoadDisplayAssociationFieldsOfForm.ts
=> fix: should load association data of sub details

packages/core/client/src/api-client/APIClient.ts, packages/core/server/src/middlewares/data-wrapping.ts
Add message handling on success.
If need to show some messages from successful response, there is no way.
- Response interceptor in APIClient.
- Backend (后端)
- Data wrapping middleware.
None.
None.
None.
=> feat(core): add message handling on success

packages/plugins/@nocobase/plugin-workflow-manual/src/server/Plugin.ts, packages/plugins/@nocobase/plugin-workflow-sql/src/client/SQLInstruction.tsx, packages/plugins/@nocobase/plugin-workflow-sql/src/locale/index.ts, packages/plugins/@nocobase/plugin-workflow-sql/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-sql/src/server/SQLInstruction.ts, packages/plugins/@nocobase/plugin-workflow-sql/src/server/__tests__/instruction.test.ts, packages/plugins/@nocobase/plugin-workflow/src/client/nodes/end.tsx, packages/plugins/@nocobase/plugin-workflow/src/client/schemas/workflows.ts, packages/plugins/@nocobase/plugin-workflow/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow/src/server/migrations/20240115220721-add-node-key-to-job.ts
SQL node error under sync mode.
1. Use SQL node under a sync collection workflow.
Process correctly.
Throws error.
#3383.
Not pass default transaction to SQL instruction.
Pass default transaction to SQL instruction.
=> fix(plugin-workflow): fix sql transaction and locale

packages/core/client/src/schema-component/antd/menu/Menu.tsx
=> style: fix side menu text overflow style

packages/core/client/src/schema-initializer/items/FilterFormBlockInitializer.tsx
=> fix: filter form block failed to link with data block as a template filter.

packages/core/client/src/schema-component/antd/association-field/Editable.tsx, packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
=> fix(CascadeSelect): should change value when deleting value

packages/core/client/src/schema-component/antd/upload/Upload.tsx
…ttachments after deleted
- Backend (后端)
=> fix: attachment field set as single and doesn't display re-uploaded file

packages/core/client/src/block-provider/FilterFormBlockProvider.tsx, packages/core/client/src/collection-manager/CollectionField.tsx
=> fix(defaultValue): should not use defaultValue in filter blocks

packages/plugins/@nocobase/plugin-workflow-parallel/src/client/__e2e__/parallelBranch.test.ts, packages/plugins/@nocobase/plugin-workflow-test/src/e2e/e2ePageObjectModel.ts
=> test: parallel branch node e2e

packages/core/client/src/global.less, packages/core/client/src/index.ts, packages/core/client/src/route-switch/antd/admin-layout/index.tsx
=> style: fix color of more button and scrollbar style

packages/core/client/src/pm/PluginManagerLink.tsx
插件设置图标小于3个时，布局不正常
- Backend (后端)
=> fix: layout of plugin settings icons

packages/core/database/src/fields/uid-field.ts
=> fix: fix T-3012

packages/plugins/@nocobase/plugin-workflow-form-trigger/src/locale/zh-CN.json
Language not translated.
1. Use trigger data from form trigger.
"Trigger data" should be translated.
None.
None.
Add locale.
=> fix(plugin-workflow-form-trigger): fix locale

packages/core/client/src/schema-initializer/buttons/TableColumnInitializers.tsx
=> fix: sub-table should not support action column

packages/plugins/@nocobase/plugin-workflow/package.json
Duplicated menu items in plugin navigation.
Open plugin list.
Showing only one workflow.
Duplicated.
None.
Keyword cases.
Use upper case.
=> docs(plugin-workflow): fix keyword

packages/core/client/src/plugin-manager/PinnedPluginListProvider.tsx
=> style(PinnedPluginList): fix hover background color

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/modules/form-creation/__e2e__/schemaInitializer.test.ts, packages/core/client/src/modules/form-creation/__e2e__/templatesOfBug.ts, packages/core/client/src/schema-component/antd/form-item/hooks/useParseDefaultValue.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx
=> fix(subTable): should clear form value after submit

packages/plugins/@nocobase/plugin-formula-field/src/client/interfaces/formula.tsx, packages/plugins/@nocobase/plugin-formula-field/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-sequence-field/src/client/sequence.tsx, packages/plugins/@nocobase/plugin-sequence-field/src/locale/zh-CN.json, packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/client/expression.tsx, packages/plugins/@nocobase/plugin-workflow-dynamic-calculation/src/locale/zh-CN.json
Fix locales.
None.
Has descriptions.
Descriptions missed.
None.
None.
Add descriptions.
=> fix: fields locales

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/collection-manager/Configuration/DeleteCollectionAction.tsx, packages/core/client/src/locale/en_US.json, packages/core/client/src/locale/ja_JP.json, packages/core/client/src/locale/zh-CN.json
=> fix: detail block should not support pageSizeChanger

packages/core/client/src/schema-component/antd/form-v2/utils.tsx
=> refactor(Linkage): optimize the parsing of expression variables

.env.example, packages/core/cli/src/util.js, packages/core/logger/src/deprecated/create-logger.ts, packages/core/server/src/commands/install.ts, packages/plugins/@nocobase/plugin-client/src/server/server.ts, packages/plugins/@nocobase/plugin-file-manager/src/server/server.ts, packages/plugins/@nocobase/plugin-users/src/client/index.ts, packages/plugins/@nocobase/plugin-users/src/server/server.ts
DEFAULT_STORAGE_TYPE=local
LOCAL_STORAGE_BASE_URL=/storage/uploads
LOCAL_STORAGE_DEST=storage/uploads
ALI_OSS_STORAGE_BASE_URL=
ALI_OSS_REGION=oss-cn-beijing
ALI_OSS_ACCESS_KEY_ID=
ALI_OSS_ACCESS_KEY_SECRET=
ALI_OSS_BUCKET=
TX_COS_STORAGE_BASE_URL=
TX_COS_REGION=ap-guangzhou
TX_COS_SECRET_ID=
TX_COS_SECRET_KEY=
TX_COS_BUCKET=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_S3_REGION=
AWS_S3_BUCKET=
AWS_S3_STORAGE_BASE_URL=
INIT_ALI_SMS_ACCESS_KEY=
INIT_ALI_SMS_ACCESS_KEY_SECRET=
INIT_ALI_SMS_ENDPOINT=
INIT_ALI_SMS_VERIFY_CODE_TEMPLATE=
INIT_ALI_SMS_VERIFY_CODE_SIGN=
DEFAULT_SMS_VERIFY_CODE_PROVIDER=
=> chore: optimize environmental variables

packages/core/client/src/schema-component/antd/form-v2/Form.tsx, packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/variables/VariablesProvider.tsx
=> fix(LinkageRules): avoid to change observable object

packages/core/client/src/block-provider/hooks/index.ts, packages/core/client/src/schema-component/antd/action/utils.ts, packages/core/client/src/schema-component/antd/form-v2/utils.tsx, packages/core/client/src/schema-component/common/utils/uitls.tsx
=> fix(LinkageRules): fix appends

packages/plugins/@nocobase/plugin-iframe-block/src/client/index.ts
=> refactor(iframe): iframe block support in RecordFormBlockInitializers

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/list/List.Decorator.tsx, packages/core/client/src/schema-component/antd/list/List.Item.tsx, packages/core/client/src/schema-component/antd/list/List.style.ts, packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx
=> refactor: formula field should not trigger form value change

packages/plugins/@nocobase/plugin-snapshot-field/src/client/interface.ts, packages/plugins/@nocobase/plugin-snapshot-field/src/locale/zh-CN.json
=> docs(plugin-snapshot-field): adjust description

packages/core/client/src/user/CurrentUser.tsx, packages/core/client/src/user/Help.tsx
=> style: set size of icon button

packages/core/client/src/pm/PluginManager.tsx
=> style: plugin manager style improve

packages/core/client/src/schema-component/antd/action/Action.Modal.tsx, packages/core/client/src/schema-component/antd/form-item/FormItem.Settings.tsx
=> refactor: the default openSize of dialog should be middle

packages/core/client/src/schema-settings/DateFormat/ExpiresRadio.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx
=> fix: dateTime format should  support preview

packages/core/client/src/schema-component/antd/checkbox/Checkbox.tsx, packages/core/client/src/schema-component/antd/radio/Radio.tsx, packages/core/client/src/schema-component/antd/select/ReadPretty.tsx
=> fix:  field dataSource in select readPretty is missing

packages/plugins/@nocobase/plugin-file-manager/src/client/hooks/useUploadFiles.ts, packages/plugins/@nocobase/plugin-file-manager/src/client/initializers/UploadActionInitializer.tsx
=> fix: upload action

packages/core/client/src/modules/form-creation/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/form-creation/__e2e__/templatesOfBug.ts, packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix(LinkageRules): fix linkage rules with nested conditions

packages/plugins/@nocobase/plugin-formula-field/src/client/components/Formula/Result.tsx
=> fix: formula field should trigger onChange even when value change

packages/plugins/@nocobase/plugin-workflow/src/server/triggers/ScheduleTrigger/StaticScheduleTrigger.ts
Interval number overflow than 32 bits cause warning.
Link T-3316.
1. Create a schedule workflow in static time mode.
2. Set start time to a day after 2 month.
Correctly scheduled.
Error logs:
```
TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647
```
#3590.
https://stackoverflow.com/questions/60474110/why-is-my-console-logging-timeoutoverflowwarning-4294967296000-does-not-fit-i
Add rescheduling logic when number greater than limit.
=> fix(plugin-workflow): fix interval number greater then 32-bits integer

packages/core/client/src/css-variable/CSSVariableProvider.tsx, packages/core/client/src/global.less, packages/core/client/src/schema-component/antd/table-v2/Table.Column.ActionBar.tsx
=> style(TableColumn): fix style of mouse hover

packages/core/client/src/schema-component/antd/form-v2/Form.tsx
=> fix: field hidden with linkage rule should clear value

packages/core/client/src/data-source/data-block/DataBlockRequestProvider.tsx
=> fix: data-block parent request with data-source

packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/configure.test.ts, packages/plugins/@nocobase/plugin-acl/src/client/__e2e__/menu.test.ts
=> test: acl test

packages/plugins/@nocobase/plugin-action-bulk-edit/src/client/bulkEditFormItemSettings.ts
=> fix: bulkEditFormItemSettings collection undefined

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/DataSourceTable.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/PermissionManager/RoleConfigure.tsx
=> fix(acl-plugin): role name  is error in role configure parmas

packages/plugins/@nocobase/plugin-kanban/src/client/style.tsx
=> fix(kanban): fix block

packages/core/client/src/block-provider/hooks/index.ts
=> fix(save-record): differentiate between creation and updating based on record.isNew

packages/core/client/src/css-variable/CSSVariableProvider.tsx, packages/core/client/src/global.less, packages/core/client/src/schema-component/antd/table-v2/Table.Column.ActionBar.tsx, packages/core/client/src/schema-component/antd/table-v2/Table.Column.Decorator.tsx
=> fix: fix hover style for sub table

packages/core/client/src/modules/fields/component/Select/selectComponentFieldSettings.tsx, packages/core/client/src/schema-component/antd/remote-select/RemoteSelect.tsx, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/fields/manyToOne/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/fields/manyToOne/templatesOfBug.ts
=> fix(subTable): fix changing title field invalid

packages/plugins/@nocobase/plugin-acl/src/client/permissions/PluginPermissions.tsx
=> fix(acl-plugin-setting):  pluginPermissions for snippets check

packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx
=> fix(graph-collection-manager): graph collection position data missing

packages/plugins/@nocobase/plugin-custom-request/src/client/__e2e__/schemaSettings.test.ts, packages/plugins/@nocobase/plugin-custom-request/src/client/schemaSettings.ts
=> fix(customRequestAction): should not support setting icons and colours

packages/core/client/src/schema-component/antd/action/ActionBar.tsx
=> style(actionBar): multiple action display should wrap

packages/core/client/src/modules/fields/component/DatePicker/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/fields/component/DatePicker/__e2e__/utils.ts, packages/core/client/src/modules/fields/component/DatePicker/datePickerComponentFieldSettings.tsx, packages/core/client/src/schema-settings/DateFormat/ExpiresRadio.tsx, packages/core/client/src/schema-settings/SchemaSettingsDateFormat.tsx, packages/plugins/@nocobase/plugin-collection-manager/src/client/__e2e__/fields/datetime/schemaSettings.test.ts
=> fix: dateTime format configured in table is invalid

packages/core/client/src/schema-component/antd/association-field/InternalCascadeSelect.tsx
=> fix(cascadeSelect): cascadeSelect does not display data in edit form

packages/core/client/src/collection-manager/templates/components/PreviewFields.tsx
=> fix: view collection confgiure interface missing

packages/plugins/@nocobase/plugin-cas/src/server/actions/login.ts, packages/plugins/@nocobase/plugin-cas/src/server/auth.ts, yarn.lock
1. Add a CAS authenticator.
2. Initiate CAS sign in request.
Successfully sign in.
`INVALID_SERVICE` error during validation.
None.
Inconsistency in `service` URL parameters between login and validation.
Ensure consistency in the parameters of the service URL used for login and service validation.
=> fix(auth): cas service validate issue

packages/core/client/src/collection-manager/Configuration/components/index.tsx
=> fix: view collection association field foreignKey should be select

packages/core/client/src/modules/actions/add-child/CreateChildInitializer.tsx, packages/core/client/src/modules/actions/add-child/addChildActionSettings.tsx, packages/core/client/src/schema-component/antd/action/Action.Designer.tsx, packages/core/client/src/schema-initializer/components/CreateRecordAction.tsx
=> refactor: add child in inheritance of tree collection

packages/core/client/src/schema-component/antd/radio/Radio.tsx
=> fix: radio support mutiple type 

packages/core/client/src/schema-initializer/utils.ts
=> fix(client): field configuration of Kanban interacts with other block

packages/core/client/src/schema-component/antd/select/Select.tsx
=> fix(select): select display with fieldNames

packages/core/client/src/schema-component/antd/date-picker/DatePicker.tsx, packages/core/client/src/schema-component/antd/radio/Radio.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/FieldTitleInput.tsx
=> refactor(radio): radio support multiple field types

packages/core/client/src/schema-component/antd/nanoIDInput/NanoIDInput.tsx, packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/index.tsx
=> fix(client): size undefined in nanoid

packages/core/client/src/block-provider/TableBlockProvider.tsx
close T-3584
https://github.com/nocobase/nocobase/assets/38434641/c79f2f93-2e71-42eb-9718-b26f519fbf1e
=> fix(Table): fix disappearing content after selecting a row

packages/plugins/@nocobase/plugin-data-source-manager/src/client/component/CollectionsManager/components/index.tsx
=> fix(data-source):  external data source association field foreign key options

packages/core/client/src/block-provider/FormBlockProvider.tsx, packages/core/client/src/modules/blocks/data-blocks/table-selector/__e2e__/schemaSettings.test.ts, packages/core/client/src/modules/blocks/data-blocks/table-selector/__e2e__/templatesOfBug.ts, packages/core/client/src/schema-component/antd/association-field/Nester.tsx, packages/core/client/src/schema-component/antd/association-field/hooks.ts, packages/core/client/src/schema-component/antd/table-v2/Table.tsx, packages/core/client/src/schema-initializer/utils.ts, packages/core/client/src/schema-settings/EnableChildCollections/DynamicComponent.tsx, packages/core/client/src/schema-settings/LinkageRules/index.tsx, packages/core/client/src/schema-settings/SchemaSettings.tsx, packages/core/client/src/schema-settings/VariableInput/VariableInput.tsx, packages/core/client/src/schema-settings/VariableInput/hooks/useFormVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useIterationVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useRecordVariable.ts, packages/core/client/src/schema-settings/VariableInput/hooks/useVariableOptions.ts
close T-3580
修正`当前表单`和`当前对象`两个变量的可选字段：
https://github.com/nocobase/nocobase/assets/38434641/c46969cc-6c39-4dad-be35-3e1ada67b80e
=> fix(variables): fix varaibles for table selector

packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/chart.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/configs.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/dualAxes.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/g2plot.ts, packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/index.ts
=> fix: compatibility of @ant-design/plots 2.x

packages/core/client/src/acl/ACLProvider.tsx
=> fix(acl): invalid action permission judgment
